// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.broadcast.message.reply;

// Source: com/bapis/bilibili/broadcast/message/reply/SubjectInteractionResp.java
message SubjectInteractionResp {
  int64 oid = 1;
  int64 type = 2;
  Interaction interactionType = 3;
  int64 rpid = 4;
  int64 likeCount = 5;
  int64 frequency = 6;
  enum Interaction {
    Unknown = 0;
    ReplyLike = 1;
    UNRECOGNIZED = -1;
  }

}

// Source: com/bapis/bilibili/broadcast/message/reply/SubjectNoticeResp.java
message SubjectNoticeResp {
  int64 oid = 1;
  int64 type = 2;
  string title = 3;
  string link = 4;
  int64 timestamp = 5;
  int64 rpid = 6;
  string interactionType = 7;
  int64 hoverDuration = 8;
  int64 rootRpid = 9;
  string interactionScene = 10;
}

// Source: com/bapis/bilibili/broadcast/message/reply/SubjectReplyInsertionResp.java
message SubjectReplyInsertionResp {
  int64 oid = 1;
  int64 type = 2;
  string title = 3;
  int64 rpid = 4;
  int64 timestamp = 5;
  int64 rank = 6;
  int64 stepSize = 7;
  repeated int64 supportMode = 8;
  repeated string supportTag = 9;
  repeated int64 supportTagIds = 10;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/broadcast/message/reply";
