// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.ad.v1;

enum PauseAdFormType {
  DEFAULT = 0;
  RADIO = 1;
  CHECKBOX = 2;
  TEXT = 3;
  PHONE = 4;
  UNRECOGNIZED = -1;
}

// Source: com/bapis/bilibili/ad/v1/AdAutoPlayVideoDto.java
message AdAutoPlayVideoDto {
  int64 avid = 1;
  int64 cid = 2;
  int64 page = 3;
  string from = 4;
  string url = 5;
  string cover = 6;
  bool autoPlay = 7;
  bool btnDycColor = 8;
  int32 btnDycTime = 9;
  int64 bizId = 10;
  repeated string process0Urls = 11;
  repeated string play3sUrls = 12;
  repeated string play5sUrls = 13;
  int32 orientation = 14;
  string fromSpmid = 15;
  int32 autoPlayValue = 16;
  int32 height = 17;
  int32 width = 18;
  repeated CustomPlayUrl customPlayUrls = 19;
  repeated string play10sUrls = 20;
  repeated string play15sUrls = 21;
  repeated string process1Urls = 22;
  repeated string process2Urls = 23;
  repeated string process3Urls = 24;
  repeated string process4Urls = 25;
  repeated string play0sUrls = 26;
}

// Source: com/bapis/bilibili/ad/v1/AdBusinessMarkDto.java
message AdBusinessMarkDto {
  int32 type = 1;
  string text = 2;
  string textColor = 3;
  string textColorNight = 4;
  string bgColor = 5;
  string bgColorNight = 6;
  string borderColor = 7;
  string borderColorNight = 8;
  string imgUrl = 9;
  int32 imgHeight = 10;
  int32 imgWidth = 11;
  string bgBorderColor = 12;
}

// Source: com/bapis/bilibili/ad/v1/AdButtonDto.java
message AdButtonDto {
  int32 type = 1;
  string text = 2;
  string jumpUrl = 3;
  repeated string reportUrls = 4;
  string dlsucCallupUrl = 5;
  int32 gameId = 6;
  string gameMonitorParam = 7;
  int32 gameChannelId = 8;
  string gameChannelExtra = 9;
  string callupUrl = 10;
  string gameSourcefrom = 11;
  bool showGameCustomText = 12;
  string dlsucCallupText = 13;
  string leftIcon = 14;
}

// Source: com/bapis/bilibili/ad/v1/AdCardCalenderInfo.java
message AdCardCalenderInfo {
  string title = 1;
  int64 startTime = 2;
  int64 endTime = 3;
  int32 calenderId = 4;
  string comment = 5;
  string calendarIdStr = 6;
}

// Source: com/bapis/bilibili/ad/v1/AdCardDto.java
message AdCardDto {
  int32 cardType = 1;
  string title = 2;
  string desc = 3;
  string extraDesc = 4;
  string longDesc = 5;
  string shortTitle = 6;
  string danmuTitle = 7;
  int32 danmuHeight = 8;
  int32 danmuWidth = 9;
  int32 danmuLife = 10;
  int32 danmuBegin = 11;
  string danmuColor = 12;
  string danmuH5url = 13;
  string danmuIcon = 14;
  int32 foldTime = 15;
  string adTag = 16;
  repeated AdCoverDto covers = 17;
  string jumpUrl = 18;
  string imaxLandingPageJsonString = 19;
  string callupUrl = 20;
  string universalApp = 21;
  string oriPrice = 22;
  int32 curPrice = 23;
  string priceDesc = 24;
  string priceSymbol = 25;
  string goodsCurPrice = 26;
  string goodsOriPrice = 27;
  AdGoodDto good = 28;
  int32 rank = 29;
  int32 hotScore = 30;
  AdButtonDto button = 31;
  string adverLogo = 32;
  string adverName = 33;
  string adverPageUrl = 34;
  repeated string videoBarrage = 35;
  AdBusinessMarkDto adTagStyle = 36;
  AdAutoPlayVideoDto video = 37;
  AdFeedbackPanelDto feedbackPanel = 38;
  int64 adverMid = 39;
  int64 adverAccountId = 40;
  string duration = 41;
  repeated QualityInfo qualityInfos = 42;
  string dynamicText = 43;
  AdverDto adver = 44;
  int32 gradeLevel = 45;
  bool supportTransition = 46;
  string transition = 47;
  int32 underPlayerInteractionStyle = 48;
  string imaxLandingPageV2 = 49;
  SubCardModule subcardModule = 50;
  int32 gradeDenominator = 51;
  int32 starLevel = 52;
  Bulletin bulletin = 53;
  Gift gift = 54;
  repeated string gameTags = 55;
  int32 oriMarkHidden = 56;
  bool useMultiCover = 57;
  WxProgramInfo wxProgramInfo = 58;
  AndroidGamePageRes androidGamePageRes = 59;
  NotClickableArea notClickableArea = 60;
  ForwardReply forwardReply = 61;
  string avContent = 62;
  int32 animInEnable = 63;
  string extraParams = 64;
  int64 goodsItemId = 65;
  int32 cardStyle = 66;
  GameInfo gameInfo = 67;
  LeftCoverBadgeNewStyle leftCoverBadgeNewStyle = 68;
  GameRank gameRank = 69;
  string gameRating = 70;
  FeedsRcmdReasonStyle rcmdReasonStyle = 71;
  int32 underframeCardStyle = 72;
  string lotteryText = 73;
  AdCardCalenderInfo calenderInfo = 74;
  int32 halfPanelInteractionStyle = 75;
  int32 halfPanelContentType = 76;
  StoryAnchor storyAnchor = 77;
  int32 jumpInteractionStyle = 78;
  string warmUpText = 79;
  int32 livePageType = 80;
  int32 playpageCardStyle = 81;
  AppDownloadStyle appDownloadStyle = 82;
  repeated Text descList = 83;
  string productSource = 84;
  string couponDesc = 85;
  string couponPrice = 86;
  string volumeDesc = 87;
  repeated string labels = 88;
  int32 itemSource = 89;
  int32 underframeIconType = 90;
  AdBusinessMarkDto adTagStyleFullScreen = 91;
  string benefitIcon = 92;
  int32 relatedInteractionStyle = 93;
  bool hasAntiSnipingPrice = 94;
  string antiSnipingText = 95;
  string liveroomUrl = 96;
  FakeButtonDto fakeButton = 97;
  MidPageDto midPage = 98;
  IosGamePageRes iosGamePageRes = 99;
  bool halfPanelNonModal = 100;
  BrandTrending trending = 101;
}

// Source: com/bapis/bilibili/ad/v1/AdContentExtraDto.java
message AdContentExtraDto {
  string layout = 1;
  repeated string showUrls = 2;
  repeated string clickUrls = 3;
  repeated string danmuListShowUrls = 4;
  repeated string danmuListClickUrls = 5;
  repeated string danmuDetailShowUrls = 6;
  repeated string danmuTrolleyAddUrls = 7;
  bool useAdWebV2 = 8;
  repeated string openWhitelist = 9;
  repeated AppPackageDto downloadWhitelist = 10;
  AdCardDto card = 11;
  int32 reportTime = 12;
  int32 appstorePriority = 13;
  int32 salesType = 14;
  int32 preloadLandingpage = 15;
  bool specialIndustry = 16;
  string specialIndustryTips = 17;
  bool enableDownloadDialog = 18;
  bool enableShare = 19;
  int32 upzoneEntranceType = 20;
  int32 upzoneEntranceReportId = 21;
  AdShareInfoDto shareInfo = 22;
  string topviewPicUrl = 23;
  string topviewVideoUrl = 24;
  int32 clickArea = 25;
  int64 shopId = 26;
  int64 upMid = 27;
  string trackId = 28;
  int32 enableStoreDirectLaunch = 29;
  int64 productId = 30;
  bool enableDoubleJump = 31;
  repeated string show1sUrls = 32;
  string fromTrackId = 33;
  bool storeCallupCard = 34;
  int32 landingpageDownloadStyle = 35;
  int32 specialIndustryStyle = 36;
  bool enableH5Alert = 37;
  int32 macroReplacePriority = 38;
  int32 feedbackPanelStyle = 39;
  string appstoreUrl = 40;
  int32 enableH5PreLoad = 41;
  string h5PreLoadUrl = 42;
  string cmFromTrackId = 43;
  string abtest = 44;
  int32 downloadUrlType = 45;
  int32 enableAutoCallup = 46;
  string externalLinkWarning = 47;
  int64 liveBookingId = 48;
  string storeDplinkXiaomi = 49;
  int64 lotteryId = 50;
  bool enableOpenapkDialog = 51;
  repeated LiveBookInfoDto liveBookingInfos = 52;
  int32 userCancelJumpType = 53;
  string userCancelJumpUrl = 54;
  string appExpParams = 55;
  PauseAdLandingPage pauseAdLandingpage = 56;
  string pausePageType = 57;
  BrandPausePageDto brandPausePage = 58;
  PausedDynamicPage dynamicPage = 59;
}

// Source: com/bapis/bilibili/ad/v1/AdCoverDto.java
message AdCoverDto {
  string url = 1;
  int32 loop = 2;
  string jumpUrl = 3;
  repeated string reportUrls = 4;
  int32 imageHeight = 5;
  int32 imageWidth = 6;
  string nightUrl = 7;
}

// Source: com/bapis/bilibili/ad/v1/AdDto.java
message AdDto {
  int64 creativeId = 1;
  string adCb = 2;
  AdContentExtraDto extra = 3;
  int32 cmMark = 4;
  int64 topViewId = 5;
  int32 creativeType = 6;
  int32 cardType = 7;
  int32 creativeStyle = 8;
  bool isAd = 9;
  CreativeDto creativeContent = 10;
}

// Source: com/bapis/bilibili/ad/v1/AdFeedbackPanelDto.java
message AdFeedbackPanelDto {
  string panelTypeText = 1;
  repeated AdFeedbackPanelModuleDto feedbackPanelDetail = 2;
  string toast = 3;
  string openRecTips = 4;
  string closeRecTips = 5;
}

// Source: com/bapis/bilibili/ad/v1/AdFeedbackPanelModuleDto.java
message AdFeedbackPanelModuleDto {
  int32 moduleId = 1;
  string iconUrl = 2;
  int32 jumpType = 3;
  string jumpUrl = 4;
  string text = 5;
  repeated AdSecondFeedbackPanelDto secondaryPanel = 6;
  string subText = 7;
}

// Source: com/bapis/bilibili/ad/v1/AdGoodDto.java
message AdGoodDto {
  int64 itemId = 1;
  int64 skuId = 2;
  int64 shopId = 3;
  int64 skuNum = 4;
}

// Source: com/bapis/bilibili/ad/v1/AdOgvEpDto.java
message AdOgvEpDto {
  int64 epid = 1;
  bool hasRecommend = 2;
}

// Source: com/bapis/bilibili/ad/v1/AdsControlDto.java
message AdsControlDto {
  int32 hasDanmu = 1;
  repeated int64 cids = 2;
  repeated AdOgvEpDto eps = 3;
  int32 underPlayerScrollerSeconds = 4;
  bool vipSkippedAd = 5;
  bool hasLiveBookingAd = 6;
  int32 underPlayerBannerMode = 7;
}

// Source: com/bapis/bilibili/ad/v1/AdSecondFeedbackPanelDto.java
message AdSecondFeedbackPanelDto {
  int32 reasonId = 1;
  string text = 2;
}

// Source: com/bapis/bilibili/ad/v1/AdShareInfoDto.java
message AdShareInfoDto {
  string title = 1;
  string subtitle = 2;
  string imageUrl = 3;
}

// Source: com/bapis/bilibili/ad/v1/AdverDto.java
message AdverDto {
  int64 adverId = 1;
  string adverLogo = 2;
  string adverName = 3;
  int32 adverType = 4;
  string adverPageUrl = 5;
  string adverDesc = 6;
  int32 liveStatus = 7;
}

// Source: com/bapis/bilibili/ad/v1/AndroidGamePageRes.java
message AndroidGamePageRes {
  Module1 module1 = 1;
  Module3 module3 = 2;
  Module4 module4 = 3;
  Module5 module5 = 4;
  Module6 module6 = 5;
  Module7 module7 = 6;
  Module8 module8 = 7;
  Module9 module9 = 8;
  Module10 module10 = 9;
  Module11 module11 = 10;
  Module12 module12 = 11;
  Module13 module13 = 12;
  repeated int32 moduleSeq = 13;
  string backgroundColor = 14;
  Module14 module14 = 15;
}

// Source: com/bapis/bilibili/ad/v1/AndroidTag.java
message AndroidTag {
  string text = 1;
  int32 type = 2;
}

// Source: com/bapis/bilibili/ad/v1/AppDownloadStyle.java
message AppDownloadStyle {
  int32 style = 1;
  repeated string tags = 2;
  string guideText = 3;
  repeated string headImgs = 4;
  repeated string detailImgs = 5;
  int32 detailImgLayout = 6;
  string detailText = 7;
}

// Source: com/bapis/bilibili/ad/v1/AppPackageDto.java
message AppPackageDto {
  int64 size = 1;
  string displayName = 2;
  string apkName = 3;
  string url = 4;
  string biliUrl = 5;
  string md5 = 6;
  string icon = 7;
  string devName = 8;
  string authUrl = 9;
  string authName = 10;
  string version = 11;
  string updateTime = 12;
  string privacyName = 13;
  string privacyUrl = 14;
}

// Source: com/bapis/bilibili/ad/v1/BrandPauseGuideComponentDto.java
message BrandPauseGuideComponentDto {
  string goodsImage = 1;
  string guideImage = 2;
  string guideText = 3;
  bool clickable = 4;
}

// Source: com/bapis/bilibili/ad/v1/BrandPauseLoopCardDto.java
message BrandPauseLoopCardDto {
  string logoImage = 1;
  string logoSlogan = 2;
  BrandPauseLoopImageDto loopImage = 3;
  BrandPauseGuideComponentDto guideComponent = 4;
  BrandPausePanInteractDto panInteract = 5;
  bool bgClickable = 6;
}

// Source: com/bapis/bilibili/ad/v1/BrandPauseLoopImageDto.java
message BrandPauseLoopImageDto {
  repeated BrandPauseLoopImageItemDto images = 1;
  int32 loopInterval = 2;
  bool clickable = 3;
  bool hiddenInBg = 4;
}

// Source: com/bapis/bilibili/ad/v1/BrandPauseLoopImageItemDto.java
message BrandPauseLoopImageItemDto {
  string url = 1;
  string desc = 2;
  string mainColorDay = 3;
  string mainColorNight = 4;
  string textColorDay = 5;
  string textColorNight = 6;
}

// Source: com/bapis/bilibili/ad/v1/BrandPausePageDto.java
message BrandPausePageDto {
  oneof oneof_0 {
    BrandPauseLoopCardDto loopCard = 1;
  }
  enum CardCase {
    LOOP_CARD = 1;
    CARD_NOT_SET = 0;
  }

}

// Source: com/bapis/bilibili/ad/v1/BrandPausePanInteractDto.java
message BrandPausePanInteractDto {
  int32 startAngle = 1;
  int32 endAngle = 2;
  int32 distance = 3;
}

// Source: com/bapis/bilibili/ad/v1/BrandTrending.java
message BrandTrending {
  int64 score = 1;
  string scoreImg = 2;
  string title = 3;
  int64 ownScore = 4;
  int64 activityId = 5;
}

// Source: com/bapis/bilibili/ad/v1/Bulletin.java
message Bulletin {
  string tagText = 1;
  string text = 2;
}

// Source: com/bapis/bilibili/ad/v1/BxPage.java
message BxPage {
  string url = 1;
  string materialInfo = 2;
  string configInfo = 3;
  string templateCode = 4;
}

// Source: com/bapis/bilibili/ad/v1/Comment.java
message Comment {
  int64 gameBaseId = 1;
  string userName = 2;
  string userFace = 3;
  int32 userLevel = 4;
  string commentNo = 5;
  int32 grade = 6;
  string content = 7;
  int32 upCount = 8;
}

// Source: com/bapis/bilibili/ad/v1/CreativeDto.java
message CreativeDto {
  string title = 1;
  string description = 2;
  string imageUrl = 3;
  string imageMd5 = 4;
  string url = 5;
  string clickUrl = 6;
  string showUrl = 7;
  int64 videoId = 8;
  string thumbnailUrl = 9;
  string thumbnailUrlMd5 = 10;
  string logoUrl = 11;
  string logoMd5 = 12;
  string username = 13;
}

// Source: com/bapis/bilibili/ad/v1/CustomPlayUrl.java
message CustomPlayUrl {
  int32 playTime = 1;
  repeated string urls = 2;
}

// Source: com/bapis/bilibili/ad/v1/CustomShowUrlInfo.java
message CustomShowUrlInfo {
  int32 showTime = 1;
  repeated string urls = 2;
}

// Source: com/bapis/bilibili/ad/v1/FakeButtonDto.java
message FakeButtonDto {
  string text = 1;
  bool showArrow = 2;
  MidPageDto midPage = 3;
  bool blankClickDisable = 4;
}

// Source: com/bapis/bilibili/ad/v1/FeedsRcmdReasonStyle.java
message FeedsRcmdReasonStyle {
  string bgColor = 1;
  string bgColorNight = 2;
  int32 bgStyle = 3;
  string borderColor = 4;
  string borderColorNight = 5;
  string textColor = 6;
  string textColorNight = 7;
  string text = 8;
  string iconUrl = 9;
  string iconNightUrl = 10;
}

// Source: com/bapis/bilibili/ad/v1/ForwardReply.java
message ForwardReply {
  int64 commentId = 1;
  string message_ = 2;
  string highlightText = 3;
  string highlightPrefixIcon = 4;
  string callupUrl = 5;
  string jumpUrl = 6;
  int32 jumpType = 7;
  string authorName = 8;
  string authorIcon = 9;
}

// Source: com/bapis/bilibili/ad/v1/FullText.java
message FullText {
  string icon = 1;
  string iconForNight = 2;
  string jumpUri = 3;
  string prefix = 4;
  string text = 5;
}

// Source: com/bapis/bilibili/ad/v1/GameInfo.java
message GameInfo {
  string gameLogo = 1;
  string gameName = 2;
  string gameDesc = 3;
}

// Source: com/bapis/bilibili/ad/v1/GameRank.java
message GameRank {
  string iconUrl = 1;
  string nightIconUrl = 2;
  string bkgNightColor = 3;
  string bkgDayColor = 4;
  string fontNightColor = 5;
  string fontDayColor = 6;
  string rankContent = 7;
  string rankLink = 8;
}

// Source: com/bapis/bilibili/ad/v1/Gift.java
message Gift {
  string icon = 1;
  string nightIcon = 2;
  string text = 3;
  string url = 4;
}

// Source: com/bapis/bilibili/ad/v1/GiftCardInfo.java
message GiftCardInfo {
  string desc = 1;
  repeated string iconUrls = 2;
}

// Source: com/bapis/bilibili/ad/v1/IosGamePageRes.java
message IosGamePageRes {
  string logo = 1;
  string name = 2;
  string subTitile = 3;
  repeated string imageUrl = 4;
  string desc = 5;
  AdButtonDto gameButton = 6;
  double grade = 7;
  string rankNum = 8;
  string rankName = 9;
}

// Source: com/bapis/bilibili/ad/v1/LeftCoverBadgeNewStyle.java
message LeftCoverBadgeNewStyle {
  string iconUrl = 1;
  string iconNightUrl = 2;
  int32 iconWidth = 3;
  int32 iconHeight = 4;
}

// Source: com/bapis/bilibili/ad/v1/LiveBookInfoDto.java
message LiveBookInfoDto {
  int64 liveBookingId = 1;
  AdCardCalenderInfo calenderInfo = 2;
  int32 livePageType = 3;
}

// Source: com/bapis/bilibili/ad/v1/MidPageDto.java
message MidPageDto {
  int32 type = 1;
  int32 interactionStyle = 2;
  bool showPlayIcon = 3;
  bool blankClickable = 4;
  AdButtonDto button = 5;
  string h5PageUrl = 7;
  NextPageButtonDto nextPageButton = 8;
  string mainThemeDay = 9;
  string mainThemeNight = 10;
  string buttonThemeDay = 11;
  string buttonThemeNight = 12;
}

// Source: com/bapis/bilibili/ad/v1/Module1.java
message Module1 {
  string gameName = 1;
  string gameIcon = 2;
  string developerInputName = 3;
  repeated AndroidTag tagList = 4;
}

// Source: com/bapis/bilibili/ad/v1/Module10.java
message Module10 {
  bool display = 1;
  string latestUpdate = 2;
}

// Source: com/bapis/bilibili/ad/v1/Module11.java
message Module11 {
  bool display = 1;
  repeated int32 starNumberList = 2;
  string commentStr = 3;
  double grade = 4;
}

// Source: com/bapis/bilibili/ad/v1/Module12.java
message Module12 {
  bool display = 1;
  repeated Comment commentList = 2;
  string commentNum = 3;
  bool showAllComment = 4;
}

// Source: com/bapis/bilibili/ad/v1/Module13.java
message Module13 {
  int64 pkgSize = 1;
  string customerService = 2;
  string website = 3;
  string authority = 4;
  string privacy = 5;
  string developerName = 6;
  string updateTime = 7;
  string gameVersion = 8;
  string androidPkgName = 9;
}

// Source: com/bapis/bilibili/ad/v1/Module14.java
message Module14 {
  repeated Reward rewardList = 1;
  bool display = 2;
}

// Source: com/bapis/bilibili/ad/v1/Module3.java
message Module3 {
  bool display = 1;
  repeated QualityParmas qualityParams = 3;
}

// Source: com/bapis/bilibili/ad/v1/Module4.java
message Module4 {
  bool display = 1;
  int32 giftNum = 2;
  string giftName = 3;
  int32 giftIconNum = 4;
  repeated string iconUrls = 5;
  repeated int64 giftInfoIds = 6;
}

// Source: com/bapis/bilibili/ad/v1/Module5.java
message Module5 {
  bool display = 1;
  string gameSummary = 2;
}

// Source: com/bapis/bilibili/ad/v1/Module6.java
message Module6 {
  bool display = 1;
  string gameDesc = 2;
}

// Source: com/bapis/bilibili/ad/v1/Module7.java
message Module7 {
  bool display = 1;
  repeated ScreenShots screenShots = 2;
}

// Source: com/bapis/bilibili/ad/v1/Module8.java
message Module8 {
  bool display = 1;
  repeated string tagList = 2;
}

// Source: com/bapis/bilibili/ad/v1/Module9.java
message Module9 {
  bool display = 1;
  string devIntroduction = 2;
}

// Source: com/bapis/bilibili/ad/v1/NextPageButtonDto.java
message NextPageButtonDto {
  string text = 1;
  string h5PageUrl = 2;
  int32 interactionStyle = 3;
  int32 type = 4;
  AdButtonDto button = 5;
}

// Source: com/bapis/bilibili/ad/v1/NotClickableArea.java
message NotClickableArea {
  int32 x = 1;
  int32 y = 2;
  int32 z = 3;
}

// Source: com/bapis/bilibili/ad/v1/PauseAdAIComponent.java
message PauseAdAIComponent {
  string icon = 1;
  string title = 2;
  repeated string labelInformations = 3;
  repeated PauseAdFeature features = 4;
}

// Source: com/bapis/bilibili/ad/v1/PauseAdBackgroundColor.java
message PauseAdBackgroundColor {
  string bgColorLight = 1;
  string bgColorDark = 2;
}

// Source: com/bapis/bilibili/ad/v1/PauseAdBottomComponent.java
message PauseAdBottomComponent {
  int32 style = 1;
  string icon = 2;
  string title = 3;
  string subtitle = 4;
  AdButtonDto button = 5;
  int32 autoShowDelay = 6;
  int32 presentStyle = 7;
  int32 enableShowInDetail = 8;
}

// Source: com/bapis/bilibili/ad/v1/PauseAdCommentComponent.java
message PauseAdCommentComponent {
  string title = 1;
  SubCardModule subcard = 2;
}

// Source: com/bapis/bilibili/ad/v1/PauseAdDecisionInfo.java
message PauseAdDecisionInfo {
  string title = 1;
  string subtitle = 2;
  string left = 3;
  string mid = 4;
  string right = 5;
  string rating = 6;
}

// Source: com/bapis/bilibili/ad/v1/PauseAdDetailIntroduction.java
message PauseAdDetailIntroduction {
  string moduleTitle = 1;
  repeated AdCoverDto imgs = 2;
  string desc = 3;
  int32 imgsType = 4;
}

// Source: com/bapis/bilibili/ad/v1/PauseAdFeature.java
message PauseAdFeature {
  string title = 1;
  string desc = 2;
}

// Source: com/bapis/bilibili/ad/v1/PauseAdForm.java
message PauseAdForm {
  string formId = 1;
  string pageId = 2;
  string moduleTitle = 3;
  PauseAdFormItem name = 4;
  PauseAdFormItem phone = 5;
  string privacyText = 6;
  string privacyBlueText = 7;
  string privacyBlueUrl = 8;
}

// Source: com/bapis/bilibili/ad/v1/PauseAdFormItem.java
message PauseAdFormItem {
  string formItemId = 1;
  string title = 2;
  bool isRequired = 3;
  PauseAdFormType type = 4;
  string hint = 5;
  string error = 6;
}

// Source: com/bapis/bilibili/ad/v1/PauseAdHeaderComponent.java
message PauseAdHeaderComponent {
  string title = 1;
  string adTag = 2;
  string icon = 3;
  string desc = 4;
  repeated string qualityInfos = 5;
  string rating = 6;
  string ratingUnit = 7;
  string price = 8;
  string priceSymbol = 9;
  int32 headerStyle = 10;
  int32 adTagPositionStyle = 11;
}

// Source: com/bapis/bilibili/ad/v1/PauseAdHeaderPictureComponent.java
message PauseAdHeaderPictureComponent {
  int32 imgType = 1;
  AdCoverDto img = 2;
  int32 tipsAniType = 3;
  int32 tipsAniTime = 4;
  repeated PauseAdHeaderPictureTip tips = 5;
  SubCardModule subcard = 6;
  string jumpUrl = 7;
  string callupUrl = 8;
  WxProgramInfo wxProgramInfo = 9;
  repeated AdCoverDto imgs = 10;
  int32 duration = 11;
  string slideText = 12;
  string jumpText = 13;
  double jumpThreshold = 14;
}

// Source: com/bapis/bilibili/ad/v1/PauseAdHeaderPictureTip.java
message PauseAdHeaderPictureTip {
  string title = 1;
  string textColorLight = 2;
  string textColorDark = 3;
  string bgColorLightStart = 4;
  string bgColorLightEnd = 5;
  string bgColorDarkStart = 6;
  string bgColorDarkEnd = 7;
  int32 anchorPos = 8;
  int32 locationX = 9;
  int32 locationY = 10;
  int32 fontSize = 11;
  int32 highlightFontSize = 12;
}

// Source: com/bapis/bilibili/ad/v1/PauseAdLandingPage.java
message PauseAdLandingPage {
  repeated PauseAdLandingPageModule modules = 1;
  PauseAdBackgroundColor backgroundColor = 2;
  PauseAdBottomComponent bottomComponent = 3;
  repeated string clickableAreas = 4;
  CustomShowUrlInfo customShowUrls = 5;
  repeated string reportableAreas = 6;
  bool enableSlideReport = 7;
}

// Source: com/bapis/bilibili/ad/v1/PauseAdLandingPageModule.java
message PauseAdLandingPageModule {
  string type = 1;
  PauseAdHeaderComponent headerComponent = 2;
  PauseAdAIComponent aiComponent = 3;
  PauseAdProductComponent productComponent = 4;
  PauseAdRelateVideos relateVideos = 5;
  PauseAdDetailIntroduction detailIntroduction = 6;
  PauseAdForm form = 7;
  PauseAdHeaderPictureComponent headerPictureComponent = 8;
  PauseAdCommentComponent commentComponent = 9;
  PauseAdQualityInfoComponent qualityInfoComponent = 10;
}

// Source: com/bapis/bilibili/ad/v1/PauseAdProductComponent.java
message PauseAdProductComponent {
  repeated PauseAdDecisionInfo cognitiveInfos = 1;
  AdCoverDto productImg = 2;
  string productLineColorLight = 3;
  string productLineColorDark = 4;
  repeated PauseAdDecisionInfo decisionInfos = 5;
}

// Source: com/bapis/bilibili/ad/v1/PauseAdQualityInfo.java
message PauseAdQualityInfo {
  string iconLight = 1;
  string iconDark = 2;
  string leftText = 3;
  string rightText = 4;
  string subtitle = 5;
}

// Source: com/bapis/bilibili/ad/v1/PauseAdQualityInfoComponent.java
message PauseAdQualityInfoComponent {
  string title = 1;
  repeated PauseAdQualityInfo infos = 2;
}

// Source: com/bapis/bilibili/ad/v1/PauseAdRelateVideoItem.java
message PauseAdRelateVideoItem {
  int64 aid = 1;
  string url = 2;
}

// Source: com/bapis/bilibili/ad/v1/PauseAdRelateVideos.java
message PauseAdRelateVideos {
  string moduleTitle = 1;
  repeated PauseAdRelateVideoItem relateVideos = 2;
}

// Source: com/bapis/bilibili/ad/v1/PausedDynamicPage.java
message PausedDynamicPage {
  oneof oneof_0 {
    BxPage bxPage = 1;
  }
  repeated int64 relatedAids = 2;
  enum PageCase {
    BX_PAGE = 1;
    PAGE_NOT_SET = 0;
  }

}

// Source: com/bapis/bilibili/ad/v1/QualityInfo.java
message QualityInfo {
  string icon = 1;
  string text = 2;
  bool isBg = 3;
  string bgColor = 4;
  string bgColorNight = 5;
  string textColor = 6;
  string textColorNight = 7;
  repeated string userFaces = 8;
  string iconNight = 9;
  int32 bgStyle = 10;
  string borderColor = 11;
  string borderColorNight = 12;
}

// Source: com/bapis/bilibili/ad/v1/QualityParmas.java
message QualityParmas {
  string firstLine = 1;
  string secondLine = 2;
  double grade = 3;
  string rankIcon = 4;
  int32 qualityType = 5;
}

// Source: com/bapis/bilibili/ad/v1/Reward.java
message Reward {
  int32 level = 1;
  string title = 2;
  string content = 3;
  string pic = 4;
  bool reach = 5;
}

// Source: com/bapis/bilibili/ad/v1/ScreenShots.java
message ScreenShots {
  string url = 1;
  int32 height = 2;
  int32 width = 3;
  int32 seq = 4;
}

// Source: com/bapis/bilibili/ad/v1/SourceContentDto.java
message SourceContentDto {
  string requestId = 1;
  int32 sourceId = 2;
  int32 resourceId = 3;
  bool isAdLoc = 4;
  Int32Value serverType = 5;
  string clientIp = 6;
  Int32Value cardIndex = 7;
  int32 index = 8;
  AdDto adContent = 9;
}

// Source: com/bapis/bilibili/ad/v1/StoryAnchor.java
message StoryAnchor {
  int32 type = 1;
  StoryCartIcon storyCartIcon = 2;
  string title = 3;
  string desc = 4;
}

// Source: com/bapis/bilibili/ad/v1/StoryCartIcon.java
message StoryCartIcon {
  string iconUrl = 1;
  string iconText = 2;
  string iconTitle = 3;
}

// Source: com/bapis/bilibili/ad/v1/SubCardModule.java
message SubCardModule {
  string subcardType = 1;
  string icon = 2;
  string desc = 3;
  string rankStars = 4;
  string amountNumber = 5;
  string avatar = 6;
  string title = 7;
  AdButtonDto button = 8;
  repeated TagInfo tagInfos = 9;
  repeated QualityInfo qualityInfos = 10;
  string starRating = 11;
  string subDesc = 12;
  string priceSymbol = 13;
  string goodsPrice = 14;
  repeated Comment commentList = 15;
  GiftCardInfo giftCardInfo = 16;
  string extraImg = 17;
  repeated AdButtonDto chooseButtonList = 18;
  int64 componentId = 19;
  int64 popDelayTime = 20;
  string callupUrl = 21;
  string jumpUrl = 22;
  string adImgTag = 23;
  FullText fullText = 24;
  ForwardReply forwardReply = 25;
  WxProgramInfo wxProgramInfo = 26;
  string nightIcon = 27;
  string priceDesc = 28;
  string oriPrice = 29;
  string highLightText = 30;
  string highLightColor = 31;
  repeated PauseAdDecisionInfo decisionInfos = 32;
  repeated string clickUrls = 33;
  repeated string showUrls = 34;
}

// Source: com/bapis/bilibili/ad/v1/Tab2ExtraDto.java
message Tab2ExtraDto {
  string coverUrl = 1;
  string title = 2;
  string desc = 3;
  AdButtonDto button = 5;
  int32 autoAnimateTimeMs = 6;
  bool enableClick = 7;
  string panelUrl = 8;
  repeated AppPackageDto downloadWhitelist = 9;
  repeated string openWhitelist = 10;
  bool useAdWebV2 = 11;
  bool enableStoreDirectLaunch = 12;
  int32 salesType = 13;
  int32 landingpageDownloadStyle = 15;
  int32 appstorePriority = 16;
  string appstoreUrl = 17;
  int32 appstoreDelayTime = 18;
  int32 pageCoverType = 19;
  int32 pagePullType = 20;
  AndroidGamePageRes androidGamePageRes = 21;
  IosGamePageRes iosGamePageRes = 22;
  AdBusinessMarkDto adTagStyle = 23;
  AdFeedbackPanelDto feedbackPanel = 24;
  string adCb = 25;
  int32 urlType = 26;
  string avContent = 27;
  int32 downloadWhitelistMode = 28;
  int64 downloadWhitelistDuration = 29;
  string abtest = 30;
  int32 downloadUrlType = 31;
  int32 enableAutoCallup = 32;
  string externalLinkWarning = 33;
  string storeDplinkXiaomi = 34;
  bool enableOpenapkDialog = 35;
  int32 upperLandingpageStyle = 36;
  int32 upperLandingpageInteractionStyle = 37;
  int32 underPlayerFullScreen = 38;
  repeated Text descList = 39;
}

// Source: com/bapis/bilibili/ad/v1/TabExtraDto.java
message TabExtraDto {
  string tabUrl = 1;
  int32 enableStoreDirectLaunch = 2;
  int32 storeCallupCard = 3;
  int32 salesType = 4;
  repeated AppPackageDto downloadWhitelist = 5;
  bool specialIndustry = 6;
  string specialIndustryTips = 7;
  repeated string openWhitelist = 8;
  int32 landingpageDownloadStyle = 9;
  int32 appstorePriority = 10;
  bool useAdWebV2 = 11;
  bool enableDownloadDialog = 12;
  string appstoreUrl = 13;
  int32 appstoreDelayTime = 14;
  string avContent = 15;
}

// Source: com/bapis/bilibili/ad/v1/TabInfoDto.java
message TabInfoDto {
  string tabName = 1;
  Any extra = 2;
  int32 tabVersion = 3;
}

// Source: com/bapis/bilibili/ad/v1/TagInfo.java
message TagInfo {
  string text = 1;
  string textColor = 2;
  string textColorNight = 3;
  string bgColor = 4;
  string bgColorNight = 5;
  string borderColor = 6;
  string borderColorNight = 7;
  string type = 8;
}

// Source: com/bapis/bilibili/ad/v1/Text.java
message Text {
  string text = 1;
  string dayColor = 2;
  string nightColor = 3;
  int64 fontSize = 4;
  int32 textDecoration = 5;
  string img = 6;
  int32 imgHeight = 7;
  int32 imgWidth = 8;
  int32 leftMargin = 9;
  string nightImg = 10;
}

// Source: com/bapis/bilibili/ad/v1/WxProgramInfo.java
message WxProgramInfo {
  string orgId = 1;
  string name = 2;
  string path = 3;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/ad/v1";
