// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.mall.tab3.viewunite.v1;

enum BizType {
  BizTypeNone = 0;
  BizTypeFollowVideo = 1;
  BizTypeReserveActivity = 2;
  BizTypeJumpLink = 3;
  BizTypeFavSeason = 4;
  BizTypeReserveGame = 5;
  UNRECOGNIZED = -1;
}

enum ECode {
  CODE_DEFAULT = 0;
  CODE_404 = 1;
  CODE_TEENAGER = 78301;
  UNRECOGNIZED = -1;
}

enum JumpShowType {
  JST_DEFAULT = 0;
  JST_FULLSCREEN = 1;
  JST_HALFSCREEN = 2;
  UNRECOGNIZED = -1;
}

enum MaterialBizType {
  NONE = 0;
  ACTIVITY = 1;
  BGM = 2;
  EFFECT = 3;
  SHOOT_SAME = 4;
  SHOOT_TOGETHER = 5;
  ACTIVITY_ICON = 6;
  NEW_BGM = 7;
  UNRECOGNIZED = -1;
}

enum MaterialSource {
  DEFAULT = 0;
  BIJIAN = 1;
  UNRECOGNIZED = -1;
}

enum PageCategory {
  COMMON_PAGE = 0;
  ACTIVITY_PAGE = 1;
  UNRECOGNIZED = -1;
}

enum PageType {
  H5 = 0;
  NA = 1;
  UNRECOGNIZED = -1;
}

enum PlayToastEnum {
  PLAYTOAST_UNKNOWN = 0;
  PLAYTOAST_CHARGINGPLUS = 1;
  UNRECOGNIZED = -1;
}

enum TabType {
  TAB_NONE = 0;
  TAB_INTRODUCTION = 1;
  TAB_REPLY = 2;
  TAB_OGV_ACTIVITY = 3;
  UNRECOGNIZED = -1;
}

enum UnionType {
  UGC = 0;
  OGV = 1;
  UNRECOGNIZED = -1;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/ActivityResource.java
message ActivityResource {
  string darkTextColor = 1;
  string dividerColor = 2;
  string bgColor = 3;
  string selectedBgColor = 4;
  string textColor = 5;
  string lightTextColor = 6;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/Arc.java
message Arc {
  int64 aid = 1;
  int64 cid = 2;
  int64 duration = 3;
  Stat stat = 4;
  string bvid = 5;
  int32 copyright = 6;
  Rights right = 7;
  string cover = 8;
  int64 typeId = 9;
  string title = 10;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/ArcRefreshReply.java
message ArcRefreshReply {
  Stat stat = 1;
  SimpleReqUser reqUser = 2;
  SimpleArc arc = 3;
  Online online = 4;
  LikeConfig likeConfig = 5;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/ArcRefreshReq.java
message ArcRefreshReq {
  int64 aid = 1;
  string bvid = 2;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/AttentionCard.java
message AttentionCard {
  repeated ShowTime showTime = 1;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/BizFollowVideoParam.java
message BizFollowVideoParam {
  int64 seasonId = 1;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/BizJumpLinkParam.java
message BizJumpLinkParam {
  string url = 1;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/BizReserveActivityParam.java
message BizReserveActivityParam {
  int64 activityId = 1;
  string from = 2;
  string type = 3;
  int64 oid = 4;
  int64 reserveId = 5;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/BizReserveGameParam.java
message BizReserveGameParam {
  int64 gameId = 1;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/Button.java
message Button {
  string title = 1;
  string uri = 2;
  string icon = 3;
  JumpShowType jumpShowType = 4;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/ChargingPlus.java
message ChargingPlus {
  bool pass = 1;
  repeated PlayToast playToast = 2;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/Chronos.java
message Chronos {
  string md5 = 1;
  string file = 2;
  string sign = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/ChronosParam.java
message ChronosParam {
  string engineVersion = 1;
  string messageProtocol = 2;
  string serviceKey = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/CM.java
message CM {
  Any cmUnderPlayer = 1;
  Any adsControl = 2;
  repeated Any sourceContent = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/CommandDm.java
message CommandDm {
  int64 id = 1;
  int64 oid = 2;
  int64 mid = 3;
  string command = 4;
  string content = 5;
  int32 progress = 6;
  string ctime = 7;
  string mtime = 8;
  string extra = 9;
  string idstr = 10;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/Config.java
message Config {
  Online online = 1;
  PlayerIcon playerIcon = 2;
  StoryEntrance storyEntrance = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/ContractCard.java
message ContractCard {
  float displayProgress = 1;
  int64 displayAccuracy = 2;
  int64 displayDuration = 3;
  int32 showMode = 4;
  int32 pageType = 5;
  UpperInfos upper = 6;
  int32 isFollowDisplay = 7;
  ContractText text = 8;
  int64 followDisplayEndDuration = 9;
  int32 isPlayDisplay = 10;
  int32 isInteractDisplay = 11;
  bool playDisplaySwitch = 12;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/ContractText.java
message ContractText {
  string title = 1;
  string subtitle = 2;
  string inlineTitle = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/Control.java
message Control {
  bool limit = 1;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/DmResource.java
message DmResource {
  repeated bytes commanddms = 1;
  AttentionCard attention = 2;
  repeated OperationCard cards = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/ECodeConfig.java
message ECodeConfig {
  string redirectUrl = 1;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/IconData.java
message IconData {
  string metaJson = 1;
  string spritsImg = 2;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/IntroductionTab.java
message IntroductionTab {
  string title = 1;
  repeated Module modules = 2;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/LikeConfig.java
message LikeConfig {
  UpLikeImg tripleLike = 1;
  string likeAnimation = 2;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/Material.java
message Material {
  string icon = 1;
  string text = 2;
  string url = 3;
  MaterialBizType type = 4;
  string param = 5;
  string staticIcon = 6;
  string bgColor = 7;
  string bgPic = 8;
  int32 jumpType = 9;
  PageType pageType = 10;
  bool needLogin = 11;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/Online.java
message Online {
  bool onlineShow = 1;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/OperationCard.java
message OperationCard {
  int64 id = 1;
  int32 from = 2;
  int32 to = 3;
  bool status = 4;
  BizType bizType = 5;
  OperationCardContent content = 6;
  oneof oneof_0 {
    BizFollowVideoParam follow = 7;
    BizReserveActivityParam reserve = 8;
    BizJumpLinkParam jump = 9;
    BizReserveGameParam game = 10;
  }
  enum ParamCase {
    FOLLOW = 7;
    RESERVE = 8;
    JUMP = 9;
    GAME = 10;
    PARAM_NOT_SET = 0;
  }

}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/OperationCardContent.java
message OperationCardContent {
  string title = 1;
  string subtitle = 2;
  string icon = 3;
  string buttonTitle = 4;
  string buttonSelectedTitle = 5;
  bool showSelected = 6;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/PageControl.java
message PageControl {
  Control toastShow = 1;
  Control materialShow = 2;
  Control upShow = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/PlayerIcon.java
message PlayerIcon {
  string url1 = 1;
  string hash1 = 2;
  string url2 = 3;
  string hash2 = 4;
  string dragLeftPng = 5;
  string middlePng = 6;
  string dragRightPng = 7;
  IconData dragData = 8;
  IconData nodragData = 9;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/PlayToast.java
message PlayToast {
  PlayToastEnum business = 1;
  string iconUrl = 2;
  string text = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/PointMaterial.java
message PointMaterial {
  string url = 1;
  MaterialSource materialSource = 2;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/Relate.java
message Relate {
  int64 deviceType = 1;
  Pagination pagination = 2;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/RelatesFeedReply.java
message RelatesFeedReply {
  repeated RelateCard relates = 1;
  Pagination pagination = 2;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/RelatesFeedReq.java
message RelatesFeedReq {
  int64 aid = 1;
  string bvid = 2;
  string from = 3;
  string spmid = 4;
  string fromSpmid = 5;
  PlayerArgs playerArgs = 6;
  Pagination pagination = 7;
  string sessionId = 8;
  int64 autoPlay = 9;
  string fromTrackId = 10;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/ReplyStyle.java
message ReplyStyle {
  string badgeUrl = 1;
  string badgeText = 2;
  int64 badgeType = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/ReplyTab.java
message ReplyTab {
  ReplyStyle replyStyle = 1;
  string title = 2;
  TabControl control = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/ReqUser.java
message ReqUser {
  int32 favorite = 1;
  int32 like = 2;
  int32 coin = 3;
  int32 favSeason = 4;
  int32 follow = 5;
  int32 dislike = 6;
  Button elecPlusBtn = 7;
  ChargingPlus chargingPlus = 8;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/Rights.java
message Rights {
  bool onlyVipDownload = 1;
  bool noReprint = 2;
  bool download = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/ShowTime.java
message ShowTime {
  int32 startTime = 1;
  int32 endTime = 2;
  double posX = 3;
  double posY = 4;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/SimpleArc.java
message SimpleArc {
  int32 copyright = 1;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/SimpleReqUser.java
message SimpleReqUser {
  int32 favorite = 1;
  int32 like = 2;
  int32 coin = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/StoryEntrance.java
message StoryEntrance {
  bool arcPlayStory = 1;
  string storyIcon = 2;
  bool arcLandscapeStory = 3;
  string landscapeIcon = 4;
  bool playStory = 5;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/Tab.java
message Tab {
  repeated TabModule tabModule = 1;
  string tabBg = 2;
  TabControl danmakuEntrance = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/TabControl.java
message TabControl {
  bool limit = 1;
  bool disable = 2;
  string disableClickTip = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/TabModule.java
message TabModule {
  TabType tabType = 1;
  oneof oneof_0 {
    IntroductionTab introduction = 2;
    ReplyTab reply = 3;
    ActivityTab activityTab = 4;
  }
  enum TabCase {
    INTRODUCTION = 2;
    REPLY = 3;
    ACTIVITY_TAB = 4;
    TAB_NOT_SET = 0;
  }

}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/UpperInfos.java
message UpperInfos {
  int64 fansCount = 1;
  int64 arcCountLastHalfYear = 2;
  int64 firstUpDates = 3;
  int64 totalPlayCount = 4;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/VideoGuide.java
message VideoGuide {
  repeated Material material = 1;
  VideoViewPoint videoPoint = 2;
  ContractCard contractCard = 3;
  Material rightMaterial = 4;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/VideoPoint.java
message VideoPoint {
  int32 type = 1;
  int64 from = 2;
  int64 to = 3;
  string content = 4;
  string cover = 5;
  string logoUrl = 6;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/VideoShot.java
message VideoShot {
  string pvData = 1;
  int32 imgXLen = 2;
  int32 imgYLen = 3;
  int32 imgXSize = 4;
  int32 imgYSize = 5;
  repeated string image = 6;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/VideoViewPoint.java
message VideoViewPoint {
  repeated VideoPoint points = 1;
  PointMaterial pointMaterial = 2;
  bool pointPermanent = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/ViewBase.java
message ViewBase {
  BizType bizType = 1;
  PageCategory pageType = 2;
  PageControl control = 3;
  ActivityResource activityResource = 4;
  Config config = 5;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/ViewProgressReply.java
message ViewProgressReply {
  VideoGuide videoGuide = 1;
  Chronos chronos = 2;
  VideoShot arcShot = 3;
  DmResource dm = 4;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/ViewProgressReq.java
message ViewProgressReq {
  int64 aid = 1;
  int64 cid = 2;
  int64 upMid = 3;
  ChronosParam chronosParam = 4;
  UnionType type = 5;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/ViewReply.java
message ViewReply {
  ViewBase viewBase = 1;
  Arc arc = 2;
  ReqUser reqUser = 3;
  Owner owner = 4;
  Tab tab = 5;
  Any supplement = 6;
  CM cm = 7;
  ECode ecode = 8;
  ECodeConfig ecodeConfig = 9;
  map<string, string> report = 10;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/v1/ViewReq.java
message ViewReq {
  int64 aid = 1;
  string bvid = 2;
  string from = 3;
  string spmid = 4;
  string fromSpmid = 5;
  string sessionId = 6;
  PlayerArgs playerArgs = 7;
  string trackId = 8;
  map<string, string> extraContent = 9;
  string playMode = 10;
  Relate relate = 11;
  string bizExtra = 12;
  string adExtra = 13;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/mall/tab3/viewunite/v1";
