// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.pgc.gateway.player.v2;

import "google/protobuf/timestamp.proto";

enum CanWatchQnReason {
  CAN_WATCH_QN_REASON_DEFAULT = 0;
  CAN_WATCH_QN_REASON_VIP_QN_TRY_WATCH = 1;
  CAN_WATCH_QN_REASON_CTCC_HOME_NETWORK = 2;
  CAN_WATCH_QN_REASON_BIG_VIP = 3;
  CAN_WATCH_QN_REASON_TV_BIG_VIP = 4;
  CAN_WATCH_QN_REASON_OGV_TVOD_PAY = 5;
}

enum ClipType {
  NT_UNKNOWN = 0;
  CLIP_TYPE_OP = 1;
  CLIP_TYPE_ED = 2;
  CLIP_TYPE_HE = 3;
  CLIP_TYPE_MULTI_VIEW = 4;
  CLIP_TYPE_AD = 5;
  CLIP_TYPE_PREVIEW = 6;
}

enum CodeType {
  NOCODE = 0;
  CODE264 = 1;
  CODE265 = 2;
}

enum DrmTechType {
  NON = 0;
  FAIR_PLAY = 1;
  WIDE_VINE = 2;
  BILI_DRM = 3;
}

enum EpPublicityVideoType {
  PRE = 0;
  INLINE = 1;
  ADV_TYPE_UNKNOWN = -1;
}

enum InlineScene {
  UNKNOWN = 0;
  RELATED_EP = 1;
  HE = 2;
  SKIP = 3;
}

enum InlineType {
  TYPE_UNKNOWN = 0;
  TYPE_WHOLE = 1;
  TYPE_HE_CLIP = 2;
  TYPE_PREVIEW = 3;
}

enum LimitActionType {
  LAT_UNKNOWN = 0;
  SHOW_LIMIT_DIALOG = 1;
  SKIP_CURRENT_EP = 2;
}

enum LimitWatchQnReason {
  LIMIT_WATCH_QN_REASON_DEFAULT = 0;
  LIMIT_WATCH_QN_REASON_QN_VIP_PLAY = 1;
  LIMIT_WATCH_QN_REASON_CTCC_HOME_NETWORK_DEVICE_LIMIT = 2;
}

enum PlayErr {
  NoErr = 0;
  WithMultiDeviceLoginErr = 1;
}

enum PromptBarType {
  PROMPT_BAR_TYPE_UNKNOWN = 0;
  OPEN_PROMPT_BAR = 1;
  TRY_PROMPT_BAR = 2;
}

enum QnGroupType {
  UNKNOWN_GROUP = 0;
  VIP_VISION = 1;
}

enum RedemptionMode {
  REDEMPTION_MODE_UNKNOWN = 0;
  EXCHANGE = 1;
  PAYMENT = 2;
}

enum SecurityLevel {
  LEVEL_UNKNOWN = 0;
  LEVEL_L1 = 1;
  LEVEL_L2 = 2;
  LEVEL_L3 = 3;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/Animation.java
message Animation {
  map<string, string> qnSvgaAnimationMap = 1;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/AudioMaterialProto.java
message AudioMaterialProto {
  string audioId = 1;
  string title = 2;
  string edition = 3;
  int64 personId = 4;
  string personName = 5;
  string personAvatar = 6;
  repeated DashItem audio = 7;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/BadgeInfo.java
message BadgeInfo {
  string text = 1;
  string bgColor = 2;
  string bgColorNight = 3;
  string textColor = 4;
  GradientColor bgGradientColor = 5;
  string img = 6;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/BottomDisplay.java
message BottomDisplay {
  TextInfo title = 1;
  string icon = 2;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/BrandReport.java
message BrandReport {
  string brandList = 1;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/ButtonInfo.java
message ButtonInfo {
  string text = 1;
  string textColor = 2;
  string textColorNight = 3;
  string bgColor = 4;
  string bgColorNight = 5;
  string link = 6;
  string actionType = 7;
  BadgeInfo badgeInfo = 8;
  Report report = 9;
  string leftStrikethroughText = 10;
  TextInfo simpleTextInfo = 11;
  string simpleBgColor = 12;
  string simpleBgColorNight = 13;
  GradientColor bgGradientColor = 14;
  map<string, string> orderReportParams = 15;
  TaskParam taskParam = 16;
  string pcLink = 17;
  int64 jumpType = 18;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/CastTips.java
message CastTips {
  int32 code = 1;
  string message_ = 2;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/ClipInfo.java
message ClipInfo {
  int64 materialNo = 1;
  int32 start = 2;
  int32 end = 3;
  ClipType clipType = 4;
  string toastText = 5;
  MultiView multiView = 6;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/ContinuePlayInfo.java
message ContinuePlayInfo {
  int64 continuePlayEpId = 1;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/Coupon.java
message Coupon {
  string couponToken = 1;
  int64 type = 2;
  string value = 3;
  string useDesc = 4;
  string title = 5;
  string desc = 6;
  string payButtonText = 7;
  string payButtonTextLineThrough = 8;
  string realAmount = 9;
  google.protobuf.Timestamp expireTime = 10;
  int64 otype = 11;
  string amount = 12;
  RedemptionMode redemptionMode = 13;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/CouponInfo.java
message CouponInfo {
  CouponToast toast = 1;
  PopWin popWin = 2;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/CouponTextInfo.java
message CouponTextInfo {
  string positivePreview = 1;
  string section = 2;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/CouponToast.java
message CouponToast {
  CouponTextInfo textInfo = 1;
  ButtonInfo button = 2;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/DashItem.java
message DashItem {
  uint32 id = 1;
  string baseUrl = 2;
  repeated string backupUrl = 3;
  uint32 bandwidth = 4;
  uint32 codecid = 5;
  string md5 = 6;
  uint64 size = 7;
  string frameRate = 8;
  string widevinePssh = 9;
  string bilidrmUri = 10;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/DashVideo.java
message DashVideo {
  string baseUrl = 1;
  repeated string backupUrl = 2;
  uint32 bandwidth = 3;
  uint32 codecid = 4;
  string md5 = 5;
  uint64 size = 6;
  uint32 audioId = 7;
  bool noRexcode = 8;
  string frameRate = 9;
  uint32 width = 10;
  uint32 height = 11;
  string widevinePssh = 12;
  string bilidrmUri = 13;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/DataControl.java
message DataControl {
  bool needWatchProgress = 1;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/Dialog.java
message Dialog {
  int64 code = 1;
  string msg = 2;
  string type = 3;
  string styleType = 4;
  DialogConfig config = 5;
  TextInfo title = 6;
  TextInfo subtitle = 7;
  ImageInfo image = 8;
  repeated ButtonInfo button = 9;
  ButtonInfo bottomDesc = 10;
  Report report = 11;
  int32 countDownSec = 12;
  TextInfo rightBottomDesc = 13;
  repeated BottomDisplay bottomDisplay = 14;
  repeated Playlist playList = 15;
  string link = 16;
  ImageInfo halfImage = 17;
  int32 hideButtonOnHalf = 18;
  string linkDesc = 19;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/DialogConfig.java
message DialogConfig {
  bool isShowCover = 1;
  bool isOrientationEnable = 2;
  bool isNestedScrollEnable = 3;
  bool isForceHalfscreenEnable = 4;
  bool isBackgroundTranslucentEnable = 5;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/Dimension.java
message Dimension {
  int32 width = 1;
  int32 height = 2;
  int32 rotate = 3;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/DolbyItem.java
message DolbyItem {
  Type type = 1;
  repeated DashItem audio = 2;
  enum Type {
    NONE = 0;
    COMMON = 1;
    ATMOS = 2;
  }

}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/EndPage.java
message EndPage {
  Dialog dialog = 1;
  bool hide = 2;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/EpInlineVideo.java
message EpInlineVideo {
  int64 materialNo = 1;
  int64 aid = 2;
  int64 cid = 3;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/EpisodeAdvertisementInfo.java
message EpisodeAdvertisementInfo {
  int64 aid = 1;
  string title = 2;
  string link = 3;
  int32 followVideoBntFlag = 4;
  string nextVideoTitle = 5;
  string nextVideoLink = 6;
  int64 cid = 7;
  int32 seasonId = 8;
  int32 follow = 9;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/EpisodeInfo.java
message EpisodeInfo {
  int32 epId = 1;
  int64 cid = 2;
  int64 aid = 3;
  int32 epStatus = 4;
  SeasonInfo seasonInfo = 5;
  string cover = 6;
  string title = 7;
  Interaction interaction = 8;
  string longTitle = 9;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/EpPreVideo.java
message EpPreVideo {
  int64 aid = 1;
  int64 cid = 2;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/EpPublicityVideo.java
message EpPublicityVideo {
  EpPublicityVideoType type = 1;
  oneof oneof_0 {
    EpPreVideo epPreVideo = 2;
    EpInlineVideo epInline = 3;
  }
  enum DataCase {
    DATA_NOT_SET = 0;
    EP_PRE_VIDEO = 2;
    EP_INLINE = 3;
  }

}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/Event.java
message Event {
  Shake shake = 1;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/ExtraData.java
message ExtraData {
  string harmonyDialogPayLink = 1;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/FreyaConfig.java
message FreyaConfig {
  string desc = 1;
  int32 type = 2;
  int32 issuedCnt = 3;
  bool isAlwaysShow = 4;
  int32 screenNumber = 5;
  int32 fullScreenNumber = 6;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/GradientColor.java
message GradientColor {
  string startColor = 1;
  string endColor = 2;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/HideField.java
message HideField {
  bool fragmentDisable = 1;
  int32 vipStatus = 2;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/HighDefinitionTrialInfo.java
message HighDefinitionTrialInfo {
  bool trialAble = 1;
  int32 remainingTimes = 2;
  int32 start = 3;
  int32 timeLength = 4;
  Toast startToast = 5;
  Toast endToast = 6;
  Report report = 7;
  ButtonInfo qualityOpenTipBtn = 8;
  ButtonInfo noLongerTrialBtn = 9;
  int32 trialQualityType = 10;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/HistoryNode.java
message HistoryNode {
  int64 nodeId = 1;
  string title = 2;
  int64 cid = 3;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/ImageInfo.java
message ImageInfo {
  string url = 1;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/Interaction.java
message Interaction {
  HistoryNode historyNode = 1;
  int64 graphVersion = 2;
  string msg = 3;
  bool isInteraction = 4;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/MaterialInfo.java
message MaterialInfo {
  int64 id = 1;
  string img = 2;
  string title = 3;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/MultiDashVideo.java
message MultiDashVideo {
  repeated DashVideo dashVideos = 1;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/MultiView.java
message MultiView {
  string buttonMaterial = 1;
  int64 epId = 2;
  int64 cid = 3;
  int64 avid = 4;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/PayTip.java
message PayTip {
  string title = 1;
  string url = 2;
  string icon = 3;
  int32 type = 4;
  int32 showType = 5;
  string img = 6;
  string bgDayColor = 7;
  string bgNightColor = 8;
  string bgLineColor = 9;
  string bgNightLineColor = 10;
  string textColor = 11;
  string textNightColor = 12;
  int64 viewStartTime = 13;
  repeated ButtonInfo button = 14;
  int32 urlOpenType = 15;
  Report report = 16;
  int32 angleStyle = 17;
  int32 reportType = 18;
  map<string, string> orderReportParams = 19;
  string giantScreenImg = 20;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/PlayAbilityConf.java
message PlayAbilityConf {
  bool backgroundPlayDisable = 1;
  bool flipDisable = 2;
  bool castDisable = 3;
  bool feedbackDisable = 4;
  bool subtitleDisable = 5;
  bool playbackRateDisable = 6;
  bool timeUpDisable = 7;
  bool playbackModeDisable = 8;
  bool scaleModeDisable = 9;
  bool likeDisable = 10;
  bool dislikeDisable = 11;
  bool coinDisable = 12;
  bool elecDisable = 13;
  bool shareDisable = 14;
  bool screenShotDisable = 15;
  bool lockScreenDisable = 16;
  bool recommendDisable = 17;
  bool playbackSpeedDisable = 18;
  bool definitionDisable = 19;
  bool selectionsDisable = 20;
  bool nextDisable = 21;
  bool editDmDisable = 22;
  bool smallWindowDisable = 23;
  bool shakeDisable = 24;
  bool outerDmDisable = 25;
  bool innerDmDisable = 26;
  bool freyaEnterDisable = 27;
  bool dolbyDisable = 28;
  bool freyaFullDisable = 29;
  bool skipOpedSwitchDisable = 30;
  bool recordScreenDisable = 31;
  bool colorOptimizeDisable = 32;
  bool dubbingDisable = 33;
  bool systemRecordScreenDisable = 34;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/PlayAbilityExtConf.java
message PlayAbilityExtConf {
  bool allowCloseSubtitle = 1;
  FreyaConfig freyaConfig = 2;
  CastTips castTips = 3;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/PlayDubbingInfo.java
message PlayDubbingInfo {
  AudioMaterialProto backgroundAudio = 1;
  repeated RoleAudioProto roleAudioList = 2;
  string guideText = 3;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/PlayExtInfo.java
message PlayExtInfo {
  PlayDubbingInfo playDubbingInfo = 1;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/Playlist.java
message Playlist {
  int64 seasonId = 1;
  string title = 2;
  string cover = 3;
  string link = 4;
  BadgeInfo badgeInfo = 5;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/PlayViewBusinessInfo.java
message PlayViewBusinessInfo {
  bool isPreview = 1;
  bool bp = 2;
  string marlinToken = 3;
  string playbackSpeedColor = 4;
  ContinuePlayInfo continuePlayInfo = 5;
  repeated ClipInfo clipInfo = 6;
  InlineType inlineType = 7;
  int32 epWholeDuration = 8;
  Dimension dimension = 9;
  map<int32, QualityExtInfo> qualityExtMap = 10;
  map<string, int32> expMap = 11;
  DrmTechType drmTechType = 12;
  LimitActionType limitActionType = 13;
  bool isDrm = 14;
  RecordInfo recordInfo = 15;
  int32 vipStatus = 16;
  bool isLivePre = 17;
  EpisodeInfo episodeInfo = 18;
  EpisodeAdvertisementInfo episodeAdvertisementInfo = 19;
  UserStatus userStatus = 20;
  repeated EpPublicityVideo epPublicityVideoList = 21;
  uint64 watchTimeLength = 22;
  BrandReport brandReport = 23;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/PlayViewReply.java
message PlayViewReply {
  VideoInfo videoInfo = 1;
  PlayAbilityConf playConf = 2;
  PlayViewBusinessInfo business = 3;
  Event event = 4;
  ViewInfo viewInfo = 5;
  PlayAbilityExtConf playExtConf = 6;
  PlayExtInfo playExtInfo = 7;
  HideField hideField = 8;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/PlayViewReq.java
message PlayViewReq {
  int64 epId = 1;
  int64 cid = 2;
  int64 qn = 3;
  int32 fnver = 4;
  int32 fnval = 5;
  uint32 download = 6;
  int32 forceHost = 7;
  bool fourk = 8;
  string spmid = 9;
  string fromSpmid = 10;
  int32 teenagersMode = 11;
  CodeType preferCodecType = 12;
  bool isPreview = 13;
  int64 roomId = 14;
  bool isNeedViewInfo = 15;
  SceneControl sceneControl = 16;
  InlineScene inlineScene = 17;
  int64 materialNo = 18;
  SecurityLevel securityLevel = 19;
  int64 seasonId = 20;
  DataControl dataControl = 21;
  bool isCloseDrm = 22;
  map<string, string> extraContent = 23;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/PopWin.java
message PopWin {
  string title = 1;
  repeated Coupon coupon = 2;
  repeated ButtonInfo button = 3;
  string bottomText = 4;
  TextInfo popTitle = 5;
  TextInfo subtitle = 6;
  ButtonInfo bottomDesc = 7;
  string cover = 8;
  string popType = 9;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/PromptBar.java
message PromptBar {
  TextInfo title = 1;
  bytes subtitle = 2;
  string subTitleIcon = 3;
  string bgImage = 4;
  GradientColor bgGradientColor = 5;
  repeated ButtonInfo button = 6;
  Report report = 7;
  string fullScreenIpIcon = 8;
  GradientColor fullScreenBgGradientColor = 9;
  PromptBarType promptBarType = 10;
  int64 configType = 11;
  repeated MaterialInfo fixedBenefits = 12;
  repeated MaterialInfo cardOpenGift = 13;
  int64 endTime = 14;
  int32 showOnPaywall = 15;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/QnGroup.java
message QnGroup {
  bool needVip = 1;
  bool needLogin = 2;
  bool vipFree = 3;
  string titleImg = 4;
  string titleImgSelected = 5;
  repeated StreamInfo streamInfos = 6;
  QnGroupType groupType = 7;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/QnItem.java
message QnItem {
  oneof oneof_0 {
    StreamInfo streamInfo = 1;
    QnGroup qnGroup = 2;
  }
  enum ContentCase {
    CONTENT_NOT_SET = 0;
    STREAM_INFO = 1;
    QN_GROUP = 2;
  }

}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/QnPanel.java
message QnPanel {
  repeated QnItem qnItems = 1;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/QualityExtInfo.java
message QualityExtInfo {
  bool trialSupport = 1;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/RecordInfo.java
message RecordInfo {
  string record = 1;
  string recordIcon = 2;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/Report.java
message Report {
  string showEventId = 1;
  string clickEventId = 2;
  string extends = 3;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/ResponseUrl.java
message ResponseUrl {
  uint32 order = 1;
  uint64 length = 2;
  uint64 size = 3;
  string url = 4;
  repeated string backupUrl = 5;
  string md5 = 6;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/Rights.java
message Rights {
  int32 canWatch = 1;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/RoleAudioProto.java
message RoleAudioProto {
  int64 roleId = 1;
  string roleName = 2;
  string roleAvatar = 3;
  repeated AudioMaterialProto audioMaterialList = 4;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/SceneControl.java
message SceneControl {
  bool favPlaylist = 1;
  bool smallWindow = 2;
  bool pip = 3;
  bool wasHeInline = 4;
  bool isNeedTrial = 5;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/Scheme.java
message Scheme {
  ActionType actionType = 1;
  string toast = 2;
  enum ActionType {
    UNKNOWN = 0;
    SHOW_TOAST = 1;
  }

}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/SeasonInfo.java
message SeasonInfo {
  int32 seasonId = 1;
  int32 seasonType = 2;
  int32 seasonStatus = 3;
  string cover = 4;
  string title = 5;
  Rights rights = 6;
  int32 mode = 7;
  string horizontalCover169 = 8;
  string horizontalCover1610 = 9;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/SegmentVideo.java
message SegmentVideo {
  repeated ResponseUrl segment = 1;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/Shake.java
message Shake {
  string file = 1;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/Stream.java
message Stream {
  StreamInfo streamInfo = 1;
  oneof oneof_0 {
    DashVideo dashVideo = 2;
    SegmentVideo segmentVideo = 3;
    MultiDashVideo multiDashVideo = 4;
  }
  enum ContentCase {
    CONTENT_NOT_SET = 0;
    DASH_VIDEO = 2;
    SEGMENT_VIDEO = 3;
    MULTI_DASH_VIDEO = 4;
  }

}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/StreamInfo.java
message StreamInfo {
  uint32 quality = 1;
  string format = 2;
  string description = 3;
  PlayErr errCode = 4;
  StreamLimit limit = 5;
  bool needVip = 6;
  bool needLogin = 7;
  bool intact = 8;
  bool noRexcode = 9;
  int64 attribute = 10;
  string newDescription = 11;
  string displayDesc = 12;
  string superscript = 13;
  Scheme scheme = 14;
  bool supportDrm = 15;
  string subtitle = 16;
  string displayDescImg = 17;
  string descriptionImg = 18;
  string descriptionImgSelected = 19;
  string descriptionFoldImg = 20;
  map<string, string> reportParams = 21;
  string switchToast = 22;
  CanWatchQnReason canWatchQnReason = 23;
  LimitWatchQnReason limitWatchReason = 24;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/StreamLimit.java
message StreamLimit {
  string title = 1;
  string uri = 2;
  string msg = 3;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/TaskParam.java
message TaskParam {
  string taskType = 1;
  int64 activityId = 2;
  int64 tipsId = 3;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/TextInfo.java
message TextInfo {
  string text = 1;
  string textColor = 2;
  string textColorNight = 3;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/Toast.java
message Toast {
  string text = 1;
  ButtonInfo button = 2;
  int32 showStyleType = 3;
  string icon = 4;
  TextInfo toastText = 5;
  Report report = 6;
  map<string, string> orderReportParams = 7;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/UserStatus.java
message UserStatus {
  bool payCheck = 1;
  bool sponsor = 2;
  WatchProgress watchProgress = 3;
  WatchProgress aidWatchProgress = 4;
  string canWatchReason = 5;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/VideoInfo.java
message VideoInfo {
  uint32 quality = 1;
  string format = 2;
  uint64 timelength = 3;
  uint32 videoCodecid = 4;
  repeated Stream streamList = 5;
  repeated DashItem dashAudio = 6;
  DolbyItem dolby = 7;
  uint64 mainTimelength = 8;
  QnPanel qnPanel = 9;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/ViewInfo.java
message ViewInfo {
  Dialog dialog = 1;
  Toast toast = 2;
  CouponInfo couponInfo = 3;
  repeated int64 demandNoPayEpids = 4;
  EndPage endPage = 5;
  map<string, bool> expConfig = 6;
  PopWin popWin = 7;
  PromptBar tryWatchPromptBar = 8;
  PayTip payTip = 9;
  HighDefinitionTrialInfo highDefinitionTrialInfo = 10;
  map<string, Dialog> extDialog = 11;
  Animation animation = 12;
  map<string, Toast> extToast = 13;
  ExtraData extraData = 14;
}

// Source: com/bapis/bilibili/pgc/gateway/player/v2/WatchProgress.java
message WatchProgress {
  int32 lastEpId = 1;
  string lastEpIndex = 2;
  int64 progress = 3;
  int64 lastPlayCid = 4;
  Toast toast = 5;
  Toast toastWithoutTime = 6;
  int64 lastPlayAid = 7;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/pgc/gateway/player/v2";
