// Reconstructed from gRPC service descriptors.
syntax = "proto3";

package bilibili.pgc.gateway.player.v2;

import "bilibili/pgc/gateway/player/v2/messages.proto";

service PlayURL {
  rpc PlayView(.com.bapis.bilibili.pgc.gateway.player.v2.PlayViewReq) returns (.com.bapis.bilibili.pgc.gateway.player.v2.PlayViewReply);
  rpc PlayViewComic(.com.bapis.bilibili.pgc.gateway.player.v2.PlayViewReq) returns (.com.bapis.bilibili.pgc.gateway.player.v2.PlayViewReply);
}

option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/pgc/gateway/player/v2";
