// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.polymer.contract;

// Source: com/bapis/bilibili/polymer/contract/AddContractReply.java
message AddContractReply {
  bool allowMessage = 1;
  bool allowReply = 2;
  string inputText = 3;
  string inputTitle = 4;
}

// Source: com/bapis/bilibili/polymer/contract/AddContractReq.java
message AddContractReq {
  CommonReq common = 1;
  int64 mid = 2;
  int64 upMid = 3;
  int64 aid = 4;
  Source source = 5;
  enum Source {
    PLAY = 0;
    SPACE = 1;
  }

}

// Source: com/bapis/bilibili/polymer/contract/CommonReq.java
message CommonReq {
  string platform = 1;
  int32 build = 2;
  string buvid = 3;
  string mobiApp = 4;
  string device = 5;
  string ip = 6;
  string spmid = 7;
}

// Source: com/bapis/bilibili/polymer/contract/ContractCard.java
message ContractCard {
  string title = 1;
  string subTitle = 2;
}

// Source: com/bapis/bilibili/polymer/contract/ContractConfigReply.java
message ContractConfigReply {
  int32 isFollowDisplay = 1;
  int32 isTripleDisplay = 2;
  ContractCard contractCard = 3;
}

// Source: com/bapis/bilibili/polymer/contract/ContractConfigReq.java
message ContractConfigReq {
  CommonReq common = 1;
  int64 mid = 2;
  int64 upMid = 3;
  int64 aid = 4;
  Source source = 5;
  enum Source {
    PLAY = 0;
    SPACE = 1;
    STORY = 2;
  }

}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/polymer/contract";
