// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.app.overseas.ad.v1;

enum AdArbitration {
  AD_ARBITRATION_UNSPECIFIED = 0;
  AD_ARBITRATION_PRIORITY = 1;
  AD_ARBITRATION_BID = 2;
}

enum BizType {
  BIZ_TYPE_UNKNOWN = 0;
  BIZ_TYPE_UGC = 1;
  BIZ_TYPE_PGC = 2;
  BIZ_TYPE_PUGV = 3;
}

// Source: com/bapis/bilibili/app/overseas/ad/v1/GetSdkAdConfigReply.java
message GetSdkAdConfigReply {
  bool showAd = 1;
  map<string, SlotAdConfigs> slots = 2;
}

// Source: com/bapis/bilibili/app/overseas/ad/v1/GetSdkAdConfigReq.java
message GetSdkAdConfigReq {
}

// Source: com/bapis/bilibili/app/overseas/ad/v1/OverseasAdInfo.java
message OverseasAdInfo {
  map<string, UnitAdConfigs> slots = 1;
}

// Source: com/bapis/bilibili/app/overseas/ad/v1/SlotAdConfigs.java
message SlotAdConfigs {
  repeated SlotSdkConfig configs = 1;
}

// Source: com/bapis/bilibili/app/overseas/ad/v1/SlotSdkConfig.java
message SlotSdkConfig {
  string adFormat = 1;
  string adUnitId = 2;
  int64 loadDelay = 3;
  int64 loadTimeout = 4;
}

// Source: com/bapis/bilibili/app/overseas/ad/v1/UnitAdConfig.java
message UnitAdConfig {
  string adFormat = 1;
  string placementId = 2;
  int64 minPlayInterval = 3;
  int64 showDelay = 4;
  int64 countDown = 5;
  int64 maxShowPerDay = 6;
  int64 maxShowPerVideo = 7;
  int64 preloadDuration = 8;
  double floorEcpm = 9;
  int32 priority = 10;
  int64 minVideoInterval = 11;
}

// Source: com/bapis/bilibili/app/overseas/ad/v1/UnitAdConfigs.java
message UnitAdConfigs {
  repeated UnitAdConfig configs = 1;
  AdArbitration arbitration = 2;
}

// Source: com/bapis/bilibili/app/overseas/ad/v1/VideoAttr.java
message VideoAttr {
  int64 avid = 1;
  int64 cid = 2;
  int64 category = 3;
  int64 subCategory = 4;
  int64 upMid = 5;
  int64 duration = 6;
  int64 upType = 7;
  bool playerIsVertical = 9;
  BizType bizType = 10;
  int64 sid = 11;
  int64 epid = 12;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/app/overseas/ad/v1";
