// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.app.listener.v1;

enum CardModuleType {
  Module_invalid = 0;
  Module_header = 1;
  Module_archive = 2;
  Module_cbtn = 3;
  UNRECOGNIZED = -1;
}

enum ListOrder {
  NO_ORDER = 0;
  ORDER_NORMAL = 1;
  ORDER_REVERSE = 2;
  ORDER_RANDOM = 3;
  UNRECOGNIZED = -1;
}

enum ListSortField {
  NO_SORT = 0;
  SORT_CTIME = 1;
  SORT_VIEWCNT = 2;
  SORT_FAVCNT = 3;
  UNRECOGNIZED = -1;
}

enum PlaylistSource {
  DEFAULT = 0;
  MEM_SPACE = 1;
  AUDIO_COLLECTION = 2;
  AUDIO_CARD = 3;
  USER_FAVOURITE = 4;
  UP_ARCHIVE = 5;
  AUDIO_CACHE = 6;
  PICK_CARD = 7;
  MEDIA_LIST = 8;
  UNRECOGNIZED = -1;
}

enum TopCardType {
  UNSPECIFIED = 0;
  LISTEN_HISTORY = 1;
  FAVORITE_FOLDER = 2;
  UP_RECALL = 3;
  PICK_TODAY = 4;
  UNRECOGNIZED = -1;
}

// Source: com/bapis/bilibili/app/listener/v1/Author.java
message Author {
  int64 mid = 1;
  string name = 2;
  string avatar = 3;
  FollowRelation relation = 4;
}

// Source: com/bapis/bilibili/app/listener/v1/BKArcDetailsReq.java
message BKArcDetailsReq {
  repeated PlayItem items = 1;
  PlayerArgs playerArgs = 2;
}

// Source: com/bapis/bilibili/app/listener/v1/BKArcDetailsResp.java
message BKArcDetailsResp {
  repeated DetailItem list = 1;
}

// Source: com/bapis/bilibili/app/listener/v1/BKArchive.java
message BKArchive {
  int64 oid = 1;
  string title = 2;
  string cover = 3;
  string desc = 4;
  int64 duration = 5;
  int32 rid = 6;
  string rname = 7;
  int64 publish = 8;
  string displayedOid = 9;
  int32 copyright = 10;
  BKArcRights rights = 11;
}

// Source: com/bapis/bilibili/app/listener/v1/BKArcPart.java
message BKArcPart {
  int64 oid = 1;
  int64 subId = 2;
  string title = 3;
  int64 duration = 4;
  int32 page = 5;
}

// Source: com/bapis/bilibili/app/listener/v1/BKArcRights.java
message BKArcRights {
  int32 noReprint = 1;
}

// Source: com/bapis/bilibili/app/listener/v1/BKStat.java
message BKStat {
  int32 like = 1;
  int32 coin = 2;
  int32 favourite = 3;
  int32 reply = 4;
  int32 share = 5;
  int32 view = 6;
  bool hasLike = 7;
  bool hasCoin = 8;
  bool hasFav = 9;
  bool useViewVt = 10;
  string viewVtText = 11;
}

// Source: com/bapis/bilibili/app/listener/v1/CardModule.java
message CardModule {
  CardModuleType moduleType = 1;
  oneof oneof_0 {
    PkcmHeader moduleHeader = 2;
    PkcmArchive moduleArchive = 3;
    PkcmCenterButton moduleCbtn = 4;
  }
  enum ModuleCase {
    MODULE_HEADER = 2;
    MODULE_ARCHIVE = 3;
    MODULE_CBTN = 4;
    MODULE_NOT_SET = 0;
  }

}

// Source: com/bapis/bilibili/app/listener/v1/ClickReq.java
message ClickReq {
  int64 sid = 1;
  ClickAction action = 2;
  enum ClickAction {
    INVALID = 0;
    SHARE = 1;
    UNRECOGNIZED = -1;
  }

}

// Source: com/bapis/bilibili/app/listener/v1/ClickResp.java
message ClickResp {
}

// Source: com/bapis/bilibili/app/listener/v1/CoinAddReq.java
message CoinAddReq {
  PlayItem item = 1;
  int32 num = 2;
  bool thumbUp = 3;
}

// Source: com/bapis/bilibili/app/listener/v1/CoinAddResp.java
message CoinAddResp {
  string message_ = 1;
}

// Source: com/bapis/bilibili/app/listener/v1/DashItem.java
message DashItem {
  uint32 id = 1;
  string baseUrl = 2;
  repeated string backupUrl = 3;
  uint32 bandwidth = 4;
  string mimeType = 5;
  string codecs = 6;
  DashSegmentBase segmentBase = 12;
  uint32 codecid = 13;
  string md5 = 14;
  uint64 size = 15;
}

// Source: com/bapis/bilibili/app/listener/v1/DashSegmentBase.java
message DashSegmentBase {
  string initialization = 1;
  string indexRange = 2;
}

// Source: com/bapis/bilibili/app/listener/v1/DetailItem.java
message DetailItem {
  PlayItem item = 1;
  BKArchive arc = 2;
  repeated BKArcPart parts = 3;
  Author owner = 4;
  BKStat stat = 5;
  int64 lastPart = 6;
  int64 progress = 7;
  int32 playable = 8;
  string message_ = 9;
  map<int64, PlayInfo> playerInfo = 10;
  PlayItem associatedItem = 11;
  int64 lastPlayTime = 12;
  string historyTag = 13;
  DeviceType deviceType = 14;
  FavFolder ugcSeasonInfo = 15;
}

// Source: com/bapis/bilibili/app/listener/v1/EventReq.java
message EventReq {
  EventType eventType = 1;
  PlayItem item = 2;
  enum EventType {
    INVALID = 0;
    GUIDE_BAR_SHOW = 1;
    UNRECOGNIZED = -1;
  }

}

// Source: com/bapis/bilibili/app/listener/v1/EventResp.java
message EventResp {
}

// Source: com/bapis/bilibili/app/listener/v1/EventTracking.java
message EventTracking {
  string operator = 1;
  string batch = 2;
  string trackId = 3;
  string entityType = 4;
  string entityId = 5;
  string trackJson = 6;
}

// Source: com/bapis/bilibili/app/listener/v1/FavFolder.java
message FavFolder {
  int64 fid = 1;
  int32 folderType = 2;
  FavFolderAuthor owner = 3;
  string name = 4;
  string cover = 5;
  string desc = 6;
  int32 count = 7;
  int32 attr = 8;
  int32 state = 9;
  int32 favored = 10;
  int64 ctime = 11;
  int64 mtime = 12;
  int32 statFavCnt = 13;
  int32 statShareCnt = 14;
  int32 statLikeCnt = 15;
  int32 statPlayCnt = 16;
  int32 statReplyCnt = 17;
  int32 favState = 18;
  bool useViewVt = 19;
  string viewVtText = 20;
}

// Source: com/bapis/bilibili/app/listener/v1/FavFolderAction.java
message FavFolderAction {
  int64 fid = 1;
  int32 folderType = 2;
  Action action = 3;
  enum Action {
    UNSPECIFIED = 0;
    ADD = 1;
    DEL = 2;
    UNRECOGNIZED = -1;
  }

}

// Source: com/bapis/bilibili/app/listener/v1/FavFolderAuthor.java
message FavFolderAuthor {
  int64 mid = 1;
  string name = 2;
}

// Source: com/bapis/bilibili/app/listener/v1/FavFolderCreateReq.java
message FavFolderCreateReq {
  string name = 1;
  string desc = 2;
  int32 public_ = 3;
  int32 folderType = 4;
}

// Source: com/bapis/bilibili/app/listener/v1/FavFolderCreateResp.java
message FavFolderCreateResp {
  int64 fid = 1;
  int32 folderType = 2;
  string message_ = 3;
}

// Source: com/bapis/bilibili/app/listener/v1/FavFolderDeleteReq.java
message FavFolderDeleteReq {
  int64 fid = 1;
  int32 folderType = 2;
}

// Source: com/bapis/bilibili/app/listener/v1/FavFolderDeleteResp.java
message FavFolderDeleteResp {
  string message_ = 1;
}

// Source: com/bapis/bilibili/app/listener/v1/FavFolderDetailReq.java
message FavFolderDetailReq {
  int64 fid = 1;
  int32 folderType = 2;
  int64 favMid = 3;
  FavItem lastItem = 4;
  uint32 pageSize = 5;
  bool needFolderInfo = 6;
}

// Source: com/bapis/bilibili/app/listener/v1/FavFolderDetailResp.java
message FavFolderDetailResp {
  uint32 total = 1;
  bool reachEnd = 2;
  repeated FavItemDetail list = 3;
  FavFolder folderInfo = 4;
}

// Source: com/bapis/bilibili/app/listener/v1/FavFolderListReq.java
message FavFolderListReq {
  repeated int32 folderTypes = 1;
  PlayItem item = 2;
}

// Source: com/bapis/bilibili/app/listener/v1/FavFolderListResp.java
message FavFolderListResp {
  repeated FavFolder list = 1;
}

// Source: com/bapis/bilibili/app/listener/v1/FavFolderMeta.java
message FavFolderMeta {
  int64 fid = 1;
  int32 folderType = 2;
}

// Source: com/bapis/bilibili/app/listener/v1/FavItem.java
message FavItem {
  int32 itemType = 1;
  int64 oid = 2;
  int64 fid = 3;
  int64 mid = 4;
  int64 mtime = 5;
  int64 ctime = 6;
  EventTracking et = 7;
}

// Source: com/bapis/bilibili/app/listener/v1/FavItemAddReq.java
message FavItemAddReq {
  int64 fid = 1;
  int32 folderType = 2;
  oneof oneof_0 {
    PlayItem play = 3;
    FavItem fav = 4;
  }
  bool isFastAddFav = 5;
  enum ItemCase {
    PLAY = 3;
    FAV = 4;
    ITEM_NOT_SET = 0;
  }

}

// Source: com/bapis/bilibili/app/listener/v1/FavItemAddResp.java
message FavItemAddResp {
  string message_ = 1;
}

// Source: com/bapis/bilibili/app/listener/v1/FavItemAuthor.java
message FavItemAuthor {
  int64 mid = 1;
  string name = 2;
}

// Source: com/bapis/bilibili/app/listener/v1/FavItemBatchReq.java
message FavItemBatchReq {
  repeated FavFolderAction actions = 1;
  oneof oneof_0 {
    PlayItem play = 2;
    FavItem fav = 3;
  }
  enum ItemCase {
    PLAY = 2;
    FAV = 3;
    ITEM_NOT_SET = 0;
  }

}

// Source: com/bapis/bilibili/app/listener/v1/FavItemBatchResp.java
message FavItemBatchResp {
  string message_ = 1;
}

// Source: com/bapis/bilibili/app/listener/v1/FavItemDelReq.java
message FavItemDelReq {
  int64 fid = 1;
  int32 folderType = 2;
  oneof oneof_0 {
    PlayItem play = 3;
    FavItem fav = 4;
  }
  bool isFastDelFav = 5;
  enum ItemCase {
    PLAY = 3;
    FAV = 4;
    ITEM_NOT_SET = 0;
  }

}

// Source: com/bapis/bilibili/app/listener/v1/FavItemDelResp.java
message FavItemDelResp {
  string message_ = 1;
}

// Source: com/bapis/bilibili/app/listener/v1/FavItemDetail.java
message FavItemDetail {
  FavItem item = 1;
  FavItemAuthor owner = 2;
  FavItemStat stat = 3;
  string cover = 4;
  string name = 5;
  int64 duration = 6;
  int32 state = 7;
  string message_ = 8;
  int32 parts = 9;
}

// Source: com/bapis/bilibili/app/listener/v1/FavItemStat.java
message FavItemStat {
  int32 view = 1;
  int32 reply = 2;
  bool useViewVt = 3;
  string viewVtText = 4;
}

// Source: com/bapis/bilibili/app/listener/v1/FavoredInAnyFoldersReq.java
message FavoredInAnyFoldersReq {
  repeated int32 folderTypes = 1;
  PlayItem item = 2;
}

// Source: com/bapis/bilibili/app/listener/v1/FavoredInAnyFoldersResp.java
message FavoredInAnyFoldersResp {
  repeated FavFolderMeta folders = 1;
  PlayItem item = 2;
}

// Source: com/bapis/bilibili/app/listener/v1/FavTabShowReq.java
message FavTabShowReq {
  int64 mid = 1;
}

// Source: com/bapis/bilibili/app/listener/v1/FavTabShowResp.java
message FavTabShowResp {
  bool showMenu = 1;
}

// Source: com/bapis/bilibili/app/listener/v1/FollowRelation.java
message FollowRelation {
  RelationStatus status = 1;
  enum RelationStatus {
    UNSPECIFIED = 0;
    NO_FOLLOW = 1;
    FOLLOWING = 2;
    FOLLOWED = 3;
    MUTUAL_FOLLOWING = 4;
    SPECIAL_FOLLOWING = 5;
    UNRECOGNIZED = -1;
  }

}

// Source: com/bapis/bilibili/app/listener/v1/FormatDescription.java
message FormatDescription {
  uint32 quality = 1;
  string format = 2;
  string description = 3;
  string displayDesc = 4;
  string superscript = 5;
}

// Source: com/bapis/bilibili/app/listener/v1/MainFavMusicMenuListReq.java
message MainFavMusicMenuListReq {
  int32 tabType = 1;
  string offset = 2;
}

// Source: com/bapis/bilibili/app/listener/v1/MainFavMusicMenuListResp.java
message MainFavMusicMenuListResp {
  int32 tabType = 1;
  repeated MusicMenu menuList = 2;
  bool hasMore = 3;
  string offset = 4;
}

// Source: com/bapis/bilibili/app/listener/v1/MainFavMusicSubTabListReq.java
message MainFavMusicSubTabListReq {
}

// Source: com/bapis/bilibili/app/listener/v1/MainFavMusicSubTabListResp.java
message MainFavMusicSubTabListResp {
  repeated MusicSubTab tabs = 1;
  MainFavMusicMenuListResp defaultTabRes = 2;
  map<int32, MainFavMusicMenuListResp> firstPageRes = 3;
}

// Source: com/bapis/bilibili/app/listener/v1/MedialistItem.java
message MedialistItem {
  PlayItem item = 1;
  string title = 2;
  string cover = 3;
  int64 duration = 4;
  int32 parts = 5;
  int64 upMid = 6;
  string upName = 7;
  int32 state = 8;
  string message_ = 9;
  int64 statView = 10;
  int64 statReply = 11;
  bool useStatViewVt = 12;
  string statViewVtText = 13;
}

// Source: com/bapis/bilibili/app/listener/v1/MedialistReq.java
message MedialistReq {
  int64 listType = 1;
  int64 bizId = 2;
  string offset = 3;
}

// Source: com/bapis/bilibili/app/listener/v1/MedialistResp.java
message MedialistResp {
  int64 total = 1;
  bool hasMore = 2;
  string offset = 3;
  repeated MedialistItem items = 4;
  MedialistUpInfo upInfo = 5;
}

// Source: com/bapis/bilibili/app/listener/v1/MedialistUpInfo.java
message MedialistUpInfo {
  int64 mid = 1;
  string avatar = 2;
  int64 fans = 3;
  string name = 4;
}

// Source: com/bapis/bilibili/app/listener/v1/MenuDeleteReq.java
message MenuDeleteReq {
  int64 id = 1;
}

// Source: com/bapis/bilibili/app/listener/v1/MenuDeleteResp.java
message MenuDeleteResp {
  string message_ = 1;
}

// Source: com/bapis/bilibili/app/listener/v1/MenuEditReq.java
message MenuEditReq {
  int64 id = 1;
  string title = 2;
  string desc = 3;
  int32 isPublic = 4;
}

// Source: com/bapis/bilibili/app/listener/v1/MenuEditResp.java
message MenuEditResp {
  string message_ = 1;
}

// Source: com/bapis/bilibili/app/listener/v1/MenuSubscribeReq.java
message MenuSubscribeReq {
  SubscribeAction action = 1;
  int64 targetId = 2;
  enum SubscribeAction {
    INVALID = 0;
    ADD = 1;
    DEL = 2;
    UNRECOGNIZED = -1;
  }

}

// Source: com/bapis/bilibili/app/listener/v1/MenuSubscribeResp.java
message MenuSubscribeResp {
  string message_ = 1;
}

// Source: com/bapis/bilibili/app/listener/v1/MusicMenu.java
message MusicMenu {
  int64 id = 1;
  int32 menuType = 2;
  string title = 3;
  string desc = 4;
  string cover = 5;
  MusicMenuAuthor owner = 6;
  int32 state = 7;
  int64 attr = 8;
  MusicMenuStat stat = 9;
  int64 total = 10;
  int64 ctime = 11;
  string uri = 12;
}

// Source: com/bapis/bilibili/app/listener/v1/MusicMenuAuthor.java
message MusicMenuAuthor {
  int64 mid = 1;
  string name = 2;
  string avatar = 3;
}

// Source: com/bapis/bilibili/app/listener/v1/MusicMenuStat.java
message MusicMenuStat {
  int64 play = 1;
  int64 reply = 2;
}

// Source: com/bapis/bilibili/app/listener/v1/MusicSubTab.java
message MusicSubTab {
  string name = 1;
  int32 tabType = 2;
  int64 total = 3;
}

// Source: com/bapis/bilibili/app/listener/v1/PageOption.java
message PageOption {
  uint32 pageSize = 1;
  Direction direction = 2;
  PlayItem lastItem = 3;
  enum Direction {
    SCROLL_DOWN = 0;
    SCROLL_UP = 1;
    UNRECOGNIZED = -1;
  }

}

// Source: com/bapis/bilibili/app/listener/v1/PickArchive.java
message PickArchive {
  PlayItem item = 1;
  string title = 2;
  PickArchiveAuthor owner = 3;
  string cover = 4;
  int64 duration = 5;
  int32 parts = 6;
  int32 statView = 7;
  int32 statReply = 8;
  int32 state = 9;
  string message_ = 10;
  bool useStatViewVt = 11;
  string statViewVtText = 12;
}

// Source: com/bapis/bilibili/app/listener/v1/PickArchiveAuthor.java
message PickArchiveAuthor {
  int64 mid = 1;
  string name = 2;
}

// Source: com/bapis/bilibili/app/listener/v1/PickCard.java
message PickCard {
  int64 pickId = 1;
  int64 cardId = 2;
  string cardName = 3;
  repeated CardModule modules = 4;
}

// Source: com/bapis/bilibili/app/listener/v1/PickCardDetailReq.java
message PickCardDetailReq {
  int64 cardId = 1;
  int64 pickId = 2;
}

// Source: com/bapis/bilibili/app/listener/v1/PickCardDetailResp.java
message PickCardDetailResp {
  int64 cardId = 1;
  int64 pickId = 2;
  repeated CardModule modules = 3;
}

// Source: com/bapis/bilibili/app/listener/v1/PickFeedReq.java
message PickFeedReq {
  int64 offset = 1;
}

// Source: com/bapis/bilibili/app/listener/v1/PickFeedResp.java
message PickFeedResp {
  int64 offset = 1;
  repeated PickCard cards = 2;
}

// Source: com/bapis/bilibili/app/listener/v1/PkcmArchive.java
message PkcmArchive {
  PickArchive arc = 1;
  string pickReason = 2;
}

// Source: com/bapis/bilibili/app/listener/v1/PkcmCenterButton.java
message PkcmCenterButton {
  string iconHead = 1;
  string iconTail = 2;
  string title = 3;
  string uri = 4;
}

// Source: com/bapis/bilibili/app/listener/v1/PkcmHeader.java
message PkcmHeader {
  string title = 1;
  string desc = 2;
  string btnIcon = 3;
  string btnText = 4;
  string btnUri = 5;
}

// Source: com/bapis/bilibili/app/listener/v1/PlayActionReportReq.java
message PlayActionReportReq {
  PlayItem item = 1;
  string fromSpmid = 2;
}

// Source: com/bapis/bilibili/app/listener/v1/PlayDASH.java
message PlayDASH {
  uint32 duration = 1;
  float minBufferTime = 2;
  repeated DashItem audio = 3;
}

// Source: com/bapis/bilibili/app/listener/v1/PlayHistoryAddReq.java
message PlayHistoryAddReq {
  PlayItem item = 1;
  int64 progress = 2;
  int64 duration = 3;
  int32 playStyle = 4;
}

// Source: com/bapis/bilibili/app/listener/v1/PlayHistoryDelReq.java
message PlayHistoryDelReq {
  repeated PlayItem items = 1;
  bool truncate = 2;
}

// Source: com/bapis/bilibili/app/listener/v1/PlayHistoryReq.java
message PlayHistoryReq {
  PageOption pageOpt = 1;
  int64 localTodayZero = 2;
  Pagination pagination = 3;
}

// Source: com/bapis/bilibili/app/listener/v1/PlayHistoryResp.java
message PlayHistoryResp {
  uint32 total = 1;
  bool reachEnd = 2;
  repeated DetailItem list = 3;
  PaginationReply paginationReply = 4;
}

// Source: com/bapis/bilibili/app/listener/v1/PlayInfo.java
message PlayInfo {
  uint32 qn = 1;
  string format = 2;
  int32 qnType = 3;
  oneof oneof_0 {
    PlayURL playUrl = 4;
    PlayDASH playDash = 5;
  }
  uint32 fnver = 6;
  uint32 fnval = 7;
  repeated FormatDescription formats = 8;
  uint32 videoCodecid = 9;
  uint64 length = 10;
  uint32 code = 11;
  string message_ = 12;
  uint64 expireTime = 13;
  VolumeInfo volume = 14;
  enum InfoCase {
    PLAY_URL = 4;
    PLAY_DASH = 5;
    INFO_NOT_SET = 0;
  }

}

// Source: com/bapis/bilibili/app/listener/v1/PlayItem.java
message PlayItem {
  int32 itemType = 1;
  int64 oid = 3;
  repeated int64 subId = 4;
  EventTracking et = 5;
  int64 pos = 6;
}

// Source: com/bapis/bilibili/app/listener/v1/PlaylistAddReq.java
message PlaylistAddReq {
  repeated PlayItem items = 1;
  oneof oneof_0 {
    PlayItem after = 2;
    bool head = 3;
    bool tail = 4;
  }
  enum PosCase {
    AFTER = 2;
    HEAD = 3;
    TAIL = 4;
    POS_NOT_SET = 0;
  }

}

// Source: com/bapis/bilibili/app/listener/v1/PlaylistDelReq.java
message PlaylistDelReq {
  repeated PlayItem items = 1;
  bool truncate = 2;
}

// Source: com/bapis/bilibili/app/listener/v1/PlaylistOffset.java
message PlaylistOffset {
  PlaylistScrollDirection direction = 1;
  PlayItem lastItem = 2;
  RandomOrderStatus randomState = 3;
  SortOption sortOpt = 4;
  enum PlaylistScrollDirection {
    DOWN = 0;
    UP = 1;
    UNRECOGNIZED = -1;
  }

}

// Source: com/bapis/bilibili/app/listener/v1/PlaylistReq.java
message PlaylistReq {
  PlaylistSource from = 1;
  int64 id = 2;
  PlayItem anchor = 3;
  PageOption pageOpt = 4;
  PlayerArgs playerArgs = 5;
  int64 extraId = 6;
  SortOption sortOpt = 7;
  Pagination pagination = 8;
}

// Source: com/bapis/bilibili/app/listener/v1/PlaylistResp.java
message PlaylistResp {
  uint32 total = 1;
  bool reachStart = 2;
  bool reachEnd = 3;
  repeated DetailItem list = 4;
  PlayItem lastPlay = 5;
  int64 lastProgress = 6;
  PaginationReply paginationReply = 7;
}

// Source: com/bapis/bilibili/app/listener/v1/PlayURL.java
message PlayURL {
  repeated ResponseUrl durl = 1;
}

// Source: com/bapis/bilibili/app/listener/v1/PlayURLReq.java
message PlayURLReq {
  PlayItem item = 1;
  PlayerArgs playerArgs = 2;
}

// Source: com/bapis/bilibili/app/listener/v1/PlayURLResp.java
message PlayURLResp {
  PlayItem item = 1;
  int32 playable = 2;
  string message_ = 3;
  map<int64, PlayInfo> playerInfo = 4;
}

// Source: com/bapis/bilibili/app/listener/v1/RandomOrderStatus.java
message RandomOrderStatus {
  repeated uint64 exposedPos = 1;
}

// Source: com/bapis/bilibili/app/listener/v1/RcmdOffset.java
message RcmdOffset {
  int64 rcmdFrom = 1;
  int64 id = 2;
  int32 page = 3;
  string sessionId = 4;
  string fromTrackid = 5;
}

// Source: com/bapis/bilibili/app/listener/v1/RcmdPlaylistReq.java
message RcmdPlaylistReq {
  RcmdFrom from = 1;
  int64 id = 2;
  bool needHistory = 3;
  bool needTopCards = 4;
  PlayerArgs playerArgs = 5;
  Pagination page = 6;
  map<string, string> annotations = 7;
  enum RcmdFrom {
    UNSPECIFIED = 0;
    UP_ARCHIVE = 1;
    INDEX_ENTRY = 2;
    ARCHIVE_VIEW = 3;
    UNRECOGNIZED = -1;
  }

}

// Source: com/bapis/bilibili/app/listener/v1/RcmdPlaylistResp.java
message RcmdPlaylistResp {
  repeated DetailItem list = 1;
  int64 historyLen = 2;
  repeated TopCard topCards = 3;
  PaginationReply nextPage = 4;
}

// Source: com/bapis/bilibili/app/listener/v1/ResponseUrl.java
message ResponseUrl {
  uint32 order = 1;
  uint64 length = 2;
  uint64 size = 3;
  string ahead = 4;
  string vhead = 5;
  string url = 6;
  repeated string backupUrl = 7;
  string md5 = 8;
}

// Source: com/bapis/bilibili/app/listener/v1/SortOption.java
message SortOption {
  ListOrder order = 1;
  ListSortField sortField = 2;
  bool isSwitching = 3;
}

// Source: com/bapis/bilibili/app/listener/v1/ThumbUpReq.java
message ThumbUpReq {
  PlayItem item = 1;
  ThumbType action = 2;
  enum ThumbType {
    LIKE = 0;
    CANCEL_LIKE = 1;
    DISLIKE = 2;
    CANCEL_DISLIKE = 3;
    UNRECOGNIZED = -1;
  }

}

// Source: com/bapis/bilibili/app/listener/v1/ThumbUpResp.java
message ThumbUpResp {
  string message_ = 1;
}

// Source: com/bapis/bilibili/app/listener/v1/TopCard.java
message TopCard {
  string title = 1;
  PlayStrategy playStyle = 2;
  TopCardType cardType = 3;
  oneof oneof_0 {
    TpcdHistory listenHistory = 4;
    TpcdFavFolder favFolder = 5;
    TpcdUpRecall upRecall = 6;
    TpcdPickToday pickToday = 7;
  }
  int64 pos = 8;
  string titleIcon = 9;
  enum CardCase {
    LISTEN_HISTORY = 4;
    FAV_FOLDER = 5;
    UP_RECALL = 6;
    PICK_TODAY = 7;
    CARD_NOT_SET = 0;
  }

  enum PlayStrategy {
    NO_INTERRUPT = 0;
    PLAY_TARGET = 1;
    PLAY_FIRST = 2;
    UNRECOGNIZED = -1;
  }

}

// Source: com/bapis/bilibili/app/listener/v1/TpcdFavFolder.java
message TpcdFavFolder {
  DetailItem item = 1;
  string text = 2;
  string pic = 3;
  int64 fid = 4;
  int32 folderType = 5;
}

// Source: com/bapis/bilibili/app/listener/v1/TpcdHistory.java
message TpcdHistory {
  DetailItem item = 1;
  string text = 2;
  string pic = 3;
}

// Source: com/bapis/bilibili/app/listener/v1/TpcdPickToday.java
message TpcdPickToday {
  DetailItem item = 1;
  string text = 2;
  string pic = 3;
  int64 pickId = 4;
  int64 pickCardId = 5;
}

// Source: com/bapis/bilibili/app/listener/v1/TpcdUpRecall.java
message TpcdUpRecall {
  int64 upMid = 1;
  string text = 2;
  string avatar = 3;
  int64 medialistType = 4;
  int64 medialistBizId = 5;
  DetailItem item = 6;
}

// Source: com/bapis/bilibili/app/listener/v1/TripleLikeReq.java
message TripleLikeReq {
  PlayItem item = 1;
}

// Source: com/bapis/bilibili/app/listener/v1/TripleLikeResp.java
message TripleLikeResp {
  string message_ = 1;
  bool thumbOk = 2;
  bool coinOk = 3;
  bool favOk = 4;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/app/listener/v1";
