// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.live.xuserreward.v1;

import "bilibili/live/component/common_model/fans_club/messages.proto";
import "bilibili/live/component/common_model/user_dagw/messages.proto";

// Source: com/bapis/bilibili/live/xuserreward/v1/InteractWord.java
message InteractWord {
  int64 uid = 1;
  string uname = 2;
  string unameColor = 3;
  repeated int64 identities = 4;
  int64 msgType = 5;
  int64 roomid = 6;
  int64 timestamp = 7;
  int64 score = 8;
  InteractWord_FansMedalInfo fansMedal = 9;
  int64 isSpread = 10;
  string spreadInfo = 11;
  InteractWord_ContributionInfo contribution = 12;
  string spreadDesc = 13;
  int64 tailIcon = 14;
  int64 triggerTime = 15;
  int64 privilegeType = 16;
  int64 coreUserType = 17;
  string tailText = 18;
  InteractWord_ContributionInfoV2 contributionV2 = 19;
  com.bapis.bilibili.live.component.common_model.fans_club.GroupMedalBrief groupMedal = 20;
  bool isMystery = 21;
  com.bapis.bilibili.live.component.common_model.user_dagw.UserInfo uinfo = 22;
  InteractWord_UserAnchorRelation relationTail = 23;
  InteractWord_ControlInfo controlInfo = 24;
  int64 from = 25;
}

// Source: com/bapis/bilibili/live/xuserreward/v1/InteractWord.java
message InteractWord_ContributionInfo {
  int64 grade = 1;
}

// Source: com/bapis/bilibili/live/xuserreward/v1/InteractWord.java
message InteractWord_ContributionInfoV2 {
  int64 grade = 1;
  string rankType = 2;
  string text = 3;
}

// Source: com/bapis/bilibili/live/xuserreward/v1/InteractWord.java
message InteractWord_ControlInfo {
  int64 type = 1;
  string text = 2;
  string textColor = 3;
}

// Source: com/bapis/bilibili/live/xuserreward/v1/InteractWord.java
message InteractWord_FansMedalInfo {
  int64 targetId = 1;
  int64 medalLevel = 2;
  string medalName = 3;
  int64 medalColor = 4;
  int64 medalColorStart = 5;
  int64 medalColorEnd = 6;
  int64 medalColorBorder = 7;
  int64 isLighted = 8;
  int64 guardLevel = 9;
  string special = 10;
  int64 iconId = 11;
  int64 anchorRoomid = 12;
  int64 score = 13;
}

// Source: com/bapis/bilibili/live/xuserreward/v1/InteractWord.java
message InteractWord_UserAnchorRelation {
  string tailIcon = 1;
  string tailGuideText = 2;
  int64 tailType = 3;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/live/xuserreward/v1";
