// Reconstructed from gRPC service descriptors.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: bilibili/app/show/v1/services.proto

package v1

import (
	context "context"
	v1 "github.com/stmtc233/bili-grpc-api-go/bilibili/app/show/popular/v1"
	v11 "github.com/stmtc233/bili-grpc-api-go/bilibili/app/show/rank/v1"
	v12 "github.com/stmtc233/bili-grpc-api-go/bilibili/app/show/region/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Popular_Index_FullMethodName = "/bilibili.app.show.v1.Popular/Index"
)

// PopularClient is the client API for Popular service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PopularClient interface {
	Index(ctx context.Context, in *v1.PopularResultReq, opts ...grpc.CallOption) (*v1.PopularReply, error)
}

type popularClient struct {
	cc grpc.ClientConnInterface
}

func NewPopularClient(cc grpc.ClientConnInterface) PopularClient {
	return &popularClient{cc}
}

func (c *popularClient) Index(ctx context.Context, in *v1.PopularResultReq, opts ...grpc.CallOption) (*v1.PopularReply, error) {
	out := new(v1.PopularReply)
	err := c.cc.Invoke(ctx, Popular_Index_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PopularServer is the server API for Popular service.
// All implementations must embed UnimplementedPopularServer
// for forward compatibility
type PopularServer interface {
	Index(context.Context, *v1.PopularResultReq) (*v1.PopularReply, error)
	mustEmbedUnimplementedPopularServer()
}

// UnimplementedPopularServer must be embedded to have forward compatible implementations.
type UnimplementedPopularServer struct {
}

func (UnimplementedPopularServer) Index(context.Context, *v1.PopularResultReq) (*v1.PopularReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Index not implemented")
}
func (UnimplementedPopularServer) mustEmbedUnimplementedPopularServer() {}

// UnsafePopularServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PopularServer will
// result in compilation errors.
type UnsafePopularServer interface {
	mustEmbedUnimplementedPopularServer()
}

func RegisterPopularServer(s grpc.ServiceRegistrar, srv PopularServer) {
	s.RegisterService(&Popular_ServiceDesc, srv)
}

func _Popular_Index_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.PopularResultReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PopularServer).Index(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Popular_Index_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PopularServer).Index(ctx, req.(*v1.PopularResultReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Popular_ServiceDesc is the grpc.ServiceDesc for Popular service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Popular_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bilibili.app.show.v1.Popular",
	HandlerType: (*PopularServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Index",
			Handler:    _Popular_Index_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bilibili/app/show/v1/services.proto",
}

const (
	Rank_RankAll_FullMethodName    = "/bilibili.app.show.v1.Rank/RankAll"
	Rank_RankRegion_FullMethodName = "/bilibili.app.show.v1.Rank/RankRegion"
)

// RankClient is the client API for Rank service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RankClient interface {
	RankAll(ctx context.Context, in *v11.RankAllResultReq, opts ...grpc.CallOption) (*v11.RankListReply, error)
	RankRegion(ctx context.Context, in *v11.RankRegionResultReq, opts ...grpc.CallOption) (*v11.RankListReply, error)
}

type rankClient struct {
	cc grpc.ClientConnInterface
}

func NewRankClient(cc grpc.ClientConnInterface) RankClient {
	return &rankClient{cc}
}

func (c *rankClient) RankAll(ctx context.Context, in *v11.RankAllResultReq, opts ...grpc.CallOption) (*v11.RankListReply, error) {
	out := new(v11.RankListReply)
	err := c.cc.Invoke(ctx, Rank_RankAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankClient) RankRegion(ctx context.Context, in *v11.RankRegionResultReq, opts ...grpc.CallOption) (*v11.RankListReply, error) {
	out := new(v11.RankListReply)
	err := c.cc.Invoke(ctx, Rank_RankRegion_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RankServer is the server API for Rank service.
// All implementations must embed UnimplementedRankServer
// for forward compatibility
type RankServer interface {
	RankAll(context.Context, *v11.RankAllResultReq) (*v11.RankListReply, error)
	RankRegion(context.Context, *v11.RankRegionResultReq) (*v11.RankListReply, error)
	mustEmbedUnimplementedRankServer()
}

// UnimplementedRankServer must be embedded to have forward compatible implementations.
type UnimplementedRankServer struct {
}

func (UnimplementedRankServer) RankAll(context.Context, *v11.RankAllResultReq) (*v11.RankListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RankAll not implemented")
}
func (UnimplementedRankServer) RankRegion(context.Context, *v11.RankRegionResultReq) (*v11.RankListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RankRegion not implemented")
}
func (UnimplementedRankServer) mustEmbedUnimplementedRankServer() {}

// UnsafeRankServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RankServer will
// result in compilation errors.
type UnsafeRankServer interface {
	mustEmbedUnimplementedRankServer()
}

func RegisterRankServer(s grpc.ServiceRegistrar, srv RankServer) {
	s.RegisterService(&Rank_ServiceDesc, srv)
}

func _Rank_RankAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v11.RankAllResultReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankServer).RankAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rank_RankAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankServer).RankAll(ctx, req.(*v11.RankAllResultReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rank_RankRegion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v11.RankRegionResultReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankServer).RankRegion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rank_RankRegion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankServer).RankRegion(ctx, req.(*v11.RankRegionResultReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Rank_ServiceDesc is the grpc.ServiceDesc for Rank service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rank_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bilibili.app.show.v1.Rank",
	HandlerType: (*RankServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RankAll",
			Handler:    _Rank_RankAll_Handler,
		},
		{
			MethodName: "RankRegion",
			Handler:    _Rank_RankRegion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bilibili/app/show/v1/services.proto",
}

const (
	Region_Region_FullMethodName = "/bilibili.app.show.v1.Region/Region"
)

// RegionClient is the client API for Region service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegionClient interface {
	Region(ctx context.Context, in *v12.RegionReq, opts ...grpc.CallOption) (*v12.RegionReply, error)
}

type regionClient struct {
	cc grpc.ClientConnInterface
}

func NewRegionClient(cc grpc.ClientConnInterface) RegionClient {
	return &regionClient{cc}
}

func (c *regionClient) Region(ctx context.Context, in *v12.RegionReq, opts ...grpc.CallOption) (*v12.RegionReply, error) {
	out := new(v12.RegionReply)
	err := c.cc.Invoke(ctx, Region_Region_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegionServer is the server API for Region service.
// All implementations must embed UnimplementedRegionServer
// for forward compatibility
type RegionServer interface {
	Region(context.Context, *v12.RegionReq) (*v12.RegionReply, error)
	mustEmbedUnimplementedRegionServer()
}

// UnimplementedRegionServer must be embedded to have forward compatible implementations.
type UnimplementedRegionServer struct {
}

func (UnimplementedRegionServer) Region(context.Context, *v12.RegionReq) (*v12.RegionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Region not implemented")
}
func (UnimplementedRegionServer) mustEmbedUnimplementedRegionServer() {}

// UnsafeRegionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegionServer will
// result in compilation errors.
type UnsafeRegionServer interface {
	mustEmbedUnimplementedRegionServer()
}

func RegisterRegionServer(s grpc.ServiceRegistrar, srv RegionServer) {
	s.RegisterService(&Region_ServiceDesc, srv)
}

func _Region_Region_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v12.RegionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegionServer).Region(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Region_Region_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegionServer).Region(ctx, req.(*v12.RegionReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Region_ServiceDesc is the grpc.ServiceDesc for Region service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Region_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bilibili.app.show.v1.Region",
	HandlerType: (*RegionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Region",
			Handler:    _Region_Region_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bilibili/app/show/v1/services.proto",
}
