// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.app.distribution.setting.pegasus;

import "bilibili/app/distribution/messages.proto";

// Source: com/bapis/bilibili/app/distribution/setting/pegasus/FeedModeValue.java
message FeedModeValue {
  com.bapis.bilibili.app.distribution.Int64Value value = 1;
}

// Source: com/bapis/bilibili/app/distribution/setting/pegasus/PegasusAutoPlay.java
message PegasusAutoPlay {
  com.bapis.bilibili.app.distribution.Int64Value single = 1;
  com.bapis.bilibili.app.distribution.Int64Value double_ = 2;
  com.bapis.bilibili.app.distribution.BoolValue singleAffectedByServerSide = 3;
  com.bapis.bilibili.app.distribution.BoolValue doubleAffectedByServerSide = 4;
}

// Source: com/bapis/bilibili/app/distribution/setting/pegasus/PegasusColumnValue.java
message PegasusColumnValue {
  com.bapis.bilibili.app.distribution.Int64Value value = 1;
  com.bapis.bilibili.app.distribution.BoolValue affectedByServerSide = 2;
}

// Source: com/bapis/bilibili/app/distribution/setting/pegasus/PegasusDeviceConfig.java
message PegasusDeviceConfig {
  PegasusColumnValue column = 1;
  FeedModeValue mode = 2;
  PegasusAutoPlay autoPlay = 3;
}

// Source: com/bapis/bilibili/app/distribution/setting/pegasus/PegasusDeviceWithoutFplocalConfig.java
message PegasusDeviceWithoutFplocalConfig {
  com.bapis.bilibili.app.distribution.Int64Value autoRefreshState = 1;
}

// Source: com/bapis/bilibili/app/distribution/setting/pegasus/PegasusMidConfig.java
message PegasusMidConfig {
  com.bapis.bilibili.app.distribution.Int64Value column = 1;
  com.bapis.bilibili.app.distribution.Int64Value playMode = 2;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/app/distribution/setting/pegasus";
