// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: bilibili/broadcast/live/multi_conn.proto

package live

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScoreEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*ScoreEventInfo `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	InvokingTime int64 `protobuf:"varint,2,opt,name=invoking_time,json=invokingTime,proto3" json:"invoking_time,omitempty"`
	Version int64 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Layout string `protobuf:"bytes,4,opt,name=layout,proto3" json:"layout,omitempty"`
	RoomStatus int64 `protobuf:"varint,5,opt,name=room_status,json=roomStatus,proto3" json:"room_status,omitempty"`
	BizSessionId string `protobuf:"bytes,6,opt,name=biz_session_id,json=bizSessionId,proto3" json:"biz_session_id,omitempty"`
}

func (x *ScoreEvent) Reset() {
	*x = ScoreEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_broadcast_live_multi_conn_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScoreEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreEvent) ProtoMessage() {}

func (x *ScoreEvent) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_broadcast_live_multi_conn_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreEvent.ProtoReflect.Descriptor instead.
func (*ScoreEvent) Descriptor() ([]byte, []int) {
	return file_bilibili_broadcast_live_multi_conn_proto_rawDescGZIP(), []int{0}
}

func (x *ScoreEvent) GetData() []*ScoreEventInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ScoreEvent) GetInvokingTime() int64 {
	if x != nil {
		return x.InvokingTime
	}
	return 0
}

func (x *ScoreEvent) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ScoreEvent) GetLayout() string {
	if x != nil {
		return x.Layout
	}
	return ""
}

func (x *ScoreEvent) GetRoomStatus() int64 {
	if x != nil {
		return x.RoomStatus
	}
	return 0
}

func (x *ScoreEvent) GetBizSessionId() string {
	if x != nil {
		return x.BizSessionId
	}
	return ""
}

type ScoreEventInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	RoomId int64 `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Avatar string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Nickname string `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Price int64 `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	PriceText string `protobuf:"bytes,6,opt,name=price_text,json=priceText,proto3" json:"price_text,omitempty"`
	Gender int64 `protobuf:"varint,7,opt,name=gender,proto3" json:"gender,omitempty"`
}

func (x *ScoreEventInfo) Reset() {
	*x = ScoreEventInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_broadcast_live_multi_conn_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScoreEventInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreEventInfo) ProtoMessage() {}

func (x *ScoreEventInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_broadcast_live_multi_conn_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreEventInfo.ProtoReflect.Descriptor instead.
func (*ScoreEventInfo) Descriptor() ([]byte, []int) {
	return file_bilibili_broadcast_live_multi_conn_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ScoreEventInfo) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ScoreEventInfo) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *ScoreEventInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *ScoreEventInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ScoreEventInfo) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ScoreEventInfo) GetPriceText() string {
	if x != nil {
		return x.PriceText
	}
	return ""
}

func (x *ScoreEventInfo) GetGender() int64 {
	if x != nil {
		return x.Gender
	}
	return 0
}

var File_bilibili_broadcast_live_multi_conn_proto protoreflect.FileDescriptor

var file_bilibili_broadcast_live_multi_conn_proto_rawDesc = []byte{
	0x0a, 0x28, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2f, 0x62, 0x72, 0x6f, 0x61, 0x64,
	0x63, 0x61, 0x73, 0x74, 0x2f, 0x6c, 0x69, 0x76, 0x65, 0x2f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x5f,
	0x63, 0x6f, 0x6e, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x22, 0x62, 0x69, 0x6c, 0x69,
	0x62, 0x69, 0x6c, 0x69, 0x2e, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x2e, 0x6c,
	0x69, 0x76, 0x65, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x22, 0xa8,
	0x03, 0x0a, 0x0a, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x47, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x62, 0x69,
	0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74,
	0x2e, 0x6c, 0x69, 0x76, 0x65, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x5f, 0x63, 0x6f, 0x6e, 0x6e,
	0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x69, 0x6e, 0x66, 0x6f,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x6e, 0x76, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x69,
	0x6e, 0x76, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x72, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x24,
	0x0a, 0x0e, 0x62, 0x69, 0x7a, 0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x62, 0x69, 0x7a, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x1a, 0xb2, 0x01, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x69, 0x63, 0x65, 0x54, 0x65, 0x78,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x6d, 0x74, 0x63, 0x32, 0x33, 0x33,
	0x2f, 0x62, 0x69, 0x6c, 0x69, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x61, 0x70, 0x69, 0x2d, 0x67,
	0x6f, 0x2f, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2f, 0x62, 0x72, 0x6f, 0x61, 0x64,
	0x63, 0x61, 0x73, 0x74, 0x2f, 0x6c, 0x69, 0x76, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_bilibili_broadcast_live_multi_conn_proto_rawDescOnce sync.Once
	file_bilibili_broadcast_live_multi_conn_proto_rawDescData = file_bilibili_broadcast_live_multi_conn_proto_rawDesc
)

func file_bilibili_broadcast_live_multi_conn_proto_rawDescGZIP() []byte {
	file_bilibili_broadcast_live_multi_conn_proto_rawDescOnce.Do(func() {
		file_bilibili_broadcast_live_multi_conn_proto_rawDescData = protoimpl.X.CompressGZIP(file_bilibili_broadcast_live_multi_conn_proto_rawDescData)
	})
	return file_bilibili_broadcast_live_multi_conn_proto_rawDescData
}

var file_bilibili_broadcast_live_multi_conn_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bilibili_broadcast_live_multi_conn_proto_goTypes = []interface{}{
	(*ScoreEvent)(nil),     // 0: bilibili.broadcast.live.multi_conn.ScoreEvent
	(*ScoreEventInfo)(nil), // 1: bilibili.broadcast.live.multi_conn.ScoreEvent.info
}
var file_bilibili_broadcast_live_multi_conn_proto_depIdxs = []int32{
	1, // 0: bilibili.broadcast.live.multi_conn.ScoreEvent.data:type_name -> bilibili.broadcast.live.multi_conn.ScoreEvent.info
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bilibili_broadcast_live_multi_conn_proto_init() }
func file_bilibili_broadcast_live_multi_conn_proto_init() {
	if File_bilibili_broadcast_live_multi_conn_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bilibili_broadcast_live_multi_conn_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScoreEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_broadcast_live_multi_conn_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScoreEventInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bilibili_broadcast_live_multi_conn_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bilibili_broadcast_live_multi_conn_proto_goTypes,
		DependencyIndexes: file_bilibili_broadcast_live_multi_conn_proto_depIdxs,
		MessageInfos:      file_bilibili_broadcast_live_multi_conn_proto_msgTypes,
	}.Build()
	File_bilibili_broadcast_live_multi_conn_proto = out.File
	file_bilibili_broadcast_live_multi_conn_proto_rawDesc = nil
	file_bilibili_broadcast_live_multi_conn_proto_goTypes = nil
	file_bilibili_broadcast_live_multi_conn_proto_depIdxs = nil
}
