// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.app.viewunite.ugcanymodel;

enum PremiereState {
  premiere_none = 0;
  premiere_before = 1;
  premiere_in = 2;
  premiere_after = 3;
  UNRECOGNIZED = -1;
}

// Source: com/bapis/bilibili/app/viewunite/ugcanymodel/AiExtra.java
message AiExtra {
  string trackId = 1;
}

// Source: com/bapis/bilibili/app/viewunite/ugcanymodel/Dislike.java
message Dislike {
  string title = 1;
  string subtitle = 2;
  repeated DislikeReason reasons = 3;
}

// Source: com/bapis/bilibili/app/viewunite/ugcanymodel/DislikeReason.java
message DislikeReason {
  int64 id = 1;
  int64 mid = 2;
  int32 rid = 3;
  int64 tagId = 4;
  string name = 5;
}

// Source: com/bapis/bilibili/app/viewunite/ugcanymodel/ElecRank.java
message ElecRank {
  repeated ElecRankItem list = 1;
  int64 count = 2;
  string text = 3;
  bool hideCount = 4;
}

// Source: com/bapis/bilibili/app/viewunite/ugcanymodel/ElecRankItem.java
message ElecRankItem {
  string avatar = 1;
  string nickname = 2;
  string message_ = 3;
  int64 mid = 4;
}

// Source: com/bapis/bilibili/app/viewunite/ugcanymodel/Experiment.java
message Experiment {
  ShareGuide shareGuide = 1;
  FollowGuide followGuide = 2;
  bool tagFold = 3;
}

// Source: com/bapis/bilibili/app/viewunite/ugcanymodel/FollowGuide.java
message FollowGuide {
  bool isView = 1;
  string viewText = 2;
  bool isThumb = 3;
  string thumbText = 4;
}

// Source: com/bapis/bilibili/app/viewunite/ugcanymodel/Premiere.java
message Premiere {
  PremiereState premiereState = 1;
  int64 startTime = 2;
  int64 serviceTime = 3;
  int64 roomId = 4;
}

// Source: com/bapis/bilibili/app/viewunite/ugcanymodel/PremiereReserve.java
message PremiereReserve {
  int64 reserveId = 1;
  int64 count = 2;
  bool isFollow = 3;
}

// Source: com/bapis/bilibili/app/viewunite/ugcanymodel/PremiereResource.java
message PremiereResource {
  Premiere premiere = 1;
  PremiereReserve reserve = 2;
  PremiereText text = 3;
}

// Source: com/bapis/bilibili/app/viewunite/ugcanymodel/PremiereText.java
message PremiereText {
  string title = 1;
  string subtitle = 2;
  string onlineText = 3;
  string onlineIcon = 4;
  string onlineIconDark = 5;
  string introTitle = 6;
  string introIcon = 7;
  string guidancePulldown = 8;
  string guidanceEntry = 9;
  string introIconNight = 10;
}

// Source: com/bapis/bilibili/app/viewunite/ugcanymodel/RelateUgcAny.java
message RelateUgcAny {
  AiExtra aiExtra = 1;
}

// Source: com/bapis/bilibili/app/viewunite/ugcanymodel/ShareGuide.java
message ShareGuide {
  bool hita = 1;
  int32 duration = 2;
  int32 counta = 3;
  bool hitb = 4;
  int32 countb = 5;
  string text = 6;
  string emphasizedText = 7;
  repeated ShareGuideExpConfig activeExps = 8;
}

// Source: com/bapis/bilibili/app/viewunite/ugcanymodel/ShareGuideExpConfig.java
message ShareGuideExpConfig {
  ExpType expType = 1;
  string text = 2;
  repeated ShareGuideStrategy strategies = 3;
  int32 dailyTotalLimit = 4;
  map<string, string> extraParams = 5;
  enum ExpType {
    UNKNOWN = 0;
    SHARE_FIRST_REWARD = 1;
    SHARE_ONLINE_VIEWERS = 2;
    UNRECOGNIZED = -1;
  }

}

// Source: com/bapis/bilibili/app/viewunite/ugcanymodel/ShareGuideStrategy.java
message ShareGuideStrategy {
  int32 delaySeconds = 1;
  float playProgressThreshold = 2;
  int32 playTimeThreshold = 3;
  int32 onlineViewerThreshold = 4;
}

// Source: com/bapis/bilibili/app/viewunite/ugcanymodel/UgcSeasonConf.java
message UgcSeasonConf {
  bool seasonUnfold = 1;
  int64 foldTime = 2;
}

// Source: com/bapis/bilibili/app/viewunite/ugcanymodel/ViewUgcAny.java
message ViewUgcAny {
  PremiereResource premiere = 1;
  Dislike dislike = 2;
  string shortLink = 3;
  string shareSubtitle = 4;
  repeated Page pages = 5;
  ElecRank elecRank = 6;
  UgcSeasonConf ugcSeasonConf = 7;
  AiExtra aiExtra = 8;
  Experiment experiment = 9;
  RelateAsync relateAsync = 10;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/app/viewunite/ugcanymodel";
