// Reconstructed from gRPC service descriptors.
syntax = "proto3";

package bilibili.cheese.gateway.player.v1;

import "bilibili/cheese/gateway/player/v1/messages.proto";

service PlayURL {
  rpc PlayView(.com.bapis.bilibili.cheese.gateway.player.v1.PlayViewReq) returns (.com.bapis.bilibili.cheese.gateway.player.v1.PlayViewReply);
  rpc Project(.com.bapis.bilibili.cheese.gateway.player.v1.ProjectReq) returns (.com.bapis.bilibili.cheese.gateway.player.v1.ProjectReply);
}

option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/cheese/gateway/player/v1";
