// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.app.playerunite.pgcanymodel;

import "bilibili/pgc/gateway/player/v2/messages.proto";

// Source: com/bapis/bilibili/app/playerunite/pgcanymodel/PGCAnyModel.java
message PGCAnyModel {
  com.bapis.bilibili.pgc.gateway.player.v2.PlayViewBusinessInfo business = 3;
  com.bapis.bilibili.pgc.gateway.player.v2.Event event = 4;
  com.bapis.bilibili.pgc.gateway.player.v2.ViewInfo viewInfo = 5;
  com.bapis.bilibili.pgc.gateway.player.v2.PlayAbilityExtConf playExtConf = 6;
  com.bapis.bilibili.pgc.gateway.player.v2.PlayExtInfo playExtInfo = 7;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/app/playerunite/pgcanymodel";
