// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.dynamic.interfaces.campus.v1;

enum ActionType {
  ACTION_NOTHING = 0;
  ACTION_CLOSE_YELLOW_BAR = 1;
}

// Source: com/bapis/bilibili/dynamic/interfaces/campus/v1/ActionReportReply.java
message ActionReportReply {
}

// Source: com/bapis/bilibili/dynamic/interfaces/campus/v1/ActionReportReq.java
message ActionReportReq {
  string identity = 1;
  ActionType action = 2;
  int64 campusId = 3;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/dynamic/interfaces/campus/v1";
