// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.live.rankdb.v1;

import "bilibili/live/component/common_model/user_dagw/messages.proto";

// Source: com/bapis/bilibili/live/rankdb/v1/GoldRankBroadcast.java
message GoldRankBroadcast {
  string rankType = 1;
  repeated GoldRankBroadcast_GoldRankBroadcastItem list = 2;
  repeated GoldRankBroadcast_GoldRankBroadcastItem onlineList = 3;
}

// Source: com/bapis/bilibili/live/rankdb/v1/GoldRankBroadcast.java
message GoldRankBroadcast_GoldRankBroadcastItem {
  int64 uid = 1;
  string face = 2;
  string score = 3;
  string uname = 4;
  int64 rank = 5;
  int64 guardLevel = 6;
  bool isMystery = 7;
  com.bapis.bilibili.live.component.common_model.user_dagw.UserInfo uinfo = 8;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/live/rankdb/v1";
