// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.account.service.v1;

enum RenderSchemeEnum {
  Default = 0;
  Colorful = 1;
  UNRECOGNIZED = -1;
}

// Source: com/bapis/bilibili/account/service/v1/Color.java
message Color {
  string colorDay = 1;
  string colorNight = 2;
}

// Source: com/bapis/bilibili/account/service/v1/ColorsInfo.java
message ColorsInfo {
  repeated int64 colorIds = 1;
  repeated Color color = 2;
}

// Source: com/bapis/bilibili/account/service/v1/NameRender.java
message NameRender {
  RenderSchemeEnum renderScheme = 1;
  ColorsInfo colorsInfo = 2;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/account/service/v1";
