// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: bilibili/app/search/v2.proto

package search

import (
	context "context"
	message "github.com/stmtc233/bili-grpc-api-go/bilibili/broadcast/message"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Search_CancelChatTask_FullMethodName  = "/bilibili.app.search.v2.Search/CancelChatTask"
	Search_GetChatAuth_FullMethodName     = "/bilibili.app.search.v2.Search/GetChatAuth"
	Search_GetChatResult_FullMethodName   = "/bilibili.app.search.v2.Search/GetChatResult"
	Search_QueryRecComment_FullMethodName = "/bilibili.app.search.v2.Search/QueryRecComment"
	Search_SearchDelFollow_FullMethodName = "/bilibili.app.search.v2.Search/SearchDelFollow"
	Search_SearchEgg_FullMethodName       = "/bilibili.app.search.v2.Search/SearchEgg"
	Search_SearchFollow_FullMethodName    = "/bilibili.app.search.v2.Search/SearchFollow"
	Search_SearchLike_FullMethodName      = "/bilibili.app.search.v2.Search/SearchLike"
	Search_SearchShortUrl_FullMethodName  = "/bilibili.app.search.v2.Search/SearchShortUrl"
	Search_SubmitChatTask_FullMethodName  = "/bilibili.app.search.v2.Search/SubmitChatTask"
)

// SearchClient is the client API for Search service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchClient interface {
	CancelChatTask(ctx context.Context, in *CancelChatTaskReq, opts ...grpc.CallOption) (*CancelChatTaskReply, error)
	GetChatAuth(ctx context.Context, in *GetChatAuthReq, opts ...grpc.CallOption) (*GetChatAuthReply, error)
	GetChatResult(ctx context.Context, in *GetChatResultReq, opts ...grpc.CallOption) (*message.ChatResult, error)
	QueryRecComment(ctx context.Context, in *QueryRecAfterClickReq, opts ...grpc.CallOption) (*QueryRecAfterClickReply, error)
	SearchDelFollow(ctx context.Context, in *SearchDelFollowRequest, opts ...grpc.CallOption) (*SearchDelFollowResponse, error)
	SearchEgg(ctx context.Context, in *SearchEggReq, opts ...grpc.CallOption) (*SearchEggReply, error)
	SearchFollow(ctx context.Context, in *SearchFollowRequest, opts ...grpc.CallOption) (*SearchFollowResponse, error)
	SearchLike(ctx context.Context, in *SearchLikeReq, opts ...grpc.CallOption) (*SearchLikeReply, error)
	SearchShortUrl(ctx context.Context, in *SearchShortUrlReq, opts ...grpc.CallOption) (*SearchShortUrlReply, error)
	SubmitChatTask(ctx context.Context, in *SubmitChatTaskReq, opts ...grpc.CallOption) (*SubmitChatTaskReply, error)
}

type searchClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchClient(cc grpc.ClientConnInterface) SearchClient {
	return &searchClient{cc}
}

func (c *searchClient) CancelChatTask(ctx context.Context, in *CancelChatTaskReq, opts ...grpc.CallOption) (*CancelChatTaskReply, error) {
	out := new(CancelChatTaskReply)
	err := c.cc.Invoke(ctx, Search_CancelChatTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) GetChatAuth(ctx context.Context, in *GetChatAuthReq, opts ...grpc.CallOption) (*GetChatAuthReply, error) {
	out := new(GetChatAuthReply)
	err := c.cc.Invoke(ctx, Search_GetChatAuth_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) GetChatResult(ctx context.Context, in *GetChatResultReq, opts ...grpc.CallOption) (*message.ChatResult, error) {
	out := new(message.ChatResult)
	err := c.cc.Invoke(ctx, Search_GetChatResult_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) QueryRecComment(ctx context.Context, in *QueryRecAfterClickReq, opts ...grpc.CallOption) (*QueryRecAfterClickReply, error) {
	out := new(QueryRecAfterClickReply)
	err := c.cc.Invoke(ctx, Search_QueryRecComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) SearchDelFollow(ctx context.Context, in *SearchDelFollowRequest, opts ...grpc.CallOption) (*SearchDelFollowResponse, error) {
	out := new(SearchDelFollowResponse)
	err := c.cc.Invoke(ctx, Search_SearchDelFollow_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) SearchEgg(ctx context.Context, in *SearchEggReq, opts ...grpc.CallOption) (*SearchEggReply, error) {
	out := new(SearchEggReply)
	err := c.cc.Invoke(ctx, Search_SearchEgg_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) SearchFollow(ctx context.Context, in *SearchFollowRequest, opts ...grpc.CallOption) (*SearchFollowResponse, error) {
	out := new(SearchFollowResponse)
	err := c.cc.Invoke(ctx, Search_SearchFollow_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) SearchLike(ctx context.Context, in *SearchLikeReq, opts ...grpc.CallOption) (*SearchLikeReply, error) {
	out := new(SearchLikeReply)
	err := c.cc.Invoke(ctx, Search_SearchLike_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) SearchShortUrl(ctx context.Context, in *SearchShortUrlReq, opts ...grpc.CallOption) (*SearchShortUrlReply, error) {
	out := new(SearchShortUrlReply)
	err := c.cc.Invoke(ctx, Search_SearchShortUrl_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) SubmitChatTask(ctx context.Context, in *SubmitChatTaskReq, opts ...grpc.CallOption) (*SubmitChatTaskReply, error) {
	out := new(SubmitChatTaskReply)
	err := c.cc.Invoke(ctx, Search_SubmitChatTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServer is the server API for Search service.
// All implementations must embed UnimplementedSearchServer
// for forward compatibility
type SearchServer interface {
	CancelChatTask(context.Context, *CancelChatTaskReq) (*CancelChatTaskReply, error)
	GetChatAuth(context.Context, *GetChatAuthReq) (*GetChatAuthReply, error)
	GetChatResult(context.Context, *GetChatResultReq) (*message.ChatResult, error)
	QueryRecComment(context.Context, *QueryRecAfterClickReq) (*QueryRecAfterClickReply, error)
	SearchDelFollow(context.Context, *SearchDelFollowRequest) (*SearchDelFollowResponse, error)
	SearchEgg(context.Context, *SearchEggReq) (*SearchEggReply, error)
	SearchFollow(context.Context, *SearchFollowRequest) (*SearchFollowResponse, error)
	SearchLike(context.Context, *SearchLikeReq) (*SearchLikeReply, error)
	SearchShortUrl(context.Context, *SearchShortUrlReq) (*SearchShortUrlReply, error)
	SubmitChatTask(context.Context, *SubmitChatTaskReq) (*SubmitChatTaskReply, error)
	mustEmbedUnimplementedSearchServer()
}

// UnimplementedSearchServer must be embedded to have forward compatible implementations.
type UnimplementedSearchServer struct {
}

func (UnimplementedSearchServer) CancelChatTask(context.Context, *CancelChatTaskReq) (*CancelChatTaskReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelChatTask not implemented")
}
func (UnimplementedSearchServer) GetChatAuth(context.Context, *GetChatAuthReq) (*GetChatAuthReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChatAuth not implemented")
}
func (UnimplementedSearchServer) GetChatResult(context.Context, *GetChatResultReq) (*message.ChatResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChatResult not implemented")
}
func (UnimplementedSearchServer) QueryRecComment(context.Context, *QueryRecAfterClickReq) (*QueryRecAfterClickReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryRecComment not implemented")
}
func (UnimplementedSearchServer) SearchDelFollow(context.Context, *SearchDelFollowRequest) (*SearchDelFollowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchDelFollow not implemented")
}
func (UnimplementedSearchServer) SearchEgg(context.Context, *SearchEggReq) (*SearchEggReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchEgg not implemented")
}
func (UnimplementedSearchServer) SearchFollow(context.Context, *SearchFollowRequest) (*SearchFollowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchFollow not implemented")
}
func (UnimplementedSearchServer) SearchLike(context.Context, *SearchLikeReq) (*SearchLikeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchLike not implemented")
}
func (UnimplementedSearchServer) SearchShortUrl(context.Context, *SearchShortUrlReq) (*SearchShortUrlReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchShortUrl not implemented")
}
func (UnimplementedSearchServer) SubmitChatTask(context.Context, *SubmitChatTaskReq) (*SubmitChatTaskReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitChatTask not implemented")
}
func (UnimplementedSearchServer) mustEmbedUnimplementedSearchServer() {}

// UnsafeSearchServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchServer will
// result in compilation errors.
type UnsafeSearchServer interface {
	mustEmbedUnimplementedSearchServer()
}

func RegisterSearchServer(s grpc.ServiceRegistrar, srv SearchServer) {
	s.RegisterService(&Search_ServiceDesc, srv)
}

func _Search_CancelChatTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelChatTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).CancelChatTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_CancelChatTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).CancelChatTask(ctx, req.(*CancelChatTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_GetChatAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatAuthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).GetChatAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_GetChatAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).GetChatAuth(ctx, req.(*GetChatAuthReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_GetChatResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatResultReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).GetChatResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_GetChatResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).GetChatResult(ctx, req.(*GetChatResultReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_QueryRecComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRecAfterClickReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).QueryRecComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_QueryRecComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).QueryRecComment(ctx, req.(*QueryRecAfterClickReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_SearchDelFollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchDelFollowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).SearchDelFollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_SearchDelFollow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).SearchDelFollow(ctx, req.(*SearchDelFollowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_SearchEgg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchEggReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).SearchEgg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_SearchEgg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).SearchEgg(ctx, req.(*SearchEggReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_SearchFollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchFollowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).SearchFollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_SearchFollow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).SearchFollow(ctx, req.(*SearchFollowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_SearchLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchLikeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).SearchLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_SearchLike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).SearchLike(ctx, req.(*SearchLikeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_SearchShortUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchShortUrlReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).SearchShortUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_SearchShortUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).SearchShortUrl(ctx, req.(*SearchShortUrlReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_SubmitChatTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitChatTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).SubmitChatTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Search_SubmitChatTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).SubmitChatTask(ctx, req.(*SubmitChatTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Search_ServiceDesc is the grpc.ServiceDesc for Search service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Search_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bilibili.app.search.v2.Search",
	HandlerType: (*SearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CancelChatTask",
			Handler:    _Search_CancelChatTask_Handler,
		},
		{
			MethodName: "GetChatAuth",
			Handler:    _Search_GetChatAuth_Handler,
		},
		{
			MethodName: "GetChatResult",
			Handler:    _Search_GetChatResult_Handler,
		},
		{
			MethodName: "QueryRecComment",
			Handler:    _Search_QueryRecComment_Handler,
		},
		{
			MethodName: "SearchDelFollow",
			Handler:    _Search_SearchDelFollow_Handler,
		},
		{
			MethodName: "SearchEgg",
			Handler:    _Search_SearchEgg_Handler,
		},
		{
			MethodName: "SearchFollow",
			Handler:    _Search_SearchFollow_Handler,
		},
		{
			MethodName: "SearchLike",
			Handler:    _Search_SearchLike_Handler,
		},
		{
			MethodName: "SearchShortUrl",
			Handler:    _Search_SearchShortUrl_Handler,
		},
		{
			MethodName: "SubmitChatTask",
			Handler:    _Search_SubmitChatTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bilibili/app/search/v2.proto",
}
