// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.main.community.reply.v1;

import "bilibili/account/service/v1/messages.proto";
import "bilibili/app/dynamic/v2/messages.proto";
import "bilibili/dagw/component/avatar/v1/messages.proto";
import "bilibili/pagination/messages.proto";
import "bilibili/vas/garb/model/messages.proto";
import "google/protobuf/any.proto";

enum DetailListScene {
  REPLY = 0;
  MSG_FEED = 1;
  NOTIFY = 2;
}

enum EditorIconState {
  EditorIconState_DEFAULT = 0;
  EditorIconState_ENABLE = 1;
  EditorIconState_DISABLE = 2;
  EditorIconState_HIDE = 3;
}

enum Mode {
  DEFAULT = 0;
  UNSPECIFIED = 1;
  MAIN_LIST_TIME = 2;
  MAIN_LIST_HOT = 3;
}

enum ReplyNotificationSwitch {
  ReplyNotificationSwitch_UNSPECIFIED = 0;
  ReplyNotificationSwitch_OFF = 1;
  ReplyNotificationSwitch_ON = 2;
}

enum SearchItemType {
  DEFAULT_ITEM_TYPE = 0;
  GOODS = 1;
  VIDEO = 2;
  ARTICLE = 3;
}

enum SearchItemVideoSubType {
  UGC = 0;
  PGC = 1;
}

enum TranslationSwitch {
  TRANSLATION_SWITCH_UNSPECIFIED = 0;
  TRANSLATION_SWITCH_UNSUPPORTED = 1;
  TRANSLATION_SWITCH_SHOW_TRANSLATION = 2;
  TRANSLATION_SWITCH_SHOW_ORIGIN = 3;
}

enum UserCallbackAction {
  Dismiss = 0;
}

enum UserCallbackScene {
  Insert = 0;
  RecommendSuperbReply = 1;
  Hotspot = 2;
}

// Source: com/bapis/bilibili/main/community/reply/v1/Activity.java
message Activity {
  int64 activityId = 1;
  int64 activityState = 2;
  string activityPlaceholder = 3;
}

// Source: com/bapis/bilibili/main/community/reply/v1/AddReplyReq.java
message AddReplyReq {
  int64 oid = 1;
  int64 type = 2;
  string message_ = 3;
  int64 root = 4;
  int64 parent = 5;
  map<string, int64> atNameToMid = 6;
  repeated Picture pictures = 7;
  bool isEasterEgg = 8;
  string code = 9;
  int64 vote = 10;
  int64 note = 11;
  bool syncToDynamic = 12;
  bool hasVoteOption = 13;
  int64 chargedFee = 14;
  bool isCharged = 15;
  int64 gradeId = 16;
  int32 gradeScore = 17;
  int32 plat = 18;
  string scene = 19;
  string spmid = 20;
  string fromSpmid = 21;
  string trackId = 22;
  string containerUuid = 23;
  string scmActionId = 24;
  bool isFly = 25;
  string flyOrderId = 26;
}

// Source: com/bapis/bilibili/main/community/reply/v1/AddReplyResp.java
message AddReplyResp {
  SuccessAction successAction = 1;
  string successToast = 2;
  string successAnimation = 3;
  bool changeNicknamePrompt = 4;
  ReplyInfo reply = 5;
  AddReplyResp_EasterEgg easterEgg = 6;
  enum SuccessAction {
    Display = 0;
    None = 1;
  }

}

// Source: com/bapis/bilibili/main/community/reply/v1/AddReplyResp.java
message AddReplyResp_EasterEgg {
  string jumpUrl = 1;
  string resource = 2;
}

// Source: com/bapis/bilibili/main/community/reply/v1/AnswerQuestionReq.java
message AnswerQuestionReq {
  int64 qid = 1;
  string optionKey = 2;
}

// Source: com/bapis/bilibili/main/community/reply/v1/AnswerQuestionResp.java
message AnswerQuestionResp {
  bool passed = 1;
  bool memberPassed = 2;
  AnswerQuestionResp_MemberPassedPopup memberPassedPopup = 3;
  string bottomText = 4;
  QuestionCardStat stat = 5;
}

// Source: com/bapis/bilibili/main/community/reply/v1/AnswerQuestionResp.java
message AnswerQuestionResp_MemberPassedPopup {
  string title = 1;
  string subtitle = 2;
  string h5Link = 3;
}

// Source: com/bapis/bilibili/main/community/reply/v1/ArticleSearchItem.java
message ArticleSearchItem {
  string title = 1;
  string upNickname = 2;
  repeated string covers = 3;
}

// Source: com/bapis/bilibili/main/community/reply/v1/AtGroup.java
message AtGroup {
  Type groupType = 1;
  string groupName = 2;
  repeated AtItem items = 3;
  enum Type {
    AT_GROUP_TYPE_DEFAULT = 0;
    AT_GROUP_TYPE_RECENT = 1;
    AT_GROUP_TYPE_FOLLOW = 2;
    AT_GROUP_TYPE_FANS = 3;
    AT_GROUP_TYPE_OTHERS = 4;
  }

}

// Source: com/bapis/bilibili/main/community/reply/v1/AtItem.java
message AtItem {
  int64 mid = 1;
  string name = 2;
  string face = 3;
  int32 fans = 4;
  int32 officialVerifyType = 5;
}

// Source: com/bapis/bilibili/main/community/reply/v1/ATRow.java
message ATRow {
  string avatar = 1;
  string text = 2;
}

// Source: com/bapis/bilibili/main/community/reply/v1/AtSearchReply.java
message AtSearchReply {
  repeated AtGroup groups = 1;
}

// Source: com/bapis/bilibili/main/community/reply/v1/AtSearchReq.java
message AtSearchReq {
  int64 mid = 1;
  string keyword = 2;
}

// Source: com/bapis/bilibili/main/community/reply/v1/CM.java
message CM {
  google.protobuf.Any sourceContent = 1;
}

// Source: com/bapis/bilibili/main/community/reply/v1/Content.java
message Content {
  string message_ = 1;
  map<string, Member> members = 2;
  map<string, Emote> emotes = 3;
  map<string, Topic> topics = 4;
  map<string, Url> urls = 5;
  Vote vote = 6;
  map<string, int64> atNameToMid = 7;
  RichText richText = 8;
  repeated Picture pictures = 9;
  double pictureScale = 10;
}

// Source: com/bapis/bilibili/main/community/reply/v1/CursorReply.java
message CursorReply {
  int64 next = 1;
  int64 prev = 2;
  bool isBegin = 3;
  bool isEnd = 4;
  Mode mode = 5;
  string modeText = 6;
}

// Source: com/bapis/bilibili/main/community/reply/v1/CursorReq.java
message CursorReq {
  int64 next = 1;
  int64 prev = 2;
  Mode mode = 4;
}

// Source: com/bapis/bilibili/main/community/reply/v1/DetailListReply.java
message DetailListReply {
  CursorReply cursor = 1;
  SubjectControl subjectControl = 2;
  ReplyInfo root = 3;
  Activity activity = 4;
  LikeInfo likes = 5;
  Mode mode = 6;
  string modeText = 7;
  com.bapis.bilibili.pagination.FeedPaginationReply paginationReply = 8;
  string sessionId = 9;
  DetailListReply_SubjectTitle subjectTitle = 10;
  repeated MixedCard mixedCards = 11;
}

// Source: com/bapis/bilibili/main/community/reply/v1/DetailListReply.java
message DetailListReply_SubjectTitle {
  string leftIcon = 1;
  string title = 2;
  string link = 3;
  int64 rpidMute = 4;
  ReplyNotificationSwitch pushSwitch = 5;
}

// Source: com/bapis/bilibili/main/community/reply/v1/DetailListReq.java
message DetailListReq {
  int64 oid = 1;
  int64 type = 2;
  int64 root = 3;
  int64 rpid = 4;
  CursorReq cursor = 5;
  DetailListScene scene = 6;
  Mode mode = 7;
  com.bapis.bilibili.pagination.FeedPagination pagination = 8;
  string extra = 9;
  string adExtra = 10;
  bool needSubjectTitle = 11;
}

// Source: com/bapis/bilibili/main/community/reply/v1/DialogListReply.java
message DialogListReply {
  CursorReply cursor = 1;
  SubjectControl subjectControl = 2;
  repeated ReplyInfo replies = 3;
  Activity activity = 4;
  com.bapis.bilibili.pagination.FeedPaginationReply paginationReply = 5;
  string sessionId = 6;
}

// Source: com/bapis/bilibili/main/community/reply/v1/DialogListReq.java
message DialogListReq {
  int64 oid = 1;
  int64 type = 2;
  int64 root = 3;
  int64 dialog = 4;
  CursorReq cursor = 5;
  com.bapis.bilibili.pagination.FeedPagination pagination = 6;
  string extra = 7;
  string adExtra = 8;
}

// Source: com/bapis/bilibili/main/community/reply/v1/DoVoteReq.java
message DoVoteReq {
  int64 oid = 1;
  int64 type = 2;
  int64 voteId = 3;
  int64 option_ = 4;
}

// Source: com/bapis/bilibili/main/community/reply/v1/DoVoteResp.java
message DoVoteResp {
}

// Source: com/bapis/bilibili/main/community/reply/v1/Effects.java
message Effects {
  string preloading = 1;
}

// Source: com/bapis/bilibili/main/community/reply/v1/Emote.java
message Emote {
  int64 size = 1;
  string url = 2;
  string jumpUrl = 3;
  string jumpTitle = 4;
  int64 id = 5;
  int64 packageId = 6;
  string gifUrl = 7;
  string text = 8;
  string webpUrl = 9;
}

// Source: com/bapis/bilibili/main/community/reply/v1/EmptyPage.java
message EmptyPage {
  string imageUrl = 1;
  repeated EmptyPage_Text texts = 2;
  EmptyPage_Button leftButton = 3;
  EmptyPage_Button rightButton = 4;
  enum Action {
    UNAVAILABLE = 0;
    SHOW_KEYBOARD = 1;
    SEND_REPLY_WITH_BOLD_TEXT = 2;
  }

}

// Source: com/bapis/bilibili/main/community/reply/v1/EmptyPage.java
message EmptyPage_Button {
  string title = 1;
  EmptyPage.Action action = 2;
}

// Source: com/bapis/bilibili/main/community/reply/v1/EmptyPage.java
message EmptyPage_Text {
  string raw = 1;
  TextStyle style = 2;
  EmptyPage.Action action = 3;
}

// Source: com/bapis/bilibili/main/community/reply/v1/ESportsGradeCard.java
message ESportsGradeCard {
  string title = 1;
  string description = 2;
  string image = 3;
  string link = 4;
}

// Source: com/bapis/bilibili/main/community/reply/v1/FoldCard.java
message FoldCard {
  string bottomText = 1;
  com.bapis.bilibili.pagination.FeedPagination foldPagination = 2;
}

// Source: com/bapis/bilibili/main/community/reply/v1/FoldListReq.java
message FoldListReq {
  int64 oid = 1;
  int64 type = 2;
  string extra = 3;
  com.bapis.bilibili.pagination.FeedPagination pagination = 4;
}

// Source: com/bapis/bilibili/main/community/reply/v1/FoldListResp.java
message FoldListResp {
  repeated ReplyInfo replies = 1;
  com.bapis.bilibili.pagination.FeedPaginationReply paginationReply = 2;
  string title = 3;
  SubjectControl subjectControl = 4;
}

// Source: com/bapis/bilibili/main/community/reply/v1/Form.java
message Form {
  int32 type = 1;
  repeated QoeOption options = 2;
}

// Source: com/bapis/bilibili/main/community/reply/v1/GoodsSearchItem.java
message GoodsSearchItem {
  int64 id = 1;
  string name = 2;
  string price = 3;
  string income = 4;
  string img = 5;
  string label = 6;
}

// Source: com/bapis/bilibili/main/community/reply/v1/HotReplyInfo.java
message HotReplyInfo {
  string arcTitle = 1;
  int32 opinionIdx = 2;
  string fromText = 3;
}

// Source: com/bapis/bilibili/main/community/reply/v1/HotspotCard.java
message HotspotCard {
  string icon = 1;
  string title = 2;
  string titleText = 3;
  int64 rpid = 4;
  int64 oid = 5;
  Content content = 6;
  MemberV2 member = 7;
  int64 hotspotId = 8;
  ReplyControl replyControl = 9;
  int64 like = 10;
  string arcTitle = 11;
  string fromText = 12;
  int32 type = 13;
}

// Source: com/bapis/bilibili/main/community/reply/v1/HotspotPageReq.java
message HotspotPageReq {
  int64 tid = 1;
  int32 ps = 2;
  int32 opinionIdx = 3;
  string cursor = 4;
  ReferReply referReply = 5;
}

// Source: com/bapis/bilibili/main/community/reply/v1/HotspotPageResp.java
message HotspotPageResp {
  string hotspotTitle = 1;
  string hotspotDesc = 2;
  repeated Opinion opinions = 3;
  PageInfo page = 4;
  repeated ReplyInfo replies = 5;
  string updateText = 6;
  string icon = 7;
}

// Source: com/bapis/bilibili/main/community/reply/v1/LikeInfo.java
message LikeInfo {
  repeated LikeInfo_Item items = 1;
  string title = 2;
}

// Source: com/bapis/bilibili/main/community/reply/v1/LikeInfo.java
message LikeInfo_Item {
  Member member = 1;
}

// Source: com/bapis/bilibili/main/community/reply/v1/Lottery.java
message Lottery {
  int64 lotteryId = 1;
  int64 lotteryStatus = 2;
  int64 lotteryMid = 3;
  int64 lotteryTime = 4;
  int64 oid = 5;
  int64 type = 6;
  int64 ctime = 7;
  Content content = 8;
  Member member = 9;
  ReplyControl replyControl = 10;
}

// Source: com/bapis/bilibili/main/community/reply/v1/MainListReply.java
message MainListReply {
  CursorReply cursor = 1;
  repeated ReplyInfo replies = 2;
  SubjectControl subjectControl = 3;
  ReplyInfo upTop = 4;
  ReplyInfo adminTop = 5;
  ReplyInfo voteTop = 6;
  Notice notice = 7;
  Lottery lottery = 8;
  Activity activity = 9;
  UpSelection upSelection = 10;
  CM cm = 11;
  Effects effects = 12;
  Operation operation = 13;
  repeated ReplyInfo topReplies = 14;
  QoeInfo qoe = 15;
  map<string, int32> callbacks = 16;
  OperationV2 operationV2 = 17;
  Mode mode = 18;
  string modeText = 19;
  com.bapis.bilibili.pagination.FeedPaginationReply paginationReply = 20;
  string sessionId = 21;
  string reportParams = 22;
  VoteCard voteCard = 23;
  ESportsGradeCard esportsGradeCard = 24;
  string contextFeature = 25;
  string paginationEndText = 26;
  repeated MixedCard mixedCards = 27;
  repeated SubjectTopCards subjectTopCards = 28;
}

// Source: com/bapis/bilibili/main/community/reply/v1/MainListReq.java
message MainListReq {
  int64 oid = 1;
  int64 type = 2;
  CursorReq cursor = 3;
  string extra = 4;
  string adExtra = 5;
  int64 rpid = 6;
  int64 seekRpid = 7;
  string filterTagName = 8;
  Mode mode = 9;
  com.bapis.bilibili.pagination.FeedPagination pagination = 10;
  repeated int64 clientRecallRpids = 11;
  WordSearchParam wordSearchParam = 12;
}

// Source: com/bapis/bilibili/main/community/reply/v1/Member.java
message Member {
  int64 mid = 1;
  string name = 2;
  string sex = 3;
  string face = 4;
  int64 level = 5;
  int64 officialVerifyType = 6;
  int64 vipType = 7;
  int64 vipStatus = 8;
  int64 vipThemeType = 9;
  string vipLabelPath = 10;
  string garbPendantImage = 11;
  string garbCardImage = 12;
  string garbCardImageWithFocus = 13;
  string garbCardJumpUrl = 14;
  string garbCardNumber = 15;
  string garbCardFanColor = 16;
  bool garbCardIsFan = 17;
  string fansMedalName = 18;
  int64 fansMedalLevel = 19;
  int64 fansMedalColor = 20;
  string vipNicknameColor = 21;
  int32 vipAvatarSubscript = 22;
  string vipLabelText = 23;
  string vipLabelTheme = 24;
  int64 fansMedalColorEnd = 25;
  int64 fansMedalColorBorder = 26;
  int64 fansMedalColorName = 27;
  int64 fansMedalColorLevel = 28;
  int64 fansGuardLevel = 29;
  int32 faceNft = 30;
  int32 faceNftNew = 31;
  int32 isSeniorMember = 32;
  Member_NftInteraction nftInteraction = 33;
  string fansGuardIcon = 34;
  string fansHonorIcon = 35;
}

// Source: com/bapis/bilibili/main/community/reply/v1/Member.java
message Member_NftInteraction {
  string itype = 1;
  string metadataUrl = 2;
  string nftId = 3;
  Member_NftInteraction_Region region = 4;
  enum RegionType {
    DEFAULT = 0;
    MAINLAND = 1;
    GAT = 2;
  }

  enum ShowStatus {
    SHOWDEFAULT = 0;
    ZOOMINMAINLAND = 1;
    RAW = 2;
  }

}

// Source: com/bapis/bilibili/main/community/reply/v1/Member.java
message Member_NftInteraction_Region {
  Member_NftInteraction.RegionType type = 1;
  string icon = 2;
  Member_NftInteraction.ShowStatus showStatus = 3;
}

// Source: com/bapis/bilibili/main/community/reply/v1/MemberV2.java
message MemberV2 {
  MemberV2_Basic basic = 1;
  MemberV2_Official official = 2;
  MemberV2_Vip vip = 3;
  MemberV2_Garb garb = 4;
  MemberV2_Medal medal = 5;
  MemberV2_Nft nft = 6;
  MemberV2_Senior senior = 7;
  MemberV2_Contractor contractor = 8;
  com.bapis.bilibili.vas.garb.model.UserSailing userSailing = 9;
}

// Source: com/bapis/bilibili/main/community/reply/v1/MemberV2.java
message MemberV2_Basic {
  int64 mid = 1;
  string name = 2;
  string sex = 3;
  string face = 4;
  int64 level = 5;
  com.bapis.bilibili.dagw.component.avatar.v1.AvatarItem avatarItem = 6;
  com.bapis.bilibili.account.service.v1.NameRender nameRender = 7;
  string handle = 8;
}

// Source: com/bapis/bilibili/main/community/reply/v1/MemberV2.java
message MemberV2_Contractor {
  bool isContractor = 1;
  string contractDesc = 2;
}

// Source: com/bapis/bilibili/main/community/reply/v1/MemberV2.java
message MemberV2_Garb {
  string pendantImage = 1;
  string cardImage = 2;
  string cardImageWithFocus = 3;
  string cardJumpUrl = 4;
  string cardNumber = 5;
  string cardFanColor = 6;
  bool cardIsFan = 7;
  string fanNumPrefix = 8;
  MemberV2_Garb_FanNumColorFormat fanNumColorFormat = 9;
}

// Source: com/bapis/bilibili/main/community/reply/v1/MemberV2.java
message MemberV2_Garb_FanNumColorFormat {
  string startPoint = 1;
  string endPoint = 2;
  repeated string colors = 3;
  repeated int64 gradients = 4;
}

// Source: com/bapis/bilibili/main/community/reply/v1/MemberV2.java
message MemberV2_Medal {
  string name = 1;
  int64 level = 2;
  int64 colorStart = 3;
  int64 colorEnd = 4;
  int64 colorBorder = 5;
  int64 colorName = 6;
  int64 colorLevel = 7;
  int64 guardLevel = 8;
  string firstIcon = 9;
  string secondIcon = 10;
  int64 levelBgColor = 11;
}

// Source: com/bapis/bilibili/main/community/reply/v1/MemberV2.java
message MemberV2_Nft {
  int32 face = 1;
  MemberV2_Nft_Interaction interaction = 2;
}

// Source: com/bapis/bilibili/main/community/reply/v1/MemberV2.java
message MemberV2_Nft_Interaction {
  string itype = 1;
  string metadataUrl = 2;
  string nftId = 3;
  MemberV2_Nft_Interaction_Region region = 4;
  enum RegionType {
    DEFAULT = 0;
    MAINLAND = 1;
    GAT = 2;
  }

  enum ShowStatus {
    SHOWDEFAULT = 0;
    ZOOMINMAINLAND = 1;
    RAW = 2;
  }

}

// Source: com/bapis/bilibili/main/community/reply/v1/MemberV2.java
message MemberV2_Nft_Interaction_Region {
  MemberV2_Nft_Interaction.RegionType type = 1;
  string icon = 2;
  MemberV2_Nft_Interaction.ShowStatus showStatus = 3;
}

// Source: com/bapis/bilibili/main/community/reply/v1/MemberV2.java
message MemberV2_Official {
  int64 verifyType = 1;
}

// Source: com/bapis/bilibili/main/community/reply/v1/MemberV2.java
message MemberV2_Senior {
  int32 isSeniorMember = 1;
  Status status = 2;
  enum Status {
    Normal = 0;
    Pending = 1;
    Senior = 2;
    WillExpire = 3;
    Expired = 4;
  }

}

// Source: com/bapis/bilibili/main/community/reply/v1/MemberV2.java
message MemberV2_Vip {
  int64 type = 1;
  int64 status = 2;
  int64 themeType = 3;
  string labelPath = 4;
  string nicknameColor = 5;
  int32 avatarSubscript = 6;
  string labelText = 7;
  string vipLabelTheme = 8;
}

// Source: com/bapis/bilibili/main/community/reply/v1/MixedCard.java
message MixedCard {
  Type type = 1;
  string oid = 2;
  int64 displayRank = 3;
  oneof oneof_0 {
    QuestionCard question = 4;
    FoldCard fold = 5;
    HotspotCard hotspot = 6;
  }
  enum ItemCase {
    ITEM_NOT_SET = 0;
    ITEM_CASE_QUESTION = 4;
    ITEM_CASE_FOLD = 5;
    ITEM_CASE_HOTSPOT = 6;
  }

  enum Type {
    UNKNOWN = 0;
    TYPE_QUESTION = 1;
    TYPE_FOLD = 2;
    TYPE_HOTSPOT = 3;
  }

}

// Source: com/bapis/bilibili/main/community/reply/v1/Notice.java
message Notice {
  int64 id = 1;
  string content = 2;
  string link = 3;
}

// Source: com/bapis/bilibili/main/community/reply/v1/OgvGradeCard.java
message OgvGradeCard {
  string title = 1;
  string subTitle = 2;
  string buttonText = 3;
  string gotoUrl = 4;
  string reportParam = 5;
}

// Source: com/bapis/bilibili/main/community/reply/v1/Operation.java
message Operation {
  Type type = 1;
  int64 id = 2;
  OperationTitle title = 3;
  OperationTitle subtitle = 4;
  string link = 5;
  string reportExtra = 6;
  string icon = 7;
  enum Type {
    UNKNOWN = 0;
    NOTE = 1;
    TOPIC = 2;
    NOTICE = 3;
  }

}

// Source: com/bapis/bilibili/main/community/reply/v1/OperationTitle.java
message OperationTitle {
  string content = 1;
  bool isHighlight = 2;
}

// Source: com/bapis/bilibili/main/community/reply/v1/OperationV2.java
message OperationV2 {
  Type type = 1;
  string prefixText = 2;
  OperationV2_Icon icon = 3;
  string title = 4;
  string link = 5;
  string reportExtra = 6;
  enum Type {
    UNKNOWN = 0;
    NOTE = 1;
    TOPIC = 2;
    SEARCH = 4;
  }

}

// Source: com/bapis/bilibili/main/community/reply/v1/OperationV2.java
message OperationV2_Icon {
  Position position = 1;
  string url = 2;
  enum Position {
    PREFIX = 0;
    SUFFIX = 1;
  }

}

// Source: com/bapis/bilibili/main/community/reply/v1/Opinion.java
message Opinion {
  int32 idx = 1;
  string title = 2;
  string desc = 3;
  int32 count = 4;
}

// Source: com/bapis/bilibili/main/community/reply/v1/PageInfo.java
message PageInfo {
  int32 ps = 1;
  int32 total = 2;
  string nextCursor = 3;
}

// Source: com/bapis/bilibili/main/community/reply/v1/ParentReplyMember.java
message ParentReplyMember {
  int64 mid = 1;
  string name = 2;
}

// Source: com/bapis/bilibili/main/community/reply/v1/PGCVideoSearchItem.java
message PGCVideoSearchItem {
  string title = 1;
  string category = 2;
  string cover = 3;
}

// Source: com/bapis/bilibili/main/community/reply/v1/Picture.java
message Picture {
  string imgSrc = 1;
  double imgWidth = 2;
  double imgHeight = 3;
  double imgSize = 4;
  string topRightIcon = 5;
  bool playGifThumbnail = 6;
  PictureBadge pictureBadge = 7;
}

// Source: com/bapis/bilibili/main/community/reply/v1/PictureBadge.java
message PictureBadge {
  string text = 1;
  string icon = 2;
}

// Source: com/bapis/bilibili/main/community/reply/v1/PictureListReq.java
message PictureListReq {
  int64 oid = 1;
  int64 type = 2;
  string extra = 3;
  int64 afterRpid = 4;
  Mode mode = 5;
  com.bapis.bilibili.pagination.FeedPagination pagination = 6;
  string sessionId = 7;
  string mainListSessionId = 8;
}

// Source: com/bapis/bilibili/main/community/reply/v1/PictureListResp.java
message PictureListResp {
  repeated ReplyInfo replies = 1;
  com.bapis.bilibili.pagination.FeedPaginationReply paginationReply = 2;
  string sessionId = 3;
  string reportParams = 4;
  string contextFeature = 5;
  string paginationEndText = 6;
}

// Source: com/bapis/bilibili/main/community/reply/v1/PreviewListReply.java
message PreviewListReply {
  CursorReply cursor = 1;
  repeated ReplyInfo replies = 2;
  SubjectControl subjectControl = 3;
  ReplyInfo upTop = 4;
  ReplyInfo adminTop = 5;
  ReplyInfo voteTop = 6;
}

// Source: com/bapis/bilibili/main/community/reply/v1/PreviewListReq.java
message PreviewListReq {
  int64 oid = 1;
  int64 type = 2;
  CursorReq cursor = 3;
}

// Source: com/bapis/bilibili/main/community/reply/v1/QoeInfo.java
message QoeInfo {
  int64 id = 1;
  int32 type = 2;
  int32 style = 3;
  string title = 4;
  string feedbackTitle = 5;
  repeated QoeScoreItem scoreItems = 6;
  int64 displayRank = 7;
  Form form = 8;
}

// Source: com/bapis/bilibili/main/community/reply/v1/QoeOption.java
message QoeOption {
  string title = 1;
  float score = 2;
  string imgUrl = 3;
  repeated string desc = 4;
}

// Source: com/bapis/bilibili/main/community/reply/v1/QoeOptionDesc.java
message QoeOptionDesc {
  repeated string desc = 1;
}

// Source: com/bapis/bilibili/main/community/reply/v1/QoeScoreItem.java
message QoeScoreItem {
  string title = 1;
  string url = 2;
  float score = 3;
}

// Source: com/bapis/bilibili/main/community/reply/v1/QuestionCard.java
message QuestionCard {
  QuestionCard_Question question = 1;
  QuestionCardStat stat = 2;
  string bottomText = 3;
}

// Source: com/bapis/bilibili/main/community/reply/v1/QuestionCard.java
message QuestionCard_Option {
  string key = 1;
  string title = 2;
}

// Source: com/bapis/bilibili/main/community/reply/v1/QuestionCard.java
message QuestionCard_Question {
  int64 qid = 1;
  string title = 2;
  bool mustRight = 3;
  repeated QuestionCard_Option options = 4;
}

// Source: com/bapis/bilibili/main/community/reply/v1/QuestionCardStat.java
message QuestionCardStat {
  int64 rightCnt = 1;
  int64 rightMidCnt = 2;
  int64 submitMidCnt = 3;
}

// Source: com/bapis/bilibili/main/community/reply/v1/QuizCard.java
message QuizCard {
  int64 quizId = 1;
  string title = 2;
  int32 count = 3;
  int32 allCoin = 4;
  string quizText = 5;
  repeated QuizCard_Option options = 6;
  int32 myOption = 7;
  int32 upOption = 8;
  string url = 9;
  int32 state = 10;
  int32 winOption = 11;
  string editUrl = 12;
  string quizIcon = 13;
  int32 initialPoolCoin = 14;
}

// Source: com/bapis/bilibili/main/community/reply/v1/QuizCard.java
message QuizCard_Option {
  int32 idx = 1;
  string desc = 2;
  int32 coinPer = 3;
  string prefixText = 4;
}

// Source: com/bapis/bilibili/main/community/reply/v1/QuizOption.java
message QuizOption {
  string desc = 1;
  int32 coinPer = 2;
  string color = 3;
  bool isMyOption = 4;
  bool isAnswer = 5;
  string bgColor = 6;
  int32 idx = 7;
}

// Source: com/bapis/bilibili/main/community/reply/v1/QuizShareReply.java
message QuizShareReply {
  string bgImg = 1;
  string headAvatar = 2;
  string headText = 3;
  string headTitle = 4;
  string headSubtitle = 5;
  string headSubtitleCoin = 6;
  string bodyTitle = 7;
  ATRow bodyUpRow = 8;
  repeated QuizOption options = 9;
  ATRow bodyDownRow = 10;
  string tailCover = 11;
  string tailTitle = 12;
  string tailQrCode = 13;
  string tailImg = 14;
  string headSubtitlePer = 15;
  int64 quizId = 16;
  int32 quizStatus = 17;
}

// Source: com/bapis/bilibili/main/community/reply/v1/QuizShareReq.java
message QuizShareReq {
  int32 type = 1;
  int64 oid = 2;
}

// Source: com/bapis/bilibili/main/community/reply/v1/ReferReply.java
message ReferReply {
  int64 oid = 1;
  int64 rpid = 2;
}

// Source: com/bapis/bilibili/main/community/reply/v1/ReplyCardLabel.java
message ReplyCardLabel {
  string textContent = 1;
  string textColorDay = 2;
  string textColorNight = 3;
  string labelColorDay = 4;
  string labelColorNight = 5;
  string image = 6;
  Type type = 7;
  string background = 8;
  double backgroundWidth = 9;
  double backgroundHeight = 10;
  string jumpUrl = 11;
  int64 effect = 12;
  int64 effectStartTime = 13;
  enum Type {
    UNDERLINE = 0;
    BACKGROUND = 1;
  }

}

// Source: com/bapis/bilibili/main/community/reply/v1/ReplyControl.java
message ReplyControl {
  int64 action = 1;
  bool upLike = 2;
  bool upReply = 3;
  bool showFollowBtn = 4;
  bool isAssist = 5;
  string labelText = 6;
  bool following = 7;
  bool followed = 8;
  bool blocked = 9;
  bool hasFoldedReply = 10;
  bool isFoldedReply = 11;
  bool isUpTop = 12;
  bool isAdminTop = 13;
  bool isVoteTop = 14;
  int64 maxLine = 15;
  bool invisible = 16;
  bool isContractor = 17;
  bool isNote = 18;
  repeated ReplyCardLabel cardLabels = 19;
  string subReplyEntryText = 20;
  string subReplyTitleText = 21;
  string contractDesc = 22;
  string timeDesc = 23;
  string bizScene = 24;
  string location = 25;
  bool foldPictures = 26;
  bool isNoteV2 = 27;
  bool hideNoteIcon = 28;
  string cmRecommendComponent = 29;
  ReplyControl_VoteOption voteOption = 30;
  string chargedDesc = 31;
  ReplyControl_GradeRecord gradeRecord = 32;
  string presetReplyText = 33;
  ReplyControl_EasterEggLabel easterEggLabel = 34;
  string contextFeature = 35;
  ReplyControl_InsertEffect insertEffect = 36;
  TranslationSwitch translationSwitch = 37;
  bool supportShare = 38;
  ReplyControl_FlyInfo flyInfo = 39;
}

// Source: com/bapis/bilibili/main/community/reply/v1/ReplyControl.java
message ReplyControl_EasterEggLabel {
  string image = 1;
  string jumpUrl = 2;
}

// Source: com/bapis/bilibili/main/community/reply/v1/ReplyControl.java
message ReplyControl_FlyInfo {
  string orderId = 1;
}

// Source: com/bapis/bilibili/main/community/reply/v1/ReplyControl.java
message ReplyControl_GradeRecord {
  int32 score = 1;
  repeated ReplyControl_GradeRecord_Text texts = 2;
}

// Source: com/bapis/bilibili/main/community/reply/v1/ReplyControl.java
message ReplyControl_GradeRecord_Text {
  string raw = 1;
  TextStyle style = 2;
}

// Source: com/bapis/bilibili/main/community/reply/v1/ReplyControl.java
message ReplyControl_InsertEffect {
  string content = 1;
  string icon = 2;
}

// Source: com/bapis/bilibili/main/community/reply/v1/ReplyControl.java
message ReplyControl_VoteOption {
  LabelKind labelKind = 1;
  string desc = 2;
  int64 idx = 3;
  int64 voteId = 4;
  string prefixText = 5;
  enum LabelKind {
    DEFAULT = 0;
    RED = 1;
    BLUE = 2;
    PLAIN = 3;
  }

}

// Source: com/bapis/bilibili/main/community/reply/v1/ReplyExtra.java
message ReplyExtra {
  int64 seasonId = 1;
  int64 seasonType = 2;
  int64 epId = 3;
  bool isStory = 4;
  string spmid = 5;
  string fromSpmid = 6;
  bool disableUnderline = 7;
  bool disableWeSearch = 8;
  bool disableFilterTag = 9;
  bool isActivityMode = 10;
  string trackId = 11;
}

// Source: com/bapis/bilibili/main/community/reply/v1/ReplyInAppPushPayload.java
message ReplyInAppPushPayload {
  ReplyInAppPushPayload_Reply reply = 1;
  ReplyInAppPushPayload_Reply parentReply = 2;
  ReplyInAppPushPayload_Subject subject = 3;
  ReplyInAppPushPayload_SubjectMaterial subjectMaterial = 4;
}

// Source: com/bapis/bilibili/main/community/reply/v1/ReplyInAppPushPayload.java
message ReplyInAppPushPayload_Content {
  string message_ = 1;
  map<string, Emote> emotes = 2;
  map<string, int64> atNameToMid = 3;
  repeated Picture pictures = 4;
}

// Source: com/bapis/bilibili/main/community/reply/v1/ReplyInAppPushPayload.java
message ReplyInAppPushPayload_Member {
  int64 mid = 1;
  string name = 2;
  string face = 3;
}

// Source: com/bapis/bilibili/main/community/reply/v1/ReplyInAppPushPayload.java
message ReplyInAppPushPayload_Reply {
  int64 id = 1;
  int64 type = 2;
  int64 oid = 3;
  int64 mid = 4;
  int64 root = 5;
  int64 parent = 6;
  int64 dialog = 7;
  int64 ctime = 8;
  ReplyInAppPushPayload_Content content = 9;
  ReplyInAppPushPayload_Member member = 10;
}

// Source: com/bapis/bilibili/main/community/reply/v1/ReplyInAppPushPayload.java
message ReplyInAppPushPayload_Subject {
  int64 type = 1;
  int64 oid = 2;
  int64 upMid = 3;
}

// Source: com/bapis/bilibili/main/community/reply/v1/ReplyInAppPushPayload.java
message ReplyInAppPushPayload_SubjectMaterial {
  oneof oneof_0 {
    ReplyInAppPushPayload_SubjectMaterial_Archive arc = 1;
  }
  enum ItemCase {
    ITEM_NOT_SET = 0;
    ARC = 1;
  }

}

// Source: com/bapis/bilibili/main/community/reply/v1/ReplyInAppPushPayload.java
message ReplyInAppPushPayload_SubjectMaterial_Archive {
  int64 aid = 1;
  string title = 2;
  string cover = 3;
}

// Source: com/bapis/bilibili/main/community/reply/v1/ReplyInfo.java
message ReplyInfo {
  repeated ReplyInfo replies = 1;
  int64 id = 2;
  int64 oid = 3;
  int64 type = 4;
  int64 mid = 5;
  int64 root = 6;
  int64 parent = 7;
  int64 dialog = 8;
  int64 like = 9;
  int64 ctime = 10;
  int64 count = 11;
  Content content = 12;
  Member member = 13;
  ReplyControl replyControl = 14;
  MemberV2 memberV2 = 15;
  string trackInfo = 16;
  Content translatedContent = 17;
  ParentReplyMember parentReplyMember = 18;
  HotReplyInfo hotInfo = 19;
}

// Source: com/bapis/bilibili/main/community/reply/v1/ReplyInfoReply.java
message ReplyInfoReply {
  ReplyInfo reply = 1;
}

// Source: com/bapis/bilibili/main/community/reply/v1/ReplyInfoReq.java
message ReplyInfoReq {
  int64 rpid = 1;
  ReplyInfoScene scene = 2;
  BizScene bizScene = 3;
  enum BizScene {
    DEFAULT = 0;
    INSERT_NEW = 1;
  }

  enum ReplyInfoScene {
    Insert = 0;
  }

}

// Source: com/bapis/bilibili/main/community/reply/v1/ReplyTrackInfo.java
message ReplyTrackInfo {
  string trackId = 1;
}

// Source: com/bapis/bilibili/main/community/reply/v1/RichText.java
message RichText {
  oneof oneof_0 {
    RichTextNote note = 1;
    com.bapis.bilibili.app.dynamic.v2.OpusItem opus = 2;
  }
  enum ItemCase {
    ITEM_NOT_SET = 0;
    NOTE = 1;
    OPUS = 2;
  }

}

// Source: com/bapis/bilibili/main/community/reply/v1/RichTextNote.java
message RichTextNote {
  string summary = 1;
  repeated string images = 2;
  string clickUrl = 3;
  string lastMtimeText = 4;
}

// Source: com/bapis/bilibili/main/community/reply/v1/SearchItem.java
message SearchItem {
  string url = 1;
  oneof oneof_0 {
    GoodsSearchItem goods = 2;
    VideoSearchItem video = 3;
    ArticleSearchItem article = 4;
  }
  enum ItemCase {
    ITEM_NOT_SET = 0;
    GOODS = 2;
    VIDEO = 3;
    ARTICLE = 4;
  }

}

// Source: com/bapis/bilibili/main/community/reply/v1/SearchItemCursorReply.java
message SearchItemCursorReply {
  bool hasNext = 1;
  int64 next = 2;
}

// Source: com/bapis/bilibili/main/community/reply/v1/SearchItemCursorReq.java
message SearchItemCursorReq {
  int64 next = 1;
  SearchItemType itemType = 2;
}

// Source: com/bapis/bilibili/main/community/reply/v1/SearchItemPreHookReply.java
message SearchItemPreHookReply {
  string placeholderText = 1;
  string backgroundText = 2;
  repeated SearchItemType orderedType = 3;
}

// Source: com/bapis/bilibili/main/community/reply/v1/SearchItemPreHookReq.java
message SearchItemPreHookReq {
  int64 oid = 1;
  int64 type = 2;
}

// Source: com/bapis/bilibili/main/community/reply/v1/SearchItemReply.java
message SearchItemReply {
  SearchItemCursorReply cursor = 1;
  repeated SearchItem items = 2;
  SearchItemReplyExtraInfo extra = 3;
}

// Source: com/bapis/bilibili/main/community/reply/v1/SearchItemReplyExtraInfo.java
message SearchItemReplyExtraInfo {
  string eventId = 1;
}

// Source: com/bapis/bilibili/main/community/reply/v1/SearchItemReq.java
message SearchItemReq {
  SearchItemCursorReq cursor = 1;
  int64 oid = 2;
  int64 type = 3;
  string keyword = 4;
}

// Source: com/bapis/bilibili/main/community/reply/v1/ShareRepliesInfoReq.java
message ShareRepliesInfoReq {
  repeated int64 rpids = 1;
  int64 oid = 2;
  int64 type = 3;
}

// Source: com/bapis/bilibili/main/community/reply/v1/ShareRepliesInfoResp.java
message ShareRepliesInfoResp {
  repeated ShareReplyInfo infos = 1;
  string fromTitle = 2;
  string fromUp = 3;
  string fromPic = 4;
  string url = 5;
  string sloganPic = 6;
  string sloganText = 7;
  ShareReplyTopic topic = 8;
  ShareRepliesInfoResp_ShareExtra extra = 9;
}

// Source: com/bapis/bilibili/main/community/reply/v1/ShareRepliesInfoResp.java
message ShareRepliesInfoResp_ShareExtra {
  bool isPgc = 1;
}

// Source: com/bapis/bilibili/main/community/reply/v1/ShareReplyInfo.java
message ShareReplyInfo {
  Member member = 1;
  Content content = 2;
  string title = 3;
  string subTitle = 4;
  string achievementText = 5;
  string labelUrl = 6;
}

// Source: com/bapis/bilibili/main/community/reply/v1/ShareReplyMaterialReq.java
message ShareReplyMaterialReq {
  int64 oid = 1;
  int64 type = 2;
  int64 rpid = 3;
  bool needTranslate = 4;
}

// Source: com/bapis/bilibili/main/community/reply/v1/ShareReplyMaterialResp.java
message ShareReplyMaterialResp {
  ShareReplyMaterialResp_SubjectMaterial subjectMaterial = 1;
  string qrcodeUrl = 2;
  string savePicText = 3;
  string openAppText = 4;
  string shareTimeText = 5;
  string biliLogoIcon = 6;
  ShareReplyMaterialResp_ExtraData extra = 7;
  string fromSubjectTypeText = 8;
  string openAppTextSubtitle = 9;
  string bgColor = 10;
  string contentBgColor = 11;
  string contentAnchorImage = 12;
  string bgTopOverlayImage = 13;
  ReplyInfo reply = 14;
  ReplyInfo parentReply = 15;
  SubjectControl subjectControl = 16;
}

// Source: com/bapis/bilibili/main/community/reply/v1/ShareReplyMaterialResp.java
message ShareReplyMaterialResp_ArchiveMaterial {
  string title = 1;
  string cover = 2;
  string upName = 3;
  string upIcon = 4;
  int64 videos = 5;
  int64 duration = 6;
}

// Source: com/bapis/bilibili/main/community/reply/v1/ShareReplyMaterialResp.java
message ShareReplyMaterialResp_ArticleMaterial {
  string title = 1;
  string message_ = 2;
  string titleV2 = 3;
  string cover = 4;
}

// Source: com/bapis/bilibili/main/community/reply/v1/ShareReplyMaterialResp.java
message ShareReplyMaterialResp_DynamicMaterial {
  string title = 1;
  string message_ = 2;
  string titleV2 = 3;
  string cover = 4;
}

// Source: com/bapis/bilibili/main/community/reply/v1/ShareReplyMaterialResp.java
message ShareReplyMaterialResp_ExtraData {
  bool isPgc = 1;
  string originText = 2;
  int64 topicId = 3;
}

// Source: com/bapis/bilibili/main/community/reply/v1/ShareReplyMaterialResp.java
message ShareReplyMaterialResp_SubjectMaterial {
  oneof oneof_0 {
    ShareReplyMaterialResp_ArchiveMaterial archiveMaterial = 1;
    ShareReplyMaterialResp_DynamicMaterial dynamicMaterial = 2;
    ShareReplyMaterialResp_ArticleMaterial articleMaterial = 3;
  }
  enum ItemCase {
    ITEM_NOT_SET = 0;
    ARCHIVE_MATERIAL = 1;
    DYNAMIC_MATERIAL = 2;
    ARTICLE_MATERIAL = 3;
  }

}

// Source: com/bapis/bilibili/main/community/reply/v1/ShareReplyTopic.java
message ShareReplyTopic {
  Topic topic = 1;
  string originText = 2;
}

// Source: com/bapis/bilibili/main/community/reply/v1/SubjectControl.java
message SubjectControl {
  int64 upMid = 1;
  bool isAssist = 2;
  bool readOnly = 3;
  bool hasVoteAccess = 4;
  bool hasLotteryAccess = 5;
  bool hasFoldedReply = 6;
  string bgText = 7;
  bool upBlocked = 8;
  bool hasActivityAccess = 9;
  bool showTitle = 10;
  bool showUpAction = 11;
  int64 switcherType = 12;
  bool inputDisable = 13;
  string rootText = 14;
  string childText = 15;
  int64 count = 16;
  string title = 17;
  string giveupText = 18;
  bool hasNoteAccess = 19;
  bool disableJumpEmote = 20;
  string emptyBackgroundTextPlain = 21;
  string emptyBackgroundTextHighlight = 22;
  string emptyBackgroundUri = 23;
  repeated SubjectControl_FilterTag supportFilterTags = 24;
  EditorIconState screenshotIconState = 25;
  EditorIconState uploadPictureIconState = 26;
  EmptyPage emptyPage = 27;
  SubjectControl_CmTopReplyProtection cmTopReplyProtection = 28;
  bool enableCharged = 29;
}

// Source: com/bapis/bilibili/main/community/reply/v1/SubjectControl.java
message SubjectControl_CmTopReplyProtection {
  int64 protectedTopRpid = 1;
  string popupMessage = 2;
  string appealUrl = 3;
}

// Source: com/bapis/bilibili/main/community/reply/v1/SubjectControl.java
message SubjectControl_FilterTag {
  string name = 1;
  string eventId = 2;
}

// Source: com/bapis/bilibili/main/community/reply/v1/SubjectTopCards.java
message SubjectTopCards {
  Type type = 1;
  string oid = 2;
  oneof oneof_0 {
    OgvGradeCard ogvGrade = 3;
    UpProtectionCard upProtection = 4;
    CM cm = 5;
    UpSelection upSelection = 6;
    OperationV2 operation = 7;
    VoteCard vote = 8;
    ESportsGradeCard esportsGrade = 9;
    QuizCard quiz = 10;
  }
  enum ItemCase {
    ITEM_NOT_SET = 0;
    ITEM_CASE_OGV_GRADE = 3;
    ITEM_CASE_UP_PROTECTION = 4;
    ITEM_CASE_CM = 5;
    ITEM_CASE_UP_SELECTION = 6;
    ITEM_CASE_OPERATION = 7;
    ITEM_CASE_VOTE = 8;
    ITEM_CASE_ESPORTS_GRADE = 9;
    ITEM_CASE_QUIZ = 10;
  }

  enum Type {
    UNKNOWN = 0;
    TYPE_OGV_GRADE = 1;
    TYPE_UP_PROTECTION = 2;
    TYPE_CM = 3;
    TYPE_UP_SELECTION = 4;
    TYPE_OPERATION = 5;
    TYPE_VOTE = 6;
    TYPE_ESPORTS_GRADE = 7;
    TYPE_QUIZ = 8;
  }

}

// Source: com/bapis/bilibili/main/community/reply/v1/SuggestEmotesReq.java
message SuggestEmotesReq {
  int64 oid = 1;
  int64 type = 2;
}

// Source: com/bapis/bilibili/main/community/reply/v1/SuggestEmotesResp.java
message SuggestEmotesResp {
  repeated Emote emotes = 1;
}

// Source: com/bapis/bilibili/main/community/reply/v1/TextStyle.java
message TextStyle {
  int32 fontSize = 1;
  FontStyle fontStyle = 2;
  string textDayColor = 3;
  string textNightColor = 4;
  enum FontStyle {
    NORMAL = 0;
    BOLD = 1;
  }

}

// Source: com/bapis/bilibili/main/community/reply/v1/Topic.java
message Topic {
  string link = 1;
  int64 id = 2;
}

// Source: com/bapis/bilibili/main/community/reply/v1/TranslateReplyReq.java
message TranslateReplyReq {
  int64 type = 1;
  int64 oid = 2;
  repeated int64 rpids = 3;
}

// Source: com/bapis/bilibili/main/community/reply/v1/TranslateReplyResp.java
message TranslateReplyResp {
  map<int64, ReplyInfo> translatedReplies = 1;
}

// Source: com/bapis/bilibili/main/community/reply/v1/UGCVideoSearchItem.java
message UGCVideoSearchItem {
  string title = 1;
  string upNickname = 2;
  int64 duration = 3;
  string cover = 4;
}

// Source: com/bapis/bilibili/main/community/reply/v1/UpdateSingleReplyNotificationConfigReq.java
message UpdateSingleReplyNotificationConfigReq {
  int64 rpid = 1;
  int64 type = 2;
  int64 oid = 3;
  ReplyNotificationSwitch pushSwitch = 4;
}

// Source: com/bapis/bilibili/main/community/reply/v1/UpdateSingleReplyNotificationConfigResp.java
message UpdateSingleReplyNotificationConfigResp {
}

// Source: com/bapis/bilibili/main/community/reply/v1/UpProtectionCard.java
message UpProtectionCard {
  string text = 1;
}

// Source: com/bapis/bilibili/main/community/reply/v1/UpSelection.java
message UpSelection {
  int64 pendingCount = 1;
  int64 ignoreCount = 2;
}

// Source: com/bapis/bilibili/main/community/reply/v1/Url.java
message Url {
  string title = 1;
  int64 state = 2;
  string prefixIcon = 3;
  string appUrlSchema = 4;
  string appName = 5;
  string appPackageName = 6;
  string clickReport = 7;
  bool isHalfScreen = 8;
  string exposureReport = 9;
  Url_Extra extra = 10;
  bool underline = 11;
  bool matchOnce = 12;
  string pcUrl = 13;
  IconPosition iconPosition = 14;
  enum IconPosition {
    Prefix = 0;
    Suffix = 1;
  }

}

// Source: com/bapis/bilibili/main/community/reply/v1/Url.java
message Url_Extra {
  int64 goodsItemId = 1;
  string goodsPrefetchedCache = 2;
  GoodsShowType goodsShowType = 3;
  bool isWordSearch = 4;
  int64 goodsCmControl = 5;
  string goodsClickReport = 6;
  string goodsExposureReport = 7;
  int64 goodsShowPopWindow = 8;
  enum GoodsShowType {
    Popup = 0;
    FullScreen = 1;
    HalfScreen = 2;
  }

}

// Source: com/bapis/bilibili/main/community/reply/v1/UserCallbackReply.java
message UserCallbackReply {
}

// Source: com/bapis/bilibili/main/community/reply/v1/UserCallbackReq.java
message UserCallbackReq {
  int64 mid = 1;
  UserCallbackScene scene = 2;
  UserCallbackAction action = 3;
  int64 oid = 4;
  int64 type = 5;
  repeated int64 rpids = 6;
}

// Source: com/bapis/bilibili/main/community/reply/v1/VideoSearchItem.java
message VideoSearchItem {
  SearchItemVideoSubType type = 1;
  oneof oneof_0 {
    UGCVideoSearchItem ugc = 2;
    PGCVideoSearchItem pgc = 3;
  }
  enum VideoItemCase {
    VIDEOITEM_NOT_SET = 0;
    UGC = 2;
    PGC = 3;
  }

}

// Source: com/bapis/bilibili/main/community/reply/v1/Vote.java
message Vote {
  int64 id = 1;
  string title = 2;
  int64 count = 3;
}

// Source: com/bapis/bilibili/main/community/reply/v1/VoteCard.java
message VoteCard {
  int64 voteId = 1;
  string title = 2;
  int64 count = 3;
  repeated VoteCard_Option options = 4;
  int64 myVoteOption = 5;
}

// Source: com/bapis/bilibili/main/community/reply/v1/VoteCard.java
message VoteCard_Option {
  int64 idx = 1;
  string desc = 2;
  int64 count = 3;
}

// Source: com/bapis/bilibili/main/community/reply/v1/WordSearchParam.java
message WordSearchParam {
  int64 shownCount = 1;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/main/community/reply/v1";
