// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.api.probe.v1;

// Source: com/bapis/bilibili/api/probe/v1/CodeReply.java
message CodeReply {
}

// Source: com/bapis/bilibili/api/probe/v1/CodeReq.java
message CodeReq {
  int64 code = 1;
}

// Source: com/bapis/bilibili/api/probe/v1/ProbeReply.java
message ProbeReply {
  string content = 1;
  int64 timestamp = 2;
}

// Source: com/bapis/bilibili/api/probe/v1/ProbeReq.java
message ProbeReq {
  int64 mid = 1;
  string buvid = 2;
}

// Source: com/bapis/bilibili/api/probe/v1/ProbeStreamReply.java
message ProbeStreamReply {
  int64 sequence = 1;
  int64 timestamp = 2;
  string content = 3;
}

// Source: com/bapis/bilibili/api/probe/v1/ProbeStreamReq.java
message ProbeStreamReq {
  int64 mid = 1;
  int64 sequence = 2;
}

// Source: com/bapis/bilibili/api/probe/v1/ProbeSubReply.java
message ProbeSubReply {
  int64 messageId = 1;
}

// Source: com/bapis/bilibili/api/probe/v1/ProbeSubReq.java
message ProbeSubReq {
  string buvid = 1;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/api/probe/v1";
