// Reconstructed from protobuf-lite metadata in the APK.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: bilibili/api/probe/v1/messages.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Category int32

const (
	Category_CATEGORY_UNSPECIFIED Category = 0
	Category_CATEGORY_ONE         Category = 1
	Category_CATEGORY_TWO         Category = 2
	Category_CATEGORY_THREE       Category = 3
	Category_CATEGORY_FOUR        Category = 4
)

// Enum value maps for Category.
var (
	Category_name = map[int32]string{
		0: "CATEGORY_UNSPECIFIED",
		1: "CATEGORY_ONE",
		2: "CATEGORY_TWO",
		3: "CATEGORY_THREE",
		4: "CATEGORY_FOUR",
	}
	Category_value = map[string]int32{
		"CATEGORY_UNSPECIFIED": 0,
		"CATEGORY_ONE":         1,
		"CATEGORY_TWO":         2,
		"CATEGORY_THREE":       3,
		"CATEGORY_FOUR":        4,
	}
)

func (x Category) Enum() *Category {
	p := new(Category)
	*p = x
	return p
}

func (x Category) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Category) Descriptor() protoreflect.EnumDescriptor {
	return file_bilibili_api_probe_v1_messages_proto_enumTypes[0].Descriptor()
}

func (Category) Type() protoreflect.EnumType {
	return &file_bilibili_api_probe_v1_messages_proto_enumTypes[0]
}

func (x Category) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Category.Descriptor instead.
func (Category) EnumDescriptor() ([]byte, []int) {
	return file_bilibili_api_probe_v1_messages_proto_rawDescGZIP(), []int{0}
}

// Source: com/bapis/bilibili/api/probe/v1/CodeReply.java
type CodeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Id1      string `protobuf:"bytes,2,opt,name=id1,proto3" json:"id1,omitempty"`
	Code     int64  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	MessageS string `protobuf:"bytes,4,opt,name=messageS,proto3" json:"messageS,omitempty"`
}

func (x *CodeReply) Reset() {
	*x = CodeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_api_probe_v1_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeReply) ProtoMessage() {}

func (x *CodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_api_probe_v1_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeReply.ProtoReflect.Descriptor instead.
func (*CodeReply) Descriptor() ([]byte, []int) {
	return file_bilibili_api_probe_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *CodeReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CodeReply) GetId1() string {
	if x != nil {
		return x.Id1
	}
	return ""
}

func (x *CodeReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CodeReply) GetMessageS() string {
	if x != nil {
		return x.MessageS
	}
	return ""
}

// Source: com/bapis/bilibili/api/probe/v1/CodeReq.java
type CodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *CodeReq) Reset() {
	*x = CodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_api_probe_v1_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeReq) ProtoMessage() {}

func (x *CodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_api_probe_v1_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeReq.ProtoReflect.Descriptor instead.
func (*CodeReq) Descriptor() ([]byte, []int) {
	return file_bilibili_api_probe_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CodeReq) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

// Source: com/bapis/bilibili/api/probe/v1/CreateTopic.java
type CreateTopic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateTopic) Reset() {
	*x = CreateTopic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_api_probe_v1_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTopic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopic) ProtoMessage() {}

func (x *CreateTopic) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_api_probe_v1_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopic.ProtoReflect.Descriptor instead.
func (*CreateTopic) Descriptor() ([]byte, []int) {
	return file_bilibili_api_probe_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTopic) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Source: com/bapis/bilibili/api/probe/v1/CreatTask.java
type CreatTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreatTask) Reset() {
	*x = CreatTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_api_probe_v1_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatTask) ProtoMessage() {}

func (x *CreatTask) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_api_probe_v1_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatTask.ProtoReflect.Descriptor instead.
func (*CreatTask) Descriptor() ([]byte, []int) {
	return file_bilibili_api_probe_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *CreatTask) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Source: com/bapis/bilibili/api/probe/v1/DynamicMessageUpdate.java
type DynamicMessageUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body *SimpleMessage `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *DynamicMessageUpdate) Reset() {
	*x = DynamicMessageUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_api_probe_v1_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DynamicMessageUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicMessageUpdate) ProtoMessage() {}

func (x *DynamicMessageUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_api_probe_v1_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicMessageUpdate.ProtoReflect.Descriptor instead.
func (*DynamicMessageUpdate) Descriptor() ([]byte, []int) {
	return file_bilibili_api_probe_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *DynamicMessageUpdate) GetBody() *SimpleMessage {
	if x != nil {
		return x.Body
	}
	return nil
}

// Source: com/bapis/bilibili/api/probe/v1/Embedded.java
type Embedded struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BoolVal           bool                     `protobuf:"varint,1,opt,name=boolVal,proto3" json:"boolVal,omitempty"`
	Int32Val          int32                    `protobuf:"varint,2,opt,name=int32Val,proto3" json:"int32Val,omitempty"`
	Int64Val          int64                    `protobuf:"varint,3,opt,name=int64Val,proto3" json:"int64Val,omitempty"`
	FloatVal          float32                  `protobuf:"fixed32,4,opt,name=floatVal,proto3" json:"floatVal,omitempty"`
	DoubleVal         float64                  `protobuf:"fixed64,5,opt,name=doubleVal,proto3" json:"doubleVal,omitempty"`
	StringVal         string                   `protobuf:"bytes,6,opt,name=stringVal,proto3" json:"stringVal,omitempty"`
	RepeatedBoolVal   []bool                   `protobuf:"varint,7,rep,packed,name=repeatedBoolVal,proto3" json:"repeatedBoolVal,omitempty"`
	RepeatedInt32Val  []int32                  `protobuf:"varint,8,rep,packed,name=repeatedInt32Val,proto3" json:"repeatedInt32Val,omitempty"`
	RepeatedInt64Val  []int64                  `protobuf:"varint,9,rep,packed,name=repeatedInt64Val,proto3" json:"repeatedInt64Val,omitempty"`
	RepeatedFloatVal  []float32                `protobuf:"fixed32,10,rep,packed,name=repeatedFloatVal,proto3" json:"repeatedFloatVal,omitempty"`
	RepeatedDoubleVal []float64                `protobuf:"fixed64,11,rep,packed,name=repeatedDoubleVal,proto3" json:"repeatedDoubleVal,omitempty"`
	RepeatedStringVal []string                 `protobuf:"bytes,12,rep,name=repeatedStringVal,proto3" json:"repeatedStringVal,omitempty"`
	MapStringVal      map[string]string        `protobuf:"bytes,13,rep,name=mapStringVal,proto3" json:"mapStringVal,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	MapErrorVal       map[string]*ErrorMessage `protobuf:"bytes,14,rep,name=mapErrorVal,proto3" json:"mapErrorVal,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Embedded) Reset() {
	*x = Embedded{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_api_probe_v1_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Embedded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Embedded) ProtoMessage() {}

func (x *Embedded) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_api_probe_v1_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Embedded.ProtoReflect.Descriptor instead.
func (*Embedded) Descriptor() ([]byte, []int) {
	return file_bilibili_api_probe_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *Embedded) GetBoolVal() bool {
	if x != nil {
		return x.BoolVal
	}
	return false
}

func (x *Embedded) GetInt32Val() int32 {
	if x != nil {
		return x.Int32Val
	}
	return 0
}

func (x *Embedded) GetInt64Val() int64 {
	if x != nil {
		return x.Int64Val
	}
	return 0
}

func (x *Embedded) GetFloatVal() float32 {
	if x != nil {
		return x.FloatVal
	}
	return 0
}

func (x *Embedded) GetDoubleVal() float64 {
	if x != nil {
		return x.DoubleVal
	}
	return 0
}

func (x *Embedded) GetStringVal() string {
	if x != nil {
		return x.StringVal
	}
	return ""
}

func (x *Embedded) GetRepeatedBoolVal() []bool {
	if x != nil {
		return x.RepeatedBoolVal
	}
	return nil
}

func (x *Embedded) GetRepeatedInt32Val() []int32 {
	if x != nil {
		return x.RepeatedInt32Val
	}
	return nil
}

func (x *Embedded) GetRepeatedInt64Val() []int64 {
	if x != nil {
		return x.RepeatedInt64Val
	}
	return nil
}

func (x *Embedded) GetRepeatedFloatVal() []float32 {
	if x != nil {
		return x.RepeatedFloatVal
	}
	return nil
}

func (x *Embedded) GetRepeatedDoubleVal() []float64 {
	if x != nil {
		return x.RepeatedDoubleVal
	}
	return nil
}

func (x *Embedded) GetRepeatedStringVal() []string {
	if x != nil {
		return x.RepeatedStringVal
	}
	return nil
}

func (x *Embedded) GetMapStringVal() map[string]string {
	if x != nil {
		return x.MapStringVal
	}
	return nil
}

func (x *Embedded) GetMapErrorVal() map[string]*ErrorMessage {
	if x != nil {
		return x.MapErrorVal
	}
	return nil
}

// Source: com/bapis/bilibili/api/probe/v1/ErrorMessage.java
type ErrorMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Reason   string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Message_ string `protobuf:"bytes,3,opt,name=message_,json=message,proto3" json:"message_,omitempty"`
}

func (x *ErrorMessage) Reset() {
	*x = ErrorMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_api_probe_v1_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMessage) ProtoMessage() {}

func (x *ErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_api_probe_v1_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMessage.ProtoReflect.Descriptor instead.
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return file_bilibili_api_probe_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *ErrorMessage) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorMessage) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ErrorMessage) GetMessage_() string {
	if x != nil {
		return x.Message_
	}
	return ""
}

// Source: com/bapis/bilibili/api/probe/v1/ProbeReply.java
type ProbeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content   string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp int64  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *ProbeReply) Reset() {
	*x = ProbeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_api_probe_v1_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProbeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeReply) ProtoMessage() {}

func (x *ProbeReply) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_api_probe_v1_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeReply.ProtoReflect.Descriptor instead.
func (*ProbeReply) Descriptor() ([]byte, []int) {
	return file_bilibili_api_probe_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *ProbeReply) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ProbeReply) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Source: com/bapis/bilibili/api/probe/v1/ProbeReq.java
type ProbeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mid   int64  `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	Buvid string `protobuf:"bytes,2,opt,name=buvid,proto3" json:"buvid,omitempty"`
}

func (x *ProbeReq) Reset() {
	*x = ProbeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_api_probe_v1_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProbeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeReq) ProtoMessage() {}

func (x *ProbeReq) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_api_probe_v1_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeReq.ProtoReflect.Descriptor instead.
func (*ProbeReq) Descriptor() ([]byte, []int) {
	return file_bilibili_api_probe_v1_messages_proto_rawDescGZIP(), []int{8}
}

func (x *ProbeReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *ProbeReq) GetBuvid() string {
	if x != nil {
		return x.Buvid
	}
	return ""
}

// Source: com/bapis/bilibili/api/probe/v1/ProbeStreamReply.java
type ProbeStreamReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sequence  int64  `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Timestamp int64  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Content   string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *ProbeStreamReply) Reset() {
	*x = ProbeStreamReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_api_probe_v1_messages_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProbeStreamReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeStreamReply) ProtoMessage() {}

func (x *ProbeStreamReply) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_api_probe_v1_messages_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeStreamReply.ProtoReflect.Descriptor instead.
func (*ProbeStreamReply) Descriptor() ([]byte, []int) {
	return file_bilibili_api_probe_v1_messages_proto_rawDescGZIP(), []int{9}
}

func (x *ProbeStreamReply) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ProbeStreamReply) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ProbeStreamReply) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// Source: com/bapis/bilibili/api/probe/v1/ProbeStreamReq.java
type ProbeStreamReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mid      int64 `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	Sequence int64 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
}

func (x *ProbeStreamReq) Reset() {
	*x = ProbeStreamReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_api_probe_v1_messages_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProbeStreamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeStreamReq) ProtoMessage() {}

func (x *ProbeStreamReq) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_api_probe_v1_messages_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeStreamReq.ProtoReflect.Descriptor instead.
func (*ProbeStreamReq) Descriptor() ([]byte, []int) {
	return file_bilibili_api_probe_v1_messages_proto_rawDescGZIP(), []int{10}
}

func (x *ProbeStreamReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *ProbeStreamReq) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// Source: com/bapis/bilibili/api/probe/v1/ProbeSubReply.java
type ProbeSubReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId int64 `protobuf:"varint,1,opt,name=messageId,proto3" json:"messageId,omitempty"`
}

func (x *ProbeSubReply) Reset() {
	*x = ProbeSubReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_api_probe_v1_messages_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProbeSubReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeSubReply) ProtoMessage() {}

func (x *ProbeSubReply) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_api_probe_v1_messages_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeSubReply.ProtoReflect.Descriptor instead.
func (*ProbeSubReply) Descriptor() ([]byte, []int) {
	return file_bilibili_api_probe_v1_messages_proto_rawDescGZIP(), []int{11}
}

func (x *ProbeSubReply) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

// Source: com/bapis/bilibili/api/probe/v1/ProbeSubReq.java
type ProbeSubReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Buvid string `protobuf:"bytes,1,opt,name=buvid,proto3" json:"buvid,omitempty"`
}

func (x *ProbeSubReq) Reset() {
	*x = ProbeSubReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_api_probe_v1_messages_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProbeSubReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeSubReq) ProtoMessage() {}

func (x *ProbeSubReq) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_api_probe_v1_messages_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeSubReq.ProtoReflect.Descriptor instead.
func (*ProbeSubReq) Descriptor() ([]byte, []int) {
	return file_bilibili_api_probe_v1_messages_proto_rawDescGZIP(), []int{12}
}

func (x *ProbeSubReq) GetBuvid() string {
	if x != nil {
		return x.Buvid
	}
	return ""
}

// Source: com/bapis/bilibili/api/probe/v1/SimpleMessage.java
type SimpleMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Num      int64     `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	Lang     string    `protobuf:"bytes,3,opt,name=lang,proto3" json:"lang,omitempty"`
	Cate     Category  `protobuf:"varint,4,opt,name=cate,proto3,enum=com.bapis.bilibili.api.probe.v1.Category" json:"cate,omitempty"`
	Embedded *Embedded `protobuf:"bytes,5,opt,name=embedded,proto3" json:"embedded,omitempty"`
}

func (x *SimpleMessage) Reset() {
	*x = SimpleMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_api_probe_v1_messages_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimpleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleMessage) ProtoMessage() {}

func (x *SimpleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_api_probe_v1_messages_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleMessage.ProtoReflect.Descriptor instead.
func (*SimpleMessage) Descriptor() ([]byte, []int) {
	return file_bilibili_api_probe_v1_messages_proto_rawDescGZIP(), []int{13}
}

func (x *SimpleMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SimpleMessage) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *SimpleMessage) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *SimpleMessage) GetCate() Category {
	if x != nil {
		return x.Cate
	}
	return Category_CATEGORY_UNSPECIFIED
}

func (x *SimpleMessage) GetEmbedded() *Embedded {
	if x != nil {
		return x.Embedded
	}
	return nil
}

// Source: com/bapis/bilibili/api/probe/v1/Task.java
type Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Author string `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Cache  bool   `protobuf:"varint,3,opt,name=cache,proto3" json:"cache,omitempty"`
}

func (x *Task) Reset() {
	*x = Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_api_probe_v1_messages_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_api_probe_v1_messages_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_bilibili_api_probe_v1_messages_proto_rawDescGZIP(), []int{14}
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Task) GetCache() bool {
	if x != nil {
		return x.Cache
	}
	return false
}

var File_bilibili_api_probe_v1_messages_proto protoreflect.FileDescriptor

var file_bilibili_api_probe_v1_messages_proto_rawDesc = []byte{
	0x0a, 0x24, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70,
	0x72, 0x6f, 0x62, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1f, 0x63, 0x6f, 0x6d, 0x2e, 0x62, 0x61, 0x70, 0x69,
	0x73, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70,
	0x72, 0x6f, 0x62, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x5d, 0x0a, 0x09, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x69, 0x64, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x22, 0x1d, 0x0a, 0x07, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x1d, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x6f, 0x70, 0x69, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x1f, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x54, 0x61, 0x73,
	0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x5a, 0x0a, 0x14, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x42, 0x0a,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x62, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69,
	0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x22, 0xad, 0x06, 0x0a, 0x08, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x65, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x62, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x62, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x33,
	0x32, 0x56, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x33,
	0x32, 0x56, 0x61, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x56, 0x61, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x56, 0x61, 0x6c,
	0x12, 0x1a, 0x0a, 0x08, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x56, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x08, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x56, 0x61, 0x6c, 0x12, 0x1c, 0x0a, 0x09,
	0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x09, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x12, 0x28, 0x0a, 0x0f, 0x72, 0x65, 0x70, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x42, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x18, 0x07, 0x20, 0x03, 0x28,
	0x08, 0x52, 0x0f, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x6f, 0x6f, 0x6c, 0x56,
	0x61, 0x6c, 0x12, 0x2a, 0x0a, 0x10, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x49, 0x6e,
	0x74, 0x33, 0x32, 0x56, 0x61, 0x6c, 0x18, 0x08, 0x20, 0x03, 0x28, 0x05, 0x52, 0x10, 0x72, 0x65,
	0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x56, 0x61, 0x6c, 0x12, 0x2a,
	0x0a, 0x10, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x56,
	0x61, 0x6c, 0x18, 0x09, 0x20, 0x03, 0x28, 0x03, 0x52, 0x10, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x56, 0x61, 0x6c, 0x12, 0x2a, 0x0a, 0x10, 0x72, 0x65,
	0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x56, 0x61, 0x6c, 0x18, 0x0a,
	0x20, 0x03, 0x28, 0x02, 0x52, 0x10, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x46, 0x6c,
	0x6f, 0x61, 0x74, 0x56, 0x61, 0x6c, 0x12, 0x2c, 0x0a, 0x11, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x18, 0x0b, 0x20, 0x03, 0x28,
	0x01, 0x52, 0x11, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x44, 0x6f, 0x75, 0x62, 0x6c,
	0x65, 0x56, 0x61, 0x6c, 0x12, 0x2c, 0x0a, 0x11, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x11, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56,
	0x61, 0x6c, 0x12, 0x5f, 0x0a, 0x0c, 0x6d, 0x61, 0x70, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56,
	0x61, 0x6c, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3b, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x62,
	0x61, 0x70, 0x69, 0x73, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x62, 0x65, 0x64,
	0x64, 0x65, 0x64, 0x2e, 0x4d, 0x61, 0x70, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0c, 0x6d, 0x61, 0x70, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x56, 0x61, 0x6c, 0x12, 0x5c, 0x0a, 0x0b, 0x6d, 0x61, 0x70, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x56,
	0x61, 0x6c, 0x18, 0x0e, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3a, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x62,
	0x61, 0x70, 0x69, 0x73, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x62, 0x65, 0x64,
	0x64, 0x65, 0x64, 0x2e, 0x4d, 0x61, 0x70, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x56, 0x61, 0x6c, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b, 0x6d, 0x61, 0x70, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x56, 0x61,
	0x6c, 0x1a, 0x3f, 0x0a, 0x11, 0x4d, 0x61, 0x70, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61,
	0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x1a, 0x6d, 0x0a, 0x10, 0x4d, 0x61, 0x70, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x56, 0x61,
	0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x43, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x62, 0x61,
	0x70, 0x69, 0x73, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x55, 0x0a, 0x0c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x19, 0x0a,
	0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x44, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x62,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x32,
	0x0a, 0x08, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6d, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x62, 0x75, 0x76, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x75, 0x76,
	0x69, 0x64, 0x22, 0x66, 0x0a, 0x10, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e,
	0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x3e, 0x0a, 0x0e, 0x50, 0x72,
	0x6f, 0x62, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6d, 0x69, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x22, 0x2d, 0x0a, 0x0d, 0x50, 0x72,
	0x6f, 0x62, 0x65, 0x53, 0x75, 0x62, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x22, 0x23, 0x0a, 0x0b, 0x50, 0x72, 0x6f,
	0x62, 0x65, 0x53, 0x75, 0x62, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x75, 0x76, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x75, 0x76, 0x69, 0x64, 0x22, 0xcb,
	0x01, 0x0a, 0x0d, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6e,
	0x75, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x12, 0x3d, 0x0a, 0x04, 0x63, 0x61, 0x74, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x62, 0x61, 0x70, 0x69, 0x73,
	0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72,
	0x6f, 0x62, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52,
	0x04, 0x63, 0x61, 0x74, 0x65, 0x12, 0x45, 0x0a, 0x08, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x65,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x62, 0x61,
	0x70, 0x69, 0x73, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64,
	0x65, 0x64, 0x52, 0x08, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x65, 0x64, 0x22, 0x48, 0x0a, 0x04,
	0x54, 0x61, 0x73, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x61, 0x63, 0x68, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x05, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2a, 0x6f, 0x0a, 0x08, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x12, 0x18, 0x0a, 0x14, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c,
	0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x4f, 0x4e, 0x45, 0x10, 0x01, 0x12, 0x10,
	0x0a, 0x0c, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x54, 0x57, 0x4f, 0x10, 0x02,
	0x12, 0x12, 0x0a, 0x0e, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x54, 0x48, 0x52,
	0x45, 0x45, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59,
	0x5f, 0x46, 0x4f, 0x55, 0x52, 0x10, 0x04, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x6d, 0x74, 0x63, 0x32, 0x33, 0x33, 0x2f, 0x62,
	0x69, 0x6c, 0x69, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x61, 0x70, 0x69, 0x2d, 0x67, 0x6f, 0x2f,
	0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f,
	0x62, 0x65, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bilibili_api_probe_v1_messages_proto_rawDescOnce sync.Once
	file_bilibili_api_probe_v1_messages_proto_rawDescData = file_bilibili_api_probe_v1_messages_proto_rawDesc
)

func file_bilibili_api_probe_v1_messages_proto_rawDescGZIP() []byte {
	file_bilibili_api_probe_v1_messages_proto_rawDescOnce.Do(func() {
		file_bilibili_api_probe_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_bilibili_api_probe_v1_messages_proto_rawDescData)
	})
	return file_bilibili_api_probe_v1_messages_proto_rawDescData
}

var file_bilibili_api_probe_v1_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bilibili_api_probe_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_bilibili_api_probe_v1_messages_proto_goTypes = []interface{}{
	(Category)(0),                // 0: com.bapis.bilibili.api.probe.v1.Category
	(*CodeReply)(nil),            // 1: com.bapis.bilibili.api.probe.v1.CodeReply
	(*CodeReq)(nil),              // 2: com.bapis.bilibili.api.probe.v1.CodeReq
	(*CreateTopic)(nil),          // 3: com.bapis.bilibili.api.probe.v1.CreateTopic
	(*CreatTask)(nil),            // 4: com.bapis.bilibili.api.probe.v1.CreatTask
	(*DynamicMessageUpdate)(nil), // 5: com.bapis.bilibili.api.probe.v1.DynamicMessageUpdate
	(*Embedded)(nil),             // 6: com.bapis.bilibili.api.probe.v1.Embedded
	(*ErrorMessage)(nil),         // 7: com.bapis.bilibili.api.probe.v1.ErrorMessage
	(*ProbeReply)(nil),           // 8: com.bapis.bilibili.api.probe.v1.ProbeReply
	(*ProbeReq)(nil),             // 9: com.bapis.bilibili.api.probe.v1.ProbeReq
	(*ProbeStreamReply)(nil),     // 10: com.bapis.bilibili.api.probe.v1.ProbeStreamReply
	(*ProbeStreamReq)(nil),       // 11: com.bapis.bilibili.api.probe.v1.ProbeStreamReq
	(*ProbeSubReply)(nil),        // 12: com.bapis.bilibili.api.probe.v1.ProbeSubReply
	(*ProbeSubReq)(nil),          // 13: com.bapis.bilibili.api.probe.v1.ProbeSubReq
	(*SimpleMessage)(nil),        // 14: com.bapis.bilibili.api.probe.v1.SimpleMessage
	(*Task)(nil),                 // 15: com.bapis.bilibili.api.probe.v1.Task
	nil,                          // 16: com.bapis.bilibili.api.probe.v1.Embedded.MapStringValEntry
	nil,                          // 17: com.bapis.bilibili.api.probe.v1.Embedded.MapErrorValEntry
}
var file_bilibili_api_probe_v1_messages_proto_depIdxs = []int32{
	14, // 0: com.bapis.bilibili.api.probe.v1.DynamicMessageUpdate.body:type_name -> com.bapis.bilibili.api.probe.v1.SimpleMessage
	16, // 1: com.bapis.bilibili.api.probe.v1.Embedded.mapStringVal:type_name -> com.bapis.bilibili.api.probe.v1.Embedded.MapStringValEntry
	17, // 2: com.bapis.bilibili.api.probe.v1.Embedded.mapErrorVal:type_name -> com.bapis.bilibili.api.probe.v1.Embedded.MapErrorValEntry
	0,  // 3: com.bapis.bilibili.api.probe.v1.SimpleMessage.cate:type_name -> com.bapis.bilibili.api.probe.v1.Category
	6,  // 4: com.bapis.bilibili.api.probe.v1.SimpleMessage.embedded:type_name -> com.bapis.bilibili.api.probe.v1.Embedded
	7,  // 5: com.bapis.bilibili.api.probe.v1.Embedded.MapErrorValEntry.value:type_name -> com.bapis.bilibili.api.probe.v1.ErrorMessage
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_bilibili_api_probe_v1_messages_proto_init() }
func file_bilibili_api_probe_v1_messages_proto_init() {
	if File_bilibili_api_probe_v1_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bilibili_api_probe_v1_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CodeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_api_probe_v1_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_api_probe_v1_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTopic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_api_probe_v1_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_api_probe_v1_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DynamicMessageUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_api_probe_v1_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Embedded); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_api_probe_v1_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_api_probe_v1_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProbeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_api_probe_v1_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProbeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_api_probe_v1_messages_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProbeStreamReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_api_probe_v1_messages_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProbeStreamReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_api_probe_v1_messages_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProbeSubReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_api_probe_v1_messages_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProbeSubReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_api_probe_v1_messages_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimpleMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_api_probe_v1_messages_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bilibili_api_probe_v1_messages_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bilibili_api_probe_v1_messages_proto_goTypes,
		DependencyIndexes: file_bilibili_api_probe_v1_messages_proto_depIdxs,
		EnumInfos:         file_bilibili_api_probe_v1_messages_proto_enumTypes,
		MessageInfos:      file_bilibili_api_probe_v1_messages_proto_msgTypes,
	}.Build()
	File_bilibili_api_probe_v1_messages_proto = out.File
	file_bilibili_api_probe_v1_messages_proto_rawDesc = nil
	file_bilibili_api_probe_v1_messages_proto_goTypes = nil
	file_bilibili_api_probe_v1_messages_proto_depIdxs = nil
}
