// Reconstructed from gRPC service descriptors.
syntax = "proto3";

package bilibili.api.probe.v1;

import "bilibili/api/probe/v1/messages.proto";

service Probe {
  rpc TestCode(.com.bapis.bilibili.api.probe.v1.CodeReq) returns (.com.bapis.bilibili.api.probe.v1.CodeReply);
  rpc TestReq(.com.bapis.bilibili.api.probe.v1.ProbeReq) returns (.com.bapis.bilibili.api.probe.v1.ProbeReply);
  rpc TestStream(stream .com.bapis.bilibili.api.probe.v1.ProbeStreamReq) returns (stream .com.bapis.bilibili.api.probe.v1.ProbeStreamReply);
  rpc TestSub(.com.bapis.bilibili.api.probe.v1.ProbeSubReq) returns (stream .com.bapis.bilibili.api.probe.v1.ProbeSubReply);
}

option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/api/probe/v1";
