// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.live.rtc.datachannel;

enum MuteReason {
  UserMute = 0;
  AdminMute = 1;
}

// Source: com/bapis/bilibili/live/rtc/datachannel/ClientStatsReq.java
message ClientStatsReq {
  string eventType = 1;
  string encoding = 2;
  string app = 3;
  int32 rawPayload = 6;
  int32 pbStatsPayload = 7;
  enum PayloadCase {
    PAYLOAD_NOT_SET = 0;
    RAW_PAYLOAD = 6;
    PB_STATS_PAYLOAD = 7;
  }

}

// Source: com/bapis/bilibili/live/rtc/datachannel/ClientStatsResp.java
message ClientStatsResp {
  uint32 reportInterval = 1;
  uint32 score = 2;
}

// Source: com/bapis/bilibili/live/rtc/datachannel/JoinNotify.java
message JoinNotify {
  BAPILiveRTCUserProto_User user = 1;
}

// Source: com/bapis/bilibili/live/rtc/datachannel/JoinReq.java
message JoinReq {
  BAPILiveRTCUserProto_User user = 1;
  bool autoSubscribe = 2;
  string token = 3;
}

// Source: com/bapis/bilibili/live/rtc/datachannel/JoinResp.java
message JoinResp {
  repeated BAPILiveRTCUserProto_User users = 1;
  uint32 callId = 2;
  BAPILiveRTCUserProto_CodecCapability encodeCapability = 3;
}

// Source: com/bapis/bilibili/live/rtc/datachannel/LeaveNotify.java
message LeaveNotify {
  uint64 uid = 1;
  BAPILiveRTCUserProto_UserLeaveReason reason = 2;
}

// Source: com/bapis/bilibili/live/rtc/datachannel/LeaveReq.java
message LeaveReq {
}

// Source: com/bapis/bilibili/live/rtc/datachannel/LeaveResp.java
message LeaveResp {
}

// Source: com/bapis/bilibili/live/rtc/datachannel/MembersReq.java
message MembersReq {
  uint64 channelId = 1;
  uint64 uid = 2;
  uint32 callId = 3;
}

// Source: com/bapis/bilibili/live/rtc/datachannel/MembersResp.java
message MembersResp {
  repeated BAPILiveRTCUserProto_User users = 1;
}

// Source: com/bapis/bilibili/live/rtc/datachannel/MessageNotify.java
message MessageNotify {
  uint64 uid = 1;
  uint32 bizId = 2;
  bytes payload = 3;
  bool last = 4;
}

// Source: com/bapis/bilibili/live/rtc/datachannel/MuteNotify.java
message MuteNotify {
  uint64 uid = 1;
  oneof oneof_0 {
    bool muteAudio = 2;
    bool muteVideo = 3;
  }
  MuteReason reason = 4;
  enum MuteStatusCase {
    MUTESTATUS_NOT_SET = 0;
    MUTE_AUDIO = 2;
    MUTE_VIDEO = 3;
  }

}

// Source: com/bapis/bilibili/live/rtc/datachannel/MuteReq.java
message MuteReq {
  oneof oneof_0 {
    bool muteAudio = 1;
    bool muteVideo = 2;
  }
  enum MuteReqCase {
    MUTEREQ_NOT_SET = 0;
    MUTE_AUDIO = 1;
    MUTE_VIDEO = 2;
  }

}

// Source: com/bapis/bilibili/live/rtc/datachannel/PubNotify.java
message PubNotify {
  uint64 uid = 1;
  BAPILiveRTCUserProto_Stream stream = 2;
}

// Source: com/bapis/bilibili/live/rtc/datachannel/PubReq.java
message PubReq {
  string sdp = 1;
  BAPILiveRTCUserProto_Stream stream = 2;
}

// Source: com/bapis/bilibili/live/rtc/datachannel/PubResp.java
message PubResp {
  string sdp = 1;
}

// Source: com/bapis/bilibili/live/rtc/datachannel/RequestMessage.java
message RequestMessage {
  int64 requestId = 1;
  uint64 channelId = 2;
  uint64 uid = 3;
  oneof oneof_0 {
    JoinReq join = 4;
    LeaveReq leave = 5;
    PubReq pub = 6;
    SubReq sub = 7;
    UnSubReq unSub = 8;
    MuteReq mute = 9;
    UserMsgReq message_ = 10;
    MembersReq members = 11;
    UnPubReq unPub = 12;
    UpdateSubReq updateSub = 13;
    ClientStatsReq clientStats = 14;
    UpdateCodecReq updateCodec = 15;
  }
  enum ReqCase {
    REQ_NOT_SET = 0;
    JOIN = 4;
    LEAVE = 5;
    PUB = 6;
    SUB = 7;
    UN_SUB = 8;
    MUTE = 9;
    MESSAGE = 10;
    MEMBERS = 11;
    UN_PUB = 12;
    UPDATE_SUB = 13;
    CLIENT_STATS = 14;
    UPDATE_CODEC = 15;
  }

}

// Source: com/bapis/bilibili/live/rtc/datachannel/ResponseMessage.java
message ResponseMessage {
  int64 requestId = 1;
  uint32 code = 2;
  string message_ = 3;
  oneof oneof_0 {
    JoinResp joinResp = 4;
    LeaveResp leaveResp = 5;
    PubResp pubResp = 6;
    SubResp subResp = 7;
    bytes unsubResp = 8;
    UserMuteResp muteResp = 9;
    UserMsgResp msgResp = 10;
    JoinNotify joinNotify = 11;
    LeaveNotify leaveNotify = 12;
    MuteNotify muteNotify = 13;
    PubNotify pubNotify = 14;
    MessageNotify msgNotify = 15;
    MembersResp membersResp = 16;
    TokenNotify tokenNotify = 17;
    UnPubResp unPubResp = 18;
    UnPubNotify unPubNotify = 19;
    UpdateSubResp updateSubResp = 20;
    ClientStatsResp clientStatsResp = 21;
    UpdateCodecResp updateCodecResp = 22;
    UpdateCodecNotify updateCodecNotify = 23;
  }
  enum DataCase {
    DATA_NOT_SET = 0;
    JOIN_RESP = 4;
    LEAVE_RESP = 5;
    PUB_RESP = 6;
    SUB_RESP = 7;
    UNSUB_RESP = 8;
    MUTE_RESP = 9;
    MSG_RESP = 10;
    JOIN_NOTIFY = 11;
    LEAVE_NOTIFY = 12;
    MUTE_NOTIFY = 13;
    PUB_NOTIFY = 14;
    MSG_NOTIFY = 15;
    MEMBERS_RESP = 16;
    TOKEN_NOTIFY = 17;
    UN_PUB_RESP = 18;
    UN_PUB_NOTIFY = 19;
    UPDATE_SUB_RESP = 20;
    CLIENT_STATS_RESP = 21;
    UPDATE_CODEC_RESP = 22;
    UPDATE_CODEC_NOTIFY = 23;
  }

}

// Source: com/bapis/bilibili/live/rtc/datachannel/SubReq.java
message SubReq {
  uint64 sdp = 1;
  repeated bool subUsers = 2;
  bool pauseSend = 3;
  enum SubOfferCase {
    SUBOFFER_NOT_SET = 0;
    SDP = 1;
  }

}

// Source: com/bapis/bilibili/live/rtc/datachannel/SubResp.java
message SubResp {
  uint64 uid = 1;
  string sdp = 2;
}

// Source: com/bapis/bilibili/live/rtc/datachannel/TokenNotify.java
message TokenNotify {
  string token = 1;
}

// Source: com/bapis/bilibili/live/rtc/datachannel/UnPubNotify.java
message UnPubNotify {
  uint64 uid = 1;
  BAPILiveRTCUserProto_Stream stream = 2;
}

// Source: com/bapis/bilibili/live/rtc/datachannel/UnPubReq.java
message UnPubReq {
}

// Source: com/bapis/bilibili/live/rtc/datachannel/UnPubResp.java
message UnPubResp {
}

// Source: com/bapis/bilibili/live/rtc/datachannel/UnSubReq.java
message UnSubReq {
  uint64 uid = 1;
}

// Source: com/bapis/bilibili/live/rtc/datachannel/UnSubResp.java
message UnSubResp {
}

// Source: com/bapis/bilibili/live/rtc/datachannel/UpdateCodecNotify.java
message UpdateCodecNotify {
  BAPILiveRTCUserProto_CodecCapability encodeCapability = 1;
}

// Source: com/bapis/bilibili/live/rtc/datachannel/UpdateCodecReq.java
message UpdateCodecReq {
  BAPILiveRTCUserProto_CodecCapability decodeCapability = 1;
}

// Source: com/bapis/bilibili/live/rtc/datachannel/UpdateCodecResp.java
message UpdateCodecResp {
}

// Source: com/bapis/bilibili/live/rtc/datachannel/UpdateSubReq.java
message UpdateSubReq {
  uint32 uid = 1;
  oneof oneof_0 {
    uint32 subAudio = 2;
  }
  int32 subVideo = 3;
  int32 layer = 4;
  enum AudioOptionCase {
    AUDIOOPTION_NOT_SET = 0;
    SUB_AUDIO = 2;
  }

  enum VideoLayerOptionCase {
    VIDEOLAYEROPTION_NOT_SET = 0;
    LAYER = 4;
  }

  enum VideoOptionCase {
    VIDEOOPTION_NOT_SET = 0;
    SUB_VIDEO = 3;
  }

  enum VideoTemporalLayerOptionCase {
    VIDEOTEMPORALLAYEROPTION_NOT_SET = 0;
    TEMPORAL_INDEX = 2;
  }

}

// Source: com/bapis/bilibili/live/rtc/datachannel/UpdateSubResp.java
message UpdateSubResp {
}

// Source: com/bapis/bilibili/live/rtc/datachannel/UserMsgReq.java
message UserMsgReq {
  uint32 bizId = 1;
  bytes payload = 2;
  bool last = 3;
  repeated uint64 receivers = 4;
}

// Source: com/bapis/bilibili/live/rtc/datachannel/UserMsgResp.java
message UserMsgResp {
  repeated uint64 sentUids = 1;
}

// Source: com/bapis/bilibili/live/rtc/datachannel/UserMuteResp.java
message UserMuteResp {
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/live/rtc/datachannel";
