// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bcg.sunspot.test.vo;

import "bcg/sunspot/test/dto/messages.proto";

// Source: com/bapis/bcg/sunspot/test/vo/MixResourceContentDto.java
message MixResourceContentDto {
  int32 resourceId = 1;
  map<int32, MixSourceContentDto> sourceContents = 2;
}

// Source: com/bapis/bcg/sunspot/test/vo/MixSourceContentDto.java
message MixSourceContentDto {
  com.bapis.bcg.sunspot.test.dto.SourceContentDto sourceContent = 1;
  int32 cardIndex = 2;
  int64 avId = 3;
  int32 cardType = 4;
  string jumpUrl = 5;
}

// Source: com/bapis/bcg/sunspot/test/vo/SunspotAdReplyForView.java
message SunspotAdReplyForView {
  com.bapis.bcg.sunspot.test.dto.AdsControlDto adsControl = 1;
  map<int32, MixResourceContentDto> resourceContents = 2;
}

// Source: com/bapis/bcg/sunspot/test/vo/SunspotAdRequestForView.java
message SunspotAdRequestForView {
  int64 mid = 1;
  string buvid = 2;
  repeated int32 resource = 3;
  string ip = 4;
  string country = 5;
  string province = 6;
  string city = 7;
  string network = 8;
  string mobiApp = 9;
  int64 aid = 10;
  int64 cid = 11;
  int64 avRid = 12;
  string avTid = 13;
  int64 avUpId = 14;
  string adExtra = 15;
  int32 build = 16;
  string openEvent = 17;
  int32 style = 18;
  int64 seasonId = 19;
  int64 epId = 20;
  string fromSpmid = 21;
  string spmid = 22;
  int32 topViewId = 23;
  string sid = 24;
  string dynamicfrom = 25;
  int32 index = 26;
  int32 mayResistGif = 27;
  string device = 28;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bcg/sunspot/test/vo";
