// Reconstructed from gRPC service descriptors.
syntax = "proto3";

package bilibili.app.show.rank.v1;

import "bilibili/app/show/rank/v1/messages.proto";

service Rank {
  rpc RankAll(.com.bapis.bilibili.app.show.rank.v1.RankAllResultReq) returns (.com.bapis.bilibili.app.show.rank.v1.RankListReply);
  rpc RankRegion(.com.bapis.bilibili.app.show.rank.v1.RankRegionResultReq) returns (.com.bapis.bilibili.app.show.rank.v1.RankListReply);
  rpc RankRegionList(.com.bapis.bilibili.app.show.rank.v1.RankRegionListReq) returns (.com.bapis.bilibili.app.show.rank.v1.RankRegionListReply);
}

option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/app/show/rank/v1";
