// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.im.gateway.interfaces.v1;

import "bilibili/app/dynamic/v2/messages.proto";
import "bilibili/im/type/messages.proto";

enum MsgFeedActionType {
  MSG_FEED_ACTION_TYPE_INVALID = 0;
  MSG_FEED_ACTION_TYPE_THANK = 1;
  UNRECOGNIZED = -1;
}

enum MsgFeedFilterType {
  MsgFeed_All = 0;
  MsgFeed_Following = 1;
  MsgFeed_AtMe = 2;
  UNRECOGNIZED = -1;
}

enum MsgFeedMsgType {
  LikeMsg = 0;
  ReplyMsg = 1;
  AtMsg = 2;
  DanmuMsg = 3;
  CoinMsg = 4;
  FavoriteMsg = 5;
  UNRECOGNIZED = -1;
}

enum MsgTabType {
  LikeMe = 0;
  ReplyMe = 1;
  AtMe = 2;
  SystemMsg = 3;
  HuaHuo = 4;
  NewFollow = 5;
  ReceiveReply = 100;
  ReceiveLike = 101;
  UNRECOGNIZED = -1;
}

enum SessionsFilterType {
  Sessions_All = 0;
  Sessions_Following = 1;
  UNRECOGNIZED = -1;
}

enum ToastType {
  ToastTypeDefault = 0;
  ToastTypeBanned = 1;
  ToastTypeReport = 2;
  UNRECOGNIZED = -1;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/AtBiz.java
message AtBiz {
  int64 subjectId = 1;
  int64 rootId = 2;
  int64 sourceId = 3;
  int64 targetId = 4;
  string sourceContent = 5;
  repeated User atDetails = 6;
  bool hideReplyButton = 7;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/AtCard.java
message AtCard {
  CommonMsgCard atMsg = 1;
  AtBiz atBiz = 2;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/BubbleMsg.java
message BubbleMsg {
  int64 mid = 1;
  string avatar = 2;
  string nickName = 3;
  string content = 4;
  MsgTabType tabType = 5;
  MsgFeedMsgType msgType = 6;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/CardItem.java
message CardItem {
  int64 id = 1;
  int64 itemId = 2;
  int64 originId = 3;
  int64 businessId = 4;
  string coverTitle = 7;
  string coverDesc = 8;
  string coverImage = 9;
  string coverText = 10;
  string nativeUri = 11;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/ClearBubbleMsgReq.java
message ClearBubbleMsgReq {
  MsgTabType tabType = 1;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/ClearBubbleMsgRsp.java
message ClearBubbleMsgRsp {
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/ClearMessageToastReq.java
message ClearMessageToastReq {
  ToastType toastType = 1;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/CoinCard.java
message CoinCard {
  CommonMsgCard coinMsg = 1;
  int32 noticeState = 2;
  ThankButton thankButton = 3;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/CommonMsgCard.java
message CommonMsgCard {
  int64 id = 1;
  repeated User users = 2;
  int64 itemId = 3;
  int64 msgTime = 4;
  int64 originId = 5;
  int64 businessId = 6;
  string coverImage = 7;
  string coverText = 8;
  string nativeUri = 9;
  int64 counts = 10;
  RichTextContent richTextContent = 11;
  string bizType = 12;
  bool isUnread = 13;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/Cursor.java
message Cursor {
  bool isEnd = 1;
  int64 id = 2;
  int64 time = 3;
  int64 replymsgid = 4;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/DanmuCard.java
message DanmuCard {
  CommonMsgCard danmuMsg = 1;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/DanmuInfo.java
message DanmuInfo {
  int64 aid = 1;
  int64 progress = 2;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/DelMsgCardReq.java
message DelMsgCardReq {
  int64 id = 1;
  MsgTabType tabType = 2;
  MsgFeedMsgType msgType = 3;
  MsgFeedFilterType filterType = 4;
  bool deleteTopMsg = 5;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/DelMsgItem.java
message DelMsgItem {
  uint64 talkerUid = 1;
  uint64 msgKey = 2;
  uint64 seqNo = 3;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/DelMsgReq.java
message DelMsgReq {
  repeated DelMsgItem msgs = 1;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/DelMsgRsp.java
message DelMsgRsp {
  repeated DelMsgItem fail = 1;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/DummyRsp.java
message DummyRsp {
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/FavoriteCard.java
message FavoriteCard {
  CommonMsgCard favMsg = 1;
  int32 noticeState = 2;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/GetBubbleMsgReq.java
message GetBubbleMsgReq {
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/GetBubbleMsgRsp.java
message GetBubbleMsgRsp {
  BubbleMsg bubbleMsg = 1;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/GetTotalUnreadReq.java
message GetTotalUnreadReq {
  int32 unreadType = 1;
  int32 showUnfollowList = 2;
  int32 showDustbin = 3;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/GetTotalUnreadRsp.java
message GetTotalUnreadRsp {
  SessionUnread sessionUnread = 1;
  MsgFeedUnread msgFeedUnread = 2;
  SysMsgInterfaceLastMsg sysMsgInterfaceLastMsg = 3;
  uint64 customUnread = 4;
  int32 totalUnread = 5;
  TotalUnreadNew totalUnreadNew = 6;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/HarmonyTotalUnreadRsp.java
message HarmonyTotalUnreadRsp {
  bytes totalunread = 1;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/LikeCard.java
message LikeCard {
  CommonMsgCard likeMsg = 1;
  int32 noticeState = 2;
  ThankButton thankButton = 3;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/MessageToastReq.java
message MessageToastReq {
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/MessageToastRsp.java
message MessageToastRsp {
  string content = 1;
  string title = 2;
  ToastType toastType = 3;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/MsgFansMedalInfo.java
message MsgFansMedalInfo {
  int64 uid = 1;
  int64 medalId = 2;
  string medalName = 3;
  int64 level = 4;
  int64 medalColor = 5;
  int64 medalColorEnd = 6;
  int64 medalColorBorder = 7;
  int64 medalColorName = 8;
  int64 medalColorLevel = 9;
  int64 guardLevel = 10;
  string firstIcon = 11;
  string secondIcon = 12;
  int64 medalLevelBgColor = 13;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/MsgFeedActionReq.java
message MsgFeedActionReq {
  int64 msgId = 1;
  MsgFeedActionType actionType = 2;
  MsgFeedActionThankParams thankParams = 3;
  MsgFeedMsgType msgType = 4;
  MsgFeedFilterType filterType = 5;
  bool isTopMsg = 6;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/MsgFeedActionRsp.java
message MsgFeedActionRsp {
  string toast = 1;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/MsgFeedActionThankParams.java
message MsgFeedActionThankParams {
  int64 receiverMid = 1;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/MsgFeedFilter.java
message MsgFeedFilter {
  MsgFeedFilterType type = 1;
  string name = 2;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/MsgFeedMsgCard.java
message MsgFeedMsgCard {
  MsgFeedMsgType msgType = 1;
  int64 msgId = 2;
  int64 msgTime = 3;
  MsgItem msgItem = 4;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/MsgFeedUnread.java
message MsgFeedUnread {
  map<string, int64> unread = 1;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/MsgItem.java
message MsgItem {
  oneof oneof_0 {
    ReplyCard replyCard = 1;
    AtCard atCard = 2;
    DanmuCard danmuCard = 3;
    LikeCard likeCard = 4;
    CoinCard coinCard = 5;
    FavoriteCard favoriteCard = 6;
  }
  enum MsgCardCase {
    MSGCARD_NOT_SET = 0;
    REPLY_CARD = 1;
    AT_CARD = 2;
    DANMU_CARD = 3;
    LIKE_CARD = 4;
    COIN_CARD = 5;
    FAVORITE_CARD = 6;
  }

}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/MsgListLimit.java
message MsgListLimit {
  bool limit = 1;
  string desc = 2;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/MsgListReq.java
message MsgListReq {
  Cursor cursor = 1;
  int64 pagesize = 2;
  MsgTabType tabType = 3;
  MsgFeedFilterType filterType = 4;
  int32 msgUiExpGroup = 5;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/MsgListRsp.java
message MsgListRsp {
  Cursor cursor = 1;
  repeated MsgFeedMsgCard msgCards = 2;
  int64 lastViewAt = 3;
  repeated MsgFeedFilter filters = 4;
  repeated MsgFeedMsgCard topCards = 5;
  MsgListLimit limit = 6;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/MsgRelationTag.java
message MsgRelationTag {
  string type = 1;
  oneof oneof_0 {
    MsgTextTag text = 2;
    MsgFansMedalInfo medal = 3;
    string imageUrl = 4;
  }
  enum ContentCase {
    CONTENT_NOT_SET = 0;
    TEXT = 2;
    MEDAL = 3;
    IMAGE_URL = 4;
  }

}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/MsgTextTag.java
message MsgTextTag {
  string text = 1;
  com.bapis.bilibili.app.dynamic.v2.Colors textColor = 2;
  com.bapis.bilibili.app.dynamic.v2.Colors backgroundColor = 3;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/Notice.java
message Notice {
  int32 noticeState = 1;
  int64 sourceId = 2;
  string noticeText = 3;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/Prompt.java
message Prompt {
  string msg = 1;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/PromptReq.java
message PromptReq {
  uint64 talkerAi = 1;
  uint64 key = 2;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/PromptRsp.java
message PromptRsp {
  repeated Prompt items = 1;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/QuickLinkItem.java
message QuickLinkItem {
  MsgTabType tabType = 1;
  string title = 2;
  string icon = 3;
  string iconDark = 4;
  string url = 5;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/QuickLinkReq.java
message QuickLinkReq {
  int32 teenagerMode = 1;
  int32 lessonsMode = 2;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/QuickLinkRsp.java
message QuickLinkRsp {
  repeated QuickLinkItem items = 1;
  bool isExperiment = 2;
  repeated SessionsFilter filters = 3;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/ReplyBiz.java
message ReplyBiz {
  int64 subjectId = 1;
  int64 rootId = 2;
  int64 sourceId = 3;
  int64 targetId = 4;
  string sourceContent = 5;
  string rootReplyContent = 6;
  string targetReplyContent = 7;
  repeated User atDetails = 8;
  repeated TopicInfo topicDetails = 9;
  bool hideReplyButton = 10;
  bool hideLikeButton = 11;
  int32 likeState = 12;
  string message_ = 13;
  int64 likeCount = 14;
  int64 childCount = 15;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/ReplyCard.java
message ReplyCard {
  CommonMsgCard replyMsg = 1;
  ReplyBiz replyBiz = 2;
  Notice replyNotice = 3;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/ReqGetAIInfo.java
message ReqGetAIInfo {
  int64 aiUid = 1;
  int64 uid = 2;
  int64 guestId = 3;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/ReqGetSessions.java
message ReqGetSessions {
  uint64 beginTs = 1;
  uint64 endTs = 2;
  uint32 size = 3;
  uint32 sessionType = 4;
  uint32 unfollowFold = 5;
  uint32 groupFold = 6;
  uint32 sortRule = 7;
  uint32 teenagerMode = 8;
  uint32 lessonsMode = 9;
  repeated IntList sids = 11;
  int64 aiUid = 12;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/ReqGetSystemNotice.java
message ReqGetSystemNotice {
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/ReqNewSessions.java
message ReqNewSessions {
  uint64 beginTs = 1;
  uint32 size = 2;
  uint32 teenagerMode = 3;
  uint32 lessonsMode = 4;
  repeated IntList sids = 6;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/ReqRemoveSession.java
message ReqRemoveSession {
  uint64 talkerId = 1;
  uint32 sessionType = 2;
  uint64 shopId = 3;
  uint64 shopFatherId = 4;
  uint32 systemMsgType = 5;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/ReqSetTop.java
message ReqSetTop {
  uint64 talkerId = 1;
  uint32 sessionType = 2;
  uint32 opType = 3;
  uint64 shopId = 4;
  uint64 shopFatherId = 5;
  uint32 systemMsgType = 6;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/ReqSingleInbox.java
message ReqSingleInbox {
  uint64 talkerUid = 1;
  uint64 beginSeqno = 2;
  uint64 endSeqno = 3;
  uint32 size = 4;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/RichTextContent.java
message RichTextContent {
  repeated com.bapis.bilibili.app.dynamic.v2.Paragraph paragraphs = 1;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/RspGetAIInfo.java
message RspGetAIInfo {
  com.bapis.bilibili.im.type.AiInfo aiInfo = 1;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/RspGetSystemNotice.java
message RspGetSystemNotice {
  string text = 1;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/RspSingleInbox.java
message RspSingleInbox {
  map<int64, int64> msgs = 1;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/SessionsFilter.java
message SessionsFilter {
  SessionsFilterType type = 1;
  string name = 2;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/SessionUnread.java
message SessionUnread {
  int32 unfollowUnread = 1;
  int32 followUnread = 2;
  int32 unfollowPushMsg = 3;
  int32 dustbinPushMsg = 4;
  int32 dustbinUnread = 5;
  int32 bizMsgUnfollowUnread = 6;
  int32 bizMsgFollowUnread = 7;
  int32 huahuoUnread = 8;
  int32 customUnread = 9;
  int32 systemUnread = 10;
  int32 strangerUnread = 11;
  bool strangerPushMsg = 12;
  int32 accountUnread = 13;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/SetMsgFeedNoticeReq.java
message SetMsgFeedNoticeReq {
  int64 id = 1;
  MsgFeedMsgType msgType = 2;
  int32 noticeState = 3;
  bool isTopMsg = 4;
  string bizType = 5;
  MsgFeedFilterType filterType = 6;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/SysMsgInterfaceLastMsg.java
message SysMsgInterfaceLastMsg {
  int32 unread = 1;
  string title = 2;
  string time = 3;
  uint64 id = 4;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/ThankButton.java
message ThankButton {
  bool hasSent = 1;
  string receiverName = 2;
  string senderAvatar = 3;
  string msgText = 4;
  int64 receiverMid = 5;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/TopicInfo.java
message TopicInfo {
  int64 topicId = 1;
  string topicName = 2;
  int64 isActivity = 3;
  string topicLink = 4;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/TotalUnreadNew.java
message TotalUnreadNew {
  int32 unreadCount = 1;
  int32 unreadType = 2;
}

// Source: com/bapis/bilibili/im/gateway/interfaces/v1/User.java
message User {
  int64 mid = 1;
  string nickname = 2;
  string avatar = 3;
  string link = 4;
  bool guest = 5;
  repeated MsgRelationTag relationTags = 6;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/im/gateway/interfaces/v1";
