// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.app.coldstart.v1;

// Source: com/bapis/bilibili/app/coldstart/v1/ColdStartBizReq.java
message ColdStartBizReq {
  string bizKey = 1;
  Any bizParam = 2;
}

// Source: com/bapis/bilibili/app/coldstart/v1/ColdStartBizResp.java
message ColdStartBizResp {
  string bizKey = 1;
  Any bizResp = 2;
  oneof oneof_0 {
    GrpcStatus grpcStatus = 3;
    HttpStatus httpStatus = 4;
  }
  enum StatusCase {
    STATUS_NOT_SET = 0;
    GRPC_STATUS = 3;
    HTTP_STATUS = 4;
  }

}

// Source: com/bapis/bilibili/app/coldstart/v1/GetColdStartDataReq.java
message GetColdStartDataReq {
  repeated bytes reqlist = 1;
  HttpCommon httpCommon = 2;
}

// Source: com/bapis/bilibili/app/coldstart/v1/GetColdStartDataResp.java
message GetColdStartDataResp {
  repeated bytes resplist = 1;
}

// Source: com/bapis/bilibili/app/coldstart/v1/GrpcStatus.java
message GrpcStatus {
  int32 code = 1;
  string message_ = 2;
}

// Source: com/bapis/bilibili/app/coldstart/v1/HttpCommon.java
message HttpCommon {
  map<string, string> headers = 1;
  map<string, string> params = 2;
}

// Source: com/bapis/bilibili/app/coldstart/v1/HttpGetBizReq.java
message HttpGetBizReq {
  map<string, string> headers = 1;
  map<string, string> params = 2;
}

// Source: com/bapis/bilibili/app/coldstart/v1/HttpJsonBizResp.java
message HttpJsonBizResp {
  string data = 1;
}

// Source: com/bapis/bilibili/app/coldstart/v1/HttpStatus.java
message HttpStatus {
  int32 code = 1;
  string message_ = 2;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/app/coldstart/v1";
