// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.mall.tab3.viewunite.ugcanymodel;

import "bilibili/mall/tab3/viewunite/common/messages.proto";

enum PremiereState {
  premiere_none = 0;
  premiere_before = 1;
  premiere_in = 2;
  premiere_after = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/ugcanymodel/Dislike.java
message Dislike {
  string title = 1;
  string subtitle = 2;
  repeated DislikeReason reasons = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/ugcanymodel/DislikeReason.java
message DislikeReason {
  int64 id = 1;
  int64 mid = 2;
  int32 rid = 3;
  int64 tagId = 4;
  string name = 5;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/ugcanymodel/ElecRank.java
message ElecRank {
  repeated ElecRankItem list = 1;
  int64 count = 2;
  string text = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/ugcanymodel/ElecRankItem.java
message ElecRankItem {
  string avatar = 1;
  string nickname = 2;
  string message_ = 3;
  int64 mid = 4;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/ugcanymodel/Premiere.java
message Premiere {
  PremiereState premiereState = 1;
  int64 startTime = 2;
  int64 serviceTime = 3;
  int64 roomId = 4;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/ugcanymodel/PremiereReserve.java
message PremiereReserve {
  int64 reserveId = 1;
  int64 count = 2;
  bool isFollow = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/ugcanymodel/PremiereResource.java
message PremiereResource {
  Premiere premiere = 1;
  PremiereReserve reserve = 2;
  PremiereText text = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/ugcanymodel/PremiereText.java
message PremiereText {
  string title = 1;
  string subtitle = 2;
  string onlineText = 3;
  string onlineIcon = 4;
  string onlineIconDark = 5;
  string introTitle = 6;
  string introIcon = 7;
  string guidancePulldown = 8;
  string guidanceEntry = 9;
  string introIconNight = 10;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/ugcanymodel/ViewUgcAny.java
message ViewUgcAny {
  PremiereResource premiere = 1;
  Dislike dislike = 2;
  string shortLink = 3;
  string shareSubtitle = 4;
  repeated com.bapis.bilibili.mall.tab3.viewunite.common.Page pages = 5;
  ElecRank elecRank = 6;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/mall/tab3/viewunite/ugcanymodel";
