// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.live.xgift.v1;

import "bilibili/live/component/common_model/effect/messages.proto";
import "bilibili/live/component/common_model/user_dagw/messages.proto";

// Source: com/bapis/bilibili/live/xgift/v1/EasterEggBenefit.java
message EasterEggBenefit {
  string materialUrl = 1;
  string materialMd5 = 2;
  int64 effectNum = 3;
  int64 effectNumAudience = 4;
  string unlockText = 5;
  string webMaterialUrl = 6;
  string webMaterialMd5 = 7;
}

// Source: com/bapis/bilibili/live/xgift/v1/FansLightAnimation.java
message FansLightAnimation {
  string medalName = 1;
}

// Source: com/bapis/bilibili/live/xgift/v1/GiftBenefits.java
message GiftBenefits {
  EasterEggBenefit easterEgg = 1;
  FansLightAnimation fansLightAnimation = 2;
}

// Source: com/bapis/bilibili/live/xgift/v1/GiftMaterialSnapShot.java
message GiftMaterialSnapShot {
  string imgBasic = 1;
  string webp = 2;
  int64 effectId = 3;
  int64 hasImagedGift = 4;
}

// Source: com/bapis/bilibili/live/xgift/v1/GroupMedalBrief.java
message GroupMedalBrief {
  int64 medalId = 1;
  string name = 2;
  int64 isLighted = 3;
}

// Source: com/bapis/bilibili/live/xgift/v1/SendGiftBroadcast.java
message SendGiftBroadcast {
  int64 uid = 1;
  string uname = 2;
  string face = 3;
  string nameColor = 4;
  int64 guardLevel = 5;
  int64 svgaBlock = 6;
  SendGiftBroadcast_SendMaster sendMaster = 7;
  SendGiftBroadcast_MedalInfo medalInfo = 8;
  SendGiftBroadcast_BlindGift blindGift = 9;
  repeated SendGiftBroadcast_GiftItem giftList = 10;
  bool switch = 11;
  int64 test = 12;
  SendGiftBroadcast_WealthInfo wealthInfo = 13;
  GroupMedalBrief groupMedal = 14;
  com.bapis.bilibili.live.component.common_model.user_dagw.UserInfo senderUinfo = 15;
}

// Source: com/bapis/bilibili/live/xgift/v1/SendGiftBroadcast.java
message SendGiftBroadcast_BagGiftInfo {
  int32 showPrice = 1;
  int64 priceForShow = 2;
}

// Source: com/bapis/bilibili/live/xgift/v1/SendGiftBroadcast.java
message SendGiftBroadcast_BlindGift {
  int64 blindGiftConfigId = 1;
  int64 originalGiftId = 2;
  string originalGiftName = 3;
  int64 from = 4;
  string giftAction = 5;
  int64 originalGiftPrice = 6;
  int64 giftTipPrice = 7;
}

// Source: com/bapis/bilibili/live/xgift/v1/SendGiftBroadcast.java
message SendGiftBroadcast_FaceEffect {
  int64 faceEffectType = 1;
  repeated SendGiftBroadcast_FaceEffectItem candidateFaceEffects = 2;
}

// Source: com/bapis/bilibili/live/xgift/v1/SendGiftBroadcast.java
message SendGiftBroadcast_FaceEffectItem {
  int64 effectId = 1;
  int64 source = 2;
}

// Source: com/bapis/bilibili/live/xgift/v1/SendGiftBroadcast.java
message SendGiftBroadcast_FaceEffectV2 {
  int64 id = 1;
  int64 type = 2;
}

// Source: com/bapis/bilibili/live/xgift/v1/SendGiftBroadcast.java
message SendGiftBroadcast_GiftItem {
  int64 giftId = 1;
  string giftName = 2;
  int64 num = 3;
  int64 demarcation = 4;
  int64 price = 5;
  int64 discountPrice = 6;
  int64 totalCoin = 7;
  string coinType = 8;
  string tid = 9;
  int64 timestamp = 10;
  int64 superBatchGiftNum = 11;
  string batchComboId = 12;
  int64 comboResourcesId = 13;
  int64 comboTotalCoin = 14;
  int64 comboStayTime = 15;
  float magnification = 16;
  bool showBatchComboSend = 17;
  string action = 18;
  int64 effectBlock = 19;
  int64 isSpecialBatch = 20;
  int64 floatScResourceId = 21;
  string tagImage = 22;
  int64 critProb = 23;
  int64 rcost = 24;
  int64 test = 25;
  int64 faceEffectType = 26;
  int64 faceEffectId = 27;
  bool isNaming = 28;
  SendGiftBroadcast_ReceiveUserInfo receiveUserInfo = 29;
  bool isJoinReceiver = 30;
  SendGiftBroadcast_BagGiftInfo bagGift = 31;
  repeated int64 giftTag = 32;
  com.bapis.bilibili.live.component.common_model.user_dagw.UserInfo receiverUinfo = 33;
  SendGiftBroadcast_FaceEffectV2 faceEffectV2 = 34;
  GiftMaterialSnapShot giftInfo = 35;
  int64 giftTipPrice = 36;
  SendGiftBroadcast_FaceEffect faceEffect = 37;
  GiftBenefits benefits = 38;
  com.bapis.bilibili.live.component.common_model.effect.EffectConfigItem effectConfig = 39;
}

// Source: com/bapis/bilibili/live/xgift/v1/SendGiftBroadcast.java
message SendGiftBroadcast_MedalInfo {
  int64 targetId = 1;
  string special = 2;
  string anchorUname = 3;
  int64 anchorRoomid = 4;
  int64 medalLevel = 5;
  string medalName = 6;
  int64 medalColor = 7;
  int64 medalColorStart = 8;
  int64 medalColorEnd = 9;
  int64 medalColorBorder = 10;
  int64 isLighted = 11;
  int64 guardLevel = 12;
}

// Source: com/bapis/bilibili/live/xgift/v1/SendGiftBroadcast.java
message SendGiftBroadcast_ReceiveUserInfo {
  string uname = 1;
  int64 uid = 2;
}

// Source: com/bapis/bilibili/live/xgift/v1/SendGiftBroadcast.java
message SendGiftBroadcast_SendMaster {
  int64 uid = 1;
  string uname = 2;
}

// Source: com/bapis/bilibili/live/xgift/v1/SendGiftBroadcast.java
message SendGiftBroadcast_WealthInfo {
  int64 level = 1;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/live/xgift/v1";
