// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.broadcast.live.multi_conn;

// Source: com/bapis/bilibili/broadcast/live/multi_conn/ScoreEvent.java
message ScoreEvent {
  repeated ScoreEvent_info data = 1;
  int64 invokingTime = 2;
  int64 version = 3;
  string layout = 4;
  int64 roomStatus = 5;
  string bizSessionId = 6;
}

// Source: com/bapis/bilibili/broadcast/live/multi_conn/ScoreEvent.java
message ScoreEvent_info {
  int64 uid = 1;
  int64 roomId = 2;
  string avatar = 3;
  string nickname = 4;
  int64 price = 5;
  string priceText = 6;
  int64 gender = 7;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/broadcast/live/multi_conn";
