// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.polymer.app.search.v1;

import "bilibili/app/archive/middleware/v1/messages.proto";
import "bilibili/broadcast/message/main/messages.proto";
import "bilibili/dagw/component/avatar/v1/messages.proto";
import "bilibili/pagination/messages.proto";

enum CategorySort {
  CATEGORY_SORT_DEFAULT = 0;
  CATEGORY_SORT_PUBLISH_TIME = 1;
  CATEGORY_SORT_CLICK_COUNT = 2;
  CATEGORY_SORT_COMMENT_COUNT = 3;
  CATEGORY_SORT_LIKE_COUNT = 4;
}

enum GroupStyle {
  GROUP_STYLE_NONE = 0;
  GROUP_STYLE_ROUNDED = 1;
  GROUP_STYLE_ALIENATION = 2;
}

enum OpusType {
  OPUS_TYPE_UNKNOWN = 0;
  OPUS_TYPE_ARTICLE = 1;
  OPUS_TYPE_TWITTER = 2;
}

enum ReserveType {
  RESERVE_TYPE_UNKNOWN = 0;
  RESERVE_TYPE_OGV = 1;
  RESERVE_TYPE_LIVE = 2;
  RESERVE_TYPE_SPORTS = 3;
}

enum Sort {
  SORT_DEFAULT = 0;
  SORT_VIEW_COUNT = 1;
  SORT_PUBLISH_TIME = 2;
  SORT_DANMAKU_COUNT = 3;
}

enum Style {
  score = 0;
  bikan = 1;
}

enum TribeeCoverStyle {
  TRIBEE_COVER_STYLE_BLUR_SQUARE = 0;
  TRIBEE_COVER_STYLE_CROP_16_9 = 1;
}

enum UserSort {
  USER_SORT_DEFAULT = 0;
  USER_SORT_FANS_DESCEND = 1;
  USER_SORT_FANS_ASCEND = 2;
  USER_SORT_LEVEL_DESCEND = 3;
  USER_SORT_LEVEL_ASCEND = 4;
}

enum UserType {
  ALL = 0;
  UP = 1;
  NORMAL_USER = 2;
  AUTHENTICATED_USER = 3;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/Args.java
message Args {
  int32 online = 1;
  string rname = 2;
  int64 roomId = 3;
  string tname = 4;
  int64 upId = 5;
  string upName = 6;
  int64 rid = 7;
  int64 tid = 8;
  int64 aid = 9;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/Avatar.java
message Avatar {
  string cover = 1;
  string event = 2;
  string eventV2 = 3;
  string text = 4;
  int64 upId = 5;
  string uri = 6;
  int32 faceNftNew = 7;
  NftFaceIcon nftFaceIcon = 8;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/AvItem.java
message AvItem {
  string title = 1;
  string cover = 2;
  string uri = 3;
  string ctimeLabel = 4;
  string duration = 5;
  int32 play = 6;
  int64 danmaku = 7;
  int32 ctime = 8;
  string goto = 9;
  string param = 10;
  int32 position = 11;
  string ctimeLabelV2 = 12;
  string viewContent = 13;
  int32 iconType = 14;
  LabelStyle chargingLabel = 15;
  bool isInline = 16;
  ReasonStyle coverBadge = 17;
  int32 isIaaVideo = 18;
  string translatedTitle = 19;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/Background.java
message Background {
  int32 show = 1;
  string bgPicUrl = 2;
  string fgPicUrl = 3;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/Badge.java
message Badge {
  string text = 1;
  string bgCover = 2;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/Badge2.java
message Badge2 {
  string bgCover = 1;
  string text = 2;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/BottomButton.java
message BottomButton {
  string desc = 1;
  string link = 2;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/BrandADAccount.java
message BrandADAccount {
  string param = 1;
  string goto = 2;
  int64 mid = 3;
  string name = 4;
  string face = 5;
  string sign = 6;
  Relation relation = 7;
  int64 roomid = 8;
  int64 liveStatus = 9;
  string liveLink = 10;
  OfficialVerify officialVerify = 11;
  VipInfo vip = 12;
  string uri = 13;
  int32 faceNftNew = 14;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/BrandADArc.java
message BrandADArc {
  string param = 1;
  string goto = 2;
  int64 aid = 3;
  int64 play = 4;
  int64 reply = 5;
  string duration = 6;
  string author = 7;
  string title = 8;
  string uri = 9;
  string cover = 10;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/Button.java
message Button {
  string text = 1;
  string param = 2;
  string uri = 3;
  string event = 4;
  int32 selected = 5;
  int32 type = 6;
  string eventV2 = 7;
  Relation relation = 8;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/ButtonMeta.java
message ButtonMeta {
  string icon = 1;
  string text = 2;
  string buttonStatus = 3;
  string toast = 4;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/CardBusinessBadge.java
message CardBusinessBadge {
  GotoIcon gotoIcon = 1;
  ReasonStyle badgeStyle = 2;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/CardGroupRule.java
message CardGroupRule {
  GroupStyle style = 1;
  bool merge = 2;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/CardLayout.java
message CardLayout {
  float compactCoverWidth = 1;
  float compactCoverHeight = 2;
  float verticalPadding = 3;
  float moduleSpacing = 4;
  bool isLargeAvatar = 5;
  float backgroundCoverHeight = 6;
  bool buttonTopEqualCover = 7;
  int32 column = 8;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/CardUI.java
message CardUI {
  string maskColorValue = 1;
  string maskOpacity = 2;
  string moduleColor = 3;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/ChannelLabel.java
message ChannelLabel {
  string text = 1;
  string uri = 2;
  int32 iconType = 3;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/ChannelMixedItem.java
message ChannelMixedItem {
  int64 id = 1;
  int32 coverLeftIcon1 = 2;
  string coverLeftText1 = 3;
  string cover = 4;
  string goto = 5;
  string param = 6;
  string uri = 7;
  string title = 8;
  Badge2 badge = 9;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/CheckMore.java
message CheckMore {
  string content = 1;
  string uri = 2;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/CloudGameParams.java
message CloudGameParams {
  int64 sourceFrom = 1;
  string scene = 2;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/Colors.java
message Colors {
  string day = 1;
  string night = 2;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/Comment.java
message Comment {
  string face = 1;
  int64 mid = 2;
  string name = 3;
  string content = 4;
  int64 like = 5;
  int64 row = 6;
  string upUri = 7;
  string uri = 8;
  int64 id = 9;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/CountdownInfo.java
message CountdownInfo {
  int64 countdownTime = 1;
  string countdownPicUrl = 2;
  string countdownNumPicUrl = 3;
  string countdownNumColor = 4;
  string countdownTimeColor = 5;
  int32 buttonType = 6;
  string buttonPicUrl = 7;
  string reserveButtonPicUrl = 8;
  string countdownJumpUrl = 9;
  SearchReserveInfo reserveInfo = 10;
  int64 isFollow = 11;
  int64 state = 12;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/DetailsRelationItem.java
message DetailsRelationItem {
  string title = 1;
  string cover = 2;
  string coverLeftText = 3;
  ReasonStyle coverBadgeStyle = 4;
  string modulePos = 5;
  string goto = 6;
  string param = 7;
  string uri = 8;
  int32 position = 9;
  string coverLeftTextV2 = 10;
  ReasonStyle coverBadgeStyleV2 = 11;
  string viewContent = 12;
  int32 iconType = 13;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/Disclaimer.java
message Disclaimer {
  string title = 1;
  repeated Disclaimer_Item list = 2;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/Disclaimer.java
message Disclaimer_Item {
  string icon = 1;
  string text = 2;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/DislikeReason.java
message DislikeReason {
  int32 id = 1;
  string name = 2;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/DisplayOption.java
message DisplayOption {
  int32 videoTitleRow = 1;
  int32 searchPageVisualOpti = 2;
  int32 refreshOpti = 3;
  int32 refreshExp = 4;
  int32 filterExp = 5;
  int32 tagHighlightOpti = 6;
  int32 coverExp = 7;
  double coverExpSmall = 8;
  double coverExpNormal = 9;
  double coverExpLarge = 10;
  int32 alienationCardCount = 11;
  int32 comment43exp = 12;
  int32 alienationFoldCount = 13;
  int32 pureBackgroundExp = 14;
  int32 pureCommenterExp = 15;
  int32 pureLineExp = 16;
  int32 pureLikeExp = 17;
  int32 feedbackExp = 18;
  int32 cardStyleExp = 19;
  int32 ugcPicRevampExpGroup = 20;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/DoubleOpusItem.java
message DoubleOpusItem {
  OpusType type = 1;
  int64 id = 2;
  int64 coverCount = 3;
  string cover = 4;
  int64 mid = 5;
  string uname = 6;
  string jumpUrl = 7;
  int64 imgW = 8;
  int64 imgH = 9;
  string title = 10;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/DyTopic.java
message DyTopic {
  string title = 1;
  string uri = 2;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/EasterEgg.java
message EasterEgg {
  int32 id = 1;
  int32 showCount = 2;
  int32 type = 3;
  string url = 4;
  int32 closeCount = 5;
  int32 maskTransparency = 6;
  string maskColor = 7;
  int32 picType = 8;
  int32 showTime = 9;
  string sourceUrl = 10;
  string sourceMd5 = 11;
  int32 sourceSize = 12;
  int32 eggType = 13;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/Episode.java
message Episode {
  string uri = 1;
  string param = 2;
  string index = 3;
  repeated ReasonStyle badges = 4;
  int32 position = 5;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/EpisodeNew.java
message EpisodeNew {
  string title = 1;
  string uri = 2;
  string param = 3;
  int32 isNew = 4;
  repeated ReasonStyle badges = 5;
  int32 type = 6;
  int32 position = 7;
  string cover = 8;
  string label = 9;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/ExtraLink.java
message ExtraLink {
  string text = 1;
  string uri = 2;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/ExtraWord.java
message ExtraWord {
  string firstWord = 1;
  repeated string secondWord = 2;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/Feedback.java
message Feedback {
  repeated FeedbackSection sections = 1;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/FeedbackItem.java
message FeedbackItem {
  string text = 1;
  int32 id = 2;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/FeedbackSection.java
message FeedbackSection {
  string title = 1;
  string type = 2;
  repeated FeedbackItem items = 3;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/FilterEntries.java
message FilterEntries {
  string title = 1;
  repeated FilterValue values = 2;
  string subtitle = 3;
  string filterType = 4;
  string areaForNeuron = 5;
  bool singleSelect = 6;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/FilterValue.java
message FilterValue {
  string value = 1;
  string subModuleForNeuron = 2;
  oneof oneof_0 {
    string param = 3;
    Sort sort = 4;
    UserSort userSort = 5;
    CategorySort categorySort = 6;
    UserType userType = 7;
  }
  enum FilterParamCase {
    FILTERPARAM_NOT_SET = 0;
    PARAM = 3;
    SORT = 4;
    USER_SORT = 5;
    CATEGORY_SORT = 6;
    USER_TYPE = 7;
  }

}

// Source: com/bapis/bilibili/polymer/app/search/v1/FoldingTimeLine.java
message FoldingTimeLine {
  string icon = 1;
  string leftTitle = 2;
  string rightTitle = 3;
  int32 color = 4;
  int32 segment = 5;
  int64 startSecond = 6;
  int64 endSecond = 7;
  int32 initPosition = 8;
  int32 type = 9;
  int32 hangStyleSinal = 10;
  int32 hasImgUrl = 11;
  repeated VideoTextItem items = 12;
  string iconNight = 13;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/FollowButton.java
message FollowButton {
  string icon = 1;
  map<string, string> texts = 2;
  string statusReport = 3;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/FollowButtonV2.java
message FollowButtonV2 {
  string icon = 1;
  map<int32, string> texts = 2;
  string statusReport = 3;
  string textColor = 4;
  string textColorNight = 5;
  string bgColor = 6;
  string bgColorNight = 7;
  string borderColor = 8;
  string borderColorNight = 9;
  int32 styleType = 10;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/FullTextResult.java
message FullTextResult {
  int32 type = 1;
  string showText = 2;
  int64 jumpStartProgress = 3;
  string jumpUri = 4;
  string icon = 5;
  string iconForNight = 6;
  int64 id = 7;
  string prefix = 8;
  string text = 9;
  string aheadPrefixText = 10;
  string likeCount = 11;
  string avatarCover = 12;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/GloryInfo.java
message GloryInfo {
  string title = 1;
  int32 total = 2;
  repeated GloryItem items = 3;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/GloryItem.java
message GloryItem {
  string title = 1;
  string cover = 2;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/GotoIcon.java
message GotoIcon {
  string iconUrl = 1;
  string iconNightUrl = 2;
  int32 iconWidth = 3;
  int32 iconHeight = 4;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/H5Share.java
message H5Share {
  string oid = 1;
  string shareId = 2;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/InlineProgressBar.java
message InlineProgressBar {
  string iconDrag = 1;
  string iconDragHash = 2;
  string iconStop = 3;
  string iconStopHash = 4;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/InlineThreePointPanel.java
message InlineThreePointPanel {
  int32 panelType = 1;
  string shareId = 2;
  string shareOrigin = 3;
  repeated ShareButtonItem functionalButtons = 4;
  Feedback searchFeedback = 5;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/Item.java
message Item {
  string uri = 1;
  string param = 2;
  string goto = 3;
  string linktype = 4;
  int32 position = 5;
  string trackid = 6;
  oneof oneof_0 {
    SearchSpecialCard special = 7;
    SearchArticleCard article = 8;
    SearchBannerCard banner = 9;
    SearchLiveCard live = 10;
    SearchGameCard game = 11;
    SearchPurchaseCard purchase = 12;
    SearchRecommendWordCard recommendWord = 13;
    SearchDynamicCard dynamic = 14;
    SearchNoResultSuggestWordCard suggestKeyword = 15;
    SearchSpecialGuideCard specialGuide = 16;
    SearchComicCard comic = 17;
    SearchNewChannelCard channelNew = 18;
    SearchOgvCard ogvCard = 19;
    SearchOgvRelationCard bangumiRelates = 20;
    SearchOgvRecommendCard findMore = 21;
    SearchSportCard esport = 22;
    SearchAuthorNewCard authorNew = 23;
    SearchTipsCard tips = 24;
    SearchAdCard cm = 25;
    SearchPediaCard pediaCard = 26;
    SearchUgcInlineCard ugcInline = 27;
    SearchLiveInlineCard liveInline = 28;
    SearchTopGameCard topGame = 29;
    SearchOlympicGameCard sports = 30;
    SearchOlympicWikiCard pediaCardInline = 31;
    SearchRecommendTipCard recommendTips = 32;
    SearchCollectionCard collectionCard = 33;
    SearchOgvChannelCard ogvChannel = 34;
    SearchOgvInlineCard ogvInline = 35;
    SearchUpperCard author = 36;
    SearchVideoCard av = 37;
    SearchBangumiCard bangumi = 38;
    SearchSportInlineCard esportsInline = 39;
    SearchHotBannerCard hotBanner = 40;
    SearchSubjectCard subject = 41;
    SearchDynamicCard dynamicNew = 42;
    SearchArticleCard articleNew = 43;
    SearchPediaPicCard pediaCardPic = 44;
    SearchNPSCard npsCard = 45;
    SearchChatGPTCard chatGpt = 46;
    SearchHotRecommend hotRecommend = 47;
    SearchLiveMaster liveMaster = 48;
    SearchLiveRoomTitle liveRoomTitle = 49;
    SearchLiveRoom liveRoom = 50;
    SearchCheese cheese = 51;
    SearchRelatedSearch relatedSearch = 52;
    SearchQACard qaCard = 53;
    SearchDoubleColumnCard doubleColumn = 54;
    SearchUPRecommend upRecommend = 55;
    SearchCommentCard commentCard = 57;
    SearchPlayListCard playlistCard = 58;
    SearchSeriesCard seriesCard = 59;
    SearchMusicCard musicCard = 60;
    SearchCommentClusterCard commentCluster = 61;
    SearchTimeLineCard timeLine = 62;
    SearchDoubleOpusCard doubleOpus = 64;
    SearchOgvClusterCard ogvClusterCard = 65;
    SearchDigitalChatCard digitalChat = 66;
    SearchAlienationCard alienationCard = 67;
    SearchStarBannerCard starBanner = 68;
    SearchActivityCard activityCard = 69;
    SearchGiantCard articleGiantCard = 70;
    SearchGiantCard twitterGiantCard = 71;
    SearchAIChatCard aiChat = 73;
    SearchTribeeCard tribeeCard = 74;
  }
  int64 spreadId = 56;
  string userAct = 63;
  bool isHorizontalCover = 72;
  int32 cardGroupId = 75;
  string originGoto = 76;
  map<string, string> reportExtra = 77;
  enum CardItemCase {
    CARDITEM_NOT_SET = 0;
    SPECIAL = 7;
    ARTICLE = 8;
    BANNER = 9;
    LIVE = 10;
    GAME = 11;
    PURCHASE = 12;
    RECOMMEND_WORD = 13;
    DYNAMIC = 14;
    SUGGEST_KEYWORD = 15;
    SPECIAL_GUIDE = 16;
    COMIC = 17;
    CHANNEL_NEW = 18;
    OGV_CARD = 19;
    BANGUMI_RELATES = 20;
    FIND_MORE = 21;
    ESPORT = 22;
    AUTHOR_NEW = 23;
    TIPS = 24;
    CM = 25;
    PEDIA_CARD = 26;
    UGC_INLINE = 27;
    LIVE_INLINE = 28;
    TOP_GAME = 29;
    SPORTS = 30;
    PEDIA_CARD_INLINE = 31;
    RECOMMEND_TIPS = 32;
    COLLECTION_CARD = 33;
    OGV_CHANNEL = 34;
    OGV_INLINE = 35;
    AUTHOR = 36;
    AV = 37;
    BANGUMI = 38;
    ESPORTS_INLINE = 39;
    HOT_BANNER = 40;
    SUBJECT = 41;
    DYNAMIC_NEW = 42;
    ARTICLE_NEW = 43;
    PEDIA_CARD_PIC = 44;
    NPS_CARD = 45;
    CHAT_GPT = 46;
    HOT_RECOMMEND = 47;
    LIVE_MASTER = 48;
    LIVE_ROOM_TITLE = 49;
    LIVE_ROOM = 50;
    CHEESE = 51;
    RELATED_SEARCH = 52;
    QA_CARD = 53;
    DOUBLE_COLUMN = 54;
    UP_RECOMMEND = 55;
    COMMENT_CARD = 57;
    PLAYLIST_CARD = 58;
    SERIES_CARD = 59;
    MUSIC_CARD = 60;
    COMMENT_CLUSTER = 61;
    TIME_LINE = 62;
    DOUBLE_OPUS = 64;
    OGV_CLUSTER_CARD = 65;
    DIGITAL_CHAT = 66;
    ALIENATION_CARD = 67;
    STAR_BANNER = 68;
    ACTIVITY_CARD = 69;
    ARTICLE_GIANT_CARD = 70;
    TWITTER_GIANT_CARD = 71;
    AI_CHAT = 73;
    TRIBEE_CARD = 74;
  }

}

// Source: com/bapis/bilibili/polymer/app/search/v1/LabelStyle.java
message LabelStyle {
  string text = 1;
  string textColor = 2;
  string textColorNight = 3;
  string bgColor = 4;
  string bgColorNight = 5;
  string borderColor = 6;
  string borderColorNight = 7;
  string icon = 8;
  string iconNight = 9;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/LikeResource.java
message LikeResource {
  string url = 1;
  string contentHash = 2;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/LiveBadgeResource.java
message LiveBadgeResource {
  string text = 1;
  string animationUrl = 2;
  string animationUrlHash = 3;
  string backgroundColorLight = 4;
  string backgroundColorNight = 5;
  int64 alphaLight = 6;
  int64 alphaNight = 7;
  string fontColor = 8;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/Mask.java
message Mask {
  Avatar avatar = 1;
  Button button = 2;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/MatchGuess.java
message MatchGuess {
  string cover = 1;
  string title = 2;
  string desc = 3;
  WatchButton button = 4;
  string uri = 5;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/MatchInfoObj.java
message MatchInfoObj {
  int64 id = 1;
  int32 status = 2;
  string matchStage = 3;
  MatchTeam team1 = 4;
  MatchTeam team2 = 5;
  MatchItem matchLabel = 6;
  MatchItem matchTime = 7;
  MatchItem matchButton = 8;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/MatchItem.java
message MatchItem {
  int32 state = 1;
  string text = 2;
  string textColor = 3;
  string textColorNight = 4;
  string uri = 5;
  string liveLink = 6;
  Texts texts = 7;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/MatchTeam.java
message MatchTeam {
  int64 id = 1;
  string title = 2;
  string cover = 3;
  int32 score = 4;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/Nav.java
message Nav {
  string name = 1;
  int32 total = 2;
  int32 pages = 3;
  int32 type = 4;
  int32 showMore = 5;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/Navigation.java
message Navigation {
  int64 id = 1;
  repeated Navigation children = 2;
  repeated Navigation inlineChildren = 3;
  string title = 4;
  string uri = 5;
  NavigationButton button = 6;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/NavigationButton.java
message NavigationButton {
  int64 type = 1;
  string text = 2;
  string uri = 3;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/NegativeFeedback.java
message NegativeFeedback {
  string defaultWordsFeedbackTitle = 1;
  string feedbackTitleV2 = 2;
  bool displayFeedback = 3;
  string feedbackTitle = 4;
  string feedbackReasonTitle = 5;
  int64 toastTime = 6;
  repeated NegativeFeedbackItem feedbackList = 7;
  string submitText = 8;
  string hideSearchDiscoverText = 9;
  string submitSuccessText = 10;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/NegativeFeedbackItem.java
message NegativeFeedbackItem {
  string text = 1;
  bool isUserFill = 2;
  string userFillTitle = 3;
  int64 sortIndex = 4;
  int64 userFillLimit = 5;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/NftFaceIcon.java
message NftFaceIcon {
  int32 regionType = 1;
  string icon = 2;
  int32 showStatus = 3;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/Notice.java
message Notice {
  int64 mid = 1;
  int64 noticeId = 2;
  string content = 3;
  string url = 4;
  int64 noticeType = 5;
  string icon = 6;
  string iconNight = 7;
  string textColor = 8;
  string textColorNight = 9;
  string bgColor = 10;
  string bgColorNight = 11;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/OfficialVerify.java
message OfficialVerify {
  int32 type = 1;
  string desc = 2;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/OgvCardUI.java
message OgvCardUI {
  string backgroundImage = 1;
  string gaussianBlurValue = 2;
  string moduleColor = 3;
  string maskOpacity = 4;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/OgvClipInfo.java
message OgvClipInfo {
  int64 playStartTime = 1;
  int64 playEndTime = 2;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/OgvClusterCardRelate.java
message OgvClusterCardRelate {
  string title = 1;
  repeated ExtraWord extraWordList = 2;
  int32 needOrder = 3;
  int64 showLines = 4;
  repeated DetailsRelationItem items = 5;
  string moreUrl = 6;
  int32 moreSearchType = 7;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/OgvRecommendWord.java
message OgvRecommendWord {
  string title = 1;
  string goto = 2;
  string param = 3;
  string uri = 4;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/OGVShare.java
message OGVShare {
  int64 aid = 1;
  int64 cid = 2;
  int64 seasonId = 3;
  int64 seasonType = 4;
  int64 epid = 5;
  string shareId = 6;
  string shareOrigin = 7;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/PageOffset.java
message PageOffset {
  int64 page = 1;
  string qvId = 2;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/PediaCardUI.java
message PediaCardUI {
  string backgroundImage = 1;
  string coverDefaultColor = 2;
  string gaussianBlurValue = 3;
  string maskColorValue = 4;
  string maskOpacity = 5;
  string moduleColor = 6;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/PediaCover.java
message PediaCover {
  int64 coverType = 1;
  string coverSunUrl = 2;
  string coverNightUrl = 3;
  int32 coverWidth = 4;
  int32 coverHeight = 5;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/PicNavigation.java
message PicNavigation {
  string title = 1;
  string uri = 2;
  string coverSunUrl = 3;
  string coverNightUrl = 4;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/PlayerArgs.java
message PlayerArgs {
  int32 isLive = 1;
  int64 aid = 2;
  int64 cid = 3;
  int32 subType = 4;
  int64 roomId = 5;
  int64 epId = 7;
  int32 isPreview = 8;
  string type = 9;
  int32 duration = 10;
  int64 seasonId = 11;
  int32 reportRequiredPlayDuration = 12;
  int32 reportRequiredTime = 13;
  int32 manualPlay = 14;
  bool hidePlayButton = 15;
  int32 contentMode = 16;
  int32 reportHistory = 17;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/PlayerGrade.java
message PlayerGrade {
  string nickname = 1;
  int64 playerId = 2;
  string portrait = 3;
  string hotRemark = 4;
  string gradeUsersText = 5;
  string avgGrade = 6;
  WatchButton watchButton = 7;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/PlayerWidget.java
message PlayerWidget {
  string title = 1;
  string desc = 2;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/PurchaseButton.java
message PurchaseButton {
  string jumpUrl = 1;
  string text = 2;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/RankInfo.java
message RankInfo {
  string searchNightIconUrl = 1;
  string searchDayIconUrl = 2;
  string searchBkgNightColor = 3;
  string searchBkgDayColor = 4;
  string searchFontNightColor = 5;
  string searchFontDayColor = 6;
  string rankContent = 7;
  string rankLink = 8;
  int64 gameRank = 9;
  int64 rankType = 10;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/RcmdReason.java
message RcmdReason {
  string content = 1;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/ReasonStyle.java
message ReasonStyle {
  string text = 1;
  string textColor = 2;
  string textColorNight = 3;
  string bgColor = 4;
  string bgColorNight = 5;
  string borderColor = 6;
  string borderColorNight = 7;
  int32 bgStyle = 8;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/RecommendWord.java
message RecommendWord {
  string param = 1;
  string type = 2;
  string title = 3;
  string fromSource = 4;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/RelatedQuery.java
message RelatedQuery {
  string query = 1;
  string url = 2;
  string recommendReason = 3;
  int64 iconType = 4;
  string icon = 5;
  string iconNight = 6;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/Relation.java
message Relation {
  int32 status = 1;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/ReserveInfo.java
message ReserveInfo {
  int64 sid = 1;
  string title = 2;
  int64 isFollow = 3;
  string oid = 4;
  string icon = 5;
  string iconNight = 6;
  int64 state = 7;
  int64 bgColor = 8;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/ReserveRequest.java
message ReserveRequest {
  SearchReserveInfo reserveInfo = 1;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/ReserveResponse.java
message ReserveResponse {
  string toast = 1;
  SearchReserveInfo reserveInfo = 2;
  int64 isFollow = 3;
  int64 state = 4;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/RightTopLiveBadge.java
message RightTopLiveBadge {
  int32 liveStatus = 1;
  LiveBadgeResource inLive = 2;
  string liveStatsDesc = 3;
  bool showAnimation = 4;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SaleInfo.java
message SaleInfo {
  string icon = 1;
  string iconNight = 2;
  string title = 3;
  ReasonStyle label = 4;
  string desc = 5;
  PurchaseButton button = 6;
  string vipStatus = 7;
  string vipType = 8;
  string tipsId = 9;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchActivityCard.java
message SearchActivityCard {
  string cover = 1;
  string title = 2;
  ReasonStyle corner = 3;
  string desc = 4;
  string reason = 5;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchAdCard.java
message SearchAdCard {
  string jsonstr = 1;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchAIChatCard.java
message SearchAIChatCard {
  string sessionId = 1;
  string title = 2;
  bool autoExpand = 3;
  Feedback feedback = 4;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchAlienationCard.java
message SearchAlienationCard {
  int32 coverType = 1;
  string cover = 2;
  int64 coverPicHeight = 3;
  string jumpUrl = 4;
  CardUI cardUi = 5;
  CountdownInfo countdownInfo = 6;
  string foldTitle = 7;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchAllRequest.java
message SearchAllRequest {
  string keyword = 1;
  Sort order = 2;
  string tidList = 3;
  string durationList = 4;
  string extraWord = 5;
  string fromSource = 6;
  int32 isOrgQuery = 7;
  int32 localTime = 8;
  string adExtra = 9;
  com.bapis.bilibili.pagination.Pagination pagination = 10;
  com.bapis.bilibili.app.archive.middleware.v1.PlayerArgs playerArgs = 11;
  map<string, string> fromExtra = 12;
  int32 forcedDisplayChatCard = 13;
  int32 isRefresh = 14;
  int32 refreshTimes = 15;
  string since = 16;
  int64 pubTimeBeginS = 17;
  int64 pubTimeEndS = 18;
  int64 allDoubleColumn = 19;
  string userAct = 20;
  bool needOgvExtraWord = 21;
  map<string, string> filterMap = 22;
  bool foldable = 23;
  bool isWideScreen = 24;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchAllResponse.java
message SearchAllResponse {
  string keyword = 1;
  string trackid = 2;
  repeated Nav nav = 3;
  repeated Item item = 4;
  EasterEgg easterEgg = 5;
  string expStr = 6;
  repeated string extraWordList = 7;
  string orgExtraWord = 8;
  int64 selectBarType = 9;
  int64 newSearchExpNum = 10;
  com.bapis.bilibili.pagination.PaginationReply pagination = 11;
  DisplayOption appDisplayOption = 12;
  map<string, string> annotation = 13;
  int64 page = 14;
  double realExposureRatio = 15;
  int64 allDoubleColumn = 19;
  int32 isNewUser = 20;
  SearchFilter searchFilter = 21;
  bool hasWideAutoFill = 22;
  map<int32, CardGroupRule> cardGroupRules = 23;
  int32 ogvRevampExpGroup = 24;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchArticleCard.java
message SearchArticleCard {
  string title = 1;
  string cover = 2;
  int32 play = 3;
  int32 like = 4;
  int32 reply = 5;
  repeated string imageUrls = 6;
  string author = 7;
  int32 templateId = 8;
  int64 id = 9;
  int64 mid = 10;
  string name = 11;
  string desc = 12;
  int32 view = 13;
  string pubTime = 14;
  string badge = 15;
  Feedback feedback = 16;
  CardLayout cardLayout = 17;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchAuthorNewCard.java
message SearchAuthorNewCard {
  string title = 1;
  string cover = 2;
  int32 liveFace = 3;
  string liveUri = 4;
  string liveLink = 5;
  int32 fans = 6;
  int32 level = 7;
  string sign = 8;
  bool isUp = 9;
  int32 archives = 10;
  int64 mid = 11;
  int64 roomid = 12;
  Relation relation = 13;
  OfficialVerify officialVerify = 14;
  int32 faceNftNew = 15;
  NftFaceIcon nftFaceIcon = 16;
  int32 isSeniorMember = 17;
  Background background = 18;
  int32 avStyle = 19;
  Space space = 20;
  repeated AvItem avItems = 21;
  Notice notice = 22;
  SharePlane sharePlane = 23;
  string inlineType = 24;
  SearchInlineData inlineLive = 25;
  int32 isInlineLive = 26;
  repeated ThreePoint threePoint = 27;
  int32 liveStatus = 28;
  VipInfo vip = 29;
  int32 attentions = 30;
  Feedback feedback = 31;
  repeated string userCardInfo = 32;
  CardLayout cardLayout = 33;
  com.bapis.bilibili.dagw.component.avatar.v1.AvatarItem avatarInfo = 34;
  int64 translationStatus = 35;
  string handle = 36;
  FollowButtonV2 followButton = 37;
  string moduleTitle = 38;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchBangumiCard.java
message SearchBangumiCard {
  string title = 1;
  string cover = 2;
  int32 mediaType = 3;
  int32 playState = 4;
  string area = 5;
  string style = 6;
  string styles = 7;
  string cv = 8;
  double rating = 9;
  int32 vote = 10;
  string target = 11;
  string staff = 12;
  string prompt = 13;
  int64 ptime = 14;
  string seasonTypeName = 15;
  repeated Episode episodes = 16;
  int32 isSelection = 17;
  int32 isAtten = 18;
  string label = 19;
  int64 seasonId = 20;
  string outName = 21;
  string outIcon = 22;
  string outUrl = 23;
  repeated ReasonStyle badges = 24;
  int32 isOut = 25;
  repeated EpisodeNew episodesNew = 26;
  WatchButton watchButton = 27;
  string selectionStyle = 28;
  CheckMore checkMore = 29;
  FollowButton followButton = 30;
  ReasonStyle styleLabel = 31;
  repeated ReasonStyle badgesV2 = 32;
  string stylesV2 = 33;
  CardLayout cardLayout = 34;
  SaleInfo saleInfo = 35;
  string viewContent = 36;
  int32 iconType = 37;
  repeated ThreePoint threePoint = 38;
  Share share = 39;
  repeated ReasonStyle qualityTags = 40;
  Feedback feedback = 41;
  string moduleTitle = 42;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchBannerCard.java
message SearchBannerCard {
  string title = 1;
  string cover = 2;
  string jumpUrl = 3;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchByTypeRequest.java
message SearchByTypeRequest {
  int32 type = 1;
  string keyword = 2;
  CategorySort categorySort = 3;
  int64 categoryId = 4;
  UserType userType = 5;
  UserSort userSort = 6;
  com.bapis.bilibili.pagination.Pagination pagination = 7;
  com.bapis.bilibili.app.archive.middleware.v1.PlayerArgs playerArgs = 8;
  string fromSeid = 9;
  string fromSource = 10;
  string userAct = 11;
  map<string, string> filterMap = 22;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchByTypeResponse.java
message SearchByTypeResponse {
  string trackid = 1;
  int32 pages = 2;
  string expStr = 3;
  string keyword = 4;
  int32 resultIsRecommend = 5;
  repeated Item items = 6;
  com.bapis.bilibili.pagination.PaginationReply pagination = 7;
  map<string, string> annotation = 8;
  double realExposureRatio = 9;
  int64 page = 10;
  SearchFilter searchFilter = 11;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchChatGPTCard.java
message SearchChatGPTCard {
  string sessionId = 1;
  repeated string loadingIconLight = 2;
  repeated string loadingIconNight = 3;
  string backgroundLight = 4;
  string backgroundNight = 5;
  string betaText = 6;
  Disclaimer disclaimer = 7;
  string title = 8;
  bool autoExpand = 9;
  Feedback feedback = 10;
  Colors betaTextColor = 11;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchCheese.java
message SearchCheese {
  int64 seasonId = 1;
  string title = 2;
  string cover = 3;
  string name = 4;
  string uri = 5;
  string showCardDesc1 = 6;
  string showCardDesc2 = 7;
  string viewContent = 8;
  int32 iconType = 9;
  repeated ReasonStyle badges = 10;
  repeated ThreePoint threePoint = 11;
  Feedback feedback = 12;
  string shareFrom = 13;
  CardLayout cardLayout = 14;
  int64 translationStatus = 15;
  string translatedTitle = 16;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchCollectionCard.java
message SearchCollectionCard {
  string title = 1;
  string cover = 2;
  string author = 3;
  repeated AvItem avItems = 4;
  BottomButton bottomButton = 5;
  string collectionIcon = 6;
  string showCardDesc1 = 7;
  string showCardDesc2 = 8;
  CardLayout cardLayout = 9;
  Feedback feedback = 10;
  SearchInlineData inlineData = 11;
  int32 isHideTitle = 12;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchComicCard.java
message SearchComicCard {
  string title = 1;
  string cover = 2;
  string name = 3;
  string style = 4;
  string comicUrl = 5;
  string badge = 6;
  CardLayout cardLayout = 7;
  repeated EpisodeNew episodesNew = 8;
  ReasonStyle recTag = 9;
  FollowButtonV2 followButton = 10;
  int32 isAttend = 11;
  string selectionStyle = 12;
  string recText = 13;
  int64 cid = 14;
  repeated ThreePoint threePoint = 15;
  Share share = 16;
  repeated ReasonStyle qualityTags = 17;
  Feedback feedback = 18;
  string moduleTitle = 19;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchComicInfo.java
message SearchComicInfo {
  string uri = 1;
  string param = 2;
  SearchComicCard comic = 3;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchComicRequest.java
message SearchComicRequest {
  string idList = 1;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchComicResponse.java
message SearchComicResponse {
  repeated SearchComicInfo items = 1;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchCommentCard.java
message SearchCommentCard {
  com.bapis.bilibili.dagw.component.avatar.v1.AvatarItem avatarInfo = 1;
  int64 mid = 2;
  string name = 3;
  string pubTime = 4;
  string content = 5;
  int64 like = 6;
  string replyText = 7;
  string prefix = 8;
  string title = 9;
  int64 row = 10;
  string upUri = 11;
  string badge = 12;
  string icon = 13;
  string iconNight = 14;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchCommentClusterCard.java
message SearchCommentClusterCard {
  string title = 1;
  repeated Comment items = 2;
  string moreText = 3;
  bool isMore = 4;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchDigitalChatCard.java
message SearchDigitalChatCard {
  string title = 1;
  WatchButton watchButton = 2;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchDoubleColumnCard.java
message SearchDoubleColumnCard {
  string title = 1;
  string cover = 2;
  repeated ThreePoint threePoint = 3;
  Share share = 4;
  int32 play = 5;
  int32 danmaku = 6;
  string author = 7;
  string desc = 8;
  string duration = 9;
  int64 mid = 10;
  string showCardDesc1 = 11;
  string showCardDesc2 = 12;
  Feedback feedback = 13;
  string face = 14;
  int64 ptime = 15;
  string viewContent = 16;
  int32 iconType = 17;
  int32 aspectRatio = 18;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchDoubleOpusCard.java
message SearchDoubleOpusCard {
  string title = 1;
  repeated DoubleOpusItem item = 2;
  WatchButton watchButton = 3;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchDynamicCard.java
message SearchDynamicCard {
  string title = 1;
  string cover = 2;
  int32 coverCount = 3;
  repeated string covers = 4;
  Upper upper = 5;
  Stat stat = 6;
  repeated DyTopic dyTopic = 7;
  string badge = 8;
  Feedback feedback = 9;
  CardLayout cardLayout = 10;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchFilter.java
message SearchFilter {
  repeated FilterEntries filterEntries = 1;
  int64 filterStyle = 2;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchGameCard.java
message SearchGameCard {
  string title = 1;
  string cover = 2;
  string reserve = 3;
  float rating = 4;
  string tags = 5;
  string noticeName = 6;
  string noticeContent = 7;
  string giftContent = 8;
  string giftUrl = 9;
  int32 reserveStatus = 10;
  RankInfo rankInfo = 11;
  string specialBgColor = 12;
  CloudGameParams cloudGameParams = 13;
  bool showCloudGameEntry = 14;
  ReasonStyle newRecTag = 15;
  string noticeContentName = 16;
  CardLayout cardLayout = 17;
  int32 gameStyle = 18;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchGiantCard.java
message SearchGiantCard {
  string content = 1;
  int32 view = 2;
  int32 like = 3;
  int32 reply = 4;
  repeated string imageUrls = 5;
  int64 mid = 6;
  string face = 7;
  string name = 8;
  string pubTime = 9;
  Feedback feedback = 10;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchHotBannerCard.java
message SearchHotBannerCard {
  string icon = 1;
  string iconNight = 2;
  string title = 3;
  string moreText = 4;
  string moreUrl = 5;
  string description = 6;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchHotRecommend.java
message SearchHotRecommend {
  string title = 1;
  string cover = 2;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchInlineData.java
message SearchInlineData {
  string uri = 1;
  string title = 2;
  PlayerArgs playerArgs = 3;
  int32 canPlay = 4;
  Args args = 5;
  string cardGoto = 6;
  string cardType = 7;
  string cover = 8;
  int32 coverLeftIcon1 = 9;
  int32 coverLeftIcon2 = 10;
  string coverLeftText1 = 11;
  string coverLeftText2 = 12;
  UpArgs upArgs = 13;
  string extraUri = 14;
  bool isFav = 15;
  bool isCoin = 16;
  string goto = 17;
  Share share = 18;
  ThreePoint2 threePoint = 19;
  repeated ThreePointV2 threePointV2 = 20;
  SharePlane sharePlane = 21;
  InlineThreePointPanel threePointMeta = 22;
  Avatar avatar = 23;
  string coverRightText = 24;
  string desc = 25;
  InlineProgressBar inlineProgressBar = 26;
  SearchLikeButtonItem likeButton = 27;
  int32 officialIcon = 28;
  int32 officialIconV2 = 29;
  string param = 30;
  TrafficConfig trafficConfig = 31;
  bool isAtten = 32;
  GotoIcon gotoIcon = 33;
  bool disableDanmaku = 34;
  bool hideDanmakuSwitch = 35;
  ReasonStyle badgeStyle = 36;
  PlayerWidget playerWidget = 37;
  ReasonStyle coverBadgeStyle = 38;
  RightTopLiveBadge rightTopLiveBadge = 39;
  string reportFlowData = 40;
  string translatedTitle = 41;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchLikeButtonItem.java
message SearchLikeButtonItem {
  int64 aid = 1;
  int64 count = 2;
  int32 selected = 3;
  bool showCount = 4;
  LikeResource likeResource = 5;
  LikeResource likeNightResource = 6;
  LikeResource dislikeResource = 7;
  LikeResource dislikeNightResource = 8;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchLiveCard.java
message SearchLiveCard {
  string title = 1;
  string cover = 2;
  RcmdReason rcmdReason = 3;
  string name = 4;
  int32 online = 5;
  string badge = 6;
  string liveLink = 7;
  string cardLeftText = 8;
  int32 cardLeftIcon = 9;
  string showCardDesc2 = 10;
  RightTopLiveBadge rightTopLiveBadge = 11;
  Feedback feedback = 12;
  CardLayout cardLayout = 13;
  repeated ThreePoint threePoint = 14;
  int64 translationStatus = 15;
  string translatedTitle = 16;
  int64 roomid = 17;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchLiveInlineCard.java
message SearchLiveInlineCard {
  string title = 1;
  string cover = 2;
  int64 mid = 3;
  ReasonStyle rcmdReasonStyle = 4;
  int64 roomid = 5;
  string liveLink = 6;
  SearchInlineData liveRoomInline = 7;
  string inlineType = 8;
  Feedback feedback = 9;
  CardLayout cardLayout = 10;
  com.bapis.bilibili.dagw.component.avatar.v1.AvatarItem avatarInfo = 11;
  repeated ThreePoint threePoint = 12;
  int64 translationStatus = 13;
  string translatedTitle = 14;
  int32 inlineTitleStyle = 15;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchLiveMaster.java
message SearchLiveMaster {
  string title = 1;
  string name = 2;
  string cover = 3;
  string uri = 4;
  WatchedShow watchedShow = 5;
  string ucover = 6;
  int64 attentions = 7;
  int32 verifyType = 8;
  bool faceNftNew = 9;
  string nftDamrk = 10;
  string verifyDesc = 11;
  int32 level = 12;
  int32 levelColor = 13;
  int32 isAtten = 14;
  GloryInfo gloryInfo = 15;
  int64 roomid = 16;
  int64 mid = 17;
  int32 online = 18;
  int32 liveStatus = 19;
  string cateParentName = 20;
  string cateName = 21;
  string liveLink = 22;
  com.bapis.bilibili.dagw.component.avatar.v1.AvatarItem avatarInfo = 23;
  repeated ThreePoint threePoint = 24;
  int64 translationStatus = 25;
  string translatedTitle = 26;
  ReasonStyle badge = 27;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchLiveRoom.java
message SearchLiveRoom {
  string title = 1;
  string name = 2;
  string cover = 3;
  string uri = 4;
  string param = 5;
  WatchedShow watchedShow = 6;
  int64 roomid = 7;
  int64 shortId = 8;
  string goto = 9;
  string areaV2Name = 10;
  int32 online = 11;
  int64 mid = 12;
  int32 liveStatus = 13;
  string liveLink = 14;
  repeated ThreePoint threePoint = 15;
  int64 translationStatus = 16;
  string translatedTitle = 17;
  ReasonStyle badge = 18;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchLiveRoomTitle.java
message SearchLiveRoomTitle {
  int32 totalCount = 1;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchMusicCard.java
message SearchMusicCard {
  string title = 1;
  string cover = 2;
  string badge = 3;
  string author = 4;
  string desc = 5;
  ReasonStyle newRecTag = 6;
  string showCardDesc1 = 7;
  string showCardDesc2 = 8;
  WatchButton watchButton = 9;
  Feedback feedback = 10;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchNewChannelCard.java
message SearchNewChannelCard {
  string title = 1;
  string cover = 2;
  int64 id = 3;
  string typeIcon = 4;
  ChannelLabel channelLabel1 = 5;
  ChannelLabel channelLabel2 = 6;
  ChannelLabel channelButton = 7;
  string designType = 8;
  repeated ChannelMixedItem items = 9;
  CardLayout cardLayout = 10;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchNoResultSuggestWordCard.java
message SearchNoResultSuggestWordCard {
  string title = 1;
  string cover = 2;
  int32 sugkeywordType = 3;
  CardLayout cardLayout = 4;
  string prefix = 5;
  string content = 6;
  string suffix = 7;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchNPSCard.java
message SearchNPSCard {
  string title = 1;
  repeated SearchNPSCard_Option options = 2;
  CardLayout cardLayout = 3;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchNPSCard.java
message SearchNPSCard_Option {
  string text = 1;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchOgvCard.java
message SearchOgvCard {
  string title = 1;
  string subTitle1 = 2;
  string subTitle2 = 3;
  string cover = 4;
  string bgCover = 5;
  string specialBgColor = 6;
  string coverUri = 7;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchOgvChannelCard.java
message SearchOgvChannelCard {
  string title = 1;
  string cover = 2;
  int64 mediaId = 3;
  string styles = 4;
  string area = 5;
  string staff = 6;
  string badge = 7;
  WatchButton watchButton = 8;
  double rating = 9;
  string desc = 10;
  repeated ReasonStyle badgesV2 = 11;
  string stylesV2 = 12;
  PurchaseButton purchaseButton = 13;
  ReasonStyle styleLabel = 14;
  CardLayout cardLayout = 15;
  repeated ThreePoint threePoint = 16;
  Share share = 17;
  WatchButton bikanDegree = 18;
  Style style = 19;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchOgvClusterCard.java
message SearchOgvClusterCard {
  string title = 1;
  Item singleCard = 2;
  OgvClusterCardRelate relate = 3;
  int32 inlineTitleStyle = 4;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchOgvInlineCard.java
message SearchOgvInlineCard {
  string title = 1;
  string cover = 2;
  string author = 3;
  int32 danmaku = 4;
  string desc = 5;
  string face = 6;
  string inlineType = 7;
  int64 mid = 8;
  int64 play = 9;
  SearchInlineData ogvInline = 10;
  OgvClipInfo ogvClipInfo = 11;
  WatchButton watchButton = 12;
  string score = 13;
  int32 ogvInlineExp = 14;
  repeated ReasonStyle badgesV2 = 15;
  CardLayout cardLayout = 16;
  SaleInfo saleInfo = 17;
  int32 inlineTitleStyle = 18;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchOgvRecommendCard.java
message SearchOgvRecommendCard {
  string title = 1;
  string cover = 2;
  repeated OgvRecommendWord items = 3;
  string specialBgColor = 4;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchOgvRelationCard.java
message SearchOgvRelationCard {
  string title = 1;
  string cover = 2;
  string specialBgColor = 3;
  string moreText = 4;
  string moreUrl = 5;
  repeated DetailsRelationItem items = 6;
  int32 isNewStyle = 7;
  OgvCardUI ogvCardUi = 8;
  int32 moreSearchType = 9;
  CardLayout cardLayout = 10;
  SaleInfo saleInfo = 11;
  ReasonStyle moreTextStyle = 12;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchOGVReply.java
message SearchOGVReply {
  repeated ExtraWord extraWordList = 1;
  int32 needOrder = 2;
  repeated Item items = 3;
  repeated DetailsRelationItem relationItems = 4;
  com.bapis.bilibili.pagination.PaginationReply pagination = 5;
  int64 page = 6;
  map<string, string> annotation = 7;
  string query = 8;
  string trackid = 9;
  bool hasWideAutoFill = 10;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchOGVReq.java
message SearchOGVReq {
  Sort order = 1;
  string firstExtraWord = 2;
  string secondExtraWord = 3;
  string fromSource = 4;
  string keyword = 5;
  com.bapis.bilibili.pagination.Pagination pagination = 6;
  com.bapis.bilibili.app.archive.middleware.v1.PlayerArgs playerArgs = 7;
  string userAct = 8;
  bool needOgvExtraWord = 9;
  bool isWideScreen = 10;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchOlympicGameCard.java
message SearchOlympicGameCard {
  string title = 1;
  string cover = 2;
  SportsMatchItem sportsMatchItem = 3;
  MatchItem matchTop = 4;
  string bgCover = 5;
  repeated ExtraLink extraLink = 6;
  string inlineType = 7;
  SearchInlineData ugcInline = 8;
  SearchInlineData liveRoomInline = 9;
  MatchItem matchBottom = 10;
  CardLayout cardLayout = 11;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchOlympicWikiCard.java
message SearchOlympicWikiCard {
  string title = 1;
  string cover = 2;
  CardBusinessBadge cardBusinessBadge = 3;
  NavigationButton readMore = 4;
  string inlineType = 5;
  SearchInlineData ugcInline = 6;
  SearchInlineData liveRoomInline = 7;
  PediaCover pediaCover = 8;
  repeated Navigation navigation = 9;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchPediaCard.java
message SearchPediaCard {
  string title = 1;
  string cover = 2;
  repeated Navigation navigation = 3;
  NavigationButton readMore = 4;
  int32 navigationModuleCount = 5;
  PediaCover pediaCover = 6;
  CardBusinessBadge cardBusinessBadge = 7;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchPediaPicCard.java
message SearchPediaPicCard {
  string cover = 1;
  repeated PicNavigation picNavigation = 2;
  CardLayout cardLayout = 3;
  PediaCardUI pediaCardUi = 4;
  int32 coverType = 5;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchPlayListCard.java
message SearchPlayListCard {
  string title = 1;
  repeated AvItem avItems = 2;
  Feedback feedback = 3;
  BottomButton bottomButton = 4;
  SearchInlineData inlineData = 5;
  string showCardDesc1 = 6;
  string showCardDesc2 = 7;
  int32 isHideTitle = 8;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchPurchaseCard.java
message SearchPurchaseCard {
  string title = 1;
  string cover = 2;
  string badge = 3;
  string venue = 4;
  int32 price = 5;
  string priceComplete = 6;
  int32 priceType = 7;
  int32 requiredNumber = 8;
  string city = 9;
  string showTime = 10;
  int64 id = 11;
  string shopName = 12;
  CardLayout cardLayout = 13;
  string saleType = 14;
  string saleTypeColor = 15;
  string saleTypeNightColor = 16;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchQACard.java
message SearchQACard {
  string sessionId = 1;
  repeated string loadingIconLight = 2;
  repeated string loadingIconNight = 3;
  string backgroundLight = 4;
  string backgroundNight = 5;
  string betaText = 6;
  Colors betaTextColor = 7;
  Disclaimer disclaimer = 8;
  string title = 9;
  bool autoExpand = 10;
  com.bapis.bilibili.broadcast.message.main.ChatResult result = 11;
  Feedback feedback = 12;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchRecommendTipCard.java
message SearchRecommendTipCard {
  string title = 1;
  string cover = 2;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchRecommendWordCard.java
message SearchRecommendWordCard {
  string title = 1;
  string cover = 2;
  repeated RecommendWord list = 3;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchRelatedSearch.java
message SearchRelatedSearch {
  string title = 1;
  repeated RelatedQuery relatedQueryList = 2;
  CardLayout cardLayout = 3;
  NegativeFeedback negativeFeedback = 4;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchReserveInfo.java
message SearchReserveInfo {
  int64 sid = 1;
  string oid = 2;
  ReserveType type = 3;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchReserveRequest.java
message SearchReserveRequest {
  int64 sid = 1;
  string oid = 2;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchReserveResponse.java
message SearchReserveResponse {
  ReserveInfo reserveInfo = 1;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchSeriesCard.java
message SearchSeriesCard {
  string title = 1;
  repeated AvItem avItems = 2;
  Feedback feedback = 3;
  BottomButton bottomButton = 4;
  SearchInlineData inlineData = 5;
  string showCardDesc1 = 6;
  string showCardDesc2 = 7;
  int32 isHideTitle = 8;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchSpecialCard.java
message SearchSpecialCard {
  string title = 1;
  string cover = 2;
  repeated ReasonStyle newRecTags = 3;
  CardBusinessBadge cardBusinessBadge = 4;
  string badge = 5;
  string desc = 6;
  repeated ReasonStyle newRecTagsV2 = 7;
  RcmdReason rcmdReason = 8;
  ReserveInfo reserveInfo = 9;
  CardLayout cardLayout = 10;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchSpecialGuideCard.java
message SearchSpecialGuideCard {
  string title = 1;
  string cover = 2;
  string phone = 3;
  string desc = 4;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchSportCard.java
message SearchSportCard {
  string title = 1;
  string cover = 2;
  string bgCover = 3;
  MatchItem matchTop = 4;
  MatchItem matchBottom = 5;
  repeated ExtraLink extraLink = 6;
  repeated MatchInfoObj items = 7;
  int64 id = 8;
  CardLayout cardLayout = 9;
  PlayerGrade playerGrade = 10;
  string bgCoverNight = 11;
  MatchGuess matchGuess = 12;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchSportInlineCard.java
message SearchSportInlineCard {
  string title = 1;
  string cover = 2;
  string bgCover = 3;
  MatchItem matchTop = 4;
  MatchItem matchBottom = 5;
  repeated ExtraLink extraLink = 6;
  repeated MatchInfoObj items = 7;
  int64 id = 8;
  SearchInlineData esportsInline = 9;
  string inlineType = 10;
  CardLayout cardLayout = 11;
  PlayerGrade playerGrade = 12;
  string bgCoverNight = 13;
  MatchGuess matchGuess = 14;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchStarBannerCard.java
message SearchStarBannerCard {
  string title = 1;
  string cover = 2;
  string bgImage = 3;
  string cardDesc = 4;
  ReasonStyle badge = 5;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchSubjectCard.java
message SearchSubjectCard {
  int64 id = 1;
  string title = 2;
  string cover = 3;
  string desc = 4;
  string hotText = 5;
  string moreText = 6;
  string moreUrl = 7;
  string topicType = 8;
  repeated ReasonStyle badges = 9;
  repeated TopicItem items = 10;
  Feedback feedback = 11;
  CardLayout cardLayout = 12;
  WatchButton button = 13;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchTimeLineCard.java
message SearchTimeLineCard {
  int64 timeLineId = 1;
  string timeLineTitle = 2;
  repeated TimeLineEvents timeLineEvents = 3;
  bool hasMore = 4;
  int64 startTime = 5;
  int64 endTime = 6;
  WatchButton watchButton = 7;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchTipsCard.java
message SearchTipsCard {
  string title = 1;
  string cover = 2;
  string subTitle = 4;
  string coverNight = 134;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchTopGameCard.java
message SearchTopGameCard {
  string title = 1;
  string cover = 2;
  int32 array = 3;
  string backgroundImage = 4;
  int32 buttonType = 5;
  string gameIcon = 6;
  int64 gameBaseId = 7;
  int32 gameStatus = 8;
  string inlineType = 9;
  TopGameUI topGameUi = 10;
  string noticeContent = 11;
  string noticeName = 12;
  float rating = 13;
  string score = 14;
  repeated TabInfo tabInfo = 15;
  string tags = 16;
  SearchInlineData ugcInline = 17;
  string videoCoverImage = 18;
  SearchInlineData inlineLive = 19;
  CardLayout cardLayout = 20;
  ReasonStyle recTag = 21;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchTribeeCard.java
message SearchTribeeCard {
  string cover = 1;
  string title = 2;
  ReasonStyle badge = 3;
  WatchButton button = 4;
  string tribeeDesc = 5;
  string showCardDesc = 6;
  bool isEnhanced = 7;
  repeated TribeePostItem postItems = 8;
  repeated ThreePoint threePoint = 9;
  int64 tribeeId = 10;
  string uri = 11;
  Feedback feedback = 12;
  TribeeCoverStyle coverStyle = 13;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchUgcInlineCard.java
message SearchUgcInlineCard {
  string title = 1;
  string cover = 2;
  string author = 3;
  int32 danmaku = 4;
  string desc = 5;
  string inlineType = 6;
  int64 mid = 7;
  int64 play = 8;
  SearchInlineData ugcInline = 9;
  FullTextResult fullText = 10;
  Feedback feedback = 11;
  CardLayout cardLayout = 12;
  com.bapis.bilibili.dagw.component.avatar.v1.AvatarItem avatarInfo = 13;
  repeated ThreePoint threePoint = 14;
  int64 translationStatus = 15;
  string translatedTitle = 16;
  int32 inlineTitleStyle = 17;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchUpperCard.java
message SearchUpperCard {
  string title = 1;
  string cover = 2;
  string sign = 3;
  int32 fans = 4;
  int32 archives = 5;
  int32 liveStatus = 6;
  int32 roomid = 7;
  OfficialVerify officialVerify = 8;
  int32 faceNftNew = 9;
  NftFaceIcon nftFaceIcon = 10;
  repeated AvItem avItems = 11;
  bool isUp = 12;
  int32 attentions = 13;
  int32 level = 14;
  int32 isSeniorMember = 15;
  VipInfo vip = 16;
  Relation relation = 17;
  string liveLink = 18;
  Notice notice = 19;
  com.bapis.bilibili.dagw.component.avatar.v1.AvatarItem avatarInfo = 20;
  string userCardDesc = 21;
  string handle = 22;
  FollowButtonV2 followButton = 23;
  Feedback feedback = 24;
  string moduleTitle = 25;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchUPRecommend.java
message SearchUPRecommend {
  int64 id = 1;
  int32 cardStyle = 2;
  string moreUrl = 3;
  string moreText = 4;
  int32 showFollowButton = 5;
  repeated UPRecommendItem items = 6;
  string title = 7;
  int32 followButtonStyle = 8;
  bool showTitle = 9;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SearchVideoCard.java
message SearchVideoCard {
  string title = 1;
  string cover = 2;
  RcmdReason rcmdReason = 3;
  repeated ReasonStyle newRecTags = 4;
  repeated ThreePoint threePoint = 5;
  Share share = 6;
  CardBusinessBadge cardBusinessBadge = 7;
  int32 play = 8;
  int32 danmaku = 9;
  string author = 10;
  string desc = 11;
  string duration = 12;
  repeated ReasonStyle badges = 13;
  int64 mid = 14;
  string showCardDesc1 = 15;
  string showCardDesc2 = 16;
  FullTextResult fullText = 17;
  repeated ReasonStyle newRecTagsV2 = 18;
  repeated ReasonStyle badgesV2 = 19;
  Feedback feedback = 20;
  TimeLine timeLine = 21;
  string face = 22;
  int64 ptime = 23;
  string viewContent = 24;
  int32 iconType = 25;
  FoldingTimeLine foldingTimeLine = 26;
  LabelStyle chargingLabel = 27;
  CardLayout cardLayout = 28;
  string authorPrefix = 29;
  repeated string highlightTags = 30;
  ReasonStyle coverBadge = 31;
  ShortOGVInfo shortOgvInfo = 32;
  int64 translationStatus = 33;
  string translatedTitle = 34;
  repeated ReasonStyle qualityTags = 35;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/Share.java
message Share {
  string type = 1;
  Video video = 2;
  OGVShare ogv = 3;
  H5Share h5 = 4;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/ShareButtonItem.java
message ShareButtonItem {
  int32 type = 1;
  repeated ButtonMeta buttonMetas = 2;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SharePlane.java
message SharePlane {
  string title = 1;
  string shareSubtitle = 2;
  string desc = 3;
  string cover = 4;
  int64 aid = 5;
  string bvid = 6;
  ShareTo shareTo = 7;
  string author = 8;
  int64 authorId = 9;
  string shortLink = 10;
  string playNumber = 11;
  int64 roomId = 12;
  int32 epId = 13;
  string areaName = 14;
  string authorFace = 15;
  int32 seasonId = 16;
  string shareFrom = 17;
  string seasonTitle = 18;
  string from = 19;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/ShareTo.java
message ShareTo {
  bool dynamic = 1;
  bool im = 2;
  bool copy = 3;
  bool more = 4;
  bool wechat = 5;
  bool weibo = 6;
  bool wechatMonment = 7;
  bool qq = 8;
  bool qzone = 9;
  bool facebook = 10;
  bool line = 11;
  bool messenger = 12;
  bool whatsApp = 13;
  bool twitter = 14;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/ShortOGVInfo.java
message ShortOGVInfo {
  string appId = 1;
  int64 seasonId = 2;
  int64 episodeId = 3;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/Space.java
message Space {
  int32 show = 1;
  string textColor = 2;
  string textColorNight = 3;
  string text = 4;
  string spaceUrl = 5;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/SportsMatchItem.java
message SportsMatchItem {
  int64 matchId = 1;
  int64 seasonId = 2;
  string matchName = 3;
  string img = 4;
  string beginTimeDesc = 5;
  string matchStatusDesc = 6;
  string subContent = 7;
  string subExtraIcon = 8;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/Stat.java
message Stat {
  int32 play = 1;
  int32 like = 2;
  int32 reply = 3;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/TabInfo.java
message TabInfo {
  string tabName = 1;
  string tabUrl = 2;
  int32 sort = 3;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/TextButton.java
message TextButton {
  string text = 1;
  string uri = 2;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/TextLabel.java
message TextLabel {
  string text = 1;
  string uri = 2;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/Texts.java
message Texts {
  string bookingText = 1;
  string unbookingText = 2;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/ThreePoint.java
message ThreePoint {
  string type = 1;
  string icon = 2;
  string title = 3;
  string alternateTitle = 4;
  string alternateIcon = 5;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/ThreePoint2.java
message ThreePoint2 {
  repeated DislikeReason dislikeReasons = 1;
  repeated DislikeReason feedbacks = 2;
  int32 watchLater = 3;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/ThreePointV2.java
message ThreePointV2 {
  string title = 1;
  string subtitle = 2;
  repeated DislikeReason reasons = 3;
  string type = 4;
  int64 id = 5;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/ThreePointV3.java
message ThreePointV3 {
  string title = 1;
  string selectedTitle = 2;
  string subtitle = 3;
  repeated DislikeReason reasons = 4;
  string type = 5;
  int64 id = 6;
  int32 selected = 7;
  string icon = 8;
  string selectedIcon = 9;
  string url = 10;
  int32 defaultId = 11;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/ThreePointV4.java
message ThreePointV4 {
  SharePlane sharePlane = 1;
  WatchLater watchLater = 2;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/TimeLine.java
message TimeLine {
  string icon = 1;
  string title = 2;
  int32 color = 3;
  int32 segment = 4;
  int64 startSecond = 5;
  int64 endSecond = 6;
  int32 initPosition = 7;
  int32 type = 8;
  repeated VideoTextItem items = 9;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/TimeLineEvents.java
message TimeLineEvents {
  int64 eventId = 1;
  string title = 2;
  string timeDesc = 3;
  string jumpLink = 4;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/TopGameUI.java
message TopGameUI {
  string backgroundImage = 1;
  string coverDefaultColor = 2;
  string gaussianBlurValue = 3;
  string maskColorValue = 4;
  string maskOpacity = 5;
  string moduleColor = 6;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/TopicItem.java
message TopicItem {
  string uri = 1;
  string param = 2;
  string goto = 3;
  string linktype = 4;
  int32 position = 5;
  string trackid = 6;
  int64 id = 7;
  string title = 8;
  int32 contentType = 9;
  string upName = 10;
  string publishText = 11;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/TrafficConfig.java
message TrafficConfig {
  string title = 1;
  repeated TrafficConfigOption options = 2;
  int64 defaultOptionId = 3;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/TrafficConfigOption.java
message TrafficConfigOption {
  int32 id = 1;
  string text = 2;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/TribeePostItem.java
message TribeePostItem {
  string title = 1;
  int64 reply = 2;
  string uri = 3;
  string goto = 4;
  string param = 5;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/UpArgs.java
message UpArgs {
  int64 upId = 1;
  string upName = 2;
  string upFace = 3;
  int32 selected = 4;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/Upper.java
message Upper {
  int64 mid = 1;
  string title = 2;
  string cover = 3;
  string ptimeText = 4;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/UPRecommendItem.java
message UPRecommendItem {
  int64 mid = 1;
  int32 level = 2;
  int32 isSeniorMember = 3;
  string name = 4;
  string cover = 5;
  string uri = 6;
  repeated string userCardInfo = 7;
  repeated ThreePoint threePoint = 8;
  Relation relation = 9;
  com.bapis.bilibili.dagw.component.avatar.v1.AvatarItem avatarInfo = 10;
  SharePlane sharePlane = 11;
  string liveLink = 12;
  int32 isLive = 13;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/Video.java
message Video {
  string bvid = 1;
  int64 cid = 2;
  string shareSubtitle = 3;
  bool isHotLabel = 4;
  int32 page = 5;
  int32 pageCount = 6;
  string shortLink = 7;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/VideoTextItem.java
message VideoTextItem {
  int32 type = 1;
  string text = 2;
  int64 startSecond = 3;
  string jumpUrl = 4;
  string imgUrl = 5;
  string videoTime = 6;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/VipInfo.java
message VipInfo {
  int32 type = 1;
  int32 status = 2;
  int64 dueDate = 3;
  int32 vipPayType = 4;
  int32 themeType = 5;
  VipLabel label = 6;
  int32 avatarSubscript = 7;
  string nicknameColor = 8;
  int64 role = 9;
  string avatarSubscriptUrl = 10;
  int32 tvVipStatus = 11;
  int32 tvVipPayType = 12;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/VipLabel.java
message VipLabel {
  string path = 1;
  string text = 2;
  string labelTheme = 3;
  string textColor = 4;
  int32 bgStyle = 5;
  string bgColor = 6;
  string borderColor = 7;
  bool useImgLabel = 8;
  string imgLabelUriHans = 9;
  string imgLabelUriHant = 10;
  string imgLabelUriHansStatic = 11;
  string imgLabelUriHantStatic = 12;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/WatchButton.java
message WatchButton {
  string title = 1;
  string link = 2;
  string textColor = 3;
  string textColorNight = 4;
  string bgColor = 5;
  string bgColorNight = 6;
  map<string, string> report = 7;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/WatchedShow.java
message WatchedShow {
  bool switch = 1;
  int64 num = 2;
  string textSmall = 3;
  string textLarge = 4;
  string icon = 5;
  string iconLocation = 6;
  string iconWeb = 7;
}

// Source: com/bapis/bilibili/polymer/app/search/v1/WatchLater.java
message WatchLater {
  int64 aid = 1;
  string bvid = 2;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/polymer/app/search/v1";
