// Reconstructed from protobuf-lite metadata in the APK.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: bilibili/app/growth/v1/messages.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Source: com/bapis/bilibili/app/growth/v1/AdDeviceInfo.java
type AdDeviceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Oaid         string `protobuf:"bytes,1,opt,name=oaid,proto3" json:"oaid,omitempty"`
	OaidMd5      string `protobuf:"bytes,2,opt,name=oaidMd5,proto3" json:"oaidMd5,omitempty"`
	AndroidId    string `protobuf:"bytes,3,opt,name=androidId,proto3" json:"androidId,omitempty"`
	AndroidIdMd5 string `protobuf:"bytes,4,opt,name=androidIdMd5,proto3" json:"androidIdMd5,omitempty"`
	Imei         string `protobuf:"bytes,5,opt,name=imei,proto3" json:"imei,omitempty"`
	ImeiMd5      string `protobuf:"bytes,6,opt,name=imeiMd5,proto3" json:"imeiMd5,omitempty"`
}

func (x *AdDeviceInfo) Reset() {
	*x = AdDeviceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_growth_v1_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdDeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdDeviceInfo) ProtoMessage() {}

func (x *AdDeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_growth_v1_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdDeviceInfo.ProtoReflect.Descriptor instead.
func (*AdDeviceInfo) Descriptor() ([]byte, []int) {
	return file_bilibili_app_growth_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *AdDeviceInfo) GetOaid() string {
	if x != nil {
		return x.Oaid
	}
	return ""
}

func (x *AdDeviceInfo) GetOaidMd5() string {
	if x != nil {
		return x.OaidMd5
	}
	return ""
}

func (x *AdDeviceInfo) GetAndroidId() string {
	if x != nil {
		return x.AndroidId
	}
	return ""
}

func (x *AdDeviceInfo) GetAndroidIdMd5() string {
	if x != nil {
		return x.AndroidIdMd5
	}
	return ""
}

func (x *AdDeviceInfo) GetImei() string {
	if x != nil {
		return x.Imei
	}
	return ""
}

func (x *AdDeviceInfo) GetImeiMd5() string {
	if x != nil {
		return x.ImeiMd5
	}
	return ""
}

// Source: com/bapis/bilibili/app/growth/v1/ReportAttributionReq.java
type ReportAttributionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClickTime       int64         `protobuf:"varint,1,opt,name=clickTime,proto3" json:"clickTime,omitempty"`
	DownloadTime    int64         `protobuf:"varint,2,opt,name=downloadTime,proto3" json:"downloadTime,omitempty"`
	InstallTime     int64         `protobuf:"varint,3,opt,name=installTime,proto3" json:"installTime,omitempty"`
	AttributionData string        `protobuf:"bytes,4,opt,name=attributionData,proto3" json:"attributionData,omitempty"`
	ReferrerEx      string        `protobuf:"bytes,5,opt,name=referrerEx,proto3" json:"referrerEx,omitempty"`
	AdDeviceInfo    *AdDeviceInfo `protobuf:"bytes,6,opt,name=adDeviceInfo,proto3" json:"adDeviceInfo,omitempty"`
}

func (x *ReportAttributionReq) Reset() {
	*x = ReportAttributionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_growth_v1_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportAttributionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAttributionReq) ProtoMessage() {}

func (x *ReportAttributionReq) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_growth_v1_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAttributionReq.ProtoReflect.Descriptor instead.
func (*ReportAttributionReq) Descriptor() ([]byte, []int) {
	return file_bilibili_app_growth_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ReportAttributionReq) GetClickTime() int64 {
	if x != nil {
		return x.ClickTime
	}
	return 0
}

func (x *ReportAttributionReq) GetDownloadTime() int64 {
	if x != nil {
		return x.DownloadTime
	}
	return 0
}

func (x *ReportAttributionReq) GetInstallTime() int64 {
	if x != nil {
		return x.InstallTime
	}
	return 0
}

func (x *ReportAttributionReq) GetAttributionData() string {
	if x != nil {
		return x.AttributionData
	}
	return ""
}

func (x *ReportAttributionReq) GetReferrerEx() string {
	if x != nil {
		return x.ReferrerEx
	}
	return ""
}

func (x *ReportAttributionReq) GetAdDeviceInfo() *AdDeviceInfo {
	if x != nil {
		return x.AdDeviceInfo
	}
	return nil
}

// Source: com/bapis/bilibili/app/growth/v1/ReportAttributionResp.java
type ReportAttributionResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReportAttributionResp) Reset() {
	*x = ReportAttributionResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_growth_v1_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportAttributionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAttributionResp) ProtoMessage() {}

func (x *ReportAttributionResp) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_growth_v1_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAttributionResp.ProtoReflect.Descriptor instead.
func (*ReportAttributionResp) Descriptor() ([]byte, []int) {
	return file_bilibili_app_growth_v1_messages_proto_rawDescGZIP(), []int{2}
}

var File_bilibili_app_growth_v1_messages_proto protoreflect.FileDescriptor

var file_bilibili_app_growth_v1_messages_proto_rawDesc = []byte{
	0x0a, 0x25, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x67,
	0x72, 0x6f, 0x77, 0x74, 0x68, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x20, 0x63, 0x6f, 0x6d, 0x2e, 0x62, 0x61, 0x70,
	0x69, 0x73, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x2e,
	0x67, 0x72, 0x6f, 0x77, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x22, 0xac, 0x01, 0x0a, 0x0c, 0x41, 0x64,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x61,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6f, 0x61, 0x69, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x6f, 0x61, 0x69, 0x64, 0x4d, 0x64, 0x35, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6f, 0x61, 0x69, 0x64, 0x4d, 0x64, 0x35, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x6e, 0x64, 0x72,
	0x6f, 0x69, 0x64, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x6e, 0x64,
	0x72, 0x6f, 0x69, 0x64, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x6e, 0x64, 0x72, 0x6f, 0x69,
	0x64, 0x49, 0x64, 0x4d, 0x64, 0x35, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x6e,
	0x64, 0x72, 0x6f, 0x69, 0x64, 0x49, 0x64, 0x4d, 0x64, 0x35, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6d,
	0x65, 0x69, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6d, 0x65, 0x69, 0x12, 0x18,
	0x0a, 0x07, 0x69, 0x6d, 0x65, 0x69, 0x4d, 0x64, 0x35, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x69, 0x6d, 0x65, 0x69, 0x4d, 0x64, 0x35, 0x22, 0x98, 0x02, 0x0a, 0x14, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x22, 0x0a, 0x0c, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c,
	0x6c, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x72, 0x45, 0x78, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x72, 0x45, 0x78, 0x12,
	0x52, 0x0a, 0x0c, 0x61, 0x64, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x62, 0x61, 0x70, 0x69,
	0x73, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x67,
	0x72, 0x6f, 0x77, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x61, 0x64, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x22, 0x17, 0x0a, 0x15, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x41, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x42, 0x3d, 0x5a, 0x3b,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x6d, 0x74, 0x63,
	0x32, 0x33, 0x33, 0x2f, 0x62, 0x69, 0x6c, 0x69, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x61, 0x70,
	0x69, 0x2d, 0x67, 0x6f, 0x2f, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2f, 0x61, 0x70,
	0x70, 0x2f, 0x67, 0x72, 0x6f, 0x77, 0x74, 0x68, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_bilibili_app_growth_v1_messages_proto_rawDescOnce sync.Once
	file_bilibili_app_growth_v1_messages_proto_rawDescData = file_bilibili_app_growth_v1_messages_proto_rawDesc
)

func file_bilibili_app_growth_v1_messages_proto_rawDescGZIP() []byte {
	file_bilibili_app_growth_v1_messages_proto_rawDescOnce.Do(func() {
		file_bilibili_app_growth_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_bilibili_app_growth_v1_messages_proto_rawDescData)
	})
	return file_bilibili_app_growth_v1_messages_proto_rawDescData
}

var file_bilibili_app_growth_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bilibili_app_growth_v1_messages_proto_goTypes = []interface{}{
	(*AdDeviceInfo)(nil),          // 0: com.bapis.bilibili.app.growth.v1.AdDeviceInfo
	(*ReportAttributionReq)(nil),  // 1: com.bapis.bilibili.app.growth.v1.ReportAttributionReq
	(*ReportAttributionResp)(nil), // 2: com.bapis.bilibili.app.growth.v1.ReportAttributionResp
}
var file_bilibili_app_growth_v1_messages_proto_depIdxs = []int32{
	0, // 0: com.bapis.bilibili.app.growth.v1.ReportAttributionReq.adDeviceInfo:type_name -> com.bapis.bilibili.app.growth.v1.AdDeviceInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bilibili_app_growth_v1_messages_proto_init() }
func file_bilibili_app_growth_v1_messages_proto_init() {
	if File_bilibili_app_growth_v1_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bilibili_app_growth_v1_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdDeviceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_app_growth_v1_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportAttributionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_app_growth_v1_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportAttributionResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bilibili_app_growth_v1_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bilibili_app_growth_v1_messages_proto_goTypes,
		DependencyIndexes: file_bilibili_app_growth_v1_messages_proto_depIdxs,
		MessageInfos:      file_bilibili_app_growth_v1_messages_proto_msgTypes,
	}.Build()
	File_bilibili_app_growth_v1_messages_proto = out.File
	file_bilibili_app_growth_v1_messages_proto_rawDesc = nil
	file_bilibili_app_growth_v1_messages_proto_goTypes = nil
	file_bilibili_app_growth_v1_messages_proto_depIdxs = nil
}
