// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.broadcast.message.main;

import "bilibili/app/dynamic/v2/messages.proto";

enum LikeState {
  DEFAULT = 0;
  LIKE = 1;
  DISLIKE = 2;
}

// Source: com/bapis/bilibili/broadcast/message/main/Animate.java
message Animate {
  string icon = 1;
  string json = 2;
  string svg = 3;
  int32 loop = 4;
}

// Source: com/bapis/bilibili/broadcast/message/main/ArticleCard.java
message ArticleCard {
  string title = 1;
  string desc = 2;
  string cover = 3;
  string author = 4;
  int64 mid = 5;
  int32 view = 6;
  int32 like = 7;
  int32 reply = 8;
  string pubTime = 9;
  string badge = 10;
}

// Source: com/bapis/bilibili/broadcast/message/main/Bubble.java
message Bubble {
  repeated com.bapis.bilibili.app.dynamic.v2.Paragraph paragraphs = 1;
  repeated CardItem item = 2;
}

// Source: com/bapis/bilibili/broadcast/message/main/BubbleV2.java
message BubbleV2 {
  repeated com.bapis.bilibili.app.dynamic.v2.ModuleParagraph paragraphs = 1;
}

// Source: com/bapis/bilibili/broadcast/message/main/CardItem.java
message CardItem {
  string uri = 1;
  string param = 2;
  string goto = 3;
  oneof oneof_0 {
    ArticleCard article = 4;
    VideoCard av = 5;
  }
  enum CardItemCase {
    CARDITEM_NOT_SET = 0;
    ARTICLE = 4;
    AV = 5;
  }

}

// Source: com/bapis/bilibili/broadcast/message/main/ChatResult.java
message ChatResult {
  int32 code = 1;
  string sessionId = 2;
  repeated Bubble bubbles = 3;
  string rewriteWord = 4;
  string title = 5;
  string business = 6;
  int64 messageId = 7;
  LikeState likeState = 8;
  int64 likeNumber = 9;
}

// Source: com/bapis/bilibili/broadcast/message/main/ChatResultV2.java
message ChatResultV2 {
  int32 code = 1;
  string sessionId = 2;
  repeated BubbleV2 bubbles = 3;
  string rewriteWord = 4;
  string title = 5;
  string business = 6;
  int64 messageId = 7;
  LikeState likeState = 8;
  int64 likeNumber = 9;
  Reference reference = 10;
}

// Source: com/bapis/bilibili/broadcast/message/main/CommandDm.java
message CommandDm {
  int64 id = 1;
  int64 oid = 2;
  int64 mid = 3;
  int32 type = 4;
  string command = 5;
  string content = 6;
  int32 state = 7;
  int32 progress = 8;
  string ctime = 9;
  string mtime = 10;
  string extra = 11;
  string idstr = 12;
}

// Source: com/bapis/bilibili/broadcast/message/main/DanmakuElem.java
message DanmakuElem {
  int64 id = 1;
  int32 progress = 2;
  int32 mode = 3;
  int32 fontsize = 4;
  uint32 color = 5;
  string midHash = 6;
  string content = 7;
  int64 ctime = 8;
  string action = 9;
  int32 pool = 10;
  string idStr = 11;
  int32 weight = 12;
  int32 attr = 13;
  string animation = 14;
}

// Source: com/bapis/bilibili/broadcast/message/main/DanmukuEvent.java
message DanmukuEvent {
  repeated DanmakuElem elems = 1;
}

// Source: com/bapis/bilibili/broadcast/message/main/EventItem.java
message EventItem {
  int64 itemid = 1;
  string type = 2;
  int64 num = 3;
  string displaynum = 4;
  string webkey = 5;
  int64 dimension = 6;
}

// Source: com/bapis/bilibili/broadcast/message/main/HistoryReportEvent.java
message HistoryReportEvent {
  int64 aid = 1;
  int32 type = 2;
  int64 cid = 3;
  int64 epid = 4;
  int64 sid = 5;
  int32 subType = 6;
  int32 dt = 7;
  int64 realtime = 8;
  string source = 9;
  int64 progress = 10;
  int64 duration = 11;
  string platform = 12;
  string device = 13;
  int64 playTime = 14;
  string statistics = 15;
  int64 startTs = 16;
  int64 deviceTs = 17;
  string scene = 18;
}

// Source: com/bapis/bilibili/broadcast/message/main/NativePageEvent.java
message NativePageEvent {
  int64 pageid = 1;
  repeated EventItem items = 2;
}

// Source: com/bapis/bilibili/broadcast/message/main/ReasonStyle.java
message ReasonStyle {
  string text = 1;
  string textColor = 2;
  string textColorNight = 3;
  string bgColor = 4;
  string bgColorNight = 5;
  string borderColor = 6;
  string borderColorNight = 7;
  int32 bgStyle = 8;
}

// Source: com/bapis/bilibili/broadcast/message/main/RedDot.java
message RedDot {
  int32 type = 1;
  int32 number = 2;
}

// Source: com/bapis/bilibili/broadcast/message/main/Reference.java
message Reference {
  repeated com.bapis.bilibili.app.dynamic.v2.ModuleAdditional items = 1;
}

// Source: com/bapis/bilibili/broadcast/message/main/Stats.java
message Stats {
  int32 like = 1;
  int32 coin = 2;
  int32 fav = 3;
  int32 share = 4;
}

// Source: com/bapis/bilibili/broadcast/message/main/TopActivityReply.java
message TopActivityReply {
  TopOnline online = 1;
  string hash = 2;
}

// Source: com/bapis/bilibili/broadcast/message/main/TopOnline.java
message TopOnline {
  int32 type = 1;
  string icon = 2;
  string uri = 3;
  string uniqueId = 4;
  Animate animate = 5;
  RedDot redDot = 6;
  string name = 7;
  int64 interval = 8;
}

// Source: com/bapis/bilibili/broadcast/message/main/VideoCard.java
message VideoCard {
  string title = 1;
  string desc = 2;
  string cover = 3;
  string author = 4;
  string duration = 5;
  repeated ReasonStyle newRecTags = 6;
  repeated ReasonStyle badges = 7;
  string showCardDesc2 = 8;
  string viewContent = 9;
  int32 iconType = 10;
}

// Source: com/bapis/bilibili/broadcast/message/main/ViewPush.java
message ViewPush {
  Stats stats = 1;
  int64 aid = 2;
  int64 upTime = 3;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/broadcast/message/main";
