// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.vas.garb.service;

// Source: com/bapis/bilibili/vas/garb/service/SailingEquipMultiReply.java
message SailingEquipMultiReply {
  map<int64, UserSailing> data = 1;
}

// Source: com/bapis/bilibili/vas/garb/service/SailingEquipMultiReq.java
message SailingEquipMultiReq {
  repeated int64 mids = 1;
  int64 upMid = 2;
  int64 otype = 3;
  int64 oid = 4;
  int64 mid = 5;
  Device device = 6;
}

// Source: com/bapis/bilibili/vas/garb/service/UserCard.java
message UserCard {
  int64 id = 1;
  int64 itemId = 2;
  string name = 3;
  string cardUrl = 4;
  string bigCardUrl = 5;
  int64 cardType = 6;
  int64 expireTime = 7;
  string cardTypeName = 8;
  string jumpUrl = 9;
  UserFanShow fan = 10;
  string imageEnhance = 12;
  ImageGroup imageGroup = 13;
}

// Source: com/bapis/bilibili/vas/garb/service/UserCardMultiReply.java
message UserCardMultiReply {
  map<int64, UserCard> cards = 1;
}

// Source: com/bapis/bilibili/vas/garb/service/UserCardMultiReq.java
message UserCardMultiReq {
  repeated int64 mids = 1;
  Device device = 2;
  int64 mid = 3;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/vas/garb/service";
