// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.broadcast.live.universal_interact;

import "bilibili/live/app/room/v1/messages.proto";

enum CloseUserReason {
  CloseUserReason_Invalid = 0;
  CloseUserReason_DissolveChannel = 1;
  CloseUserReason_Remove = 2;
  CloseUserReason_Banned = 3;
  CloseUserReason_Normal = 4;
  CloseUserReason_BySelf = 5;
  CloseUserReason_ByOther = 6;
  UNRECOGNIZED = -1;
}

enum Gender {
  Gender_Woman = 0;
  Gender_Man = 1;
  UNRECOGNIZED = -1;
}

enum InteractScene {
  InteractSceneVoice1V1 = 0;
  InteractSceneVideoB2B = 1;
  UNRECOGNIZED = -1;
}

enum LayoutCellOpen {
  LayoutCellOpenInvalid = 0;
  LayoutCellOpenVisible = 1;
  LayoutCellOpenInvisible = 2;
  UNRECOGNIZED = -1;
}

enum PlayMode {
  play_mode_default = 0;
  play_mode_explicit = 1;
  UNRECOGNIZED = -1;
}

enum SubMode {
  sub_mode_none = 0;
  sub_mode_audio = 1;
  sub_mode_video = 2;
  sub_mode_all = 3;
  UNRECOGNIZED = -1;
}

enum UniversalInteractActionType {
  UniversalInteractActionTypeApply = 0;
  UniversalInteractActionTypeInvitation = 1;
  UNRECOGNIZED = -1;
}

enum UniversalInteractOperationType {
  UniversalInteractOperationInvalid = 0;
  UniversalInteractOperationAccept = 1;
  UniversalInteractOperationReject = 2;
  UniversalInteractOperationCancel = 3;
  UniversalInteractOperationTimeoutCancel = 4;
  UNRECOGNIZED = -1;
}

enum UniversalItemStatus {
  UniversalItemStatus_Unknown = 0;
  UniversalItemStatus_NotLiving = 1;
  UniversalItemStatus_NotAllow = 2;
  UniversalItemStatus_Connected = 3;
  UniversalItemStatus_Connected_NoPosition = 4;
  UniversalItemStatus_AllowInvitation = 5;
  UniversalItemStatus_Applying = 6;
  UniversalItemStatus_Inviting = 7;
  UniversalItemStatus_Connecting = 8;
  UNRECOGNIZED = -1;
}

// Source: com/bapis/bilibili/broadcast/live/universal_interact/InteractLayoutData.java
message InteractLayoutData {
  int32 width = 1;
  int32 height = 2;
  LayoutCell defaultCell = 3;
  repeated LayoutCell cells = 4;
  RtcResolution rtcResolution = 5;
  int32 bestAreaShowPos = 6;
  RtcResolution rtcResolutionSimulcast = 7;
}

// Source: com/bapis/bilibili/broadcast/live/universal_interact/InteractSceneConfiguration.java
message InteractSceneConfiguration {
  string interactMode = 1;
  string interactTemplate = 2;
  int64 interactMaxUsers = 3;
  enum InteractMode {
    InteractModeB2B = 0;
    InteractModeB2C = 1;
    UNRECOGNIZED = -1;
  }

}

// Source: com/bapis/bilibili/broadcast/live/universal_interact/LayoutCell.java
message LayoutCell {
  double x = 1;
  double y = 2;
  double width = 3;
  double height = 4;
  int32 zIndex = 5;
  int64 position = 6;
  LayoutCellOpen defaultOpen = 7;
  int32 mobileFontSize = 8;
  int32 mobileAvatarSize = 9;
  int32 pcWebFontSize = 10;
  int32 pcWebAvatarSize = 11;
  int32 canZoom = 12;
  uint32 videoIndex = 13;
  string positionText = 14;
}

// Source: com/bapis/bilibili/broadcast/live/universal_interact/PeerUserInfo.java
message PeerUserInfo {
  string uname = 1;
  string face = 2;
  int64 fansNum = 3;
  string areaName = 4;
  Gender gender = 5;
}

// Source: com/bapis/bilibili/broadcast/live/universal_interact/RtcResolution.java
message RtcResolution {
  int32 verticalWidth = 1;
  int32 verticalHeight = 2;
  int32 horizontalWidth = 3;
  int32 horizontalHeight = 4;
  int64 codeRateInit = 5;
  int64 codeRateMin = 6;
  int64 codeRateMax = 7;
  double scaleDownRatio = 8;
  int64 smallBitrateWeight = 9;
  int64 bigBitrateWeight = 10;
  int64 smallMaxFps = 11;
  int64 bigMaxFps = 12;
  bool smallBitrateActive = 13;
}

// Source: com/bapis/bilibili/broadcast/live/universal_interact/UniversalBizExtra.java
message UniversalBizExtra {
  InteractScene interactScene = 1;
  InteractSceneConfiguration interactSceneConfiguration = 2;
  string bizExtraData = 3;
  int64 source = 4;
}

// Source: com/bapis/bilibili/broadcast/live/universal_interact/UniversalInteractApplyEvent.java
message UniversalInteractApplyEvent {
  uint64 rtcChannelId = 1;
  int64 uid = 2;
  string bizLabel = 3;
  string traceId = 4;
  string bizSessionId = 5;
  int64 applyTimeout = 6;
  string title = 7;
  PeerUserInfo userInfo = 8;
  int64 peerUid = 9;
}

// Source: com/bapis/bilibili/broadcast/live/universal_interact/UniversalInteractEventGift.java
message UniversalInteractEventGift {
  int64 roomId = 1;
  int64 anchorUid = 2;
  com.bapis.bilibili.live.app.room.v1.UniversalInfoResp info = 3;
}

// Source: com/bapis/bilibili/broadcast/live/universal_interact/UniversalInteractInvitationEvent.java
message UniversalInteractInvitationEvent {
  uint64 rtcChannelId = 1;
  int64 uid = 2;
  string bizLabel = 3;
  string traceId = 4;
  string bizSessionId = 5;
  int64 initiator = 6;
  int64 invitationTimeout = 7;
  string title = 8;
  PeerUserInfo userInfo = 9;
  int64 peerUid = 10;
  int64 source = 11;
  string toastRich = 12;
  string customContent = 13;
  string customContentRich = 14;
  int64 targetRoomId = 15;
  int64 wantPosition = 16;
}

// Source: com/bapis/bilibili/broadcast/live/universal_interact/UniversalInteractJoinEvent.java
message UniversalInteractJoinEvent {
  uint64 config = 1;
  int64 bizExtra = 2;
  string traceId = 3;
  string streamControl = 4;
  string channelUsers = 5;
  int64 reconnect = 6;
}

// Source: com/bapis/bilibili/broadcast/live/universal_interact/UniversalInteractLeaveEvent.java
message UniversalInteractLeaveEvent {
  uint64 rtcChannelId = 1;
  int64 uid = 2;
  string bizLabel = 3;
  string traceId = 4;
  string bizSessionId = 5;
  CloseUserReason closeUserReason = 6;
  string toast = 7;
}

// Source: com/bapis/bilibili/broadcast/live/universal_interact/UniversalInteractOperationEvent.java
message UniversalInteractOperationEvent {
  uint64 rtcChannelId = 1;
  int64 operatorUid = 2;
  int64 targetUid = 3;
  string bizLabel = 4;
  string traceId = 5;
  string bizSessionId = 6;
  UniversalInteractOperationType operationType = 7;
  string title = 8;
  UniversalInteractActionType actionType = 9;
  string operationUname = 10;
  int64 peerUid = 11;
  UniversalItemStatus universalItemStatus = 12;
  int64 sourceUid = 13;
  int64 source = 14;
  int64 targetRoomId = 15;
  bool ownSide = 16;
}

// Source: com/bapis/bilibili/broadcast/live/universal_interact/UniversalInteractStreamControl.java
message UniversalInteractStreamControl {
  int64 audioControl = 1;
  UserStreamControlItem videoControl = 2;
  int32 pubSubControl = 3;
  enum MuteLocalMode {
    mute_mode_none = 0;
    mute_mode_packet = 1;
    mute_mode_capture = 2;
    UNRECOGNIZED = -1;
  }

  enum PubStatus {
    pub_status_none = 0;
    pub_status_audio = 1;
    pub_status_video = 2;
    pub_status_all = 3;
    UNRECOGNIZED = -1;
  }

}

// Source: com/bapis/bilibili/broadcast/live/universal_interact/UniversalInteractStreamControlEvent.java
message UniversalInteractStreamControlEvent {
  uint64 rtcChannelId = 1;
  int64 uid = 2;
  string bizSessionId = 3;
  UniversalInteractStreamControl streamControl = 4;
  int64 version = 5;
  string traceId = 6;
  repeated int64 channelUsers = 7;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/broadcast/live/universal_interact";
