// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.app.playurl.v1;

enum CodeType {
  NOCODE = 0;
  CODE264 = 1;
  CODE265 = 2;
}

enum ConfType {
  NoType = 0;
  FLIPCONF = 1;
  CASTCONF = 2;
  FEEDBACK = 3;
  SUBTITLE = 4;
  PLAYBACKRATE = 5;
  TIMEUP = 6;
  PLAYBACKMODE = 7;
  SCALEMODE = 8;
  BACKGROUNDPLAY = 9;
  LIKE = 10;
  DISLIKE = 11;
  COIN = 12;
  ELEC = 13;
  SHARE = 14;
  SCREENSHOT = 15;
  LOCKSCREEN = 16;
  RECOMMEND = 17;
  PLAYBACKSPEED = 18;
  DEFINITION = 19;
  SELECTIONS = 20;
  NEXT = 21;
  EDITDM = 22;
  SMALLWINDOW = 23;
  SHAKE = 24;
}

enum PlayErr {
  NoErr = 0;
  WithMultiDeviceLoginErr = 1;
}

enum VideoType {
  Unknown = 0;
  FLV = 1;
  DASH = 2;
  MP4 = 3;
}

// Source: com/bapis/bilibili/app/playurl/v1/ArcConf.java
message ArcConf {
  bool isSupport = 1;
}

// Source: com/bapis/bilibili/app/playurl/v1/Chronos.java
message Chronos {
  string md5 = 1;
  string file = 2;
}

// Source: com/bapis/bilibili/app/playurl/v1/CloudConf.java
message CloudConf {
  bool show = 1;
  ConfType confType = 2;
  FieldValue fieldValue = 3;
}

// Source: com/bapis/bilibili/app/playurl/v1/DashItem.java
message DashItem {
  uint32 id = 1;
  string baseUrl = 2;
  repeated string backupUrl = 3;
  uint32 bandwidth = 4;
  uint32 codecid = 5;
  string md5 = 6;
  uint64 size = 7;
}

// Source: com/bapis/bilibili/app/playurl/v1/DashVideo.java
message DashVideo {
  string baseUrl = 1;
  repeated string backupUrl = 2;
  uint32 bandwidth = 3;
  uint32 codecid = 4;
  string md5 = 5;
  uint64 size = 6;
  uint32 audioId = 7;
  bool noRexcode = 8;
}

// Source: com/bapis/bilibili/app/playurl/v1/Event.java
message Event {
  Shake shake = 1;
}

// Source: com/bapis/bilibili/app/playurl/v1/FieldValue.java
message FieldValue {
  oneof oneof_0 {
    bool switch = 1;
  }
  enum ValueCase {
    VALUE_NOT_SET = 0;
    SWITCH = 1;
  }

}

// Source: com/bapis/bilibili/app/playurl/v1/FormatDescription.java
message FormatDescription {
  uint32 quality = 1;
  string format = 2;
  string description = 3;
  string newDescription = 4;
  string displayDesc = 5;
  string superscript = 6;
}

// Source: com/bapis/bilibili/app/playurl/v1/PlayAbilityConf.java
message PlayAbilityConf {
  CloudConf backgroundPlayConf = 1;
  CloudConf flipConf = 2;
  CloudConf castConf = 3;
  CloudConf feedbackConf = 4;
  CloudConf subtitleConf = 5;
  CloudConf playbackRateConf = 6;
  CloudConf timeUpConf = 7;
  CloudConf playbackModeConf = 8;
  CloudConf scaleModeConf = 9;
  CloudConf likeConf = 10;
  CloudConf dislikeConf = 11;
  CloudConf coinConf = 12;
  CloudConf elecConf = 13;
  CloudConf shareConf = 14;
  CloudConf screenShotConf = 15;
  CloudConf lockScreenConf = 16;
  CloudConf recommendConf = 17;
  CloudConf playbackSpeedConf = 18;
  CloudConf definitionConf = 19;
  CloudConf selectionsConf = 20;
  CloudConf nextConf = 21;
  CloudConf editDmConf = 22;
  CloudConf smallWindowConf = 23;
  CloudConf shakeConf = 24;
}

// Source: com/bapis/bilibili/app/playurl/v1/PlayArcConf.java
message PlayArcConf {
  ArcConf backgroundPlayConf = 1;
  ArcConf flipConf = 2;
  ArcConf castConf = 3;
  ArcConf feedbackConf = 4;
  ArcConf subtitleConf = 5;
  ArcConf playbackRateConf = 6;
  ArcConf timeUpConf = 7;
  ArcConf playbackModeConf = 8;
  ArcConf scaleModeConf = 9;
  ArcConf likeConf = 10;
  ArcConf dislikeConf = 11;
  ArcConf coinConf = 12;
  ArcConf elecConf = 13;
  ArcConf shareConf = 14;
  ArcConf screenShotConf = 15;
  ArcConf lockScreenConf = 16;
  ArcConf recommendConf = 17;
  ArcConf playbackSpeedConf = 18;
  ArcConf definitionConf = 19;
  ArcConf selectionsConf = 20;
  ArcConf nextConf = 21;
  ArcConf editDmConf = 22;
  ArcConf smallWindowConf = 23;
  ArcConf shakeConf = 24;
}

// Source: com/bapis/bilibili/app/playurl/v1/PlayConfEditReply.java
message PlayConfEditReply {
}

// Source: com/bapis/bilibili/app/playurl/v1/PlayConfEditReq.java
message PlayConfEditReq {
  repeated PlayConfState playConf = 1;
}

// Source: com/bapis/bilibili/app/playurl/v1/PlayConfReply.java
message PlayConfReply {
  PlayAbilityConf playConf = 1;
}

// Source: com/bapis/bilibili/app/playurl/v1/PlayConfReq.java
message PlayConfReq {
}

// Source: com/bapis/bilibili/app/playurl/v1/PlayConfState.java
message PlayConfState {
  ConfType confType = 1;
  bool show = 2;
  FieldValue fieldValue = 3;
}

// Source: com/bapis/bilibili/app/playurl/v1/PlayURLReply.java
message PlayURLReply {
  uint32 quality = 1;
  string format = 2;
  uint64 timelength = 3;
  uint32 videoCodecid = 4;
  uint32 fnver = 5;
  uint32 fnval = 6;
  bool videoProject = 7;
  repeated ResponseUrl durl = 8;
  ResponseDash dash = 9;
  int32 noRexcode = 10;
  UpgradeLimit upgradeLimit = 11;
  repeated FormatDescription supportFormats = 12;
  VideoType type = 13;
}

// Source: com/bapis/bilibili/app/playurl/v1/PlayURLReq.java
message PlayURLReq {
  int64 aid = 1;
  int64 cid = 2;
  int64 qn = 3;
  int32 fnver = 4;
  int32 fnval = 5;
  uint32 download = 6;
  int32 forceHost = 7;
  bool fourk = 8;
  string spmid = 9;
  string fromSpmid = 10;
}

// Source: com/bapis/bilibili/app/playurl/v1/PlayViewReply.java
message PlayViewReply {
  VideoInfo videoInfo = 1;
  PlayAbilityConf playConf = 2;
  UpgradeLimit upgradeLimit = 3;
  Chronos chronos = 4;
  PlayArcConf playArc = 5;
  Event event = 6;
}

// Source: com/bapis/bilibili/app/playurl/v1/PlayViewReq.java
message PlayViewReq {
  int64 aid = 1;
  int64 cid = 2;
  int64 qn = 3;
  int32 fnver = 4;
  int32 fnval = 5;
  uint32 download = 6;
  int32 forceHost = 7;
  bool fourk = 8;
  string spmid = 9;
  string fromSpmid = 10;
  int32 teenagersMode = 11;
  CodeType preferCodecType = 12;
}

// Source: com/bapis/bilibili/app/playurl/v1/ProjectReply.java
message ProjectReply {
  PlayURLReply project = 1;
}

// Source: com/bapis/bilibili/app/playurl/v1/ProjectReq.java
message ProjectReq {
  int64 aid = 1;
  int64 cid = 2;
  int64 qn = 3;
  int32 fnver = 4;
  int32 fnval = 5;
  uint32 download = 6;
  int32 forceHost = 7;
  bool fourk = 8;
  string spmid = 9;
  string fromSpmid = 10;
  int32 protocol = 11;
  int32 deviceType = 12;
}

// Source: com/bapis/bilibili/app/playurl/v1/ResponseDash.java
message ResponseDash {
  repeated DashItem video = 1;
  repeated DashItem audio = 2;
}

// Source: com/bapis/bilibili/app/playurl/v1/ResponseUrl.java
message ResponseUrl {
  uint32 order = 1;
  uint64 length = 2;
  uint64 size = 3;
  string url = 4;
  repeated string backupUrl = 5;
  string md5 = 6;
}

// Source: com/bapis/bilibili/app/playurl/v1/SegmentVideo.java
message SegmentVideo {
  repeated ResponseUrl segment = 1;
}

// Source: com/bapis/bilibili/app/playurl/v1/Shake.java
message Shake {
  string file = 1;
}

// Source: com/bapis/bilibili/app/playurl/v1/Stream.java
message Stream {
  StreamInfo streamInfo = 1;
  oneof oneof_0 {
    DashVideo dashVideo = 2;
    SegmentVideo segmentVideo = 3;
  }
  enum ContentCase {
    CONTENT_NOT_SET = 0;
    DASH_VIDEO = 2;
    SEGMENT_VIDEO = 3;
  }

}

// Source: com/bapis/bilibili/app/playurl/v1/StreamInfo.java
message StreamInfo {
  uint32 quality = 1;
  string format = 2;
  string description = 3;
  PlayErr errCode = 4;
  StreamLimit limit = 5;
  bool needVip = 6;
  bool needLogin = 7;
  bool intact = 8;
  bool noRexcode = 9;
}

// Source: com/bapis/bilibili/app/playurl/v1/StreamLimit.java
message StreamLimit {
  string title = 1;
  string uri = 2;
  string msg = 3;
}

// Source: com/bapis/bilibili/app/playurl/v1/UpgradeButton.java
message UpgradeButton {
  string title = 1;
  string link = 2;
}

// Source: com/bapis/bilibili/app/playurl/v1/UpgradeLimit.java
message UpgradeLimit {
  int32 code = 1;
  string message_ = 2;
  string image = 3;
  UpgradeButton button = 4;
}

// Source: com/bapis/bilibili/app/playurl/v1/VideoInfo.java
message VideoInfo {
  uint32 quality = 1;
  string format = 2;
  uint64 timelength = 3;
  uint32 videoCodecid = 4;
  repeated Stream streamList = 5;
  repeated DashItem dashAudio = 6;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/app/playurl/v1";
