// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.dagw.component.avatar.common;

// Source: com/bapis/bilibili/dagw/component/avatar/common/BasicRenderSpec.java
message BasicRenderSpec {
  double opacity = 1;
}

// Source: com/bapis/bilibili/dagw/component/avatar/common/ColorConfig.java
message ColorConfig {
  bool isDarkModeAware = 1;
  ColorSpec day = 2;
  ColorSpec night = 3;
}

// Source: com/bapis/bilibili/dagw/component/avatar/common/ColorSpec.java
message ColorSpec {
  string argb = 1;
}

// Source: com/bapis/bilibili/dagw/component/avatar/common/LayerGeneralSpec.java
message LayerGeneralSpec {
  PositionSpec posSpec = 1;
  SizeSpec sizeSpec = 2;
  BasicRenderSpec renderSpec = 3;
}

// Source: com/bapis/bilibili/dagw/component/avatar/common/MaskProperty.java
message MaskProperty {
  LayerGeneralSpec generalSpec = 1;
  ResourceSource maskSrc = 2;
}

// Source: com/bapis/bilibili/dagw/component/avatar/common/NativeDrawRes.java
message NativeDrawRes {
  NativeDraw drawType = 1;
  FillMode fillMode = 2;
  ColorConfig colorConfig = 3;
  double edgeWeight = 4;
  enum FillMode {
    FILL_MODE_INVALID = 0;
    FILL_MODE_INTERNAL = 1;
    FILL_MODE_EDGE = 2;
  }

  enum NativeDraw {
    DRAW_INVALID = 0;
    DRAW_CIRCLE = 1;
    DRAW_RECTANGLE = 2;
  }

}

// Source: com/bapis/bilibili/dagw/component/avatar/common/PositionSpec.java
message PositionSpec {
  CoordinatePos coordinatePos = 1;
  double axisX = 2;
  double axisY = 3;
  enum CoordinatePos {
    INVALID_COORDINATE = 0;
    DEFAULT_COORDINATE = 1;
    CENTRAL_COORDINATE = 2;
  }

}

// Source: com/bapis/bilibili/dagw/component/avatar/common/RemoteRes.java
message RemoteRes {
  string url = 1;
  string bfsStyle = 2;
}

// Source: com/bapis/bilibili/dagw/component/avatar/common/ResourceSource.java
message ResourceSource {
  SourceType srcType = 1;
  LocalRes placeholder = 2;
  oneof oneof_0 {
    RemoteRes remote = 3;
    LocalRes local = 4;
    NativeDrawRes draw = 5;
  }
  enum LocalRes {
    LOCAL_RES_INVALID = 0;
    LOCAL_RES_ICON_VIP = 1;
    LOCAL_RES_ICON_SMALL_VIP = 2;
    LOCAL_RES_ICON_PERSONAL_VERIFY = 3;
    LOCAL_RES_ICON_ENTERPRISE_VERIFY = 4;
    LOCAL_RES_ICON_NFT_MAINLAND = 5;
    LOCAL_RES_DEFAULT_AVATAR = 6;
    LOCAL_RES_FOLLOW_ICON = 7;
    LOCAL_RES_FOLLOW_ACTION = 8;
  }

  enum ResCase {
    RES_NOT_SET = 0;
    REMOTE = 3;
    LOCAL = 4;
    DRAW = 5;
  }

  enum SourceType {
    SRC_TYPE_INVALID = 0;
    SRC_TYPE_URL = 1;
    SRC_TYPE_LOCAL = 2;
    SRC_TYPE_DRAW = 3;
  }

}

// Source: com/bapis/bilibili/dagw/component/avatar/common/SizeSpec.java
message SizeSpec {
  double width = 1;
  double height = 2;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/dagw/component/avatar/common";
