// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.app.distribution.setting.other;

// Source: com/bapis/bilibili/app/distribution/setting/other/OtherSettingsConfig.java
message OtherSettingsConfig {
  bytes watermarktype = 1;
  bytes webimagequalitytype = 2;
  bytes enablereadpasteboard = 3;
  bytes pasteautojump = 4;
  bytes miniscreenplaywhenback = 5;
  bytes enableresumeplaying = 6;
  bytes enablewifiautoupdate = 7;
  bytes enableguidescreenshotshare = 8;
  enum WatermarkType {
    WT_UNKNOW = 0;
    None = 1;
    Center = 2;
    BottomRight = 3;
    UNRECOGNIZED = -1;
  }

  enum WebImageQualityType {
    High = 0;
    Low = 1;
    Auto = 2;
    UNRECOGNIZED = -1;
  }

}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/app/distribution/setting/other";
