// Reconstructed from gRPC service descriptors.
syntax = "proto3";

package bilibili.app.resource.v1;

import "bilibili/app/resource/v1/messages.proto";

service LegacyResource {
  rpc Download(.com.bapis.bilibili.app.resource.v1.DownloadReq) returns (.com.bapis.bilibili.app.resource.v1.DownloadReply);
}

service Module {
  rpc List(.com.bapis.bilibili.app.resource.v1.ListReq) returns (.com.bapis.bilibili.app.resource.v1.ListReply);
}

option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/app/resource/v1";
