// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: bilibili/polymer/chronos/v1.proto

package chronos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ChronosService_ObtainChronosPackage_FullMethodName   = "/bilibili.polymer.chronos.v1.ChronosService/ObtainChronosPackage"
	ChronosService_ObtainChronosPackageV2_FullMethodName = "/bilibili.polymer.chronos.v1.ChronosService/ObtainChronosPackageV2"
)

// ChronosServiceClient is the client API for ChronosService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChronosServiceClient interface {
	ObtainChronosPackage(ctx context.Context, in *ObtainChronosPackageReq, opts ...grpc.CallOption) (*ObtainChronosPackageRsp, error)
	ObtainChronosPackageV2(ctx context.Context, in *ObtainChronosPackageV2Req, opts ...grpc.CallOption) (*ObtainChronosPackageRsp, error)
}

type chronosServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChronosServiceClient(cc grpc.ClientConnInterface) ChronosServiceClient {
	return &chronosServiceClient{cc}
}

func (c *chronosServiceClient) ObtainChronosPackage(ctx context.Context, in *ObtainChronosPackageReq, opts ...grpc.CallOption) (*ObtainChronosPackageRsp, error) {
	out := new(ObtainChronosPackageRsp)
	err := c.cc.Invoke(ctx, ChronosService_ObtainChronosPackage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chronosServiceClient) ObtainChronosPackageV2(ctx context.Context, in *ObtainChronosPackageV2Req, opts ...grpc.CallOption) (*ObtainChronosPackageRsp, error) {
	out := new(ObtainChronosPackageRsp)
	err := c.cc.Invoke(ctx, ChronosService_ObtainChronosPackageV2_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChronosServiceServer is the server API for ChronosService service.
// All implementations must embed UnimplementedChronosServiceServer
// for forward compatibility
type ChronosServiceServer interface {
	ObtainChronosPackage(context.Context, *ObtainChronosPackageReq) (*ObtainChronosPackageRsp, error)
	ObtainChronosPackageV2(context.Context, *ObtainChronosPackageV2Req) (*ObtainChronosPackageRsp, error)
	mustEmbedUnimplementedChronosServiceServer()
}

// UnimplementedChronosServiceServer must be embedded to have forward compatible implementations.
type UnimplementedChronosServiceServer struct {
}

func (UnimplementedChronosServiceServer) ObtainChronosPackage(context.Context, *ObtainChronosPackageReq) (*ObtainChronosPackageRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObtainChronosPackage not implemented")
}
func (UnimplementedChronosServiceServer) ObtainChronosPackageV2(context.Context, *ObtainChronosPackageV2Req) (*ObtainChronosPackageRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObtainChronosPackageV2 not implemented")
}
func (UnimplementedChronosServiceServer) mustEmbedUnimplementedChronosServiceServer() {}

// UnsafeChronosServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChronosServiceServer will
// result in compilation errors.
type UnsafeChronosServiceServer interface {
	mustEmbedUnimplementedChronosServiceServer()
}

func RegisterChronosServiceServer(s grpc.ServiceRegistrar, srv ChronosServiceServer) {
	s.RegisterService(&ChronosService_ServiceDesc, srv)
}

func _ChronosService_ObtainChronosPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObtainChronosPackageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronosServiceServer).ObtainChronosPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChronosService_ObtainChronosPackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronosServiceServer).ObtainChronosPackage(ctx, req.(*ObtainChronosPackageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChronosService_ObtainChronosPackageV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObtainChronosPackageV2Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronosServiceServer).ObtainChronosPackageV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChronosService_ObtainChronosPackageV2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronosServiceServer).ObtainChronosPackageV2(ctx, req.(*ObtainChronosPackageV2Req))
	}
	return interceptor(ctx, in, info, handler)
}

// ChronosService_ServiceDesc is the grpc.ServiceDesc for ChronosService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChronosService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bilibili.polymer.chronos.v1.ChronosService",
	HandlerType: (*ChronosServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ObtainChronosPackage",
			Handler:    _ChronosService_ObtainChronosPackage_Handler,
		},
		{
			MethodName: "ObtainChronosPackageV2",
			Handler:    _ChronosService_ObtainChronosPackageV2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bilibili/polymer/chronos/v1.proto",
}
