// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.app.distribution.setting.dynamic;

import "bilibili/app/distribution/messages.proto";

// Source: com/bapis/bilibili/app/distribution/setting/dynamic/DynamicAutoPlay.java
message DynamicAutoPlay {
  com.bapis.bilibili.app.distribution.Int64Value value = 1;
}

// Source: com/bapis/bilibili/app/distribution/setting/dynamic/DynamicDeviceConfig.java
message DynamicDeviceConfig {
  DynamicAutoPlay autoPlay = 1;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/app/distribution/setting/dynamic";
