// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: bilibili/broadcast/v1.proto

package broadcast

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BroadcastRoom_Enter_FullMethodName = "/bilibili.broadcast.v1.BroadcastRoom/Enter"
)

// BroadcastRoomClient is the client API for BroadcastRoom service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BroadcastRoomClient interface {
	Enter(ctx context.Context, opts ...grpc.CallOption) (BroadcastRoom_EnterClient, error)
}

type broadcastRoomClient struct {
	cc grpc.ClientConnInterface
}

func NewBroadcastRoomClient(cc grpc.ClientConnInterface) BroadcastRoomClient {
	return &broadcastRoomClient{cc}
}

func (c *broadcastRoomClient) Enter(ctx context.Context, opts ...grpc.CallOption) (BroadcastRoom_EnterClient, error) {
	stream, err := c.cc.NewStream(ctx, &BroadcastRoom_ServiceDesc.Streams[0], BroadcastRoom_Enter_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &broadcastRoomEnterClient{stream}
	return x, nil
}

type BroadcastRoom_EnterClient interface {
	Send(*RoomReq) error
	Recv() (*RoomResp, error)
	grpc.ClientStream
}

type broadcastRoomEnterClient struct {
	grpc.ClientStream
}

func (x *broadcastRoomEnterClient) Send(m *RoomReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *broadcastRoomEnterClient) Recv() (*RoomResp, error) {
	m := new(RoomResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BroadcastRoomServer is the server API for BroadcastRoom service.
// All implementations must embed UnimplementedBroadcastRoomServer
// for forward compatibility
type BroadcastRoomServer interface {
	Enter(BroadcastRoom_EnterServer) error
	mustEmbedUnimplementedBroadcastRoomServer()
}

// UnimplementedBroadcastRoomServer must be embedded to have forward compatible implementations.
type UnimplementedBroadcastRoomServer struct {
}

func (UnimplementedBroadcastRoomServer) Enter(BroadcastRoom_EnterServer) error {
	return status.Errorf(codes.Unimplemented, "method Enter not implemented")
}
func (UnimplementedBroadcastRoomServer) mustEmbedUnimplementedBroadcastRoomServer() {}

// UnsafeBroadcastRoomServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BroadcastRoomServer will
// result in compilation errors.
type UnsafeBroadcastRoomServer interface {
	mustEmbedUnimplementedBroadcastRoomServer()
}

func RegisterBroadcastRoomServer(s grpc.ServiceRegistrar, srv BroadcastRoomServer) {
	s.RegisterService(&BroadcastRoom_ServiceDesc, srv)
}

func _BroadcastRoom_Enter_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BroadcastRoomServer).Enter(&broadcastRoomEnterServer{stream})
}

type BroadcastRoom_EnterServer interface {
	Send(*RoomResp) error
	Recv() (*RoomReq, error)
	grpc.ServerStream
}

type broadcastRoomEnterServer struct {
	grpc.ServerStream
}

func (x *broadcastRoomEnterServer) Send(m *RoomResp) error {
	return x.ServerStream.SendMsg(m)
}

func (x *broadcastRoomEnterServer) Recv() (*RoomReq, error) {
	m := new(RoomReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BroadcastRoom_ServiceDesc is the grpc.ServiceDesc for BroadcastRoom service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BroadcastRoom_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bilibili.broadcast.v1.BroadcastRoom",
	HandlerType: (*BroadcastRoomServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Enter",
			Handler:       _BroadcastRoom_Enter_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "bilibili/broadcast/v1.proto",
}

const (
	Laser_WatchLogUploadEvent_FullMethodName = "/bilibili.broadcast.v1.Laser/WatchLogUploadEvent"
)

// LaserClient is the client API for Laser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LaserClient interface {
	WatchLogUploadEvent(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Laser_WatchLogUploadEventClient, error)
}

type laserClient struct {
	cc grpc.ClientConnInterface
}

func NewLaserClient(cc grpc.ClientConnInterface) LaserClient {
	return &laserClient{cc}
}

func (c *laserClient) WatchLogUploadEvent(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Laser_WatchLogUploadEventClient, error) {
	stream, err := c.cc.NewStream(ctx, &Laser_ServiceDesc.Streams[0], Laser_WatchLogUploadEvent_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &laserWatchLogUploadEventClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Laser_WatchLogUploadEventClient interface {
	Recv() (*LaserLogUploadResp, error)
	grpc.ClientStream
}

type laserWatchLogUploadEventClient struct {
	grpc.ClientStream
}

func (x *laserWatchLogUploadEventClient) Recv() (*LaserLogUploadResp, error) {
	m := new(LaserLogUploadResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LaserServer is the server API for Laser service.
// All implementations must embed UnimplementedLaserServer
// for forward compatibility
type LaserServer interface {
	WatchLogUploadEvent(*emptypb.Empty, Laser_WatchLogUploadEventServer) error
	mustEmbedUnimplementedLaserServer()
}

// UnimplementedLaserServer must be embedded to have forward compatible implementations.
type UnimplementedLaserServer struct {
}

func (UnimplementedLaserServer) WatchLogUploadEvent(*emptypb.Empty, Laser_WatchLogUploadEventServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchLogUploadEvent not implemented")
}
func (UnimplementedLaserServer) mustEmbedUnimplementedLaserServer() {}

// UnsafeLaserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LaserServer will
// result in compilation errors.
type UnsafeLaserServer interface {
	mustEmbedUnimplementedLaserServer()
}

func RegisterLaserServer(s grpc.ServiceRegistrar, srv LaserServer) {
	s.RegisterService(&Laser_ServiceDesc, srv)
}

func _Laser_WatchLogUploadEvent_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LaserServer).WatchLogUploadEvent(m, &laserWatchLogUploadEventServer{stream})
}

type Laser_WatchLogUploadEventServer interface {
	Send(*LaserLogUploadResp) error
	grpc.ServerStream
}

type laserWatchLogUploadEventServer struct {
	grpc.ServerStream
}

func (x *laserWatchLogUploadEventServer) Send(m *LaserLogUploadResp) error {
	return x.ServerStream.SendMsg(m)
}

// Laser_ServiceDesc is the grpc.ServiceDesc for Laser service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Laser_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bilibili.broadcast.v1.Laser",
	HandlerType: (*LaserServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchLogUploadEvent",
			Handler:       _Laser_WatchLogUploadEvent_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "bilibili/broadcast/v1.proto",
}

const (
	ModManager_WatchResource_FullMethodName = "/bilibili.broadcast.v1.ModManager/WatchResource"
)

// ModManagerClient is the client API for ModManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModManagerClient interface {
	WatchResource(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (ModManager_WatchResourceClient, error)
}

type modManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewModManagerClient(cc grpc.ClientConnInterface) ModManagerClient {
	return &modManagerClient{cc}
}

func (c *modManagerClient) WatchResource(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (ModManager_WatchResourceClient, error) {
	stream, err := c.cc.NewStream(ctx, &ModManager_ServiceDesc.Streams[0], ModManager_WatchResource_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &modManagerWatchResourceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ModManager_WatchResourceClient interface {
	Recv() (*ModResourceResp, error)
	grpc.ClientStream
}

type modManagerWatchResourceClient struct {
	grpc.ClientStream
}

func (x *modManagerWatchResourceClient) Recv() (*ModResourceResp, error) {
	m := new(ModResourceResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ModManagerServer is the server API for ModManager service.
// All implementations must embed UnimplementedModManagerServer
// for forward compatibility
type ModManagerServer interface {
	WatchResource(*emptypb.Empty, ModManager_WatchResourceServer) error
	mustEmbedUnimplementedModManagerServer()
}

// UnimplementedModManagerServer must be embedded to have forward compatible implementations.
type UnimplementedModManagerServer struct {
}

func (UnimplementedModManagerServer) WatchResource(*emptypb.Empty, ModManager_WatchResourceServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchResource not implemented")
}
func (UnimplementedModManagerServer) mustEmbedUnimplementedModManagerServer() {}

// UnsafeModManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModManagerServer will
// result in compilation errors.
type UnsafeModManagerServer interface {
	mustEmbedUnimplementedModManagerServer()
}

func RegisterModManagerServer(s grpc.ServiceRegistrar, srv ModManagerServer) {
	s.RegisterService(&ModManager_ServiceDesc, srv)
}

func _ModManager_WatchResource_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ModManagerServer).WatchResource(m, &modManagerWatchResourceServer{stream})
}

type ModManager_WatchResourceServer interface {
	Send(*ModResourceResp) error
	grpc.ServerStream
}

type modManagerWatchResourceServer struct {
	grpc.ServerStream
}

func (x *modManagerWatchResourceServer) Send(m *ModResourceResp) error {
	return x.ServerStream.SendMsg(m)
}

// ModManager_ServiceDesc is the grpc.ServiceDesc for ModManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bilibili.broadcast.v1.ModManager",
	HandlerType: (*ModManagerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchResource",
			Handler:       _ModManager_WatchResource_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "bilibili/broadcast/v1.proto",
}

const (
	Push_WatchMessage_FullMethodName = "/bilibili.broadcast.v1.Push/WatchMessage"
)

// PushClient is the client API for Push service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PushClient interface {
	WatchMessage(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Push_WatchMessageClient, error)
}

type pushClient struct {
	cc grpc.ClientConnInterface
}

func NewPushClient(cc grpc.ClientConnInterface) PushClient {
	return &pushClient{cc}
}

func (c *pushClient) WatchMessage(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Push_WatchMessageClient, error) {
	stream, err := c.cc.NewStream(ctx, &Push_ServiceDesc.Streams[0], Push_WatchMessage_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &pushWatchMessageClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Push_WatchMessageClient interface {
	Recv() (*PushMessageResp, error)
	grpc.ClientStream
}

type pushWatchMessageClient struct {
	grpc.ClientStream
}

func (x *pushWatchMessageClient) Recv() (*PushMessageResp, error) {
	m := new(PushMessageResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PushServer is the server API for Push service.
// All implementations must embed UnimplementedPushServer
// for forward compatibility
type PushServer interface {
	WatchMessage(*emptypb.Empty, Push_WatchMessageServer) error
	mustEmbedUnimplementedPushServer()
}

// UnimplementedPushServer must be embedded to have forward compatible implementations.
type UnimplementedPushServer struct {
}

func (UnimplementedPushServer) WatchMessage(*emptypb.Empty, Push_WatchMessageServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchMessage not implemented")
}
func (UnimplementedPushServer) mustEmbedUnimplementedPushServer() {}

// UnsafePushServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PushServer will
// result in compilation errors.
type UnsafePushServer interface {
	mustEmbedUnimplementedPushServer()
}

func RegisterPushServer(s grpc.ServiceRegistrar, srv PushServer) {
	s.RegisterService(&Push_ServiceDesc, srv)
}

func _Push_WatchMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PushServer).WatchMessage(m, &pushWatchMessageServer{stream})
}

type Push_WatchMessageServer interface {
	Send(*PushMessageResp) error
	grpc.ServerStream
}

type pushWatchMessageServer struct {
	grpc.ServerStream
}

func (x *pushWatchMessageServer) Send(m *PushMessageResp) error {
	return x.ServerStream.SendMsg(m)
}

// Push_ServiceDesc is the grpc.ServiceDesc for Push service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Push_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bilibili.broadcast.v1.Push",
	HandlerType: (*PushServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchMessage",
			Handler:       _Push_WatchMessage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "bilibili/broadcast/v1.proto",
}

const (
	Test2_Test_FullMethodName = "/bilibili.broadcast.v1.Test2/Test"
)

// Test2Client is the client API for Test2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Test2Client interface {
	Test(ctx context.Context, opts ...grpc.CallOption) (Test2_TestClient, error)
}

type test2Client struct {
	cc grpc.ClientConnInterface
}

func NewTest2Client(cc grpc.ClientConnInterface) Test2Client {
	return &test2Client{cc}
}

func (c *test2Client) Test(ctx context.Context, opts ...grpc.CallOption) (Test2_TestClient, error) {
	stream, err := c.cc.NewStream(ctx, &Test2_ServiceDesc.Streams[0], Test2_Test_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &test2TestClient{stream}
	return x, nil
}

type Test2_TestClient interface {
	Send(*AddParams) error
	CloseAndRecv() (*emptypb.Empty, error)
	grpc.ClientStream
}

type test2TestClient struct {
	grpc.ClientStream
}

func (x *test2TestClient) Send(m *AddParams) error {
	return x.ClientStream.SendMsg(m)
}

func (x *test2TestClient) CloseAndRecv() (*emptypb.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(emptypb.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Test2Server is the server API for Test2 service.
// All implementations must embed UnimplementedTest2Server
// for forward compatibility
type Test2Server interface {
	Test(Test2_TestServer) error
	mustEmbedUnimplementedTest2Server()
}

// UnimplementedTest2Server must be embedded to have forward compatible implementations.
type UnimplementedTest2Server struct {
}

func (UnimplementedTest2Server) Test(Test2_TestServer) error {
	return status.Errorf(codes.Unimplemented, "method Test not implemented")
}
func (UnimplementedTest2Server) mustEmbedUnimplementedTest2Server() {}

// UnsafeTest2Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Test2Server will
// result in compilation errors.
type UnsafeTest2Server interface {
	mustEmbedUnimplementedTest2Server()
}

func RegisterTest2Server(s grpc.ServiceRegistrar, srv Test2Server) {
	s.RegisterService(&Test2_ServiceDesc, srv)
}

func _Test2_Test_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(Test2Server).Test(&test2TestServer{stream})
}

type Test2_TestServer interface {
	SendAndClose(*emptypb.Empty) error
	Recv() (*AddParams, error)
	grpc.ServerStream
}

type test2TestServer struct {
	grpc.ServerStream
}

func (x *test2TestServer) SendAndClose(m *emptypb.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *test2TestServer) Recv() (*AddParams, error) {
	m := new(AddParams)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Test2_ServiceDesc is the grpc.ServiceDesc for Test2 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Test2_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bilibili.broadcast.v1.Test2",
	HandlerType: (*Test2Server)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Test",
			Handler:       _Test2_Test_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "bilibili/broadcast/v1.proto",
}
