// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: bilibili/im/customer/interfaces.proto

package customer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CustomerInterface_CustomerPreEvaluate_FullMethodName          = "/bilibili.im.customer.interfaces.CustomerInterface/CustomerPreEvaluate"
	CustomerInterface_CustomerUpdateAck_FullMethodName            = "/bilibili.im.customer.interfaces.CustomerInterface/CustomerUpdateAck"
	CustomerInterface_CustomerWindowOptions_FullMethodName        = "/bilibili.im.customer.interfaces.CustomerInterface/CustomerWindowOptions"
	CustomerInterface_FinishParagraphsRender_FullMethodName       = "/bilibili.im.customer.interfaces.CustomerInterface/FinishParagraphsRender"
	CustomerInterface_GetCustomerSessDetail_FullMethodName        = "/bilibili.im.customer.interfaces.CustomerInterface/GetCustomerSessDetail"
	CustomerInterface_GetCustomerSessions_FullMethodName          = "/bilibili.im.customer.interfaces.CustomerInterface/GetCustomerSessions"
	CustomerInterface_GetNewCustomerSessions_FullMethodName       = "/bilibili.im.customer.interfaces.CustomerInterface/GetNewCustomerSessions"
	CustomerInterface_GetShopCfg_FullMethodName                   = "/bilibili.im.customer.interfaces.CustomerInterface/GetShopCfg"
	CustomerInterface_GetShopInfo_FullMethodName                  = "/bilibili.im.customer.interfaces.CustomerInterface/GetShopInfo"
	CustomerInterface_GetUserSettings_FullMethodName              = "/bilibili.im.customer.interfaces.CustomerInterface/GetUserSettings"
	CustomerInterface_HeartBeat_FullMethodName                    = "/bilibili.im.customer.interfaces.CustomerInterface/HeartBeat"
	CustomerInterface_OutCustomerQueue_FullMethodName             = "/bilibili.im.customer.interfaces.CustomerInterface/OutCustomerQueue"
	CustomerInterface_PopResultUpdate_FullMethodName              = "/bilibili.im.customer.interfaces.CustomerInterface/PopResultUpdate"
	CustomerInterface_RemoveSession_FullMethodName                = "/bilibili.im.customer.interfaces.CustomerInterface/RemoveSession"
	CustomerInterface_SendCustomerMsg_FullMethodName              = "/bilibili.im.customer.interfaces.CustomerInterface/SendCustomerMsg"
	CustomerInterface_SetTop_FullMethodName                       = "/bilibili.im.customer.interfaces.CustomerInterface/SetTop"
	CustomerInterface_SetUserSettings_FullMethodName              = "/bilibili.im.customer.interfaces.CustomerInterface/SetUserSettings"
	CustomerInterface_SyncFetchCustomerSessionMsgs_FullMethodName = "/bilibili.im.customer.interfaces.CustomerInterface/SyncFetchCustomerSessionMsgs"
)

// CustomerInterfaceClient is the client API for CustomerInterface service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CustomerInterfaceClient interface {
	CustomerPreEvaluate(ctx context.Context, in *PreEvaluateReq, opts ...grpc.CallOption) (*PreEvaluateRsp, error)
	CustomerUpdateAck(ctx context.Context, in *UpdateAckReq, opts ...grpc.CallOption) (*Empty, error)
	CustomerWindowOptions(ctx context.Context, in *WindowOptionsReq, opts ...grpc.CallOption) (*WindowOptionsRsp, error)
	FinishParagraphsRender(ctx context.Context, in *FinishParagraphsRenderReq, opts ...grpc.CallOption) (*FinishParagraphsRenderRsp, error)
	GetCustomerSessDetail(ctx context.Context, in *GetSessDetailReq, opts ...grpc.CallOption) (*GetSessDetailRsp, error)
	GetCustomerSessions(ctx context.Context, in *GetSessionsReq, opts ...grpc.CallOption) (*SessionsRsp, error)
	GetNewCustomerSessions(ctx context.Context, in *GetNewSessionsReq, opts ...grpc.CallOption) (*SessionsRsp, error)
	GetShopCfg(ctx context.Context, in *ShopCfgReq, opts ...grpc.CallOption) (*ShopCfgRsp, error)
	GetShopInfo(ctx context.Context, in *ShopInfoReq, opts ...grpc.CallOption) (*ShopInfoRsp, error)
	GetUserSettings(ctx context.Context, in *GetUserSettingsReq, opts ...grpc.CallOption) (*GetUserSettingsRsp, error)
	HeartBeat(ctx context.Context, in *SendHeartBeatReq, opts ...grpc.CallOption) (*Empty, error)
	OutCustomerQueue(ctx context.Context, in *OutCustomerQueueReq, opts ...grpc.CallOption) (*Empty, error)
	PopResultUpdate(ctx context.Context, in *PopResultUpdateReq, opts ...grpc.CallOption) (*PopResultUpdateRsp, error)
	RemoveSession(ctx context.Context, in *RemoveSessionReq, opts ...grpc.CallOption) (*Empty, error)
	SendCustomerMsg(ctx context.Context, in *SendMsgReq, opts ...grpc.CallOption) (*SendMsgRsp, error)
	SetTop(ctx context.Context, in *SetTopReq, opts ...grpc.CallOption) (*Empty, error)
	SetUserSettings(ctx context.Context, in *SetUserSettingsReq, opts ...grpc.CallOption) (*SetUserSettingsRsp, error)
	SyncFetchCustomerSessionMsgs(ctx context.Context, in *SessionMsgReq, opts ...grpc.CallOption) (*SessionMsgRsp, error)
}

type customerInterfaceClient struct {
	cc grpc.ClientConnInterface
}

func NewCustomerInterfaceClient(cc grpc.ClientConnInterface) CustomerInterfaceClient {
	return &customerInterfaceClient{cc}
}

func (c *customerInterfaceClient) CustomerPreEvaluate(ctx context.Context, in *PreEvaluateReq, opts ...grpc.CallOption) (*PreEvaluateRsp, error) {
	out := new(PreEvaluateRsp)
	err := c.cc.Invoke(ctx, CustomerInterface_CustomerPreEvaluate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerInterfaceClient) CustomerUpdateAck(ctx context.Context, in *UpdateAckReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, CustomerInterface_CustomerUpdateAck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerInterfaceClient) CustomerWindowOptions(ctx context.Context, in *WindowOptionsReq, opts ...grpc.CallOption) (*WindowOptionsRsp, error) {
	out := new(WindowOptionsRsp)
	err := c.cc.Invoke(ctx, CustomerInterface_CustomerWindowOptions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerInterfaceClient) FinishParagraphsRender(ctx context.Context, in *FinishParagraphsRenderReq, opts ...grpc.CallOption) (*FinishParagraphsRenderRsp, error) {
	out := new(FinishParagraphsRenderRsp)
	err := c.cc.Invoke(ctx, CustomerInterface_FinishParagraphsRender_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerInterfaceClient) GetCustomerSessDetail(ctx context.Context, in *GetSessDetailReq, opts ...grpc.CallOption) (*GetSessDetailRsp, error) {
	out := new(GetSessDetailRsp)
	err := c.cc.Invoke(ctx, CustomerInterface_GetCustomerSessDetail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerInterfaceClient) GetCustomerSessions(ctx context.Context, in *GetSessionsReq, opts ...grpc.CallOption) (*SessionsRsp, error) {
	out := new(SessionsRsp)
	err := c.cc.Invoke(ctx, CustomerInterface_GetCustomerSessions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerInterfaceClient) GetNewCustomerSessions(ctx context.Context, in *GetNewSessionsReq, opts ...grpc.CallOption) (*SessionsRsp, error) {
	out := new(SessionsRsp)
	err := c.cc.Invoke(ctx, CustomerInterface_GetNewCustomerSessions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerInterfaceClient) GetShopCfg(ctx context.Context, in *ShopCfgReq, opts ...grpc.CallOption) (*ShopCfgRsp, error) {
	out := new(ShopCfgRsp)
	err := c.cc.Invoke(ctx, CustomerInterface_GetShopCfg_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerInterfaceClient) GetShopInfo(ctx context.Context, in *ShopInfoReq, opts ...grpc.CallOption) (*ShopInfoRsp, error) {
	out := new(ShopInfoRsp)
	err := c.cc.Invoke(ctx, CustomerInterface_GetShopInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerInterfaceClient) GetUserSettings(ctx context.Context, in *GetUserSettingsReq, opts ...grpc.CallOption) (*GetUserSettingsRsp, error) {
	out := new(GetUserSettingsRsp)
	err := c.cc.Invoke(ctx, CustomerInterface_GetUserSettings_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerInterfaceClient) HeartBeat(ctx context.Context, in *SendHeartBeatReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, CustomerInterface_HeartBeat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerInterfaceClient) OutCustomerQueue(ctx context.Context, in *OutCustomerQueueReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, CustomerInterface_OutCustomerQueue_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerInterfaceClient) PopResultUpdate(ctx context.Context, in *PopResultUpdateReq, opts ...grpc.CallOption) (*PopResultUpdateRsp, error) {
	out := new(PopResultUpdateRsp)
	err := c.cc.Invoke(ctx, CustomerInterface_PopResultUpdate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerInterfaceClient) RemoveSession(ctx context.Context, in *RemoveSessionReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, CustomerInterface_RemoveSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerInterfaceClient) SendCustomerMsg(ctx context.Context, in *SendMsgReq, opts ...grpc.CallOption) (*SendMsgRsp, error) {
	out := new(SendMsgRsp)
	err := c.cc.Invoke(ctx, CustomerInterface_SendCustomerMsg_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerInterfaceClient) SetTop(ctx context.Context, in *SetTopReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, CustomerInterface_SetTop_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerInterfaceClient) SetUserSettings(ctx context.Context, in *SetUserSettingsReq, opts ...grpc.CallOption) (*SetUserSettingsRsp, error) {
	out := new(SetUserSettingsRsp)
	err := c.cc.Invoke(ctx, CustomerInterface_SetUserSettings_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerInterfaceClient) SyncFetchCustomerSessionMsgs(ctx context.Context, in *SessionMsgReq, opts ...grpc.CallOption) (*SessionMsgRsp, error) {
	out := new(SessionMsgRsp)
	err := c.cc.Invoke(ctx, CustomerInterface_SyncFetchCustomerSessionMsgs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerInterfaceServer is the server API for CustomerInterface service.
// All implementations must embed UnimplementedCustomerInterfaceServer
// for forward compatibility
type CustomerInterfaceServer interface {
	CustomerPreEvaluate(context.Context, *PreEvaluateReq) (*PreEvaluateRsp, error)
	CustomerUpdateAck(context.Context, *UpdateAckReq) (*Empty, error)
	CustomerWindowOptions(context.Context, *WindowOptionsReq) (*WindowOptionsRsp, error)
	FinishParagraphsRender(context.Context, *FinishParagraphsRenderReq) (*FinishParagraphsRenderRsp, error)
	GetCustomerSessDetail(context.Context, *GetSessDetailReq) (*GetSessDetailRsp, error)
	GetCustomerSessions(context.Context, *GetSessionsReq) (*SessionsRsp, error)
	GetNewCustomerSessions(context.Context, *GetNewSessionsReq) (*SessionsRsp, error)
	GetShopCfg(context.Context, *ShopCfgReq) (*ShopCfgRsp, error)
	GetShopInfo(context.Context, *ShopInfoReq) (*ShopInfoRsp, error)
	GetUserSettings(context.Context, *GetUserSettingsReq) (*GetUserSettingsRsp, error)
	HeartBeat(context.Context, *SendHeartBeatReq) (*Empty, error)
	OutCustomerQueue(context.Context, *OutCustomerQueueReq) (*Empty, error)
	PopResultUpdate(context.Context, *PopResultUpdateReq) (*PopResultUpdateRsp, error)
	RemoveSession(context.Context, *RemoveSessionReq) (*Empty, error)
	SendCustomerMsg(context.Context, *SendMsgReq) (*SendMsgRsp, error)
	SetTop(context.Context, *SetTopReq) (*Empty, error)
	SetUserSettings(context.Context, *SetUserSettingsReq) (*SetUserSettingsRsp, error)
	SyncFetchCustomerSessionMsgs(context.Context, *SessionMsgReq) (*SessionMsgRsp, error)
	mustEmbedUnimplementedCustomerInterfaceServer()
}

// UnimplementedCustomerInterfaceServer must be embedded to have forward compatible implementations.
type UnimplementedCustomerInterfaceServer struct {
}

func (UnimplementedCustomerInterfaceServer) CustomerPreEvaluate(context.Context, *PreEvaluateReq) (*PreEvaluateRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CustomerPreEvaluate not implemented")
}
func (UnimplementedCustomerInterfaceServer) CustomerUpdateAck(context.Context, *UpdateAckReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CustomerUpdateAck not implemented")
}
func (UnimplementedCustomerInterfaceServer) CustomerWindowOptions(context.Context, *WindowOptionsReq) (*WindowOptionsRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CustomerWindowOptions not implemented")
}
func (UnimplementedCustomerInterfaceServer) FinishParagraphsRender(context.Context, *FinishParagraphsRenderReq) (*FinishParagraphsRenderRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinishParagraphsRender not implemented")
}
func (UnimplementedCustomerInterfaceServer) GetCustomerSessDetail(context.Context, *GetSessDetailReq) (*GetSessDetailRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomerSessDetail not implemented")
}
func (UnimplementedCustomerInterfaceServer) GetCustomerSessions(context.Context, *GetSessionsReq) (*SessionsRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomerSessions not implemented")
}
func (UnimplementedCustomerInterfaceServer) GetNewCustomerSessions(context.Context, *GetNewSessionsReq) (*SessionsRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNewCustomerSessions not implemented")
}
func (UnimplementedCustomerInterfaceServer) GetShopCfg(context.Context, *ShopCfgReq) (*ShopCfgRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShopCfg not implemented")
}
func (UnimplementedCustomerInterfaceServer) GetShopInfo(context.Context, *ShopInfoReq) (*ShopInfoRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShopInfo not implemented")
}
func (UnimplementedCustomerInterfaceServer) GetUserSettings(context.Context, *GetUserSettingsReq) (*GetUserSettingsRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserSettings not implemented")
}
func (UnimplementedCustomerInterfaceServer) HeartBeat(context.Context, *SendHeartBeatReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HeartBeat not implemented")
}
func (UnimplementedCustomerInterfaceServer) OutCustomerQueue(context.Context, *OutCustomerQueueReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OutCustomerQueue not implemented")
}
func (UnimplementedCustomerInterfaceServer) PopResultUpdate(context.Context, *PopResultUpdateReq) (*PopResultUpdateRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PopResultUpdate not implemented")
}
func (UnimplementedCustomerInterfaceServer) RemoveSession(context.Context, *RemoveSessionReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveSession not implemented")
}
func (UnimplementedCustomerInterfaceServer) SendCustomerMsg(context.Context, *SendMsgReq) (*SendMsgRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCustomerMsg not implemented")
}
func (UnimplementedCustomerInterfaceServer) SetTop(context.Context, *SetTopReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTop not implemented")
}
func (UnimplementedCustomerInterfaceServer) SetUserSettings(context.Context, *SetUserSettingsReq) (*SetUserSettingsRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUserSettings not implemented")
}
func (UnimplementedCustomerInterfaceServer) SyncFetchCustomerSessionMsgs(context.Context, *SessionMsgReq) (*SessionMsgRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncFetchCustomerSessionMsgs not implemented")
}
func (UnimplementedCustomerInterfaceServer) mustEmbedUnimplementedCustomerInterfaceServer() {}

// UnsafeCustomerInterfaceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustomerInterfaceServer will
// result in compilation errors.
type UnsafeCustomerInterfaceServer interface {
	mustEmbedUnimplementedCustomerInterfaceServer()
}

func RegisterCustomerInterfaceServer(s grpc.ServiceRegistrar, srv CustomerInterfaceServer) {
	s.RegisterService(&CustomerInterface_ServiceDesc, srv)
}

func _CustomerInterface_CustomerPreEvaluate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreEvaluateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerInterfaceServer).CustomerPreEvaluate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerInterface_CustomerPreEvaluate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerInterfaceServer).CustomerPreEvaluate(ctx, req.(*PreEvaluateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerInterface_CustomerUpdateAck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAckReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerInterfaceServer).CustomerUpdateAck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerInterface_CustomerUpdateAck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerInterfaceServer).CustomerUpdateAck(ctx, req.(*UpdateAckReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerInterface_CustomerWindowOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WindowOptionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerInterfaceServer).CustomerWindowOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerInterface_CustomerWindowOptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerInterfaceServer).CustomerWindowOptions(ctx, req.(*WindowOptionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerInterface_FinishParagraphsRender_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishParagraphsRenderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerInterfaceServer).FinishParagraphsRender(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerInterface_FinishParagraphsRender_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerInterfaceServer).FinishParagraphsRender(ctx, req.(*FinishParagraphsRenderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerInterface_GetCustomerSessDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerInterfaceServer).GetCustomerSessDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerInterface_GetCustomerSessDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerInterfaceServer).GetCustomerSessDetail(ctx, req.(*GetSessDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerInterface_GetCustomerSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerInterfaceServer).GetCustomerSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerInterface_GetCustomerSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerInterfaceServer).GetCustomerSessions(ctx, req.(*GetSessionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerInterface_GetNewCustomerSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNewSessionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerInterfaceServer).GetNewCustomerSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerInterface_GetNewCustomerSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerInterfaceServer).GetNewCustomerSessions(ctx, req.(*GetNewSessionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerInterface_GetShopCfg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShopCfgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerInterfaceServer).GetShopCfg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerInterface_GetShopCfg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerInterfaceServer).GetShopCfg(ctx, req.(*ShopCfgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerInterface_GetShopInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShopInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerInterfaceServer).GetShopInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerInterface_GetShopInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerInterfaceServer).GetShopInfo(ctx, req.(*ShopInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerInterface_GetUserSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserSettingsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerInterfaceServer).GetUserSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerInterface_GetUserSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerInterfaceServer).GetUserSettings(ctx, req.(*GetUserSettingsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerInterface_HeartBeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendHeartBeatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerInterfaceServer).HeartBeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerInterface_HeartBeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerInterfaceServer).HeartBeat(ctx, req.(*SendHeartBeatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerInterface_OutCustomerQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OutCustomerQueueReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerInterfaceServer).OutCustomerQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerInterface_OutCustomerQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerInterfaceServer).OutCustomerQueue(ctx, req.(*OutCustomerQueueReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerInterface_PopResultUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PopResultUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerInterfaceServer).PopResultUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerInterface_PopResultUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerInterfaceServer).PopResultUpdate(ctx, req.(*PopResultUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerInterface_RemoveSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSessionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerInterfaceServer).RemoveSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerInterface_RemoveSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerInterfaceServer).RemoveSession(ctx, req.(*RemoveSessionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerInterface_SendCustomerMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerInterfaceServer).SendCustomerMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerInterface_SendCustomerMsg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerInterfaceServer).SendCustomerMsg(ctx, req.(*SendMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerInterface_SetTop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTopReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerInterfaceServer).SetTop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerInterface_SetTop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerInterfaceServer).SetTop(ctx, req.(*SetTopReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerInterface_SetUserSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserSettingsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerInterfaceServer).SetUserSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerInterface_SetUserSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerInterfaceServer).SetUserSettings(ctx, req.(*SetUserSettingsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerInterface_SyncFetchCustomerSessionMsgs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerInterfaceServer).SyncFetchCustomerSessionMsgs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerInterface_SyncFetchCustomerSessionMsgs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerInterfaceServer).SyncFetchCustomerSessionMsgs(ctx, req.(*SessionMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CustomerInterface_ServiceDesc is the grpc.ServiceDesc for CustomerInterface service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CustomerInterface_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bilibili.im.customer.interfaces.CustomerInterface",
	HandlerType: (*CustomerInterfaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CustomerPreEvaluate",
			Handler:    _CustomerInterface_CustomerPreEvaluate_Handler,
		},
		{
			MethodName: "CustomerUpdateAck",
			Handler:    _CustomerInterface_CustomerUpdateAck_Handler,
		},
		{
			MethodName: "CustomerWindowOptions",
			Handler:    _CustomerInterface_CustomerWindowOptions_Handler,
		},
		{
			MethodName: "FinishParagraphsRender",
			Handler:    _CustomerInterface_FinishParagraphsRender_Handler,
		},
		{
			MethodName: "GetCustomerSessDetail",
			Handler:    _CustomerInterface_GetCustomerSessDetail_Handler,
		},
		{
			MethodName: "GetCustomerSessions",
			Handler:    _CustomerInterface_GetCustomerSessions_Handler,
		},
		{
			MethodName: "GetNewCustomerSessions",
			Handler:    _CustomerInterface_GetNewCustomerSessions_Handler,
		},
		{
			MethodName: "GetShopCfg",
			Handler:    _CustomerInterface_GetShopCfg_Handler,
		},
		{
			MethodName: "GetShopInfo",
			Handler:    _CustomerInterface_GetShopInfo_Handler,
		},
		{
			MethodName: "GetUserSettings",
			Handler:    _CustomerInterface_GetUserSettings_Handler,
		},
		{
			MethodName: "HeartBeat",
			Handler:    _CustomerInterface_HeartBeat_Handler,
		},
		{
			MethodName: "OutCustomerQueue",
			Handler:    _CustomerInterface_OutCustomerQueue_Handler,
		},
		{
			MethodName: "PopResultUpdate",
			Handler:    _CustomerInterface_PopResultUpdate_Handler,
		},
		{
			MethodName: "RemoveSession",
			Handler:    _CustomerInterface_RemoveSession_Handler,
		},
		{
			MethodName: "SendCustomerMsg",
			Handler:    _CustomerInterface_SendCustomerMsg_Handler,
		},
		{
			MethodName: "SetTop",
			Handler:    _CustomerInterface_SetTop_Handler,
		},
		{
			MethodName: "SetUserSettings",
			Handler:    _CustomerInterface_SetUserSettings_Handler,
		},
		{
			MethodName: "SyncFetchCustomerSessionMsgs",
			Handler:    _CustomerInterface_SyncFetchCustomerSessionMsgs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bilibili/im/customer/interfaces.proto",
}
