// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.account.fission.v1;

// Source: com/bapis/bilibili/account/fission/v1/AnimateIcon.java
message AnimateIcon {
  string icon = 1;
  string json = 2;
}

// Source: com/bapis/bilibili/account/fission/v1/EntranceReply.java
message EntranceReply {
  string icon = 1;
  string name = 2;
  string url = 3;
  AnimateIcon animateIcon = 4;
}

// Source: com/bapis/bilibili/account/fission/v1/EntranceReq.java
message EntranceReq {
}

// Source: com/bapis/bilibili/account/fission/v1/PrivacyReply.java
message PrivacyReply {
  string message_ = 1;
}

// Source: com/bapis/bilibili/account/fission/v1/PrivacyReq.java
message PrivacyReq {
  string activityUid = 1;
}

// Source: com/bapis/bilibili/account/fission/v1/WindowReply.java
message WindowReply {
  int32 type = 1;
  string url = 2;
  string reportData = 3;
}

// Source: com/bapis/bilibili/account/fission/v1/WindowReq.java
message WindowReq {
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/account/fission/v1";
