// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.app.archive.middleware.v1;

enum QnPolicy {
  QN_POLICY_DEFAULT = 0;
  QN_POLICY_AUTO_QN_ENABLE = 1;
  UNRECOGNIZED = -1;
}

// Source: com/bapis/bilibili/app/archive/middleware/v1/PlayerArgs.java
message PlayerArgs {
  int64 qn = 1;
  int64 fnver = 2;
  int64 fnval = 3;
  int64 forceHost = 4;
  int64 voiceBalance = 5;
  QnPolicy qnPolicy = 6;
  int64 clientAttr = 7;
  map<string, string> extraContent = 8;
  int64 softFnval = 9;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/app/archive/middleware/v1";
