// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.app.dynamic.v1;

enum FoldType {
  FoldTypeZero = 0;
  FoldTypePublish = 1;
  FoldTypeFrequent = 2;
  FoldTypeUnite = 3;
  FoldTypeLimit = 4;
}

enum MediaType {
  MediaTypeNone = 0;
  MediaTypeUGC = 1;
  MediaTypePGC = 2;
  MediaTypeLive = 3;
  MediaTypeVCS = 4;
}

enum SVideoType {
  TypeNone = 0;
  TypeDynamic = 1;
}

enum VideoSubType {
  VideoSubTypeNone = 0;
  VideoSubTypeBangumi = 1;
  VideoSubTypeMovie = 2;
  VideoSubTypeDocumentary = 3;
  VideoSubTypeDomestic = 4;
  VideoSubTypeTeleplay = 5;
}

// Source: com/bapis/bilibili/app/dynamic/v1/CardCurrBatch.java
message CardCurrBatch {
  string title = 1;
  string cover = 2;
  string uri = 3;
  string text1 = 4;
  string text2 = 5;
  VideoBadge badge = 6;
}

// Source: com/bapis/bilibili/app/dynamic/v1/CardCurrSeason.java
message CardCurrSeason {
  string title = 1;
  string cover = 2;
  string uri = 3;
  string text1 = 4;
  string desc = 5;
  VideoBadge badge = 6;
}

// Source: com/bapis/bilibili/app/dynamic/v1/CardPGC.java
message CardPGC {
  string title = 1;
  string cover = 2;
  string uri = 3;
  string coverLeftText1 = 4;
  string coverLeftText2 = 5;
  string coverLeftText3 = 6;
  int64 cid = 7;
  int64 seasonId = 8;
  int64 epid = 9;
  int64 aid = 10;
  MediaType mediaType = 11;
  VideoSubType subType = 12;
  int32 isPreview = 13;
  Dimension dimension = 14;
  repeated VideoBadge badge = 15;
  int32 canPlay = 16;
  PGCSeason season = 17;
}

// Source: com/bapis/bilibili/app/dynamic/v1/CardUGC.java
message CardUGC {
  string title = 1;
  string cover = 2;
  string uri = 3;
  string coverLeftText1 = 4;
  string coverLeftText2 = 5;
  string coverLeftText3 = 6;
  int64 avid = 7;
  int64 cid = 8;
  MediaType mediaType = 9;
  Dimension dimension = 10;
  repeated VideoBadge badge = 11;
  int32 canPlay = 12;
}

// Source: com/bapis/bilibili/app/dynamic/v1/DecoCardFan.java
message DecoCardFan {
  int32 isFan = 1;
  int32 number = 2;
  string color = 3;
}

// Source: com/bapis/bilibili/app/dynamic/v1/DecorateCard.java
message DecorateCard {
  int64 id = 1;
  string cardUrl = 2;
  string jumpUrl = 3;
  DecoCardFan fan = 4;
}

// Source: com/bapis/bilibili/app/dynamic/v1/Description.java
message Description {
  string text = 1;
  string type = 2;
  string uri = 3;
  string emojiType = 4;
  string goodsType = 5;
}

// Source: com/bapis/bilibili/app/dynamic/v1/Dimension.java
message Dimension {
  int64 height = 1;
  int64 width = 2;
  int64 rotate = 3;
}

// Source: com/bapis/bilibili/app/dynamic/v1/DynamicItem.java
message DynamicItem {
  string cardType = 1;
  string itemType = 2;
  repeated Module modules = 3;
  string dynIdStr = 4;
  string origDynIdStr = 5;
  int32 rType = 6;
  int32 hasFold = 7;
}

// Source: com/bapis/bilibili/app/dynamic/v1/DynDetailsReply.java
message DynDetailsReply {
  repeated DynamicItem list = 1;
}

// Source: com/bapis/bilibili/app/dynamic/v1/DynDetailsReq.java
message DynDetailsReq {
  int32 teenagersMode = 1;
  string dynamicIds = 2;
  int32 qn = 3;
  int32 fnver = 4;
  int32 fnval = 5;
  int32 forceHost = 6;
  int32 fourk = 7;
}

// Source: com/bapis/bilibili/app/dynamic/v1/DynOurCityItem.java
message DynOurCityItem {
  string cardType = 1;
  int64 dynId = 2;
  string uri = 3;
  repeated DynOurCityModule modules = 4;
  int64 rid = 5;
}

// Source: com/bapis/bilibili/app/dynamic/v1/DynOurCityModule.java
message DynOurCityModule {
  string moduleType = 1;
  oneof oneof_0 {
    DynOurCityModuleCover moduleCover = 2;
    DynOurCityModuleDesc moduleDesc = 3;
    DynOurCityModuleAuthor moduleAuthor = 4;
    DynOurCityModuleExtend moduleExtend = 5;
  }
  enum ModuleItemCase {
    MODULEITEM_NOT_SET = 0;
    MODULE_COVER = 2;
    MODULE_DESC = 3;
    MODULE_AUTHOR = 4;
    MODULE_EXTEND = 5;
  }

}

// Source: com/bapis/bilibili/app/dynamic/v1/DynOurCityModuleAuthor.java
message DynOurCityModuleAuthor {
  int64 mid = 1;
  string name = 2;
  string face = 3;
  string uri = 4;
}

// Source: com/bapis/bilibili/app/dynamic/v1/DynOurCityModuleCover.java
message DynOurCityModuleCover {
  repeated string covers = 1;
  int32 style = 2;
  int32 coverLeftIcon1 = 3;
  string coverLeftText1 = 4;
  int32 coverLeftIcon2 = 5;
  string coverLeftText2 = 6;
  string coverLeftText3 = 7;
  repeated VideoBadge badge = 8;
}

// Source: com/bapis/bilibili/app/dynamic/v1/DynOurCityModuleDesc.java
message DynOurCityModuleDesc {
  string desc = 1;
}

// Source: com/bapis/bilibili/app/dynamic/v1/DynOurCityModuleExtend.java
message DynOurCityModuleExtend {
  string type = 1;
  oneof oneof_0 {
    DynOurCityModuleExtendLBS extendLbs = 2;
  }
  enum ExtendCase {
    EXTEND_NOT_SET = 0;
    EXTEND_LBS = 2;
  }

}

// Source: com/bapis/bilibili/app/dynamic/v1/DynOurCityModuleExtendLBS.java
message DynOurCityModuleExtendLBS {
  string title = 1;
  string uri = 2;
  string icon = 3;
  int32 poiType = 4;
}

// Source: com/bapis/bilibili/app/dynamic/v1/DynOurCityReply.java
message DynOurCityReply {
  string offset = 1;
  int32 hasMore = 2;
  int32 style = 3;
  string topLabel = 4;
  repeated DynOurCityItem list = 5;
  string topButtonLabel = 6;
}

// Source: com/bapis/bilibili/app/dynamic/v1/DynOurCityReq.java
message DynOurCityReq {
  int64 cityId = 1;
  double lat = 2;
  double lng = 3;
  string offset = 4;
  int32 pageSize = 5;
  int32 teenagersMode = 6;
  int32 qn = 7;
  int32 fnver = 8;
  int32 fnval = 9;
  int32 forceHost = 10;
  int32 fourk = 11;
  int32 lbsState = 12;
}

// Source: com/bapis/bilibili/app/dynamic/v1/DynOurCitySwitchReq.java
message DynOurCitySwitchReq {
  int32 switch = 1;
}

// Source: com/bapis/bilibili/app/dynamic/v1/DynRedItem.java
message DynRedItem {
  uint64 count = 1;
}

// Source: com/bapis/bilibili/app/dynamic/v1/DynRedReply.java
message DynRedReply {
  string redType = 1;
  DynRedItem dynRedItem = 2;
  string defaultTab = 3;
}

// Source: com/bapis/bilibili/app/dynamic/v1/DynRedReq.java
message DynRedReq {
  repeated TabOffset tabOffset = 1;
}

// Source: com/bapis/bilibili/app/dynamic/v1/DynTab.java
message DynTab {
  string title = 1;
  string uri = 2;
  string bubble = 3;
  int32 redPoint = 4;
  int64 cityId = 5;
  int32 isPopup = 6;
  Popup popup = 7;
  bool defaulttab = 8;
  string subTitle = 9;
  string anchor = 10;
}

// Source: com/bapis/bilibili/app/dynamic/v1/DynTabReply.java
message DynTabReply {
  repeated DynTab dynTab = 1;
}

// Source: com/bapis/bilibili/app/dynamic/v1/DynTabReq.java
message DynTabReq {
  int32 teenagersMode = 1;
}

// Source: com/bapis/bilibili/app/dynamic/v1/DynUpdOffsetReq.java
message DynUpdOffsetReq {
  int64 hostUid = 1;
  string readOffset = 2;
}

// Source: com/bapis/bilibili/app/dynamic/v1/DynVideoPersonalReply.java
message DynVideoPersonalReply {
  repeated DynamicItem list = 1;
  string offset = 2;
  int32 hasMore = 3;
  string readOffset = 4;
}

// Source: com/bapis/bilibili/app/dynamic/v1/DynVideoPersonalReq.java
message DynVideoPersonalReq {
  int32 teenagersMode = 1;
  int64 hostUid = 2;
  string offset = 3;
  int32 page = 4;
  int32 isPreload = 5;
  int32 qn = 6;
  int32 fnver = 7;
  int32 fnval = 8;
  int32 forceHost = 9;
  int32 fourk = 10;
}

// Source: com/bapis/bilibili/app/dynamic/v1/DynVideoReq.java
message DynVideoReq {
  int32 teenagersMode = 1;
  string updateBaseline = 2;
  string offset = 3;
  int32 page = 4;
  int32 refreshType = 5;
  int32 qn = 6;
  int32 fnver = 7;
  int32 fnval = 8;
  int32 forceHost = 9;
  int32 fourk = 10;
}

// Source: com/bapis/bilibili/app/dynamic/v1/DynVideoReqReply.java
message DynVideoReqReply {
  repeated DynamicItem list = 1;
  int32 updateNum = 2;
  string historyOffset = 3;
  string updateBaseline = 4;
  int32 hasMore = 5;
}

// Source: com/bapis/bilibili/app/dynamic/v1/Extend.java
message Extend {
  string type = 1;
  oneof oneof_0 {
    ExtInfoTopic extInfoTopic = 2;
    ExtInfoLBS extInfoLbs = 3;
    ExtInfoHot extInfoHot = 4;
    ExtInfoGame extInfoGame = 5;
  }
  enum ExtendCase {
    EXTEND_NOT_SET = 0;
    EXT_INFO_TOPIC = 2;
    EXT_INFO_LBS = 3;
    EXT_INFO_HOT = 4;
    EXT_INFO_GAME = 5;
  }

}

// Source: com/bapis/bilibili/app/dynamic/v1/ExtInfoGame.java
message ExtInfoGame {
  string title = 1;
  string uri = 2;
  string icon = 3;
}

// Source: com/bapis/bilibili/app/dynamic/v1/ExtInfoHot.java
message ExtInfoHot {
  string title = 1;
  string uri = 2;
  string icon = 3;
}

// Source: com/bapis/bilibili/app/dynamic/v1/ExtInfoLBS.java
message ExtInfoLBS {
  string title = 1;
  string uri = 2;
  string icon = 3;
  int32 poiType = 4;
}

// Source: com/bapis/bilibili/app/dynamic/v1/ExtInfoTopic.java
message ExtInfoTopic {
  string title = 1;
  string uri = 2;
  string icon = 3;
}

// Source: com/bapis/bilibili/app/dynamic/v1/FollowListItem.java
message FollowListItem {
  int32 seasonId = 1;
  string title = 2;
  string cover = 3;
  string url = 4;
  NewEP newEp = 5;
}

// Source: com/bapis/bilibili/app/dynamic/v1/LikeAnimation.java
message LikeAnimation {
  string begin = 1;
  string proc = 2;
  string end = 3;
  int64 likeIconId = 4;
}

// Source: com/bapis/bilibili/app/dynamic/v1/LikeInfo.java
message LikeInfo {
  LikeAnimation animation = 1;
  int32 isLike = 2;
}

// Source: com/bapis/bilibili/app/dynamic/v1/LikeUser.java
message LikeUser {
  int64 uid = 1;
  string uname = 2;
  string uri = 3;
}

// Source: com/bapis/bilibili/app/dynamic/v1/LiveInfo.java
message LiveInfo {
  int32 isLiving = 1;
  string uri = 2;
}

// Source: com/bapis/bilibili/app/dynamic/v1/Module.java
message Module {
  string moduleType = 1;
  oneof oneof_0 {
    ModuleFold moduleFold = 2;
    ModuleAuthor moduleAuthor = 3;
    ModuleDynamic moduleDynamic = 4;
    ModuleState moduleState = 5;
    ModuleForward moduleForward = 6;
    ModuleExtend moduleExtend = 7;
    ModuleDispute moduleDispute = 8;
    ModuleDesc moduleDesc = 9;
    bytes moduleLikeuser = 10;
    bytes moduleUplist = 11;
    bytes moduleFollowlist = 12;
  }
  enum ModuleItemCase {
    MODULEITEM_NOT_SET = 0;
    MODULE_FOLD = 2;
    MODULE_AUTHOR = 3;
    MODULE_DYNAMIC = 4;
    MODULE_STATE = 5;
    MODULE_FORWARD = 6;
    MODULE_EXTEND = 7;
    MODULE_DISPUTE = 8;
    MODULE_DESC = 9;
    MODULE_LIKEUSER = 10;
    MODULE_UPLIST = 11;
    MODULE_FOLLOWLIST = 12;
  }

}

// Source: com/bapis/bilibili/app/dynamic/v1/ModuleAuthor.java
message ModuleAuthor {
  int64 id = 1;
  string ptimeLabelText = 2;
  UserInfo author = 3;
  DecorateCard decorateCard = 4;
}

// Source: com/bapis/bilibili/app/dynamic/v1/ModuleDesc.java
message ModuleDesc {
  repeated Description desc = 1;
}

// Source: com/bapis/bilibili/app/dynamic/v1/ModuleDispute.java
message ModuleDispute {
  string title = 1;
  string desc = 2;
  string uri = 3;
}

// Source: com/bapis/bilibili/app/dynamic/v1/ModuleDynamic.java
message ModuleDynamic {
  string cardType = 1;
  oneof oneof_0 {
    CardUGC cardUgc = 2;
    CardPGC cardPgc = 3;
    CardCurrSeason cardCurrSeason = 4;
    CardCurrBatch cardCurrBatch = 5;
  }
  enum CardCase {
    CARD_NOT_SET = 0;
    CARD_UGC = 2;
    CARD_PGC = 3;
    CARD_CURR_SEASON = 4;
    CARD_CURR_BATCH = 5;
  }

}

// Source: com/bapis/bilibili/app/dynamic/v1/ModuleDynUpList.java
message ModuleDynUpList {
  string moduleTitle = 1;
  string showAll = 2;
  repeated UpListItem list = 3;
}

// Source: com/bapis/bilibili/app/dynamic/v1/ModuleExtend.java
message ModuleExtend {
  repeated Extend extend_ = 1;
}

// Source: com/bapis/bilibili/app/dynamic/v1/ModuleFold.java
message ModuleFold {
  int32 foldType = 1;
  string text = 2;
  string foldIds = 3;
  repeated UserInfo foldUsers = 4;
  FoldType foldTypeV2 = 5;
}

// Source: com/bapis/bilibili/app/dynamic/v1/ModuleFollowList.java
message ModuleFollowList {
  string viewAllLink = 1;
  repeated FollowListItem list = 2;
}

// Source: com/bapis/bilibili/app/dynamic/v1/ModuleForward.java
message ModuleForward {
  string cardType = 1;
  repeated Module modules = 2;
}

// Source: com/bapis/bilibili/app/dynamic/v1/ModuleLikeUser.java
message ModuleLikeUser {
  repeated LikeUser likeUsers = 1;
  string displayText = 2;
}

// Source: com/bapis/bilibili/app/dynamic/v1/ModuleState.java
message ModuleState {
  int32 repost = 1;
  int32 like = 2;
  int32 reply = 3;
  LikeInfo likeInfo = 4;
  bool noComment = 5;
  bool noForward = 6;
}

// Source: com/bapis/bilibili/app/dynamic/v1/Nameplate.java
message Nameplate {
  int64 nid = 1;
  string name = 2;
  string image = 3;
  string imageSmall = 4;
  string level = 5;
  string condition = 6;
}

// Source: com/bapis/bilibili/app/dynamic/v1/NewEP.java
message NewEP {
  int32 id = 1;
  string indexShow = 2;
  string cover = 3;
}

// Source: com/bapis/bilibili/app/dynamic/v1/NoReply.java
message NoReply {
}

// Source: com/bapis/bilibili/app/dynamic/v1/NoReq.java
message NoReq {
}

// Source: com/bapis/bilibili/app/dynamic/v1/OfficialVerify.java
message OfficialVerify {
  int32 type = 1;
  string desc = 2;
  int32 isAtten = 3;
}

// Source: com/bapis/bilibili/app/dynamic/v1/PGCSeason.java
message PGCSeason {
  int32 isFinish = 1;
  string title = 2;
  int32 type = 3;
}

// Source: com/bapis/bilibili/app/dynamic/v1/Popup.java
message Popup {
  string title = 1;
  string desc = 2;
  string uri = 3;
}

// Source: com/bapis/bilibili/app/dynamic/v1/ShareInfo.java
message ShareInfo {
  int64 aid = 1;
  string bvid = 2;
  string title = 3;
  string subtitle = 4;
  string cover = 5;
  int64 mid = 6;
  string name = 7;
}

// Source: com/bapis/bilibili/app/dynamic/v1/SVideoItem.java
message SVideoItem {
  string cardType = 1;
  repeated SVideoModule modules = 2;
  string dynIdStr = 3;
}

// Source: com/bapis/bilibili/app/dynamic/v1/SVideoModule.java
message SVideoModule {
  string moduleType = 1;
  oneof oneof_0 {
    SVideoModuleAuthor moduleAuthor = 2;
    SVideoModulePlayer modulePlayer = 3;
    SVideoModuleDesc moduleDesc = 4;
    SVideoModuleStat moduleStat = 5;
  }
  enum ModuleItemCase {
    MODULEITEM_NOT_SET = 0;
    MODULE_AUTHOR = 2;
    MODULE_PLAYER = 3;
    MODULE_DESC = 4;
    MODULE_STAT = 5;
  }

}

// Source: com/bapis/bilibili/app/dynamic/v1/SVideoModuleAuthor.java
message SVideoModuleAuthor {
  int64 mid = 1;
  string name = 2;
  string face = 3;
  string pubDesc = 4;
  int32 isAttention = 5;
  string uri = 6;
}

// Source: com/bapis/bilibili/app/dynamic/v1/SVideoModuleDesc.java
message SVideoModuleDesc {
  string text = 1;
  string uri = 2;
}

// Source: com/bapis/bilibili/app/dynamic/v1/SVideoModulePlayer.java
message SVideoModulePlayer {
  string title = 1;
  string cover = 2;
  string uri = 3;
  int64 aid = 4;
  int64 cid = 5;
  int64 duration = 6;
  Dimension dimension = 7;
}

// Source: com/bapis/bilibili/app/dynamic/v1/SVideoModuleStat.java
message SVideoModuleStat {
  repeated SVideoStatInfo statInfo = 1;
  ShareInfo shareInfo = 2;
}

// Source: com/bapis/bilibili/app/dynamic/v1/SVideoReply.java
message SVideoReply {
  repeated SVideoItem list = 1;
  string offset = 2;
  int32 hasMore = 3;
}

// Source: com/bapis/bilibili/app/dynamic/v1/SVideoReq.java
message SVideoReq {
  int64 oid = 1;
  SVideoType type = 2;
  string offset = 3;
  int32 qn = 4;
  int32 fnver = 5;
  int32 fnval = 6;
  int32 forceHost = 7;
  int32 fourk = 8;
  string spmid = 9;
  string fromSpmid = 10;
}

// Source: com/bapis/bilibili/app/dynamic/v1/SVideoStatInfo.java
message SVideoStatInfo {
  int32 icon = 1;
  int64 num = 2;
  int32 selected = 3;
  string uri = 4;
}

// Source: com/bapis/bilibili/app/dynamic/v1/TabOffset.java
message TabOffset {
  int32 tab = 1;
  string offset = 2;
}

// Source: com/bapis/bilibili/app/dynamic/v1/UpListItem.java
message UpListItem {
  int32 hasUpdate = 1;
  string face = 2;
  string name = 3;
  int64 uid = 4;
}

// Source: com/bapis/bilibili/app/dynamic/v1/UserInfo.java
message UserInfo {
  int64 mid = 1;
  string name = 2;
  string face = 3;
  OfficialVerify official = 4;
  VipInfo vip = 5;
  LiveInfo live = 6;
  string uri = 7;
  UserPendant pendant = 8;
  Nameplate nameplate = 9;
}

// Source: com/bapis/bilibili/app/dynamic/v1/UserPendant.java
message UserPendant {
  int64 pid = 1;
  string name = 2;
  string image = 3;
  int64 expire = 4;
}

// Source: com/bapis/bilibili/app/dynamic/v1/VideoBadge.java
message VideoBadge {
  string text = 1;
  string textColor = 2;
  string textColorNight = 3;
  string bgColor = 4;
  string bgColorNight = 5;
  string borderColor = 6;
  string borderColorNight = 7;
  int32 bgStyle = 8;
}

// Source: com/bapis/bilibili/app/dynamic/v1/VipInfo.java
message VipInfo {
  int32 type = 1;
  int32 status = 2;
  int64 dueDate = 3;
  VipLabel label = 4;
  int32 themeType = 5;
}

// Source: com/bapis/bilibili/app/dynamic/v1/VipLabel.java
message VipLabel {
  string path = 1;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/app/dynamic/v1";
