// Reconstructed from protobuf-lite metadata in the APK.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v7.35.1
// source: bcg/brand/ad/api/messages.proto

package api

import (
	spi "github.com/stmtc233/bili-grpc-api-go/bcg/sunspot/ad/spi"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Source: com/bapis/bcg/brand/ad/api/SearchObj.java
type SearchObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Empty *spi.Empty `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
}

func (x *SearchObj) Reset() {
	*x = SearchObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bcg_brand_ad_api_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchObj) ProtoMessage() {}

func (x *SearchObj) ProtoReflect() protoreflect.Message {
	mi := &file_bcg_brand_ad_api_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchObj.ProtoReflect.Descriptor instead.
func (*SearchObj) Descriptor() ([]byte, []int) {
	return file_bcg_brand_ad_api_messages_proto_rawDescGZIP(), []int{0}
}

func (x *SearchObj) GetEmpty() *spi.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

var File_bcg_brand_ad_api_messages_proto protoreflect.FileDescriptor

var file_bcg_brand_ad_api_messages_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x62, 0x63, 0x67, 0x2f, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x2f, 0x61, 0x64, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x1a, 0x63, 0x6f, 0x6d, 0x2e, 0x62, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x62, 0x63, 0x67,
	0x2e, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x2e, 0x61, 0x64, 0x2e, 0x61, 0x70, 0x69, 0x1a, 0x21, 0x62,
	0x63, 0x67, 0x2f, 0x73, 0x75, 0x6e, 0x73, 0x70, 0x6f, 0x74, 0x2f, 0x61, 0x64, 0x2f, 0x73, 0x70,
	0x69, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x46, 0x0a, 0x09, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4f, 0x62, 0x6a, 0x12, 0x39, 0x0a,
	0x05, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x63,
	0x6f, 0x6d, 0x2e, 0x62, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x62, 0x63, 0x67, 0x2e, 0x73, 0x75, 0x6e,
	0x73, 0x70, 0x6f, 0x74, 0x2e, 0x61, 0x64, 0x2e, 0x73, 0x70, 0x69, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x52, 0x05, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x6d, 0x74, 0x63, 0x32, 0x33, 0x33, 0x2f,
	0x62, 0x69, 0x6c, 0x69, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x61, 0x70, 0x69, 0x2d, 0x67, 0x6f,
	0x2f, 0x62, 0x63, 0x67, 0x2f, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x2f, 0x61, 0x64, 0x2f, 0x61, 0x70,
	0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bcg_brand_ad_api_messages_proto_rawDescOnce sync.Once
	file_bcg_brand_ad_api_messages_proto_rawDescData = file_bcg_brand_ad_api_messages_proto_rawDesc
)

func file_bcg_brand_ad_api_messages_proto_rawDescGZIP() []byte {
	file_bcg_brand_ad_api_messages_proto_rawDescOnce.Do(func() {
		file_bcg_brand_ad_api_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_bcg_brand_ad_api_messages_proto_rawDescData)
	})
	return file_bcg_brand_ad_api_messages_proto_rawDescData
}

var file_bcg_brand_ad_api_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_bcg_brand_ad_api_messages_proto_goTypes = []interface{}{
	(*SearchObj)(nil), // 0: com.bapis.bcg.brand.ad.api.SearchObj
	(*spi.Empty)(nil), // 1: com.bapis.bcg.sunspot.ad.spi.Empty
}
var file_bcg_brand_ad_api_messages_proto_depIdxs = []int32{
	1, // 0: com.bapis.bcg.brand.ad.api.SearchObj.empty:type_name -> com.bapis.bcg.sunspot.ad.spi.Empty
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bcg_brand_ad_api_messages_proto_init() }
func file_bcg_brand_ad_api_messages_proto_init() {
	if File_bcg_brand_ad_api_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bcg_brand_ad_api_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bcg_brand_ad_api_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bcg_brand_ad_api_messages_proto_goTypes,
		DependencyIndexes: file_bcg_brand_ad_api_messages_proto_depIdxs,
		MessageInfos:      file_bcg_brand_ad_api_messages_proto_msgTypes,
	}.Build()
	File_bcg_brand_ad_api_messages_proto = out.File
	file_bcg_brand_ad_api_messages_proto_rawDesc = nil
	file_bcg_brand_ad_api_messages_proto_goTypes = nil
	file_bcg_brand_ad_api_messages_proto_depIdxs = nil
}
