// Reconstructed from protobuf-lite metadata in the APK.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v7.35.1
// source: bilibili/api/ticket/v1/messages.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Source: com/bapis/bilibili/api/ticket/v1/GenWebTicketRequest.java
type GenWebTicketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Context map[string]string `protobuf:"bytes,1,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	KeyId   string            `protobuf:"bytes,2,opt,name=keyId,proto3" json:"keyId,omitempty"`
	Hexsign string            `protobuf:"bytes,3,opt,name=hexsign,proto3" json:"hexsign,omitempty"`
	Token   string            `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *GenWebTicketRequest) Reset() {
	*x = GenWebTicketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_api_ticket_v1_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenWebTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenWebTicketRequest) ProtoMessage() {}

func (x *GenWebTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_api_ticket_v1_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenWebTicketRequest.ProtoReflect.Descriptor instead.
func (*GenWebTicketRequest) Descriptor() ([]byte, []int) {
	return file_bilibili_api_ticket_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *GenWebTicketRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GenWebTicketRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *GenWebTicketRequest) GetHexsign() string {
	if x != nil {
		return x.Hexsign
	}
	return ""
}

func (x *GenWebTicketRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Source: com/bapis/bilibili/api/ticket/v1/GenWebTicketResponse.java
type GenWebTicketResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ticket    string                        `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	CreatedAt int64                         `protobuf:"varint,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Ttl       int64                         `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Context   *GenWebTicketResponse_Context `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	Nav       *GenWebTicketResponse_Nav     `protobuf:"bytes,5,opt,name=nav,proto3" json:"nav,omitempty"`
}

func (x *GenWebTicketResponse) Reset() {
	*x = GenWebTicketResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_api_ticket_v1_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenWebTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenWebTicketResponse) ProtoMessage() {}

func (x *GenWebTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_api_ticket_v1_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenWebTicketResponse.ProtoReflect.Descriptor instead.
func (*GenWebTicketResponse) Descriptor() ([]byte, []int) {
	return file_bilibili_api_ticket_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *GenWebTicketResponse) GetTicket() string {
	if x != nil {
		return x.Ticket
	}
	return ""
}

func (x *GenWebTicketResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GenWebTicketResponse) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *GenWebTicketResponse) GetContext() *GenWebTicketResponse_Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GenWebTicketResponse) GetNav() *GenWebTicketResponse_Nav {
	if x != nil {
		return x.Nav
	}
	return nil
}

// Source: com/bapis/bilibili/api/ticket/v1/GenWebTicketResponse.java
type GenWebTicketResponse_Context struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VVoucher string `protobuf:"bytes,1,opt,name=vVoucher,proto3" json:"vVoucher,omitempty"`
}

func (x *GenWebTicketResponse_Context) Reset() {
	*x = GenWebTicketResponse_Context{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_api_ticket_v1_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenWebTicketResponse_Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenWebTicketResponse_Context) ProtoMessage() {}

func (x *GenWebTicketResponse_Context) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_api_ticket_v1_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenWebTicketResponse_Context.ProtoReflect.Descriptor instead.
func (*GenWebTicketResponse_Context) Descriptor() ([]byte, []int) {
	return file_bilibili_api_ticket_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *GenWebTicketResponse_Context) GetVVoucher() string {
	if x != nil {
		return x.VVoucher
	}
	return ""
}

// Source: com/bapis/bilibili/api/ticket/v1/GenWebTicketResponse.java
type GenWebTicketResponse_Nav struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Img string `protobuf:"bytes,1,opt,name=img,proto3" json:"img,omitempty"`
	Sub string `protobuf:"bytes,2,opt,name=sub,proto3" json:"sub,omitempty"`
}

func (x *GenWebTicketResponse_Nav) Reset() {
	*x = GenWebTicketResponse_Nav{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_api_ticket_v1_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenWebTicketResponse_Nav) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenWebTicketResponse_Nav) ProtoMessage() {}

func (x *GenWebTicketResponse_Nav) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_api_ticket_v1_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenWebTicketResponse_Nav.ProtoReflect.Descriptor instead.
func (*GenWebTicketResponse_Nav) Descriptor() ([]byte, []int) {
	return file_bilibili_api_ticket_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *GenWebTicketResponse_Nav) GetImg() string {
	if x != nil {
		return x.Img
	}
	return ""
}

func (x *GenWebTicketResponse_Nav) GetSub() string {
	if x != nil {
		return x.Sub
	}
	return ""
}

// Source: com/bapis/bilibili/api/ticket/v1/GetTicketRequest.java
type GetTicketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Context map[string][]byte `protobuf:"bytes,1,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	KeyId   string            `protobuf:"bytes,2,opt,name=keyId,proto3" json:"keyId,omitempty"`
	Sign    []byte            `protobuf:"bytes,3,opt,name=sign,proto3" json:"sign,omitempty"`
	Token   string            `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *GetTicketRequest) Reset() {
	*x = GetTicketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_api_ticket_v1_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketRequest) ProtoMessage() {}

func (x *GetTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_api_ticket_v1_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketRequest.ProtoReflect.Descriptor instead.
func (*GetTicketRequest) Descriptor() ([]byte, []int) {
	return file_bilibili_api_ticket_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *GetTicketRequest) GetContext() map[string][]byte {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetTicketRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *GetTicketRequest) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

func (x *GetTicketRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Source: com/bapis/bilibili/api/ticket/v1/GetTicketResponse.java
type GetTicketResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ticket    string                     `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	CreatedAt int64                      `protobuf:"varint,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Ttl       int64                      `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Context   *GetTicketResponse_Context `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
}

func (x *GetTicketResponse) Reset() {
	*x = GetTicketResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_api_ticket_v1_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketResponse) ProtoMessage() {}

func (x *GetTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_api_ticket_v1_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketResponse.ProtoReflect.Descriptor instead.
func (*GetTicketResponse) Descriptor() ([]byte, []int) {
	return file_bilibili_api_ticket_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *GetTicketResponse) GetTicket() string {
	if x != nil {
		return x.Ticket
	}
	return ""
}

func (x *GetTicketResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GetTicketResponse) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *GetTicketResponse) GetContext() *GetTicketResponse_Context {
	if x != nil {
		return x.Context
	}
	return nil
}

// Source: com/bapis/bilibili/api/ticket/v1/GetTicketResponse.java
type GetTicketResponse_Context struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VVoucher string `protobuf:"bytes,1,opt,name=vVoucher,proto3" json:"vVoucher,omitempty"`
}

func (x *GetTicketResponse_Context) Reset() {
	*x = GetTicketResponse_Context{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_api_ticket_v1_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTicketResponse_Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketResponse_Context) ProtoMessage() {}

func (x *GetTicketResponse_Context) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_api_ticket_v1_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketResponse_Context.ProtoReflect.Descriptor instead.
func (*GetTicketResponse_Context) Descriptor() ([]byte, []int) {
	return file_bilibili_api_ticket_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *GetTicketResponse_Context) GetVVoucher() string {
	if x != nil {
		return x.VVoucher
	}
	return ""
}

var File_bilibili_api_ticket_v1_messages_proto protoreflect.FileDescriptor

var file_bilibili_api_ticket_v1_messages_proto_rawDesc = []byte{
	0x0a, 0x25, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x20, 0x63, 0x6f, 0x6d, 0x2e, 0x62, 0x61, 0x70,
	0x69, 0x73, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x22, 0xf5, 0x01, 0x0a, 0x13, 0x47, 0x65,
	0x6e, 0x57, 0x65, 0x62, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x5c, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x42, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x62, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x62,
	0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x6e, 0x57, 0x65, 0x62, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78,
	0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x6b, 0x65, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6b, 0x65, 0x79, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x78, 0x73, 0x69, 0x67, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x65, 0x78, 0x73, 0x69, 0x67, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x3a, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x86, 0x02, 0x0a, 0x14, 0x47, 0x65, 0x6e, 0x57, 0x65, 0x62, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x74, 0x74, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x74,
	0x74, 0x6c, 0x12, 0x58, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x3e, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x62, 0x61, 0x70, 0x69, 0x73, 0x2e,
	0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x6e, 0x57, 0x65, 0x62, 0x54, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x78, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x4c, 0x0a, 0x03,
	0x6e, 0x61, 0x76, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3a, 0x2e, 0x63, 0x6f, 0x6d, 0x2e,
	0x62, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x6e,
	0x57, 0x65, 0x62, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x5f, 0x4e, 0x61, 0x76, 0x52, 0x03, 0x6e, 0x61, 0x76, 0x22, 0x3a, 0x0a, 0x1c, 0x47, 0x65,
	0x6e, 0x57, 0x65, 0x62, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x5f, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x56,
	0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x76, 0x56,
	0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x22, 0x3e, 0x0a, 0x18, 0x47, 0x65, 0x6e, 0x57, 0x65, 0x62,
	0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x4e,
	0x61, 0x76, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x6d, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x69, 0x6d, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x75, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x73, 0x75, 0x62, 0x22, 0xe9, 0x01, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x54, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x59, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3f, 0x2e, 0x63,
	0x6f, 0x6d, 0x2e, 0x62, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c,
	0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6b, 0x65, 0x79, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6b, 0x65, 0x79, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x69, 0x67, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x69, 0x67, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x3a, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78,
	0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0xb2, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x74, 0x74, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x74, 0x74, 0x6c,
	0x12, 0x55, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x3b, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x62, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x62, 0x69,
	0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x22, 0x37, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x54, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x78, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x76, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72,
	0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73,
	0x74, 0x6d, 0x74, 0x63, 0x32, 0x33, 0x33, 0x2f, 0x62, 0x69, 0x6c, 0x69, 0x2d, 0x67, 0x72, 0x70,
	0x63, 0x2d, 0x61, 0x70, 0x69, 0x2d, 0x67, 0x6f, 0x2f, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c,
	0x69, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x2f, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bilibili_api_ticket_v1_messages_proto_rawDescOnce sync.Once
	file_bilibili_api_ticket_v1_messages_proto_rawDescData = file_bilibili_api_ticket_v1_messages_proto_rawDesc
)

func file_bilibili_api_ticket_v1_messages_proto_rawDescGZIP() []byte {
	file_bilibili_api_ticket_v1_messages_proto_rawDescOnce.Do(func() {
		file_bilibili_api_ticket_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_bilibili_api_ticket_v1_messages_proto_rawDescData)
	})
	return file_bilibili_api_ticket_v1_messages_proto_rawDescData
}

var file_bilibili_api_ticket_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_bilibili_api_ticket_v1_messages_proto_goTypes = []interface{}{
	(*GenWebTicketRequest)(nil),          // 0: com.bapis.bilibili.api.ticket.v1.GenWebTicketRequest
	(*GenWebTicketResponse)(nil),         // 1: com.bapis.bilibili.api.ticket.v1.GenWebTicketResponse
	(*GenWebTicketResponse_Context)(nil), // 2: com.bapis.bilibili.api.ticket.v1.GenWebTicketResponse_Context
	(*GenWebTicketResponse_Nav)(nil),     // 3: com.bapis.bilibili.api.ticket.v1.GenWebTicketResponse_Nav
	(*GetTicketRequest)(nil),             // 4: com.bapis.bilibili.api.ticket.v1.GetTicketRequest
	(*GetTicketResponse)(nil),            // 5: com.bapis.bilibili.api.ticket.v1.GetTicketResponse
	(*GetTicketResponse_Context)(nil),    // 6: com.bapis.bilibili.api.ticket.v1.GetTicketResponse_Context
	nil,                                  // 7: com.bapis.bilibili.api.ticket.v1.GenWebTicketRequest.ContextEntry
	nil,                                  // 8: com.bapis.bilibili.api.ticket.v1.GetTicketRequest.ContextEntry
}
var file_bilibili_api_ticket_v1_messages_proto_depIdxs = []int32{
	7, // 0: com.bapis.bilibili.api.ticket.v1.GenWebTicketRequest.context:type_name -> com.bapis.bilibili.api.ticket.v1.GenWebTicketRequest.ContextEntry
	2, // 1: com.bapis.bilibili.api.ticket.v1.GenWebTicketResponse.context:type_name -> com.bapis.bilibili.api.ticket.v1.GenWebTicketResponse_Context
	3, // 2: com.bapis.bilibili.api.ticket.v1.GenWebTicketResponse.nav:type_name -> com.bapis.bilibili.api.ticket.v1.GenWebTicketResponse_Nav
	8, // 3: com.bapis.bilibili.api.ticket.v1.GetTicketRequest.context:type_name -> com.bapis.bilibili.api.ticket.v1.GetTicketRequest.ContextEntry
	6, // 4: com.bapis.bilibili.api.ticket.v1.GetTicketResponse.context:type_name -> com.bapis.bilibili.api.ticket.v1.GetTicketResponse_Context
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_bilibili_api_ticket_v1_messages_proto_init() }
func file_bilibili_api_ticket_v1_messages_proto_init() {
	if File_bilibili_api_ticket_v1_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bilibili_api_ticket_v1_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenWebTicketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_api_ticket_v1_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenWebTicketResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_api_ticket_v1_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenWebTicketResponse_Context); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_api_ticket_v1_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenWebTicketResponse_Nav); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_api_ticket_v1_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTicketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_api_ticket_v1_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTicketResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_api_ticket_v1_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTicketResponse_Context); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bilibili_api_ticket_v1_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bilibili_api_ticket_v1_messages_proto_goTypes,
		DependencyIndexes: file_bilibili_api_ticket_v1_messages_proto_depIdxs,
		MessageInfos:      file_bilibili_api_ticket_v1_messages_proto_msgTypes,
	}.Build()
	File_bilibili_api_ticket_v1_messages_proto = out.File
	file_bilibili_api_ticket_v1_messages_proto_rawDesc = nil
	file_bilibili_api_ticket_v1_messages_proto_goTypes = nil
	file_bilibili_api_ticket_v1_messages_proto_depIdxs = nil
}
