// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.api.ticket.v1;

// Source: com/bapis/bilibili/api/ticket/v1/GenWebTicketRequest.java
message GenWebTicketRequest {
  map<string, string> context = 1;
  string keyId = 2;
  string hexsign = 3;
  string token = 4;
}

// Source: com/bapis/bilibili/api/ticket/v1/GenWebTicketResponse.java
message GenWebTicketResponse {
  string ticket = 1;
  int64 createdAt = 2;
  int64 ttl = 3;
  GenWebTicketResponse_Context context = 4;
  GenWebTicketResponse_Nav nav = 5;
}

// Source: com/bapis/bilibili/api/ticket/v1/GenWebTicketResponse.java
message GenWebTicketResponse_Context {
  string vVoucher = 1;
}

// Source: com/bapis/bilibili/api/ticket/v1/GenWebTicketResponse.java
message GenWebTicketResponse_Nav {
  string img = 1;
  string sub = 2;
}

// Source: com/bapis/bilibili/api/ticket/v1/GetTicketRequest.java
message GetTicketRequest {
  map<string, bytes> context = 1;
  string keyId = 2;
  bytes sign = 3;
  string token = 4;
}

// Source: com/bapis/bilibili/api/ticket/v1/GetTicketResponse.java
message GetTicketResponse {
  string ticket = 1;
  int64 createdAt = 2;
  int64 ttl = 3;
  GetTicketResponse_Context context = 4;
}

// Source: com/bapis/bilibili/api/ticket/v1/GetTicketResponse.java
message GetTicketResponse_Context {
  string vVoucher = 1;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/api/ticket/v1";
