// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.pangu.gallery.v1;

enum GT14Status {
  LT14 = 0;
  GE14 = 1;
  UNKNOWN_GT14 = 2;
  UNRECOGNIZED = -1;
}

enum NFTStatus {
  UNDEFINED = 0;
  NORMAL = 1;
  DOING = 2;
  UNRECOGNIZED = -1;
}

enum PolicyAgreeStatus {
  UNSIGNED = 0;
  ACCEPTED = 1;
  EXPIRED = 2;
  UNRECOGNIZED = -1;
}

enum PolicyType {
  UNKNOWN_POLICY = 0;
  WALLET = 1;
  SALE = 2;
  UNRECOGNIZED = -1;
}

enum RecordType {
  All = 0;
  input = 1;
  output = 2;
  UNRECOGNIZED = -1;
}

// Source: com/bapis/bilibili/pangu/gallery/v1/AgreePolicyReply.java
message AgreePolicyReply {
}

// Source: com/bapis/bilibili/pangu/gallery/v1/AgreePolicyReq.java
message AgreePolicyReq {
  PolicyType policyType = 1;
  string version = 2;
}

// Source: com/bapis/bilibili/pangu/gallery/v1/BannerInfo.java
message BannerInfo {
  string imageUrl = 1;
  string link = 2;
  string title = 3;
}

// Source: com/bapis/bilibili/pangu/gallery/v1/BasicInfoReply.java
message BasicInfoReply {
  string customerServiceUrl = 1;
  string agreementUrl = 2;
  string privacyUrl = 3;
  repeated Link links = 4;
}

// Source: com/bapis/bilibili/pangu/gallery/v1/BasicInfoReq.java
message BasicInfoReq {
  int64 mid = 1;
}

// Source: com/bapis/bilibili/pangu/gallery/v1/Display.java
message Display {
  string bgThemeLight = 1;
  string bgThemeNight = 2;
  string nftPoster = 3;
  string nftRaw = 4;
}

// Source: com/bapis/bilibili/pangu/gallery/v1/GetBannersReply.java
message GetBannersReply {
  repeated BannerInfo bannerList = 1;
}

// Source: com/bapis/bilibili/pangu/gallery/v1/GetBannersReq.java
message GetBannersReq {
  int64 uid = 1;
}

// Source: com/bapis/bilibili/pangu/gallery/v1/GetLastPolicyReply.java
message GetLastPolicyReply {
  string shortDesc = 1;
  string detailJump = 2;
  string version = 3;
}

// Source: com/bapis/bilibili/pangu/gallery/v1/GetLastPolicyReq.java
message GetLastPolicyReq {
  PolicyType policyType = 1;
}

// Source: com/bapis/bilibili/pangu/gallery/v1/GetUserInfoReply.java
message GetUserInfoReply {
  int64 mid = 1;
  string name = 2;
  string address = 3;
  string avatarUrl = 4;
  string helpUrl = 5;
}

// Source: com/bapis/bilibili/pangu/gallery/v1/GetUserInfoReq.java
message GetUserInfoReq {
  int64 mid = 1;
}

// Source: com/bapis/bilibili/pangu/gallery/v1/Link.java
message Link {
  string name = 1;
  string linkUrl = 2;
  string trackEventId = 3;
}

// Source: com/bapis/bilibili/pangu/gallery/v1/ListNFTByMidReply.java
message ListNFTByMidReply {
  repeated NFT nfts = 1;
  int64 anchorId = 2;
  bool end = 3;
}

// Source: com/bapis/bilibili/pangu/gallery/v1/ListNFTByMidReq.java
message ListNFTByMidReq {
  int64 mid = 1;
  string category = 2;
  string bizType = 3;
  int64 anchorId = 4;
  int64 pageSize = 5;
}

// Source: com/bapis/bilibili/pangu/gallery/v1/ListOrderByMidReply.java
message ListOrderByMidReply {
  repeated Order orders = 1;
  int64 anchorId = 2;
  bool end = 3;
}

// Source: com/bapis/bilibili/pangu/gallery/v1/ListOrderByMidReq.java
message ListOrderByMidReq {
  int64 mid = 1;
  int64 anchorId = 2;
  int64 pageSize = 3;
  RecordType rcType = 4;
}

// Source: com/bapis/bilibili/pangu/gallery/v1/MinePageReply.java
message MinePageReply {
  int64 uid = 1;
  string name = 2;
  string address = 3;
  string avatarUrl = 4;
  string questionJump = 5;
  string aboutUsJump = 6;
}

// Source: com/bapis/bilibili/pangu/gallery/v1/MinePageReq.java
message MinePageReq {
  int64 uid = 1;
}

// Source: com/bapis/bilibili/pangu/gallery/v1/NFT.java
message NFT {
  string nftId = 1;
  string itemName = 2;
  string serialNumber = 3;
  string issuer = 4;
  Display display = 5;
  string detailUrl = 6;
  NFTStatus nftStatus = 7;
  int64 itemId = 8;
}

// Source: com/bapis/bilibili/pangu/gallery/v1/Order.java
message Order {
  string itemName = 1;
  string serialNumber = 2;
  string txHash = 3;
  string txTime = 4;
  string issuer = 5;
  string issueTime = 6;
  string tokenId = 7;
  Display display = 8;
  string contractAddress = 9;
  string hashJump = 10;
  string contractJump = 11;
  bool disableBrowserJump = 12;
}

// Source: com/bapis/bilibili/pangu/gallery/v1/UserCheckReply.java
message UserCheckReply {
  PolicyAgreeStatus policyStatus = 1;
  GT14Status gt14 = 2;
}

// Source: com/bapis/bilibili/pangu/gallery/v1/UserCheckReq.java
message UserCheckReq {
  int64 mid = 1;
  PolicyType policyType = 2;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/pangu/gallery/v1";
