// Reconstructed from gRPC service descriptors.
syntax = "proto3";

package bilibili.app.view.v1;

import "bilibili/app/view/v1/messages.proto";

service LegacyView {
  rpc Like(.com.bapis.bilibili.app.view.v1.LikeReq) returns (.com.bapis.bilibili.app.view.v1.LikeReply);
}

service View {
  rpc AddContract(.com.bapis.bilibili.app.view.v1.AddContractReq) returns (.com.bapis.bilibili.app.view.v1.NoReply);
  rpc CacheView(.com.bapis.bilibili.app.view.v1.CacheViewReq) returns (.com.bapis.bilibili.app.view.v1.CacheViewReply);
  rpc ChronosPkg(.com.bapis.bilibili.app.view.v1.ChronosPkgReq) returns (.com.bapis.bilibili.app.view.v1.Chronos);
  rpc ClickActivitySeason(.com.bapis.bilibili.app.view.v1.ClickActivitySeasonReq) returns (.com.bapis.bilibili.app.view.v1.NoReply);
  rpc ClickPlayerCard(.com.bapis.bilibili.app.view.v1.ClickPlayerCardReq) returns (.com.bapis.bilibili.app.view.v1.NoReply);
  rpc ClickPlayerCardV2(.com.bapis.bilibili.app.view.v1.ClickPlayerCardReq) returns (.com.bapis.bilibili.app.view.v1.ClickPlayerCardReply);
  rpc ContinuousPlay(.com.bapis.bilibili.app.view.v1.ContinuousPlayReq) returns (.com.bapis.bilibili.app.view.v1.ContinuousPlayReply);
  rpc ExposePlayerCard(.com.bapis.bilibili.app.view.v1.ExposePlayerCardReq) returns (.com.bapis.bilibili.app.view.v1.NoReply);
  rpc FeedView(.com.bapis.bilibili.app.view.v1.FeedViewReq) returns (.com.bapis.bilibili.app.view.v1.FeedViewReply);
  rpc GetArcsPlayer(.com.bapis.bilibili.app.view.v1.GetArcsPlayerReq) returns (.com.bapis.bilibili.app.view.v1.GetArcsPlayerReply);
  rpc GetUser(.com.bapis.bilibili.app.view.v1.GetUserReq) returns (.com.bapis.bilibili.app.view.v1.GetUserReply);
  rpc PlayerRelates(.com.bapis.bilibili.app.view.v1.PlayerRelatesReq) returns (.com.bapis.bilibili.app.view.v1.PlayerRelatesReply);
  rpc PremiereArchive(.com.bapis.bilibili.app.view.v1.PremiereArchiveReq) returns (.com.bapis.bilibili.app.view.v1.PremiereArchiveReply);
  rpc RelatesFeed(.com.bapis.bilibili.app.view.v1.RelatesFeedReq) returns (.com.bapis.bilibili.app.view.v1.RelatesFeedReply);
  rpc Reserve(.com.bapis.bilibili.app.view.v1.ReserveReq) returns (.com.bapis.bilibili.app.view.v1.ReserveReply);
  rpc Season(.com.bapis.bilibili.app.view.v1.SeasonReq) returns (.com.bapis.bilibili.app.view.v1.SeasonReply);
  rpc SeasonActivityRecord(.com.bapis.bilibili.app.view.v1.SeasonActivityRecordReq) returns (.com.bapis.bilibili.app.view.v1.SeasonActivityRecordReply);
  rpc SeasonWidgetExpose(.com.bapis.bilibili.app.view.v1.SeasonWidgetExposeReq) returns (.com.bapis.bilibili.app.view.v1.SeasonWidgetExposeReply);
  rpc ShortFormVideoDownload(.com.bapis.bilibili.app.view.v1.ShortFormVideoDownloadReq) returns (.com.bapis.bilibili.app.view.v1.ShortFormVideoDownloadReply);
  rpc TFInfo(.com.bapis.bilibili.app.view.v1.TFInfoReq) returns (.com.bapis.bilibili.app.view.v1.TFInfoReply);
  rpc View(.com.bapis.bilibili.app.view.v1.ViewReq) returns (.com.bapis.bilibili.app.view.v1.ViewReply);
  rpc ViewMaterial(.com.bapis.bilibili.app.view.v1.ViewMaterialReq) returns (.com.bapis.bilibili.app.view.v1.ViewMaterialReply);
  rpc ViewProgress(.com.bapis.bilibili.app.view.v1.ViewProgressReq) returns (.com.bapis.bilibili.app.view.v1.ViewProgressReply);
  rpc ViewTag(.com.bapis.bilibili.app.view.v1.ViewTagReq) returns (.com.bapis.bilibili.app.view.v1.ViewTagReply);
}

option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/app/view/v1";
