// Reconstructed from gRPC service descriptors.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: bilibili/app/view/v1/services.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	View_ChronosPkg_FullMethodName             = "/bilibili.app.view.v1.View/ChronosPkg"
	View_ClickActivitySeason_FullMethodName    = "/bilibili.app.view.v1.View/ClickActivitySeason"
	View_ClickPlayerCard_FullMethodName        = "/bilibili.app.view.v1.View/ClickPlayerCard"
	View_ExposePlayerCard_FullMethodName       = "/bilibili.app.view.v1.View/ExposePlayerCard"
	View_Season_FullMethodName                 = "/bilibili.app.view.v1.View/Season"
	View_ShortFormVideoDownload_FullMethodName = "/bilibili.app.view.v1.View/ShortFormVideoDownload"
	View_View_FullMethodName                   = "/bilibili.app.view.v1.View/View"
	View_ViewProgress_FullMethodName           = "/bilibili.app.view.v1.View/ViewProgress"
)

// ViewClient is the client API for View service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ViewClient interface {
	ChronosPkg(ctx context.Context, in *ChronosPkgReq, opts ...grpc.CallOption) (*Chronos, error)
	ClickActivitySeason(ctx context.Context, in *ClickActivitySeasonReq, opts ...grpc.CallOption) (*NoReply, error)
	ClickPlayerCard(ctx context.Context, in *ClickPlayerCardReq, opts ...grpc.CallOption) (*NoReply, error)
	ExposePlayerCard(ctx context.Context, in *ExposePlayerCardReq, opts ...grpc.CallOption) (*NoReply, error)
	Season(ctx context.Context, in *SeasonReq, opts ...grpc.CallOption) (*SeasonReply, error)
	ShortFormVideoDownload(ctx context.Context, in *ShortFormVideoDownloadReq, opts ...grpc.CallOption) (*ShortFormVideoDownloadReply, error)
	View(ctx context.Context, in *ViewReq, opts ...grpc.CallOption) (*ViewReply, error)
	ViewProgress(ctx context.Context, in *ViewProgressReq, opts ...grpc.CallOption) (*ViewProgressReply, error)
}

type viewClient struct {
	cc grpc.ClientConnInterface
}

func NewViewClient(cc grpc.ClientConnInterface) ViewClient {
	return &viewClient{cc}
}

func (c *viewClient) ChronosPkg(ctx context.Context, in *ChronosPkgReq, opts ...grpc.CallOption) (*Chronos, error) {
	out := new(Chronos)
	err := c.cc.Invoke(ctx, View_ChronosPkg_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *viewClient) ClickActivitySeason(ctx context.Context, in *ClickActivitySeasonReq, opts ...grpc.CallOption) (*NoReply, error) {
	out := new(NoReply)
	err := c.cc.Invoke(ctx, View_ClickActivitySeason_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *viewClient) ClickPlayerCard(ctx context.Context, in *ClickPlayerCardReq, opts ...grpc.CallOption) (*NoReply, error) {
	out := new(NoReply)
	err := c.cc.Invoke(ctx, View_ClickPlayerCard_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *viewClient) ExposePlayerCard(ctx context.Context, in *ExposePlayerCardReq, opts ...grpc.CallOption) (*NoReply, error) {
	out := new(NoReply)
	err := c.cc.Invoke(ctx, View_ExposePlayerCard_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *viewClient) Season(ctx context.Context, in *SeasonReq, opts ...grpc.CallOption) (*SeasonReply, error) {
	out := new(SeasonReply)
	err := c.cc.Invoke(ctx, View_Season_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *viewClient) ShortFormVideoDownload(ctx context.Context, in *ShortFormVideoDownloadReq, opts ...grpc.CallOption) (*ShortFormVideoDownloadReply, error) {
	out := new(ShortFormVideoDownloadReply)
	err := c.cc.Invoke(ctx, View_ShortFormVideoDownload_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *viewClient) View(ctx context.Context, in *ViewReq, opts ...grpc.CallOption) (*ViewReply, error) {
	out := new(ViewReply)
	err := c.cc.Invoke(ctx, View_View_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *viewClient) ViewProgress(ctx context.Context, in *ViewProgressReq, opts ...grpc.CallOption) (*ViewProgressReply, error) {
	out := new(ViewProgressReply)
	err := c.cc.Invoke(ctx, View_ViewProgress_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ViewServer is the server API for View service.
// All implementations must embed UnimplementedViewServer
// for forward compatibility
type ViewServer interface {
	ChronosPkg(context.Context, *ChronosPkgReq) (*Chronos, error)
	ClickActivitySeason(context.Context, *ClickActivitySeasonReq) (*NoReply, error)
	ClickPlayerCard(context.Context, *ClickPlayerCardReq) (*NoReply, error)
	ExposePlayerCard(context.Context, *ExposePlayerCardReq) (*NoReply, error)
	Season(context.Context, *SeasonReq) (*SeasonReply, error)
	ShortFormVideoDownload(context.Context, *ShortFormVideoDownloadReq) (*ShortFormVideoDownloadReply, error)
	View(context.Context, *ViewReq) (*ViewReply, error)
	ViewProgress(context.Context, *ViewProgressReq) (*ViewProgressReply, error)
	mustEmbedUnimplementedViewServer()
}

// UnimplementedViewServer must be embedded to have forward compatible implementations.
type UnimplementedViewServer struct {
}

func (UnimplementedViewServer) ChronosPkg(context.Context, *ChronosPkgReq) (*Chronos, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChronosPkg not implemented")
}
func (UnimplementedViewServer) ClickActivitySeason(context.Context, *ClickActivitySeasonReq) (*NoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClickActivitySeason not implemented")
}
func (UnimplementedViewServer) ClickPlayerCard(context.Context, *ClickPlayerCardReq) (*NoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClickPlayerCard not implemented")
}
func (UnimplementedViewServer) ExposePlayerCard(context.Context, *ExposePlayerCardReq) (*NoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExposePlayerCard not implemented")
}
func (UnimplementedViewServer) Season(context.Context, *SeasonReq) (*SeasonReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Season not implemented")
}
func (UnimplementedViewServer) ShortFormVideoDownload(context.Context, *ShortFormVideoDownloadReq) (*ShortFormVideoDownloadReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShortFormVideoDownload not implemented")
}
func (UnimplementedViewServer) View(context.Context, *ViewReq) (*ViewReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method View not implemented")
}
func (UnimplementedViewServer) ViewProgress(context.Context, *ViewProgressReq) (*ViewProgressReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewProgress not implemented")
}
func (UnimplementedViewServer) mustEmbedUnimplementedViewServer() {}

// UnsafeViewServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ViewServer will
// result in compilation errors.
type UnsafeViewServer interface {
	mustEmbedUnimplementedViewServer()
}

func RegisterViewServer(s grpc.ServiceRegistrar, srv ViewServer) {
	s.RegisterService(&View_ServiceDesc, srv)
}

func _View_ChronosPkg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChronosPkgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ViewServer).ChronosPkg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: View_ChronosPkg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ViewServer).ChronosPkg(ctx, req.(*ChronosPkgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _View_ClickActivitySeason_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClickActivitySeasonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ViewServer).ClickActivitySeason(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: View_ClickActivitySeason_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ViewServer).ClickActivitySeason(ctx, req.(*ClickActivitySeasonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _View_ClickPlayerCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClickPlayerCardReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ViewServer).ClickPlayerCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: View_ClickPlayerCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ViewServer).ClickPlayerCard(ctx, req.(*ClickPlayerCardReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _View_ExposePlayerCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExposePlayerCardReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ViewServer).ExposePlayerCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: View_ExposePlayerCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ViewServer).ExposePlayerCard(ctx, req.(*ExposePlayerCardReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _View_Season_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeasonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ViewServer).Season(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: View_Season_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ViewServer).Season(ctx, req.(*SeasonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _View_ShortFormVideoDownload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortFormVideoDownloadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ViewServer).ShortFormVideoDownload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: View_ShortFormVideoDownload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ViewServer).ShortFormVideoDownload(ctx, req.(*ShortFormVideoDownloadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _View_View_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ViewServer).View(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: View_View_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ViewServer).View(ctx, req.(*ViewReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _View_ViewProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewProgressReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ViewServer).ViewProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: View_ViewProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ViewServer).ViewProgress(ctx, req.(*ViewProgressReq))
	}
	return interceptor(ctx, in, info, handler)
}

// View_ServiceDesc is the grpc.ServiceDesc for View service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var View_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bilibili.app.view.v1.View",
	HandlerType: (*ViewServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChronosPkg",
			Handler:    _View_ChronosPkg_Handler,
		},
		{
			MethodName: "ClickActivitySeason",
			Handler:    _View_ClickActivitySeason_Handler,
		},
		{
			MethodName: "ClickPlayerCard",
			Handler:    _View_ClickPlayerCard_Handler,
		},
		{
			MethodName: "ExposePlayerCard",
			Handler:    _View_ExposePlayerCard_Handler,
		},
		{
			MethodName: "Season",
			Handler:    _View_Season_Handler,
		},
		{
			MethodName: "ShortFormVideoDownload",
			Handler:    _View_ShortFormVideoDownload_Handler,
		},
		{
			MethodName: "View",
			Handler:    _View_View_Handler,
		},
		{
			MethodName: "ViewProgress",
			Handler:    _View_ViewProgress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bilibili/app/view/v1/services.proto",
}
