// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.dynamic.interfaces.vote.v1;

// Source: com/bapis/bilibili/dynamic/interfaces/vote/v1/NewDoVoteReq.java
message NewDoVoteReq {
  int64 voteId = 1;
  repeated int32 votes = 2;
  int32 status = 3;
  int64 dynamicId = 4;
  int64 opBit = 5;
}

// Source: com/bapis/bilibili/dynamic/interfaces/vote/v1/NewDoVoteRsp.java
message NewDoVoteRsp {
  int64 uid = 1;
  int32 type = 2;
  VoteInfo voteInfo = 3;
}

// Source: com/bapis/bilibili/dynamic/interfaces/vote/v1/VoteBizInfo.java
message VoteBizInfo {
  int64 bizId = 1;
  int32 bizType = 2;
  string bizExt = 3;
}

// Source: com/bapis/bilibili/dynamic/interfaces/vote/v1/VoteInfo.java
message VoteInfo {
  int64 voteId = 1;
  string title = 2;
  string desc = 3;
  int64 joinNum = 4;
  int32 type = 5;
  int32 choiceCnt = 6;
  int64 endTime = 7;
  int32 status = 8;
  int64 votePublisher = 9;
  int32 defaultShare = 10;
  int64 ctime = 11;
  int32 bizType = 12;
  string imgUrl = 13;
  repeated int32 myVotes = 14;
  repeated VoteOptionInfo options = 15;
  int32 optionsCnt = 16;
  int64 startTime = 17;
  int64 voterUid = 18;
  int32 voterLevel = 19;
  int64 duration = 20;
  repeated VoteBizInfo voteBizInfo = 21;
  string face = 22;
  string name = 23;
  int64 onlyFansLevel = 24;
}

// Source: com/bapis/bilibili/dynamic/interfaces/vote/v1/VoteOptionInfo.java
message VoteOptionInfo {
  int32 optIdx = 1;
  string optDesc = 2;
  string imgUrl = 3;
  int32 cnt = 4;
  string btnStr = 5;
  string title = 6;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/dynamic/interfaces/vote/v1";
