// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.broadcast.message.bgroup;

enum AppEvent {
  AppEventUnknown = 0;
  AppEventVisible = 1;
  AppEventInvisible = 2;
  AppEventHomePage = 3;
  AppEventColdStart = 4;
  UNRECOGNIZED = -1;
}

// Source: com/bapis/bilibili/broadcast/message/bgroup/AppEventMessage.java
message AppEventMessage {
  AppEvent eventType = 1;
  int64 timestamp = 2;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/broadcast/message/bgroup";
