// Reconstructed from gRPC service descriptors.
syntax = "proto3";

package bilibili.community.service.dm.v1;

import "bilibili/community/service/dm/v1/messages.proto";

service DM {
  rpc DmExpoReport(.com.bapis.bilibili.community.service.dm.v1.DmExpoReportReq) returns (.com.bapis.bilibili.community.service.dm.v1.DmExpoReportRes);
  rpc DmPlayerConfig(.com.bapis.bilibili.community.service.dm.v1.DmPlayerConfigReq) returns (.com.bapis.bilibili.community.service.dm.v1.Response);
  rpc DmSegMobile(.com.bapis.bilibili.community.service.dm.v1.DmSegMobileReq) returns (.com.bapis.bilibili.community.service.dm.v1.DmSegMobileReply);
  rpc DmSegOtt(.com.bapis.bilibili.community.service.dm.v1.DmSegOttReq) returns (.com.bapis.bilibili.community.service.dm.v1.DmSegOttReply);
  rpc DmSegSDK(.com.bapis.bilibili.community.service.dm.v1.DmSegSDKReq) returns (.com.bapis.bilibili.community.service.dm.v1.DmSegSDKReply);
  rpc DmView(.com.bapis.bilibili.community.service.dm.v1.DmViewReq) returns (.com.bapis.bilibili.community.service.dm.v1.DmViewReply);
}

option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/community/service/dm/v1";
