// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.app.story.v1;

// Source: com/bapis/bilibili/app/story/v1/AIAudioItem.java
message AIAudioItem {
  repeated DashItem audioInfo = 1;
  string title = 2;
  string buttonTitle = 3;
  string subtitleLang = 4;
}

// Source: com/bapis/bilibili/app/story/v1/AIAudioReply.java
message AIAudioReply {
  bool supportAiAudio = 1;
  repeated AIAudioItem aiAudioItems = 2;
  string aiOpenToast = 3;
  string aiCloseToast = 4;
  Language language = 5;
}

// Source: com/bapis/bilibili/app/story/v1/AIAudioReq.java
message AIAudioReq {
  int64 aid = 1;
  int64 cid = 2;
  int64 upMid = 3;
}

// Source: com/bapis/bilibili/app/story/v1/ArchiveStatusReply.java
message ArchiveStatusReply {
  bool isArchiveNormal = 1;
}

// Source: com/bapis/bilibili/app/story/v1/ArchiveStatusReq.java
message ArchiveStatusReq {
  int64 aid = 1;
}

// Source: com/bapis/bilibili/app/story/v1/BgmPlayReply.java
message BgmPlayReply {
  string url = 1;
}

// Source: com/bapis/bilibili/app/story/v1/BgmPlayReq.java
message BgmPlayReq {
  int64 musicId = 1;
}

// Source: com/bapis/bilibili/app/story/v1/BottomDiversionEntranceReply.java
message BottomDiversionEntranceReply {
  repeated DiversionEntranceInfo diversionEntranceList = 1;
}

// Source: com/bapis/bilibili/app/story/v1/BottomDiversionEntranceReq.java
message BottomDiversionEntranceReq {
  repeated StoryCardInfo cardInfo = 1;
  string trackId = 2;
  int64 fromAv = 3;
  string fromBv = 4;
  int64 displayId = 5;
}

// Source: com/bapis/bilibili/app/story/v1/DashItem.java
message DashItem {
  uint32 id = 1;
  string baseUrl = 2;
  repeated string backupUrl = 3;
  uint32 bandwidth = 4;
  uint32 codecid = 5;
  string md5 = 6;
  uint64 size = 7;
  string frameRate = 8;
  string widevinePssh = 9;
  string bilidrmUri = 10;
}

// Source: com/bapis/bilibili/app/story/v1/DiversionEntrance.java
message DiversionEntrance {
  string icon = 1;
  string jumpUri = 2;
  string title = 3;
  int64 type = 4;
  string trackInfo = 5;
  string textColor = 6;
}

// Source: com/bapis/bilibili/app/story/v1/DiversionEntranceInfo.java
message DiversionEntranceInfo {
  StoryCardInfo cardInfo = 1;
  DiversionEntrance diversionEntrance = 2;
}

// Source: com/bapis/bilibili/app/story/v1/Language.java
message Language {
  repeated LanguageItem items = 1;
}

// Source: com/bapis/bilibili/app/story/v1/LanguageItem.java
message LanguageItem {
  string lang = 1;
  string title = 2;
  string buttonTitle = 3;
  string subtitleLang = 4;
  bool videoDetext = 5;
}

// Source: com/bapis/bilibili/app/story/v1/LatestCardInfo.java
message LatestCardInfo {
  uint32 vt = 1;
  string cardGoto = 2;
  string id = 3;
}

// Source: com/bapis/bilibili/app/story/v1/RerankAdInfo.java
message RerankAdInfo {
  string requestId = 1;
}

// Source: com/bapis/bilibili/app/story/v1/RerankCardInfo.java
message RerankCardInfo {
  int32 displayId = 1;
  int32 displayPos = 2;
  string cardGoto = 3;
  string param = 4;
  map<string, string> playerArgs = 5;
  oneof oneof_0 {
    RerankAdInfo adInfo = 6;
  }
  enum InfoCase {
    INFO_NOT_SET = 0;
    AD_INFO = 6;
  }

}

// Source: com/bapis/bilibili/app/story/v1/RerankReply.java
message RerankReply {
  repeated RerankCardInfo card = 1;
}

// Source: com/bapis/bilibili/app/story/v1/RerankReq.java
message RerankReq {
  int64 preAdStartTs = 1;
  int64 preAdEndTs = 2;
  RerankCardInfo preAdCard = 3;
  int64 lastCardTs = 4;
  RerankCardInfo lastCard = 5;
  repeated RerankCardInfo unexposedCard = 6;
  int32 lastAdGap = 7;
  int64 refreshTs = 8;
  int32 requestFrom = 9;
  repeated LatestCardInfo latestCardsInfo = 10;
}

// Source: com/bapis/bilibili/app/story/v1/StoryCardInfo.java
message StoryCardInfo {
  string cardGoto = 1;
  string param = 2;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/app/story/v1";
