// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.broadcast.message.im;

enum CmdId {
  EN_CMD_ID_INVALID = 0;
  EN_CMD_ID_MSG_NOTIFY = 1;
  EN_CMD_ID_KICK_OUT = 2;
  UNRECOGNIZED = -1;
}

enum PLType {
  EN_PAYLOAD_NORMAL = 0;
  EN_PAYLOAD_BASE64 = 1;
  UNRECOGNIZED = -1;
}

// Source: com/bapis/bilibili/broadcast/message/im/ChatPushSettingChangedCommand.java
message ChatPushSettingChangedCommand {
  SessionId sessionId = 1;
  bool setting = 2;
}

// Source: com/bapis/bilibili/broadcast/message/im/CommandMsg.java
message CommandMsg {
  oneof oneof_0 {
    UpdateTotalUnreadCommand updateTotalUnreadCommand = 1;
    UpdateSessionListCommand updateSessionListCommand = 2;
    UpdateQuickLinkCommand updateQuickLinkCommand = 3;
    FetchMessageCommand fetchMessageCommand = 4;
    UpdateSessionOneCommand updateSessionOneCommand = 5;
    UpdateChatInfoCommand updateChatInfoCommand = 6;
    ChatPushSettingChangedCommand chatPushSettingChangedCommand = 7;
  }
  enum CommandCase {
    COMMAND_NOT_SET = 0;
    UPDATE_TOTAL_UNREAD_COMMAND = 1;
    UPDATE_SESSION_LIST_COMMAND = 2;
    UPDATE_QUICK_LINK_COMMAND = 3;
    FETCH_MESSAGE_COMMAND = 4;
    UPDATE_SESSION_ONE_COMMAND = 5;
    UPDATE_CHAT_INFO_COMMAND = 6;
    CHAT_PUSH_SETTING_CHANGED_COMMAND = 7;
  }

}

// Source: com/bapis/bilibili/broadcast/message/im/FetchMessageCommand.java
message FetchMessageCommand {
  SessionId sessionId = 1;
}

// Source: com/bapis/bilibili/broadcast/message/im/Msg.java
message Msg {
  uint64 senderUid = 1;
  int32 receiverType = 2;
  uint64 receiverId = 3;
  uint64 cliMsgId = 4;
  int32 msgType = 5;
  string content = 6;
  uint64 msgSeqno = 7;
  uint64 timestamp = 8;
  repeated uint64 atUids = 9;
  repeated uint64 recverIds = 10;
  uint64 msgKey = 11;
  uint32 msgStatus = 12;
  bool sysCancel = 13;
  uint32 isMultiChat = 14;
  uint64 withdrawSeqno = 15;
  string notifyCode = 16;
  uint32 msgSource = 17;
}

// Source: com/bapis/bilibili/broadcast/message/im/NotifyInfo.java
message NotifyInfo {
  uint32 msgType = 1;
  uint64 talkerId = 2;
  uint32 sessionType = 3;
}

// Source: com/bapis/bilibili/broadcast/message/im/NotifyRsp.java
message NotifyRsp {
  uint64 uid = 1;
  uint64 cmd = 2;
  bytes payload = 3;
  PLType payloadType = 4;
}

// Source: com/bapis/bilibili/broadcast/message/im/ReqServerNotify.java
message ReqServerNotify {
  uint64 lastestSeqno = 1;
  Msg instantMsg = 2;
  NotifyInfo notifyInfo = 3;
  repeated CommandMsg commandMsgs = 4;
}

// Source: com/bapis/bilibili/broadcast/message/im/UpdateChatInfoCommand.java
message UpdateChatInfoCommand {
  SessionId sessionId = 1;
}

// Source: com/bapis/bilibili/broadcast/message/im/UpdateQuickLinkCommand.java
message UpdateQuickLinkCommand {
}

// Source: com/bapis/bilibili/broadcast/message/im/UpdateSessionListCommand.java
message UpdateSessionListCommand {
}

// Source: com/bapis/bilibili/broadcast/message/im/UpdateSessionOneCommand.java
message UpdateSessionOneCommand {
  SessionId sessionId = 1;
}

// Source: com/bapis/bilibili/broadcast/message/im/UpdateTotalUnreadCommand.java
message UpdateTotalUnreadCommand {
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/broadcast/message/im";
