// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.broadcast.v1;

import "bilibili/rpc/messages.proto";
import "google/protobuf/any.proto";

// Source: com/bapis/bilibili/broadcast/v1/AddParams.java
message AddParams {
  int32 a = 1;
  int32 b = 2;
}

// Source: com/bapis/bilibili/broadcast/v1/AddResult.java
message AddResult {
  int32 r = 1;
}

// Source: com/bapis/bilibili/broadcast/v1/AuthReq.java
message AuthReq {
  string guid = 1;
  string connId = 2;
  int64 lastMsgId = 3;
}

// Source: com/bapis/bilibili/broadcast/v1/AuthResp.java
message AuthResp {
}

// Source: com/bapis/bilibili/broadcast/v1/BroadcastFrame.java
message BroadcastFrame {
  FrameOption options = 1;
  string targetPath = 2;
  google.protobuf.Any body = 3;
}

// Source: com/bapis/bilibili/broadcast/v1/FrameOption.java
message FrameOption {
  int64 messageId = 1;
  int64 sequence = 2;
  bool isAck = 3;
  com.bapis.bilibili.rpc.Status status = 4;
  string ackOrigin = 5;
}

// Source: com/bapis/bilibili/broadcast/v1/HeartbeatReq.java
message HeartbeatReq {
}

// Source: com/bapis/bilibili/broadcast/v1/HeartbeatResp.java
message HeartbeatResp {
}

// Source: com/bapis/bilibili/broadcast/v1/LaserLogUploadResp.java
message LaserLogUploadResp {
  int64 taskid = 1;
  string date = 2;
}

// Source: com/bapis/bilibili/broadcast/v1/MessageAckReq.java
message MessageAckReq {
  int64 ackId = 1;
  string ackOrigin = 2;
  string targetPath = 3;
}

// Source: com/bapis/bilibili/broadcast/v1/ModResourceResp.java
message ModResourceResp {
}

// Source: com/bapis/bilibili/broadcast/v1/PushMessageResp.java
message PushMessageResp {
  int64 oldTaskid = 1;
  Biz biz = 2;
  Type type = 3;
  string title = 4;
  string summary = 5;
  string img = 6;
  string link = 7;
  Position position = 8;
  int32 duration = 9;
  int64 expire = 10;
  string taskid = 11;
  enum Biz {
    BIZ_UNKNOWN = 0;
    BIZ_VIDEO = 1;
    BIZ_LIVE = 2;
    BIZ_ACTIVITY = 3;
  }

  enum Position {
    POS_UNKNOWN = 0;
    POS_TOP = 1;
  }

  enum Type {
    TYPE_UNKNOWN = 0;
    TYPE_DEFAULT = 1;
    TYPE_HOT = 2;
    TYPE_REALTIME = 3;
    TYPE_RECOMMEND = 4;
  }

}

// Source: com/bapis/bilibili/broadcast/v1/RoomErrorEvent.java
message RoomErrorEvent {
  com.bapis.bilibili.rpc.Status status = 1;
}

// Source: com/bapis/bilibili/broadcast/v1/RoomJoinEvent.java
message RoomJoinEvent {
}

// Source: com/bapis/bilibili/broadcast/v1/RoomLeaveEvent.java
message RoomLeaveEvent {
}

// Source: com/bapis/bilibili/broadcast/v1/RoomMessageEvent.java
message RoomMessageEvent {
  string targetPath = 1;
  google.protobuf.Any body = 2;
}

// Source: com/bapis/bilibili/broadcast/v1/RoomOnlineEvent.java
message RoomOnlineEvent {
  int32 online = 1;
}

// Source: com/bapis/bilibili/broadcast/v1/RoomReq.java
message RoomReq {
  string id = 1;
  oneof oneof_0 {
    RoomJoinEvent join = 2;
    RoomLeaveEvent leave = 3;
    RoomOnlineEvent online = 4;
    RoomMessageEvent msg = 5;
  }
  enum EventCase {
    EVENT_NOT_SET = 0;
    JOIN = 2;
    LEAVE = 3;
    ONLINE = 4;
    MSG = 5;
  }

}

// Source: com/bapis/bilibili/broadcast/v1/RoomResp.java
message RoomResp {
  string id = 1;
  oneof oneof_0 {
    RoomJoinEvent join = 2;
    RoomLeaveEvent leave = 3;
    RoomOnlineEvent online = 4;
    RoomMessageEvent msg = 5;
    RoomErrorEvent err = 6;
  }
  enum EventCase {
    EVENT_NOT_SET = 0;
    JOIN = 2;
    LEAVE = 3;
    ONLINE = 4;
    MSG = 5;
    ERR = 6;
  }

}

// Source: com/bapis/bilibili/broadcast/v1/TargetPath.java
message TargetPath {
  repeated string targetPaths = 1;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/broadcast/v1";
