// Reconstructed from protobuf-lite metadata in the APK.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: bilibili/live/rtc/messages.proto

package rtc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BAPILiveRTCStreamProto_Codec int32

const (
	BAPILiveRTCStreamProto_Codec_Opus BAPILiveRTCStreamProto_Codec = 0
	BAPILiveRTCStreamProto_Codec_H264 BAPILiveRTCStreamProto_Codec = 1
	BAPILiveRTCStreamProto_Codec_H265 BAPILiveRTCStreamProto_Codec = 2
	BAPILiveRTCStreamProto_Codec_AV1  BAPILiveRTCStreamProto_Codec = 3
)

// Enum value maps for BAPILiveRTCStreamProto_Codec.
var (
	BAPILiveRTCStreamProto_Codec_name = map[int32]string{
		0: "Opus",
		1: "H264",
		2: "H265",
		3: "AV1",
	}
	BAPILiveRTCStreamProto_Codec_value = map[string]int32{
		"Opus": 0,
		"H264": 1,
		"H265": 2,
		"AV1":  3,
	}
)

func (x BAPILiveRTCStreamProto_Codec) Enum() *BAPILiveRTCStreamProto_Codec {
	p := new(BAPILiveRTCStreamProto_Codec)
	*p = x
	return p
}

func (x BAPILiveRTCStreamProto_Codec) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BAPILiveRTCStreamProto_Codec) Descriptor() protoreflect.EnumDescriptor {
	return file_bilibili_live_rtc_messages_proto_enumTypes[0].Descriptor()
}

func (BAPILiveRTCStreamProto_Codec) Type() protoreflect.EnumType {
	return &file_bilibili_live_rtc_messages_proto_enumTypes[0]
}

func (x BAPILiveRTCStreamProto_Codec) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BAPILiveRTCStreamProto_Codec.Descriptor instead.
func (BAPILiveRTCStreamProto_Codec) EnumDescriptor() ([]byte, []int) {
	return file_bilibili_live_rtc_messages_proto_rawDescGZIP(), []int{0}
}

type BAPILiveRTCTokenProto_TurnProtocol int32

const (
	BAPILiveRTCTokenProto_TurnProtocol_UDP BAPILiveRTCTokenProto_TurnProtocol = 0
	BAPILiveRTCTokenProto_TurnProtocol_TCP BAPILiveRTCTokenProto_TurnProtocol = 1
	BAPILiveRTCTokenProto_TurnProtocol_TLS BAPILiveRTCTokenProto_TurnProtocol = 2
)

// Enum value maps for BAPILiveRTCTokenProto_TurnProtocol.
var (
	BAPILiveRTCTokenProto_TurnProtocol_name = map[int32]string{
		0: "UDP",
		1: "TCP",
		2: "TLS",
	}
	BAPILiveRTCTokenProto_TurnProtocol_value = map[string]int32{
		"UDP": 0,
		"TCP": 1,
		"TLS": 2,
	}
)

func (x BAPILiveRTCTokenProto_TurnProtocol) Enum() *BAPILiveRTCTokenProto_TurnProtocol {
	p := new(BAPILiveRTCTokenProto_TurnProtocol)
	*p = x
	return p
}

func (x BAPILiveRTCTokenProto_TurnProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BAPILiveRTCTokenProto_TurnProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_bilibili_live_rtc_messages_proto_enumTypes[1].Descriptor()
}

func (BAPILiveRTCTokenProto_TurnProtocol) Type() protoreflect.EnumType {
	return &file_bilibili_live_rtc_messages_proto_enumTypes[1]
}

func (x BAPILiveRTCTokenProto_TurnProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BAPILiveRTCTokenProto_TurnProtocol.Descriptor instead.
func (BAPILiveRTCTokenProto_TurnProtocol) EnumDescriptor() ([]byte, []int) {
	return file_bilibili_live_rtc_messages_proto_rawDescGZIP(), []int{1}
}

type BAPILiveRTCUserProto_UserLeaveReason int32

const (
	BAPILiveRTCUserProto_UserLeaveReason_NORMAL    BAPILiveRTCUserProto_UserLeaveReason = 0
	BAPILiveRTCUserProto_UserLeaveReason_KICKED    BAPILiveRTCUserProto_UserLeaveReason = 1
	BAPILiveRTCUserProto_UserLeaveReason_TIMEOUT   BAPILiveRTCUserProto_UserLeaveReason = 2
	BAPILiveRTCUserProto_UserLeaveReason_KILLED    BAPILiveRTCUserProto_UserLeaveReason = 3
	BAPILiveRTCUserProto_UserLeaveReason_RECONNECT BAPILiveRTCUserProto_UserLeaveReason = 4
)

// Enum value maps for BAPILiveRTCUserProto_UserLeaveReason.
var (
	BAPILiveRTCUserProto_UserLeaveReason_name = map[int32]string{
		0: "NORMAL",
		1: "KICKED",
		2: "TIMEOUT",
		3: "KILLED",
		4: "RECONNECT",
	}
	BAPILiveRTCUserProto_UserLeaveReason_value = map[string]int32{
		"NORMAL":    0,
		"KICKED":    1,
		"TIMEOUT":   2,
		"KILLED":    3,
		"RECONNECT": 4,
	}
)

func (x BAPILiveRTCUserProto_UserLeaveReason) Enum() *BAPILiveRTCUserProto_UserLeaveReason {
	p := new(BAPILiveRTCUserProto_UserLeaveReason)
	*p = x
	return p
}

func (x BAPILiveRTCUserProto_UserLeaveReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BAPILiveRTCUserProto_UserLeaveReason) Descriptor() protoreflect.EnumDescriptor {
	return file_bilibili_live_rtc_messages_proto_enumTypes[2].Descriptor()
}

func (BAPILiveRTCUserProto_UserLeaveReason) Type() protoreflect.EnumType {
	return &file_bilibili_live_rtc_messages_proto_enumTypes[2]
}

func (x BAPILiveRTCUserProto_UserLeaveReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BAPILiveRTCUserProto_UserLeaveReason.Descriptor instead.
func (BAPILiveRTCUserProto_UserLeaveReason) EnumDescriptor() ([]byte, []int) {
	return file_bilibili_live_rtc_messages_proto_rawDescGZIP(), []int{2}
}

type BAPILiveRTCUserProto_UserRole int32

const (
	BAPILiveRTCUserProto_UserRole_Normal   BAPILiveRTCUserProto_UserRole = 0
	BAPILiveRTCUserProto_UserRole_Audience BAPILiveRTCUserProto_UserRole = 1
	BAPILiveRTCUserProto_UserRole_Monitor  BAPILiveRTCUserProto_UserRole = 2
	BAPILiveRTCUserProto_UserRole_Relay    BAPILiveRTCUserProto_UserRole = 3
	BAPILiveRTCUserProto_UserRole_App      BAPILiveRTCUserProto_UserRole = 4
	BAPILiveRTCUserProto_UserRole_Mix      BAPILiveRTCUserProto_UserRole = 5
	BAPILiveRTCUserProto_UserRole_Unknown  BAPILiveRTCUserProto_UserRole = 99
)

// Enum value maps for BAPILiveRTCUserProto_UserRole.
var (
	BAPILiveRTCUserProto_UserRole_name = map[int32]string{
		0:  "Normal",
		1:  "Audience",
		2:  "Monitor",
		3:  "Relay",
		4:  "App",
		5:  "Mix",
		99: "Unknown",
	}
	BAPILiveRTCUserProto_UserRole_value = map[string]int32{
		"Normal":   0,
		"Audience": 1,
		"Monitor":  2,
		"Relay":    3,
		"App":      4,
		"Mix":      5,
		"Unknown":  99,
	}
)

func (x BAPILiveRTCUserProto_UserRole) Enum() *BAPILiveRTCUserProto_UserRole {
	p := new(BAPILiveRTCUserProto_UserRole)
	*p = x
	return p
}

func (x BAPILiveRTCUserProto_UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BAPILiveRTCUserProto_UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_bilibili_live_rtc_messages_proto_enumTypes[3].Descriptor()
}

func (BAPILiveRTCUserProto_UserRole) Type() protoreflect.EnumType {
	return &file_bilibili_live_rtc_messages_proto_enumTypes[3]
}

func (x BAPILiveRTCUserProto_UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BAPILiveRTCUserProto_UserRole.Descriptor instead.
func (BAPILiveRTCUserProto_UserRole) EnumDescriptor() ([]byte, []int) {
	return file_bilibili_live_rtc_messages_proto_rawDescGZIP(), []int{3}
}

type BAPILiveRTCStreamProto_StreamMeta_MetadataCase int32

const (
	BAPILiveRTCStreamProto_StreamMeta_METADATA_NOT_SET BAPILiveRTCStreamProto_StreamMeta_MetadataCase = 0
	BAPILiveRTCStreamProto_StreamMeta_AUDIO            BAPILiveRTCStreamProto_StreamMeta_MetadataCase = 2
	BAPILiveRTCStreamProto_StreamMeta_VIDEO            BAPILiveRTCStreamProto_StreamMeta_MetadataCase = 3
)

// Enum value maps for BAPILiveRTCStreamProto_StreamMeta_MetadataCase.
var (
	BAPILiveRTCStreamProto_StreamMeta_MetadataCase_name = map[int32]string{
		0: "METADATA_NOT_SET",
		2: "AUDIO",
		3: "VIDEO",
	}
	BAPILiveRTCStreamProto_StreamMeta_MetadataCase_value = map[string]int32{
		"METADATA_NOT_SET": 0,
		"AUDIO":            2,
		"VIDEO":            3,
	}
)

func (x BAPILiveRTCStreamProto_StreamMeta_MetadataCase) Enum() *BAPILiveRTCStreamProto_StreamMeta_MetadataCase {
	p := new(BAPILiveRTCStreamProto_StreamMeta_MetadataCase)
	*p = x
	return p
}

func (x BAPILiveRTCStreamProto_StreamMeta_MetadataCase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BAPILiveRTCStreamProto_StreamMeta_MetadataCase) Descriptor() protoreflect.EnumDescriptor {
	return file_bilibili_live_rtc_messages_proto_enumTypes[4].Descriptor()
}

func (BAPILiveRTCStreamProto_StreamMeta_MetadataCase) Type() protoreflect.EnumType {
	return &file_bilibili_live_rtc_messages_proto_enumTypes[4]
}

func (x BAPILiveRTCStreamProto_StreamMeta_MetadataCase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BAPILiveRTCStreamProto_StreamMeta_MetadataCase.Descriptor instead.
func (BAPILiveRTCStreamProto_StreamMeta_MetadataCase) EnumDescriptor() ([]byte, []int) {
	return file_bilibili_live_rtc_messages_proto_rawDescGZIP(), []int{1, 0}
}

// Source: com/bapis/bilibili/live/rtc/BAPILiveRTCStreamProto$AudioMetaData.java
type BAPILiveRTCStreamProto_AudioMetaData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channels   int64 `protobuf:"varint,1,opt,name=channels,proto3" json:"channels,omitempty"`
	Samplerate int64 `protobuf:"varint,2,opt,name=samplerate,proto3" json:"samplerate,omitempty"`
	Payload    int64 `protobuf:"varint,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Ssrc       int32 `protobuf:"varint,4,opt,name=ssrc,proto3" json:"ssrc,omitempty"`
}

func (x *BAPILiveRTCStreamProto_AudioMetaData) Reset() {
	*x = BAPILiveRTCStreamProto_AudioMetaData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_live_rtc_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BAPILiveRTCStreamProto_AudioMetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BAPILiveRTCStreamProto_AudioMetaData) ProtoMessage() {}

func (x *BAPILiveRTCStreamProto_AudioMetaData) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_live_rtc_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BAPILiveRTCStreamProto_AudioMetaData.ProtoReflect.Descriptor instead.
func (*BAPILiveRTCStreamProto_AudioMetaData) Descriptor() ([]byte, []int) {
	return file_bilibili_live_rtc_messages_proto_rawDescGZIP(), []int{0}
}

func (x *BAPILiveRTCStreamProto_AudioMetaData) GetChannels() int64 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *BAPILiveRTCStreamProto_AudioMetaData) GetSamplerate() int64 {
	if x != nil {
		return x.Samplerate
	}
	return 0
}

func (x *BAPILiveRTCStreamProto_AudioMetaData) GetPayload() int64 {
	if x != nil {
		return x.Payload
	}
	return 0
}

func (x *BAPILiveRTCStreamProto_AudioMetaData) GetSsrc() int32 {
	if x != nil {
		return x.Ssrc
	}
	return 0
}

// Source: com/bapis/bilibili/live/rtc/BAPILiveRTCStreamProto$StreamMeta.java
type BAPILiveRTCStreamProto_StreamMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Codec BAPILiveRTCStreamProto_Codec `protobuf:"varint,1,opt,name=codec,proto3,enum=com.bapis.bilibili.live.rtc.BAPILiveRTCStreamProto_Codec" json:"codec,omitempty"`
	// Types that are assignable to Oneof_0:
	//
	//	*BAPILiveRTCStreamProto_StreamMeta_Audio
	//	*BAPILiveRTCStreamProto_StreamMeta_Video
	Oneof_0 isBAPILiveRTCStreamProto_StreamMeta_Oneof_0 `protobuf_oneof:"oneof_0"`
}

func (x *BAPILiveRTCStreamProto_StreamMeta) Reset() {
	*x = BAPILiveRTCStreamProto_StreamMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_live_rtc_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BAPILiveRTCStreamProto_StreamMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BAPILiveRTCStreamProto_StreamMeta) ProtoMessage() {}

func (x *BAPILiveRTCStreamProto_StreamMeta) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_live_rtc_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BAPILiveRTCStreamProto_StreamMeta.ProtoReflect.Descriptor instead.
func (*BAPILiveRTCStreamProto_StreamMeta) Descriptor() ([]byte, []int) {
	return file_bilibili_live_rtc_messages_proto_rawDescGZIP(), []int{1}
}

func (x *BAPILiveRTCStreamProto_StreamMeta) GetCodec() BAPILiveRTCStreamProto_Codec {
	if x != nil {
		return x.Codec
	}
	return BAPILiveRTCStreamProto_Codec_Opus
}

func (m *BAPILiveRTCStreamProto_StreamMeta) GetOneof_0() isBAPILiveRTCStreamProto_StreamMeta_Oneof_0 {
	if m != nil {
		return m.Oneof_0
	}
	return nil
}

func (x *BAPILiveRTCStreamProto_StreamMeta) GetAudio() *BAPILiveRTCStreamProto_AudioMetaData {
	if x, ok := x.GetOneof_0().(*BAPILiveRTCStreamProto_StreamMeta_Audio); ok {
		return x.Audio
	}
	return nil
}

func (x *BAPILiveRTCStreamProto_StreamMeta) GetVideo() *BAPILiveRTCStreamProto_VideoMetaData {
	if x, ok := x.GetOneof_0().(*BAPILiveRTCStreamProto_StreamMeta_Video); ok {
		return x.Video
	}
	return nil
}

type isBAPILiveRTCStreamProto_StreamMeta_Oneof_0 interface {
	isBAPILiveRTCStreamProto_StreamMeta_Oneof_0()
}

type BAPILiveRTCStreamProto_StreamMeta_Audio struct {
	Audio *BAPILiveRTCStreamProto_AudioMetaData `protobuf:"bytes,2,opt,name=audio,proto3,oneof"`
}

type BAPILiveRTCStreamProto_StreamMeta_Video struct {
	Video *BAPILiveRTCStreamProto_VideoMetaData `protobuf:"bytes,3,opt,name=video,proto3,oneof"`
}

func (*BAPILiveRTCStreamProto_StreamMeta_Audio) isBAPILiveRTCStreamProto_StreamMeta_Oneof_0() {}

func (*BAPILiveRTCStreamProto_StreamMeta_Video) isBAPILiveRTCStreamProto_StreamMeta_Oneof_0() {}

// Source: com/bapis/bilibili/live/rtc/BAPILiveRTCStreamProto$VideoMetaData.java
type BAPILiveRTCStreamProto_VideoMetaData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload int64 `protobuf:"varint,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Ssrc    int32 `protobuf:"varint,2,opt,name=ssrc,proto3" json:"ssrc,omitempty"`
}

func (x *BAPILiveRTCStreamProto_VideoMetaData) Reset() {
	*x = BAPILiveRTCStreamProto_VideoMetaData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_live_rtc_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BAPILiveRTCStreamProto_VideoMetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BAPILiveRTCStreamProto_VideoMetaData) ProtoMessage() {}

func (x *BAPILiveRTCStreamProto_VideoMetaData) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_live_rtc_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BAPILiveRTCStreamProto_VideoMetaData.ProtoReflect.Descriptor instead.
func (*BAPILiveRTCStreamProto_VideoMetaData) Descriptor() ([]byte, []int) {
	return file_bilibili_live_rtc_messages_proto_rawDescGZIP(), []int{2}
}

func (x *BAPILiveRTCStreamProto_VideoMetaData) GetPayload() int64 {
	if x != nil {
		return x.Payload
	}
	return 0
}

func (x *BAPILiveRTCStreamProto_VideoMetaData) GetSsrc() int32 {
	if x != nil {
		return x.Ssrc
	}
	return 0
}

// Source: com/bapis/bilibili/live/rtc/BAPILiveRTCTokenProto$AccessToken.java
type BAPILiveRTCTokenProto_AccessToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelId       uint64                          `protobuf:"varint,1,opt,name=channelId,proto3" json:"channelId,omitempty"`
	Uid             uint64                          `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Token           string                          `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Addr            []string                        `protobuf:"bytes,4,rep,name=addr,proto3" json:"addr,omitempty"`
	Fingerprint     string                          `protobuf:"bytes,5,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Password        string                          `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	HttpDns         []string                        `protobuf:"bytes,7,rep,name=httpDns,proto3" json:"httpDns,omitempty"`
	Version         uint32                          `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	BusinessName    string                          `protobuf:"bytes,9,opt,name=businessName,proto3" json:"businessName,omitempty"`
	TurnAddr        *BAPILiveRTCTokenProto_TurnAddr `protobuf:"bytes,10,opt,name=turnAddr,proto3" json:"turnAddr,omitempty"`
	MediaServerName string                          `protobuf:"bytes,11,opt,name=mediaServerName,proto3" json:"mediaServerName,omitempty"`
}

func (x *BAPILiveRTCTokenProto_AccessToken) Reset() {
	*x = BAPILiveRTCTokenProto_AccessToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_live_rtc_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BAPILiveRTCTokenProto_AccessToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BAPILiveRTCTokenProto_AccessToken) ProtoMessage() {}

func (x *BAPILiveRTCTokenProto_AccessToken) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_live_rtc_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BAPILiveRTCTokenProto_AccessToken.ProtoReflect.Descriptor instead.
func (*BAPILiveRTCTokenProto_AccessToken) Descriptor() ([]byte, []int) {
	return file_bilibili_live_rtc_messages_proto_rawDescGZIP(), []int{3}
}

func (x *BAPILiveRTCTokenProto_AccessToken) GetChannelId() uint64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *BAPILiveRTCTokenProto_AccessToken) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *BAPILiveRTCTokenProto_AccessToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *BAPILiveRTCTokenProto_AccessToken) GetAddr() []string {
	if x != nil {
		return x.Addr
	}
	return nil
}

func (x *BAPILiveRTCTokenProto_AccessToken) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *BAPILiveRTCTokenProto_AccessToken) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *BAPILiveRTCTokenProto_AccessToken) GetHttpDns() []string {
	if x != nil {
		return x.HttpDns
	}
	return nil
}

func (x *BAPILiveRTCTokenProto_AccessToken) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BAPILiveRTCTokenProto_AccessToken) GetBusinessName() string {
	if x != nil {
		return x.BusinessName
	}
	return ""
}

func (x *BAPILiveRTCTokenProto_AccessToken) GetTurnAddr() *BAPILiveRTCTokenProto_TurnAddr {
	if x != nil {
		return x.TurnAddr
	}
	return nil
}

func (x *BAPILiveRTCTokenProto_AccessToken) GetMediaServerName() string {
	if x != nil {
		return x.MediaServerName
	}
	return ""
}

// Source: com/bapis/bilibili/live/rtc/BAPILiveRTCTokenProto$Token.java
type BAPILiveRTCTokenProto_Token struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelId uint64                        `protobuf:"varint,1,opt,name=channelId,proto3" json:"channelId,omitempty"`
	Uid       uint64                        `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Timestamp uint64                        `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Role      BAPILiveRTCUserProto_UserRole `protobuf:"varint,4,opt,name=role,proto3,enum=com.bapis.bilibili.live.rtc.BAPILiveRTCUserProto_UserRole" json:"role,omitempty"`
}

func (x *BAPILiveRTCTokenProto_Token) Reset() {
	*x = BAPILiveRTCTokenProto_Token{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_live_rtc_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BAPILiveRTCTokenProto_Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BAPILiveRTCTokenProto_Token) ProtoMessage() {}

func (x *BAPILiveRTCTokenProto_Token) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_live_rtc_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BAPILiveRTCTokenProto_Token.ProtoReflect.Descriptor instead.
func (*BAPILiveRTCTokenProto_Token) Descriptor() ([]byte, []int) {
	return file_bilibili_live_rtc_messages_proto_rawDescGZIP(), []int{4}
}

func (x *BAPILiveRTCTokenProto_Token) GetChannelId() uint64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *BAPILiveRTCTokenProto_Token) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *BAPILiveRTCTokenProto_Token) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BAPILiveRTCTokenProto_Token) GetRole() BAPILiveRTCUserProto_UserRole {
	if x != nil {
		return x.Role
	}
	return BAPILiveRTCUserProto_UserRole_Normal
}

// Source: com/bapis/bilibili/live/rtc/BAPILiveRTCTokenProto$TurnAddr.java
type BAPILiveRTCTokenProto_TurnAddr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string                               `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string                               `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Addr     []string                             `protobuf:"bytes,3,rep,name=addr,proto3" json:"addr,omitempty"`
	Protocol []BAPILiveRTCTokenProto_TurnProtocol `protobuf:"varint,4,rep,packed,name=protocol,proto3,enum=com.bapis.bilibili.live.rtc.BAPILiveRTCTokenProto_TurnProtocol" json:"protocol,omitempty"`
	TurnOnly bool                                 `protobuf:"varint,5,opt,name=turnOnly,proto3" json:"turnOnly,omitempty"`
}

func (x *BAPILiveRTCTokenProto_TurnAddr) Reset() {
	*x = BAPILiveRTCTokenProto_TurnAddr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_live_rtc_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BAPILiveRTCTokenProto_TurnAddr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BAPILiveRTCTokenProto_TurnAddr) ProtoMessage() {}

func (x *BAPILiveRTCTokenProto_TurnAddr) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_live_rtc_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BAPILiveRTCTokenProto_TurnAddr.ProtoReflect.Descriptor instead.
func (*BAPILiveRTCTokenProto_TurnAddr) Descriptor() ([]byte, []int) {
	return file_bilibili_live_rtc_messages_proto_rawDescGZIP(), []int{5}
}

func (x *BAPILiveRTCTokenProto_TurnAddr) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BAPILiveRTCTokenProto_TurnAddr) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *BAPILiveRTCTokenProto_TurnAddr) GetAddr() []string {
	if x != nil {
		return x.Addr
	}
	return nil
}

func (x *BAPILiveRTCTokenProto_TurnAddr) GetProtocol() []BAPILiveRTCTokenProto_TurnProtocol {
	if x != nil {
		return x.Protocol
	}
	return nil
}

func (x *BAPILiveRTCTokenProto_TurnAddr) GetTurnOnly() bool {
	if x != nil {
		return x.TurnOnly
	}
	return false
}

// Source: com/bapis/bilibili/live/rtc/BAPILiveRTCUserProto$CodecCapability.java
type BAPILiveRTCUserProto_CodecCapability struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Av1  bool `protobuf:"varint,1,opt,name=av1,proto3" json:"av1,omitempty"`
	H265 bool `protobuf:"varint,2,opt,name=h265,proto3" json:"h265,omitempty"`
}

func (x *BAPILiveRTCUserProto_CodecCapability) Reset() {
	*x = BAPILiveRTCUserProto_CodecCapability{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_live_rtc_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BAPILiveRTCUserProto_CodecCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BAPILiveRTCUserProto_CodecCapability) ProtoMessage() {}

func (x *BAPILiveRTCUserProto_CodecCapability) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_live_rtc_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BAPILiveRTCUserProto_CodecCapability.ProtoReflect.Descriptor instead.
func (*BAPILiveRTCUserProto_CodecCapability) Descriptor() ([]byte, []int) {
	return file_bilibili_live_rtc_messages_proto_rawDescGZIP(), []int{6}
}

func (x *BAPILiveRTCUserProto_CodecCapability) GetAv1() bool {
	if x != nil {
		return x.Av1
	}
	return false
}

func (x *BAPILiveRTCUserProto_CodecCapability) GetH265() bool {
	if x != nil {
		return x.H265
	}
	return false
}

// Source: com/bapis/bilibili/live/rtc/BAPILiveRTCUserProto$Stream.java
type BAPILiveRTCUserProto_Stream struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HasVideo      bool   `protobuf:"varint,1,opt,name=hasVideo,proto3" json:"hasVideo,omitempty"`
	HasAudio      bool   `protobuf:"varint,2,opt,name=hasAudio,proto3" json:"hasAudio,omitempty"`
	AudioMuted    bool   `protobuf:"varint,3,opt,name=audioMuted,proto3" json:"audioMuted,omitempty"`
	VideoMuted    bool   `protobuf:"varint,4,opt,name=videoMuted,proto3" json:"videoMuted,omitempty"`
	VideoCount    uint32 `protobuf:"varint,5,opt,name=videoCount,proto3" json:"videoCount,omitempty"`
	TemporalCount uint32 `protobuf:"varint,6,opt,name=temporalCount,proto3" json:"temporalCount,omitempty"`
}

func (x *BAPILiveRTCUserProto_Stream) Reset() {
	*x = BAPILiveRTCUserProto_Stream{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_live_rtc_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BAPILiveRTCUserProto_Stream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BAPILiveRTCUserProto_Stream) ProtoMessage() {}

func (x *BAPILiveRTCUserProto_Stream) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_live_rtc_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BAPILiveRTCUserProto_Stream.ProtoReflect.Descriptor instead.
func (*BAPILiveRTCUserProto_Stream) Descriptor() ([]byte, []int) {
	return file_bilibili_live_rtc_messages_proto_rawDescGZIP(), []int{7}
}

func (x *BAPILiveRTCUserProto_Stream) GetHasVideo() bool {
	if x != nil {
		return x.HasVideo
	}
	return false
}

func (x *BAPILiveRTCUserProto_Stream) GetHasAudio() bool {
	if x != nil {
		return x.HasAudio
	}
	return false
}

func (x *BAPILiveRTCUserProto_Stream) GetAudioMuted() bool {
	if x != nil {
		return x.AudioMuted
	}
	return false
}

func (x *BAPILiveRTCUserProto_Stream) GetVideoMuted() bool {
	if x != nil {
		return x.VideoMuted
	}
	return false
}

func (x *BAPILiveRTCUserProto_Stream) GetVideoCount() uint32 {
	if x != nil {
		return x.VideoCount
	}
	return 0
}

func (x *BAPILiveRTCUserProto_Stream) GetTemporalCount() uint32 {
	if x != nil {
		return x.TemporalCount
	}
	return 0
}

// Source: com/bapis/bilibili/live/rtc/BAPILiveRTCUserProto$User.java
type BAPILiveRTCUserProto_User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid              uint64                                `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Role             BAPILiveRTCUserProto_UserRole         `protobuf:"varint,2,opt,name=role,proto3,enum=com.bapis.bilibili.live.rtc.BAPILiveRTCUserProto_UserRole" json:"role,omitempty"`
	PubStream        *BAPILiveRTCUserProto_Stream          `protobuf:"bytes,3,opt,name=pubStream,proto3" json:"pubStream,omitempty"`
	Platform         string                                `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	SdkVersion       string                                `protobuf:"bytes,5,opt,name=sdkVersion,proto3" json:"sdkVersion,omitempty"`
	DecodeCapability *BAPILiveRTCUserProto_CodecCapability `protobuf:"bytes,6,opt,name=decodeCapability,proto3" json:"decodeCapability,omitempty"`
}

func (x *BAPILiveRTCUserProto_User) Reset() {
	*x = BAPILiveRTCUserProto_User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_live_rtc_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BAPILiveRTCUserProto_User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BAPILiveRTCUserProto_User) ProtoMessage() {}

func (x *BAPILiveRTCUserProto_User) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_live_rtc_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BAPILiveRTCUserProto_User.ProtoReflect.Descriptor instead.
func (*BAPILiveRTCUserProto_User) Descriptor() ([]byte, []int) {
	return file_bilibili_live_rtc_messages_proto_rawDescGZIP(), []int{8}
}

func (x *BAPILiveRTCUserProto_User) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *BAPILiveRTCUserProto_User) GetRole() BAPILiveRTCUserProto_UserRole {
	if x != nil {
		return x.Role
	}
	return BAPILiveRTCUserProto_UserRole_Normal
}

func (x *BAPILiveRTCUserProto_User) GetPubStream() *BAPILiveRTCUserProto_Stream {
	if x != nil {
		return x.PubStream
	}
	return nil
}

func (x *BAPILiveRTCUserProto_User) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *BAPILiveRTCUserProto_User) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *BAPILiveRTCUserProto_User) GetDecodeCapability() *BAPILiveRTCUserProto_CodecCapability {
	if x != nil {
		return x.DecodeCapability
	}
	return nil
}

var File_bilibili_live_rtc_messages_proto protoreflect.FileDescriptor

var file_bilibili_live_rtc_messages_proto_rawDesc = []byte{
	0x0a, 0x20, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2f, 0x6c, 0x69, 0x76, 0x65, 0x2f,
	0x72, 0x74, 0x63, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x1b, 0x63, 0x6f, 0x6d, 0x2e, 0x62, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x62, 0x69,
	0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x6c, 0x69, 0x76, 0x65, 0x2e, 0x72, 0x74, 0x63, 0x22,
	0x90, 0x01, 0x0a, 0x24, 0x42, 0x41, 0x50, 0x49, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x54, 0x43, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x41, 0x75, 0x64, 0x69, 0x6f,
	0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x73, 0x72, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x73,
	0x72, 0x63, 0x22, 0xf1, 0x02, 0x0a, 0x21, 0x42, 0x41, 0x50, 0x49, 0x4c, 0x69, 0x76, 0x65, 0x52,
	0x54, 0x43, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x4f, 0x0a, 0x05, 0x63, 0x6f, 0x64, 0x65,
	0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x39, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x62, 0x61,
	0x70, 0x69, 0x73, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x6c, 0x69, 0x76,
	0x65, 0x2e, 0x72, 0x74, 0x63, 0x2e, 0x42, 0x41, 0x50, 0x49, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x54,
	0x43, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x43, 0x6f, 0x64,
	0x65, 0x63, 0x52, 0x05, 0x63, 0x6f, 0x64, 0x65, 0x63, 0x12, 0x59, 0x0a, 0x05, 0x61, 0x75, 0x64,
	0x69, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x41, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x62,
	0x61, 0x70, 0x69, 0x73, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x6c, 0x69,
	0x76, 0x65, 0x2e, 0x72, 0x74, 0x63, 0x2e, 0x42, 0x41, 0x50, 0x49, 0x4c, 0x69, 0x76, 0x65, 0x52,
	0x54, 0x43, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x41, 0x75,
	0x64, 0x69, 0x6f, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x05, 0x61,
	0x75, 0x64, 0x69, 0x6f, 0x12, 0x59, 0x0a, 0x05, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x41, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x62, 0x61, 0x70, 0x69, 0x73, 0x2e,
	0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x6c, 0x69, 0x76, 0x65, 0x2e, 0x72, 0x74,
	0x63, 0x2e, 0x42, 0x41, 0x50, 0x49, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x54, 0x43, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4d, 0x65,
	0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x05, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x22,
	0x3a, 0x0a, 0x0c, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x43, 0x61, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x10, 0x4d, 0x45, 0x54, 0x41, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x4e, 0x4f, 0x54, 0x5f,
	0x53, 0x45, 0x54, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x55, 0x44, 0x49, 0x4f, 0x10, 0x02,
	0x12, 0x09, 0x0a, 0x05, 0x56, 0x49, 0x44, 0x45, 0x4f, 0x10, 0x03, 0x42, 0x09, 0x0a, 0x07, 0x6f,
	0x6e, 0x65, 0x6f, 0x66, 0x5f, 0x30, 0x22, 0x54, 0x0a, 0x24, 0x42, 0x41, 0x50, 0x49, 0x4c, 0x69,
	0x76, 0x65, 0x52, 0x54, 0x43, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x5f, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x73, 0x72, 0x63,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x73, 0x72, 0x63, 0x22, 0x96, 0x03, 0x0a,
	0x21, 0x42, 0x41, 0x50, 0x49, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x54, 0x43, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x20, 0x0a, 0x0b,
	0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x74,
	0x74, 0x70, 0x44, 0x6e, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x68, 0x74, 0x74,
	0x70, 0x44, 0x6e, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x22,
	0x0a, 0x0c, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x57, 0x0a, 0x08, 0x74, 0x75, 0x72, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x3b, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x62, 0x61, 0x70, 0x69, 0x73,
	0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x6c, 0x69, 0x76, 0x65, 0x2e, 0x72,
	0x74, 0x63, 0x2e, 0x42, 0x41, 0x50, 0x49, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x54, 0x43, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x54, 0x75, 0x72, 0x6e, 0x41, 0x64, 0x64,
	0x72, 0x52, 0x08, 0x74, 0x75, 0x72, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x12, 0x28, 0x0a, 0x0f, 0x6d,
	0x65, 0x64, 0x69, 0x61, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xbb, 0x01, 0x0a, 0x1b, 0x42, 0x41, 0x50, 0x49, 0x4c, 0x69,
	0x76, 0x65, 0x52, 0x54, 0x43, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5f,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x4e, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x3a, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x62, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x62, 0x69,
	0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x6c, 0x69, 0x76, 0x65, 0x2e, 0x72, 0x74, 0x63, 0x2e,
	0x42, 0x41, 0x50, 0x49, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x54, 0x43, 0x55, 0x73, 0x65, 0x72, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x72,
	0x6f, 0x6c, 0x65, 0x22, 0xe5, 0x01, 0x0a, 0x1e, 0x42, 0x41, 0x50, 0x49, 0x4c, 0x69, 0x76, 0x65,
	0x52, 0x54, 0x43, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x54, 0x75,
	0x72, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64,
	0x64, 0x72, 0x12, 0x5b, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0e, 0x32, 0x3f, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x62, 0x61, 0x70, 0x69, 0x73,
	0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x6c, 0x69, 0x76, 0x65, 0x2e, 0x72,
	0x74, 0x63, 0x2e, 0x42, 0x41, 0x50, 0x49, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x54, 0x43, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x54, 0x75, 0x72, 0x6e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12,
	0x1a, 0x0a, 0x08, 0x74, 0x75, 0x72, 0x6e, 0x4f, 0x6e, 0x6c, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x74, 0x75, 0x72, 0x6e, 0x4f, 0x6e, 0x6c, 0x79, 0x22, 0x4c, 0x0a, 0x24, 0x42,
	0x41, 0x50, 0x49, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x54, 0x43, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x5f, 0x43, 0x6f, 0x64, 0x65, 0x63, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x76, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x03, 0x61, 0x76, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x32, 0x36, 0x35, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x04, 0x68, 0x32, 0x36, 0x35, 0x22, 0xdb, 0x01, 0x0a, 0x1b, 0x42, 0x41,
	0x50, 0x49, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x54, 0x43, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x5f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x61, 0x73,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x68, 0x61, 0x73,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x61, 0x73, 0x41, 0x75, 0x64, 0x69,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x68, 0x61, 0x73, 0x41, 0x75, 0x64, 0x69,
	0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x4d, 0x75, 0x74, 0x65, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x4d, 0x75, 0x74, 0x65,
	0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x4d, 0x75, 0x74, 0x65, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x4d, 0x75, 0x74, 0x65,
	0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x24, 0x0a, 0x0d, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x6c, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72,
	0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x80, 0x03, 0x0a, 0x19, 0x42, 0x41, 0x50, 0x49,
	0x4c, 0x69, 0x76, 0x65, 0x52, 0x54, 0x43, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x5f, 0x55, 0x73, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x4e, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3a, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x62, 0x61, 0x70, 0x69,
	0x73, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x6c, 0x69, 0x76, 0x65, 0x2e,
	0x72, 0x74, 0x63, 0x2e, 0x42, 0x41, 0x50, 0x49, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x54, 0x43, 0x55,
	0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c,
	0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x56, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x38, 0x2e, 0x63, 0x6f, 0x6d,
	0x2e, 0x62, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e,
	0x6c, 0x69, 0x76, 0x65, 0x2e, 0x72, 0x74, 0x63, 0x2e, 0x42, 0x41, 0x50, 0x49, 0x4c, 0x69, 0x76,
	0x65, 0x52, 0x54, 0x43, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x52, 0x09, 0x70, 0x75, 0x62, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x73,
	0x64, 0x6b, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x73, 0x64, 0x6b, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x6d, 0x0a, 0x10, 0x64,
	0x65, 0x63, 0x6f, 0x64, 0x65, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x41, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x62, 0x61, 0x70, 0x69,
	0x73, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x6c, 0x69, 0x76, 0x65, 0x2e,
	0x72, 0x74, 0x63, 0x2e, 0x42, 0x41, 0x50, 0x49, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x54, 0x43, 0x55,
	0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x43, 0x6f, 0x64, 0x65, 0x63, 0x43, 0x61,
	0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x10, 0x64, 0x65, 0x63, 0x6f, 0x64, 0x65,
	0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x2a, 0x45, 0x0a, 0x1c, 0x42, 0x41,
	0x50, 0x49, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x54, 0x43, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x43, 0x6f, 0x64, 0x65, 0x63, 0x12, 0x08, 0x0a, 0x04, 0x4f, 0x70,
	0x75, 0x73, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x32, 0x36, 0x34, 0x10, 0x01, 0x12, 0x08,
	0x0a, 0x04, 0x48, 0x32, 0x36, 0x35, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x56, 0x31, 0x10,
	0x03, 0x2a, 0x3f, 0x0a, 0x22, 0x42, 0x41, 0x50, 0x49, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x54, 0x43,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x54, 0x75, 0x72, 0x6e, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x07, 0x0a, 0x03, 0x55, 0x44, 0x50, 0x10, 0x00,
	0x12, 0x07, 0x0a, 0x03, 0x54, 0x43, 0x50, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x54, 0x4c, 0x53,
	0x10, 0x02, 0x2a, 0x66, 0x0a, 0x24, 0x42, 0x41, 0x50, 0x49, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x54,
	0x43, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x4c,
	0x65, 0x61, 0x76, 0x65, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x4f,
	0x52, 0x4d, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4b, 0x49, 0x43, 0x4b, 0x45, 0x44,
	0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x54, 0x49, 0x4d, 0x45, 0x4f, 0x55, 0x54, 0x10, 0x02, 0x12,
	0x0a, 0x0a, 0x06, 0x4b, 0x49, 0x4c, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x52,
	0x45, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x10, 0x04, 0x2a, 0x70, 0x0a, 0x1d, 0x42, 0x41,
	0x50, 0x49, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x54, 0x43, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4e,
	0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x75, 0x64, 0x69, 0x65,
	0x6e, 0x63, 0x65, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72,
	0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x10, 0x03, 0x12, 0x07, 0x0a,
	0x03, 0x41, 0x70, 0x70, 0x10, 0x04, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x69, 0x78, 0x10, 0x05, 0x12,
	0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x63, 0x42, 0x38, 0x5a, 0x36,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x6d, 0x74, 0x63,
	0x32, 0x33, 0x33, 0x2f, 0x62, 0x69, 0x6c, 0x69, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x61, 0x70,
	0x69, 0x2d, 0x67, 0x6f, 0x2f, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2f, 0x6c, 0x69,
	0x76, 0x65, 0x2f, 0x72, 0x74, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bilibili_live_rtc_messages_proto_rawDescOnce sync.Once
	file_bilibili_live_rtc_messages_proto_rawDescData = file_bilibili_live_rtc_messages_proto_rawDesc
)

func file_bilibili_live_rtc_messages_proto_rawDescGZIP() []byte {
	file_bilibili_live_rtc_messages_proto_rawDescOnce.Do(func() {
		file_bilibili_live_rtc_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_bilibili_live_rtc_messages_proto_rawDescData)
	})
	return file_bilibili_live_rtc_messages_proto_rawDescData
}

var file_bilibili_live_rtc_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_bilibili_live_rtc_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_bilibili_live_rtc_messages_proto_goTypes = []interface{}{
	(BAPILiveRTCStreamProto_Codec)(0),                   // 0: com.bapis.bilibili.live.rtc.BAPILiveRTCStreamProto_Codec
	(BAPILiveRTCTokenProto_TurnProtocol)(0),             // 1: com.bapis.bilibili.live.rtc.BAPILiveRTCTokenProto_TurnProtocol
	(BAPILiveRTCUserProto_UserLeaveReason)(0),           // 2: com.bapis.bilibili.live.rtc.BAPILiveRTCUserProto_UserLeaveReason
	(BAPILiveRTCUserProto_UserRole)(0),                  // 3: com.bapis.bilibili.live.rtc.BAPILiveRTCUserProto_UserRole
	(BAPILiveRTCStreamProto_StreamMeta_MetadataCase)(0), // 4: com.bapis.bilibili.live.rtc.BAPILiveRTCStreamProto_StreamMeta.MetadataCase
	(*BAPILiveRTCStreamProto_AudioMetaData)(nil),        // 5: com.bapis.bilibili.live.rtc.BAPILiveRTCStreamProto_AudioMetaData
	(*BAPILiveRTCStreamProto_StreamMeta)(nil),           // 6: com.bapis.bilibili.live.rtc.BAPILiveRTCStreamProto_StreamMeta
	(*BAPILiveRTCStreamProto_VideoMetaData)(nil),        // 7: com.bapis.bilibili.live.rtc.BAPILiveRTCStreamProto_VideoMetaData
	(*BAPILiveRTCTokenProto_AccessToken)(nil),           // 8: com.bapis.bilibili.live.rtc.BAPILiveRTCTokenProto_AccessToken
	(*BAPILiveRTCTokenProto_Token)(nil),                 // 9: com.bapis.bilibili.live.rtc.BAPILiveRTCTokenProto_Token
	(*BAPILiveRTCTokenProto_TurnAddr)(nil),              // 10: com.bapis.bilibili.live.rtc.BAPILiveRTCTokenProto_TurnAddr
	(*BAPILiveRTCUserProto_CodecCapability)(nil),        // 11: com.bapis.bilibili.live.rtc.BAPILiveRTCUserProto_CodecCapability
	(*BAPILiveRTCUserProto_Stream)(nil),                 // 12: com.bapis.bilibili.live.rtc.BAPILiveRTCUserProto_Stream
	(*BAPILiveRTCUserProto_User)(nil),                   // 13: com.bapis.bilibili.live.rtc.BAPILiveRTCUserProto_User
}
var file_bilibili_live_rtc_messages_proto_depIdxs = []int32{
	0,  // 0: com.bapis.bilibili.live.rtc.BAPILiveRTCStreamProto_StreamMeta.codec:type_name -> com.bapis.bilibili.live.rtc.BAPILiveRTCStreamProto_Codec
	5,  // 1: com.bapis.bilibili.live.rtc.BAPILiveRTCStreamProto_StreamMeta.audio:type_name -> com.bapis.bilibili.live.rtc.BAPILiveRTCStreamProto_AudioMetaData
	7,  // 2: com.bapis.bilibili.live.rtc.BAPILiveRTCStreamProto_StreamMeta.video:type_name -> com.bapis.bilibili.live.rtc.BAPILiveRTCStreamProto_VideoMetaData
	10, // 3: com.bapis.bilibili.live.rtc.BAPILiveRTCTokenProto_AccessToken.turnAddr:type_name -> com.bapis.bilibili.live.rtc.BAPILiveRTCTokenProto_TurnAddr
	3,  // 4: com.bapis.bilibili.live.rtc.BAPILiveRTCTokenProto_Token.role:type_name -> com.bapis.bilibili.live.rtc.BAPILiveRTCUserProto_UserRole
	1,  // 5: com.bapis.bilibili.live.rtc.BAPILiveRTCTokenProto_TurnAddr.protocol:type_name -> com.bapis.bilibili.live.rtc.BAPILiveRTCTokenProto_TurnProtocol
	3,  // 6: com.bapis.bilibili.live.rtc.BAPILiveRTCUserProto_User.role:type_name -> com.bapis.bilibili.live.rtc.BAPILiveRTCUserProto_UserRole
	12, // 7: com.bapis.bilibili.live.rtc.BAPILiveRTCUserProto_User.pubStream:type_name -> com.bapis.bilibili.live.rtc.BAPILiveRTCUserProto_Stream
	11, // 8: com.bapis.bilibili.live.rtc.BAPILiveRTCUserProto_User.decodeCapability:type_name -> com.bapis.bilibili.live.rtc.BAPILiveRTCUserProto_CodecCapability
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_bilibili_live_rtc_messages_proto_init() }
func file_bilibili_live_rtc_messages_proto_init() {
	if File_bilibili_live_rtc_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bilibili_live_rtc_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BAPILiveRTCStreamProto_AudioMetaData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_live_rtc_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BAPILiveRTCStreamProto_StreamMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_live_rtc_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BAPILiveRTCStreamProto_VideoMetaData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_live_rtc_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BAPILiveRTCTokenProto_AccessToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_live_rtc_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BAPILiveRTCTokenProto_Token); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_live_rtc_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BAPILiveRTCTokenProto_TurnAddr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_live_rtc_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BAPILiveRTCUserProto_CodecCapability); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_live_rtc_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BAPILiveRTCUserProto_Stream); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_live_rtc_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BAPILiveRTCUserProto_User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_bilibili_live_rtc_messages_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*BAPILiveRTCStreamProto_StreamMeta_Audio)(nil),
		(*BAPILiveRTCStreamProto_StreamMeta_Video)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bilibili_live_rtc_messages_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bilibili_live_rtc_messages_proto_goTypes,
		DependencyIndexes: file_bilibili_live_rtc_messages_proto_depIdxs,
		EnumInfos:         file_bilibili_live_rtc_messages_proto_enumTypes,
		MessageInfos:      file_bilibili_live_rtc_messages_proto_msgTypes,
	}.Build()
	File_bilibili_live_rtc_messages_proto = out.File
	file_bilibili_live_rtc_messages_proto_rawDesc = nil
	file_bilibili_live_rtc_messages_proto_goTypes = nil
	file_bilibili_live_rtc_messages_proto_depIdxs = nil
}
