// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.live.rtc;

enum BAPILiveRTCStreamProto_Codec {
  Opus = 0;
  H264 = 1;
  H265 = 2;
  AV1 = 3;
  UNRECOGNIZED = -1;
}

enum BAPILiveRTCTokenProto_TurnProtocol {
  UDP = 0;
  TCP = 1;
  TLS = 2;
  UNRECOGNIZED = -1;
}

enum BAPILiveRTCUserProto_UserLeaveReason {
  NORMAL = 0;
  KICKED = 1;
  TIMEOUT = 2;
  KILLED = 3;
  RECONNECT = 4;
  UNRECOGNIZED = -1;
}

enum BAPILiveRTCUserProto_UserRole {
  Normal = 0;
  Audience = 1;
  Monitor = 2;
  Relay = 3;
  App = 4;
  Mix = 5;
  Unknown = 99;
  UNRECOGNIZED = -1;
}

// Source: com/bapis/bilibili/live/rtc/BAPILiveRTCStreamProto$AudioMetaData.java
message BAPILiveRTCStreamProto_AudioMetaData {
  int64 channels = 1;
  int64 samplerate = 2;
  int64 payload = 3;
  int32 ssrc = 4;
}

// Source: com/bapis/bilibili/live/rtc/BAPILiveRTCStreamProto$StreamMeta.java
message BAPILiveRTCStreamProto_StreamMeta {
  BAPILiveRTCStreamProto_Codec codec = 1;
  oneof oneof_0 {
    BAPILiveRTCStreamProto_AudioMetaData audio = 2;
    BAPILiveRTCStreamProto_VideoMetaData video = 3;
  }
  enum MetadataCase {
    METADATA_NOT_SET = 0;
    AUDIO = 2;
    VIDEO = 3;
  }

}

// Source: com/bapis/bilibili/live/rtc/BAPILiveRTCStreamProto$VideoMetaData.java
message BAPILiveRTCStreamProto_VideoMetaData {
  int64 payload = 1;
  int32 ssrc = 2;
}

// Source: com/bapis/bilibili/live/rtc/BAPILiveRTCTokenProto$AccessToken.java
message BAPILiveRTCTokenProto_AccessToken {
  uint64 channelId = 1;
  uint64 uid = 2;
  string token = 3;
  repeated string addr = 4;
  string fingerprint = 5;
  string password = 6;
  repeated string httpDns = 7;
  uint32 version = 8;
  string businessName = 9;
  BAPILiveRTCTokenProto_TurnAddr turnAddr = 10;
  string mediaServerName = 11;
}

// Source: com/bapis/bilibili/live/rtc/BAPILiveRTCTokenProto$Token.java
message BAPILiveRTCTokenProto_Token {
  uint64 channelId = 1;
  uint64 uid = 2;
  uint64 timestamp = 3;
  BAPILiveRTCUserProto_UserRole role = 4;
}

// Source: com/bapis/bilibili/live/rtc/BAPILiveRTCTokenProto$TurnAddr.java
message BAPILiveRTCTokenProto_TurnAddr {
  string username = 1;
  string password = 2;
  repeated string addr = 3;
  repeated IntList protocol = 4;
  bool turnOnly = 5;
}

// Source: com/bapis/bilibili/live/rtc/BAPILiveRTCUserProto$CodecCapability.java
message BAPILiveRTCUserProto_CodecCapability {
  bool av1 = 1;
  bool h265 = 2;
}

// Source: com/bapis/bilibili/live/rtc/BAPILiveRTCUserProto$Stream.java
message BAPILiveRTCUserProto_Stream {
  bool hasVideo = 1;
  bool hasAudio = 2;
  bool audioMuted = 3;
  bool videoMuted = 4;
  uint32 videoCount = 5;
  uint32 temporalCount = 6;
}

// Source: com/bapis/bilibili/live/rtc/BAPILiveRTCUserProto$User.java
message BAPILiveRTCUserProto_User {
  uint64 uid = 1;
  BAPILiveRTCUserProto_UserRole role = 2;
  BAPILiveRTCUserProto_Stream pubStream = 3;
  string platform = 4;
  string sdkVersion = 5;
  BAPILiveRTCUserProto_CodecCapability decodeCapability = 6;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/live/rtc";
