// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.pgc.gateway.view.v1;

// Source: com/bapis/bilibili/pgc/gateway/view/v1/PageSectionEpisodesReply.java
message PageSectionEpisodesReply {
  repeated ViewEpisode episodes = 1;
  SectionPagination pagination = 2;
  int32 sectionId = 3;
}

// Source: com/bapis/bilibili/pgc/gateway/view/v1/PageSectionEpisodesReq.java
message PageSectionEpisodesReq {
  int32 teenagersMode = 4;
  int32 lessonsMode = 5;
  string spmid = 6;
  string fromSpmid = 7;
  map<string, string> extraContent = 8;
  int32 sectionId = 9;
  oneof oneof_0 {
    int32 pageIndex = 20;
    int64 cursorEpId = 21;
    int64 aid = 22;
    int64 cid = 23;
  }
  enum LocatorCase {
    PAGE_INDEX = 20;
    CURSOR_EP_ID = 21;
    AID = 22;
    CID = 23;
    LOCATOR_NOT_SET = 0;
  }

}

// Source: com/bapis/bilibili/pgc/gateway/view/v1/SeasonSectionsReply.java
message SeasonSectionsReply {
  repeated SectionData sections = 1;
  Reserve reserve = 2;
  map<int32, SectionPagination> sectionPagination = 3;
}

// Source: com/bapis/bilibili/pgc/gateway/view/v1/SeasonSectionsReq.java
message SeasonSectionsReq {
  int64 aid = 1;
  int32 seasonId = 2;
  int64 epId = 4;
  int32 teenagersMode = 5;
  int32 lessonsMode = 6;
  string spmid = 7;
  string fromSpmid = 8;
  map<string, string> extraContent = 9;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/pgc/gateway/view/v1";
