// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.broadcast.message.dialing;

// Source: com/bapis/bilibili/broadcast/message/dialing/DialingTaskMessage.java
message DialingTaskMessage {
  string dialingtype = 1;
  bytes httpjob = 2;
  bytes tcpjob = 3;
  string resultreportaddress = 4;
  string userisp = 5;
  string userprovince = 6;
  string buvid = 7;
  int64 mid = 8;
  bytes iptonodeid = 9;
}

// Source: com/bapis/bilibili/broadcast/message/dialing/HTTPTask.java
message HTTPTask {
  HTTPTaskPair pairs = 1;
  string size = 2;
  string type = 3;
  int64 ttl = 4;
}

// Source: com/bapis/bilibili/broadcast/message/dialing/HTTPTaskPair.java
message HTTPTaskPair {
  string frompeer = 1;
  repeated string topeers = 2;
  repeated string remotedaddrs = 3;
  string localip = 4;
  string direction = 5;
}

// Source: com/bapis/bilibili/broadcast/message/dialing/TCPTask.java
message TCPTask {
  TCPTaskPair pairs = 1;
  int64 tcppingcnt = 2;
  int64 intervalms = 3;
  int64 ttl = 4;
}

// Source: com/bapis/bilibili/broadcast/message/dialing/TCPTaskPair.java
message TCPTaskPair {
  string frompeer = 1;
  repeated string topeers = 2;
  repeated string remotedaddrs = 3;
  string localip = 4;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/broadcast/message/dialing";
