// Reconstructed from protobuf-lite metadata in the APK.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v7.35.1
// source: bilibili/broadcast/message/dialing/messages.proto

package dialing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Source: com/bapis/bilibili/broadcast/message/dialing/DialingTaskMessage.java
type DialingTaskMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dialingtype         string `protobuf:"bytes,1,opt,name=dialingtype,proto3" json:"dialingtype,omitempty"`
	Httpjob             []byte `protobuf:"bytes,2,opt,name=httpjob,proto3" json:"httpjob,omitempty"`
	Tcpjob              []byte `protobuf:"bytes,3,opt,name=tcpjob,proto3" json:"tcpjob,omitempty"`
	Resultreportaddress string `protobuf:"bytes,4,opt,name=resultreportaddress,proto3" json:"resultreportaddress,omitempty"`
	Userisp             string `protobuf:"bytes,5,opt,name=userisp,proto3" json:"userisp,omitempty"`
	Userprovince        string `protobuf:"bytes,6,opt,name=userprovince,proto3" json:"userprovince,omitempty"`
	Buvid               string `protobuf:"bytes,7,opt,name=buvid,proto3" json:"buvid,omitempty"`
	Mid                 int64  `protobuf:"varint,8,opt,name=mid,proto3" json:"mid,omitempty"`
	Iptonodeid          []byte `protobuf:"bytes,9,opt,name=iptonodeid,proto3" json:"iptonodeid,omitempty"`
}

func (x *DialingTaskMessage) Reset() {
	*x = DialingTaskMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_broadcast_message_dialing_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DialingTaskMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialingTaskMessage) ProtoMessage() {}

func (x *DialingTaskMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_broadcast_message_dialing_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialingTaskMessage.ProtoReflect.Descriptor instead.
func (*DialingTaskMessage) Descriptor() ([]byte, []int) {
	return file_bilibili_broadcast_message_dialing_messages_proto_rawDescGZIP(), []int{0}
}

func (x *DialingTaskMessage) GetDialingtype() string {
	if x != nil {
		return x.Dialingtype
	}
	return ""
}

func (x *DialingTaskMessage) GetHttpjob() []byte {
	if x != nil {
		return x.Httpjob
	}
	return nil
}

func (x *DialingTaskMessage) GetTcpjob() []byte {
	if x != nil {
		return x.Tcpjob
	}
	return nil
}

func (x *DialingTaskMessage) GetResultreportaddress() string {
	if x != nil {
		return x.Resultreportaddress
	}
	return ""
}

func (x *DialingTaskMessage) GetUserisp() string {
	if x != nil {
		return x.Userisp
	}
	return ""
}

func (x *DialingTaskMessage) GetUserprovince() string {
	if x != nil {
		return x.Userprovince
	}
	return ""
}

func (x *DialingTaskMessage) GetBuvid() string {
	if x != nil {
		return x.Buvid
	}
	return ""
}

func (x *DialingTaskMessage) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *DialingTaskMessage) GetIptonodeid() []byte {
	if x != nil {
		return x.Iptonodeid
	}
	return nil
}

// Source: com/bapis/bilibili/broadcast/message/dialing/HTTPTask.java
type HTTPTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pairs *HTTPTaskPair `protobuf:"bytes,1,opt,name=pairs,proto3" json:"pairs,omitempty"`
	Size  string        `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
	Type  string        `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Ttl   int64         `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
}

func (x *HTTPTask) Reset() {
	*x = HTTPTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_broadcast_message_dialing_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HTTPTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPTask) ProtoMessage() {}

func (x *HTTPTask) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_broadcast_message_dialing_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPTask.ProtoReflect.Descriptor instead.
func (*HTTPTask) Descriptor() ([]byte, []int) {
	return file_bilibili_broadcast_message_dialing_messages_proto_rawDescGZIP(), []int{1}
}

func (x *HTTPTask) GetPairs() *HTTPTaskPair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

func (x *HTTPTask) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *HTTPTask) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *HTTPTask) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

// Source: com/bapis/bilibili/broadcast/message/dialing/HTTPTaskPair.java
type HTTPTaskPair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Frompeer     string   `protobuf:"bytes,1,opt,name=frompeer,proto3" json:"frompeer,omitempty"`
	Topeers      []string `protobuf:"bytes,2,rep,name=topeers,proto3" json:"topeers,omitempty"`
	Remotedaddrs []string `protobuf:"bytes,3,rep,name=remotedaddrs,proto3" json:"remotedaddrs,omitempty"`
	Localip      string   `protobuf:"bytes,4,opt,name=localip,proto3" json:"localip,omitempty"`
	Direction    string   `protobuf:"bytes,5,opt,name=direction,proto3" json:"direction,omitempty"`
}

func (x *HTTPTaskPair) Reset() {
	*x = HTTPTaskPair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_broadcast_message_dialing_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HTTPTaskPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPTaskPair) ProtoMessage() {}

func (x *HTTPTaskPair) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_broadcast_message_dialing_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPTaskPair.ProtoReflect.Descriptor instead.
func (*HTTPTaskPair) Descriptor() ([]byte, []int) {
	return file_bilibili_broadcast_message_dialing_messages_proto_rawDescGZIP(), []int{2}
}

func (x *HTTPTaskPair) GetFrompeer() string {
	if x != nil {
		return x.Frompeer
	}
	return ""
}

func (x *HTTPTaskPair) GetTopeers() []string {
	if x != nil {
		return x.Topeers
	}
	return nil
}

func (x *HTTPTaskPair) GetRemotedaddrs() []string {
	if x != nil {
		return x.Remotedaddrs
	}
	return nil
}

func (x *HTTPTaskPair) GetLocalip() string {
	if x != nil {
		return x.Localip
	}
	return ""
}

func (x *HTTPTaskPair) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

// Source: com/bapis/bilibili/broadcast/message/dialing/TCPTask.java
type TCPTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pairs      *TCPTaskPair `protobuf:"bytes,1,opt,name=pairs,proto3" json:"pairs,omitempty"`
	Tcppingcnt int64        `protobuf:"varint,2,opt,name=tcppingcnt,proto3" json:"tcppingcnt,omitempty"`
	Intervalms int64        `protobuf:"varint,3,opt,name=intervalms,proto3" json:"intervalms,omitempty"`
	Ttl        int64        `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
}

func (x *TCPTask) Reset() {
	*x = TCPTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_broadcast_message_dialing_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TCPTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCPTask) ProtoMessage() {}

func (x *TCPTask) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_broadcast_message_dialing_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCPTask.ProtoReflect.Descriptor instead.
func (*TCPTask) Descriptor() ([]byte, []int) {
	return file_bilibili_broadcast_message_dialing_messages_proto_rawDescGZIP(), []int{3}
}

func (x *TCPTask) GetPairs() *TCPTaskPair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

func (x *TCPTask) GetTcppingcnt() int64 {
	if x != nil {
		return x.Tcppingcnt
	}
	return 0
}

func (x *TCPTask) GetIntervalms() int64 {
	if x != nil {
		return x.Intervalms
	}
	return 0
}

func (x *TCPTask) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

// Source: com/bapis/bilibili/broadcast/message/dialing/TCPTaskPair.java
type TCPTaskPair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Frompeer     string   `protobuf:"bytes,1,opt,name=frompeer,proto3" json:"frompeer,omitempty"`
	Topeers      []string `protobuf:"bytes,2,rep,name=topeers,proto3" json:"topeers,omitempty"`
	Remotedaddrs []string `protobuf:"bytes,3,rep,name=remotedaddrs,proto3" json:"remotedaddrs,omitempty"`
	Localip      string   `protobuf:"bytes,4,opt,name=localip,proto3" json:"localip,omitempty"`
}

func (x *TCPTaskPair) Reset() {
	*x = TCPTaskPair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_broadcast_message_dialing_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TCPTaskPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCPTaskPair) ProtoMessage() {}

func (x *TCPTaskPair) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_broadcast_message_dialing_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCPTaskPair.ProtoReflect.Descriptor instead.
func (*TCPTaskPair) Descriptor() ([]byte, []int) {
	return file_bilibili_broadcast_message_dialing_messages_proto_rawDescGZIP(), []int{4}
}

func (x *TCPTaskPair) GetFrompeer() string {
	if x != nil {
		return x.Frompeer
	}
	return ""
}

func (x *TCPTaskPair) GetTopeers() []string {
	if x != nil {
		return x.Topeers
	}
	return nil
}

func (x *TCPTaskPair) GetRemotedaddrs() []string {
	if x != nil {
		return x.Remotedaddrs
	}
	return nil
}

func (x *TCPTaskPair) GetLocalip() string {
	if x != nil {
		return x.Localip
	}
	return ""
}

var File_bilibili_broadcast_message_dialing_messages_proto protoreflect.FileDescriptor

var file_bilibili_broadcast_message_dialing_messages_proto_rawDesc = []byte{
	0x0a, 0x31, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2f, 0x62, 0x72, 0x6f, 0x61, 0x64,
	0x63, 0x61, 0x73, 0x74, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x64, 0x69, 0x61,
	0x6c, 0x69, 0x6e, 0x67, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x2c, 0x63, 0x6f, 0x6d, 0x2e, 0x62, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x62,
	0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73,
	0x74, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x64, 0x69, 0x61, 0x6c, 0x69, 0x6e,
	0x67, 0x22, 0xa0, 0x02, 0x0a, 0x12, 0x44, 0x69, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x73,
	0x6b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x69, 0x61, 0x6c,
	0x69, 0x6e, 0x67, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x69, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x74,
	0x74, 0x70, 0x6a, 0x6f, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x68, 0x74, 0x74,
	0x70, 0x6a, 0x6f, 0x62, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x63, 0x70, 0x6a, 0x6f, 0x62, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x74, 0x63, 0x70, 0x6a, 0x6f, 0x62, 0x12, 0x30, 0x0a, 0x13,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x69, 0x73, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x69, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72,
	0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x75, 0x73, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x62, 0x75, 0x76, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x75, 0x76,
	0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x6d, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x70, 0x74, 0x6f, 0x6e, 0x6f, 0x64, 0x65,
	0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x69, 0x70, 0x74, 0x6f, 0x6e, 0x6f,
	0x64, 0x65, 0x69, 0x64, 0x22, 0x96, 0x01, 0x0a, 0x08, 0x48, 0x54, 0x54, 0x50, 0x54, 0x61, 0x73,
	0x6b, 0x12, 0x50, 0x0a, 0x05, 0x70, 0x61, 0x69, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x3a, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x62, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x62, 0x69, 0x6c,
	0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x64, 0x69, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x2e,
	0x48, 0x54, 0x54, 0x50, 0x54, 0x61, 0x73, 0x6b, 0x50, 0x61, 0x69, 0x72, 0x52, 0x05, 0x70, 0x61,
	0x69, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74,
	0x74, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x74, 0x74, 0x6c, 0x22, 0xa0, 0x01,
	0x0a, 0x0c, 0x48, 0x54, 0x54, 0x50, 0x54, 0x61, 0x73, 0x6b, 0x50, 0x61, 0x69, 0x72, 0x12, 0x1a,
	0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x70, 0x65, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x70, 0x65, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x6f,
	0x70, 0x65, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x74, 0x6f, 0x70,
	0x65, 0x65, 0x72, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x64, 0x61,
	0x64, 0x64, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x64, 0x61, 0x64, 0x64, 0x72, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x6f, 0x63, 0x61,
	0x6c, 0x69, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x63, 0x61, 0x6c,
	0x69, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0xac, 0x01, 0x0a, 0x07, 0x54, 0x43, 0x50, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x4f, 0x0a, 0x05,
	0x70, 0x61, 0x69, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x39, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x62, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69,
	0x2e, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x64, 0x69, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x54, 0x43, 0x50, 0x54, 0x61,
	0x73, 0x6b, 0x50, 0x61, 0x69, 0x72, 0x52, 0x05, 0x70, 0x61, 0x69, 0x72, 0x73, 0x12, 0x1e, 0x0a,
	0x0a, 0x74, 0x63, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x63, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x74, 0x63, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x63, 0x6e, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x6d, 0x73, 0x12, 0x10, 0x0a,
	0x03, 0x74, 0x74, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x74, 0x74, 0x6c, 0x22,
	0x81, 0x01, 0x0a, 0x0b, 0x54, 0x43, 0x50, 0x54, 0x61, 0x73, 0x6b, 0x50, 0x61, 0x69, 0x72, 0x12,
	0x1a, 0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x70, 0x65, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x70, 0x65, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x74,
	0x6f, 0x70, 0x65, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x74, 0x6f,
	0x70, 0x65, 0x65, 0x72, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x64,
	0x61, 0x64, 0x64, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x64, 0x61, 0x64, 0x64, 0x72, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x6f, 0x63,
	0x61, 0x6c, 0x69, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x63, 0x61,
	0x6c, 0x69, 0x70, 0x42, 0x49, 0x5a, 0x47, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x73, 0x74, 0x6d, 0x74, 0x63, 0x32, 0x33, 0x33, 0x2f, 0x62, 0x69, 0x6c, 0x69, 0x2d,
	0x67, 0x72, 0x70, 0x63, 0x2d, 0x61, 0x70, 0x69, 0x2d, 0x67, 0x6f, 0x2f, 0x62, 0x69, 0x6c, 0x69,
	0x62, 0x69, 0x6c, 0x69, 0x2f, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x2f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x64, 0x69, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bilibili_broadcast_message_dialing_messages_proto_rawDescOnce sync.Once
	file_bilibili_broadcast_message_dialing_messages_proto_rawDescData = file_bilibili_broadcast_message_dialing_messages_proto_rawDesc
)

func file_bilibili_broadcast_message_dialing_messages_proto_rawDescGZIP() []byte {
	file_bilibili_broadcast_message_dialing_messages_proto_rawDescOnce.Do(func() {
		file_bilibili_broadcast_message_dialing_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_bilibili_broadcast_message_dialing_messages_proto_rawDescData)
	})
	return file_bilibili_broadcast_message_dialing_messages_proto_rawDescData
}

var file_bilibili_broadcast_message_dialing_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_bilibili_broadcast_message_dialing_messages_proto_goTypes = []interface{}{
	(*DialingTaskMessage)(nil), // 0: com.bapis.bilibili.broadcast.message.dialing.DialingTaskMessage
	(*HTTPTask)(nil),           // 1: com.bapis.bilibili.broadcast.message.dialing.HTTPTask
	(*HTTPTaskPair)(nil),       // 2: com.bapis.bilibili.broadcast.message.dialing.HTTPTaskPair
	(*TCPTask)(nil),            // 3: com.bapis.bilibili.broadcast.message.dialing.TCPTask
	(*TCPTaskPair)(nil),        // 4: com.bapis.bilibili.broadcast.message.dialing.TCPTaskPair
}
var file_bilibili_broadcast_message_dialing_messages_proto_depIdxs = []int32{
	2, // 0: com.bapis.bilibili.broadcast.message.dialing.HTTPTask.pairs:type_name -> com.bapis.bilibili.broadcast.message.dialing.HTTPTaskPair
	4, // 1: com.bapis.bilibili.broadcast.message.dialing.TCPTask.pairs:type_name -> com.bapis.bilibili.broadcast.message.dialing.TCPTaskPair
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_bilibili_broadcast_message_dialing_messages_proto_init() }
func file_bilibili_broadcast_message_dialing_messages_proto_init() {
	if File_bilibili_broadcast_message_dialing_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bilibili_broadcast_message_dialing_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DialingTaskMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_broadcast_message_dialing_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HTTPTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_broadcast_message_dialing_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HTTPTaskPair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_broadcast_message_dialing_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TCPTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_broadcast_message_dialing_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TCPTaskPair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bilibili_broadcast_message_dialing_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bilibili_broadcast_message_dialing_messages_proto_goTypes,
		DependencyIndexes: file_bilibili_broadcast_message_dialing_messages_proto_depIdxs,
		MessageInfos:      file_bilibili_broadcast_message_dialing_messages_proto_msgTypes,
	}.Build()
	File_bilibili_broadcast_message_dialing_messages_proto = out.File
	file_bilibili_broadcast_message_dialing_messages_proto_rawDesc = nil
	file_bilibili_broadcast_message_dialing_messages_proto_goTypes = nil
	file_bilibili_broadcast_message_dialing_messages_proto_depIdxs = nil
}
