// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.vega.deneb.v1;

// Source: com/bapis/bilibili/vega/deneb/v1/MessagePullsReply.java
message MessagePullsReply {
  repeated Any data = 1;
  int32 pn = 2;
  int32 ps = 3;
  int64 count = 4;
  bool hasNext = 5;
}

// Source: com/bapis/bilibili/vega/deneb/v1/MessagePullsReq.java
message MessagePullsReq {
  int64 startSeqId = 1;
  int64 endSeqId = 2;
  int32 pn = 3;
  int32 ps = 4;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/vega/deneb/v1";
