// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.vas.garb.model;

// Source: com/bapis/bilibili/vas/garb/model/FanNumColorFormat.java
message FanNumColorFormat {
  string startPoint = 1;
  string endPoint = 2;
  repeated string colors = 3;
  repeated int64 gradients = 4;
}

// Source: com/bapis/bilibili/vas/garb/model/ImageGroup.java
message ImageGroup {
  string type = 1;
  int64 effectVisual = 2;
  bool cardGame = 3;
}

// Source: com/bapis/bilibili/vas/garb/model/UserCardBG.java
message UserCardBG {
  int64 id = 1;
  string name = 2;
  string image = 3;
  string jumpUrl = 4;
  UserFanShow fan = 5;
  string type = 6;
  ImageGroup imageGroup = 7;
}

// Source: com/bapis/bilibili/vas/garb/model/UserFanShow.java
message UserFanShow {
  int64 isFan = 1;
  int64 number = 2;
  string color = 3;
  string name = 4;
  string numDesc = 5;
  string numPrefix = 6;
  FanNumColorFormat colorFormat = 7;
}

// Source: com/bapis/bilibili/vas/garb/model/UserPendant.java
message UserPendant {
  int64 id = 1;
  string name = 2;
  string image = 3;
  string jumpUrl = 4;
  string type = 5;
  string imageEnhance = 6;
  string imageEnhanceFrame = 7;
}

// Source: com/bapis/bilibili/vas/garb/model/UserSailing.java
message UserSailing {
  UserPendant pendant = 1;
  UserCardBG cardBg = 2;
  UserCardBG cardBgWithFocus = 3;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/vas/garb/model";
