// Reconstructed from gRPC service descriptors.
syntax = "proto3";

package bilibili.app.playerunite.v1;

import "bilibili/app/playerunite/v1/messages.proto";

service Player {
  rpc PlayAddition(.com.bapis.bilibili.app.playerunite.v1.PlayAdditionReq) returns (.com.bapis.bilibili.app.playerunite.v1.PlayAdditionReply);
  rpc PlayHalfChannels(.com.bapis.bilibili.app.playerunite.v1.PlayHalfChannelsReq) returns (.com.bapis.bilibili.app.playerunite.v1.PlayHalfChannelsReply);
  rpc PlayViewUnite(.com.bapis.bilibili.app.playerunite.v1.PlayViewUniteReq) returns (.com.bapis.bilibili.app.playerunite.v1.PlayViewUniteReply);
}

option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/app/playerunite/v1";
