// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.app.distribution.setting.home;

// Source: com/bapis/bilibili/app/distribution/setting/home/MidHomeConfig.java
message MidHomeConfig {
  bytes topleftgoto = 1;
  bytes recentpagetab = 2;
  repeated bytes androidmineselectionoptionitemsid = 3;
  repeated bytes iosmineselectionoptionitemsid = 4;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/app/distribution/setting/home";
