// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: bilibili/app/story/v1.proto

package story

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Story_AIAudio_FullMethodName       = "/bilibili.app.story.v1.Story/AIAudio"
	Story_ArchiveStatus_FullMethodName = "/bilibili.app.story.v1.Story/ArchiveStatus"
	Story_BgmPlay_FullMethodName       = "/bilibili.app.story.v1.Story/BgmPlay"
	Story_Rerank_FullMethodName        = "/bilibili.app.story.v1.Story/Rerank"
)

// StoryClient is the client API for Story service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StoryClient interface {
	AIAudio(ctx context.Context, in *AIAudioReq, opts ...grpc.CallOption) (*AIAudioReply, error)
	ArchiveStatus(ctx context.Context, in *ArchiveStatusReq, opts ...grpc.CallOption) (*ArchiveStatusReply, error)
	BgmPlay(ctx context.Context, in *BgmPlayReq, opts ...grpc.CallOption) (*BgmPlayReply, error)
	Rerank(ctx context.Context, in *RerankReq, opts ...grpc.CallOption) (*RerankReply, error)
}

type storyClient struct {
	cc grpc.ClientConnInterface
}

func NewStoryClient(cc grpc.ClientConnInterface) StoryClient {
	return &storyClient{cc}
}

func (c *storyClient) AIAudio(ctx context.Context, in *AIAudioReq, opts ...grpc.CallOption) (*AIAudioReply, error) {
	out := new(AIAudioReply)
	err := c.cc.Invoke(ctx, Story_AIAudio_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storyClient) ArchiveStatus(ctx context.Context, in *ArchiveStatusReq, opts ...grpc.CallOption) (*ArchiveStatusReply, error) {
	out := new(ArchiveStatusReply)
	err := c.cc.Invoke(ctx, Story_ArchiveStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storyClient) BgmPlay(ctx context.Context, in *BgmPlayReq, opts ...grpc.CallOption) (*BgmPlayReply, error) {
	out := new(BgmPlayReply)
	err := c.cc.Invoke(ctx, Story_BgmPlay_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storyClient) Rerank(ctx context.Context, in *RerankReq, opts ...grpc.CallOption) (*RerankReply, error) {
	out := new(RerankReply)
	err := c.cc.Invoke(ctx, Story_Rerank_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoryServer is the server API for Story service.
// All implementations must embed UnimplementedStoryServer
// for forward compatibility
type StoryServer interface {
	AIAudio(context.Context, *AIAudioReq) (*AIAudioReply, error)
	ArchiveStatus(context.Context, *ArchiveStatusReq) (*ArchiveStatusReply, error)
	BgmPlay(context.Context, *BgmPlayReq) (*BgmPlayReply, error)
	Rerank(context.Context, *RerankReq) (*RerankReply, error)
	mustEmbedUnimplementedStoryServer()
}

// UnimplementedStoryServer must be embedded to have forward compatible implementations.
type UnimplementedStoryServer struct {
}

func (UnimplementedStoryServer) AIAudio(context.Context, *AIAudioReq) (*AIAudioReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AIAudio not implemented")
}
func (UnimplementedStoryServer) ArchiveStatus(context.Context, *ArchiveStatusReq) (*ArchiveStatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchiveStatus not implemented")
}
func (UnimplementedStoryServer) BgmPlay(context.Context, *BgmPlayReq) (*BgmPlayReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BgmPlay not implemented")
}
func (UnimplementedStoryServer) Rerank(context.Context, *RerankReq) (*RerankReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rerank not implemented")
}
func (UnimplementedStoryServer) mustEmbedUnimplementedStoryServer() {}

// UnsafeStoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoryServer will
// result in compilation errors.
type UnsafeStoryServer interface {
	mustEmbedUnimplementedStoryServer()
}

func RegisterStoryServer(s grpc.ServiceRegistrar, srv StoryServer) {
	s.RegisterService(&Story_ServiceDesc, srv)
}

func _Story_AIAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AIAudioReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServer).AIAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Story_AIAudio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServer).AIAudio(ctx, req.(*AIAudioReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Story_ArchiveStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServer).ArchiveStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Story_ArchiveStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServer).ArchiveStatus(ctx, req.(*ArchiveStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Story_BgmPlay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BgmPlayReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServer).BgmPlay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Story_BgmPlay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServer).BgmPlay(ctx, req.(*BgmPlayReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Story_Rerank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RerankReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServer).Rerank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Story_Rerank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServer).Rerank(ctx, req.(*RerankReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Story_ServiceDesc is the grpc.ServiceDesc for Story service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Story_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bilibili.app.story.v1.Story",
	HandlerType: (*StoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AIAudio",
			Handler:    _Story_AIAudio_Handler,
		},
		{
			MethodName: "ArchiveStatus",
			Handler:    _Story_ArchiveStatus_Handler,
		},
		{
			MethodName: "BgmPlay",
			Handler:    _Story_BgmPlay_Handler,
		},
		{
			MethodName: "Rerank",
			Handler:    _Story_Rerank_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bilibili/app/story/v1.proto",
}
