// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.app.distribution.setting.play;

import "bilibili/app/distribution/messages.proto";

// Source: com/bapis/bilibili/app/distribution/setting/play/CloudPlayConfig.java
message CloudPlayConfig {
  bytes enablepanorama = 1;
  bytes enabledolby = 2;
  bytes enableshake = 3;
  bytes enablebackground = 4;
  bytes enablelossless = 5;
  bytes priorityusedolbyhdr = 6;
}

// Source: com/bapis/bilibili/app/distribution/setting/play/MidPlayConfig.java
message MidPlayConfig {
  com.bapis.bilibili.app.distribution.BoolValue dynamicToPlaylist = 1;
}

// Source: com/bapis/bilibili/app/distribution/setting/play/PlayConfig.java
message PlayConfig {
  bytes shouldautoplay = 1;
  bytes shouldautofullscreen = 2;
  bytes enableplayurlhttps = 3;
  bytes enabledanmakuinteraction = 4;
  bytes smallscreenstatus = 5;
  bytes playercodecmodekey = 6;
  bytes enablegravityrotatescreen = 7;
  bytes enabledanmakumonospaced = 8;
  bytes enableeditsubtitle = 9;
  bytes enablesubtitle = 10;
  bytes colorfilter = 11;
  bytes shouldautostory = 12;
  bytes landscapeautostory = 13;
  bytes volumebalance = 14;
  bytes volumebalancemode = 15;
}

// Source: com/bapis/bilibili/app/distribution/setting/play/SpecificPlayConfig.java
message SpecificPlayConfig {
  bytes enablesegmentedsection = 1;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/app/distribution/setting/play";
