// Reconstructed from gRPC service descriptors.
syntax = "proto3";

package bilibili.app.playeronline.v1;

import "bilibili/app/playeronline/v1/messages.proto";

service PlayerOnline {
  rpc PlayerOnline(.com.bapis.bilibili.app.playeronline.v1.PlayerOnlineReq) returns (.com.bapis.bilibili.app.playeronline.v1.PlayerOnlineReply);
  rpc PremiereInfo(.com.bapis.bilibili.app.playeronline.v1.PremiereInfoReq) returns (.com.bapis.bilibili.app.playeronline.v1.PremiereInfoReply);
  rpc ReportWatch(.com.bapis.bilibili.app.playeronline.v1.ReportWatchReq) returns (.com.bapis.bilibili.app.playeronline.v1.NoReply);
}

option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/app/playeronline/v1";
