// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.mall.tab3.dynamic.v1;

import "bilibili/app/dynamic/v2/messages.proto";

enum ReserveState {
  INVALID = 0;
  Reserve = 1;
  PrizeReserve = 2;
  CancelReserve = 3;
  Cancel = 4;
  PrizeCancel = 5;
  Going = 6;
  End = 7;
  Canceled = -1;
  Expired = -2;
}

enum UpActReserveRelationLotteryType {
  UpActReserveRelationLotteryTypeDefault = 0;
  UpActReserveRelationLotteryTypeCron = 1;
}

// Source: com/bapis/bilibili/mall/tab3/dynamic/v1/AuthorInfo.java
message AuthorInfo {
  string face = 1;
  int64 mid = 2;
  string name = 3;
  RelationInfo relationInfo = 4;
  LiveInfo liveInfo = 5;
  string link = 6;
  string rightIcon = 7;
  string rightIconDark = 8;
  string nicknameColor = 9;
  string icon = 10;
}

// Source: com/bapis/bilibili/mall/tab3/dynamic/v1/Bottom.java
message Bottom {
  com.bapis.bilibili.app.dynamic.v2.ModuleButtom moduleButtom = 1;
  com.bapis.bilibili.app.dynamic.v2.DynModuleType moduleType = 2;
}

// Source: com/bapis/bilibili/mall/tab3/dynamic/v1/CreatorSmallShopEntry.java
message CreatorSmallShopEntry {
  string iconUrl = 1;
  string iconUrlNight = 2;
  string shopName = 3;
  repeated string workIdentity = 4;
  string shopMeta = 5;
  string shopUrl = 6;
  repeated ShopItem shopItems = 7;
}

// Source: com/bapis/bilibili/mall/tab3/dynamic/v1/IconInfo.java
message IconInfo {
  string iconUrl = 1;
  string iconNightUrl = 2;
  int32 iconWidth = 3;
  int32 iconHeight = 4;
}

// Source: com/bapis/bilibili/mall/tab3/dynamic/v1/IpCity.java
message IpCity {
  com.bapis.bilibili.app.dynamic.v2.ModuleCopyright moduleCopyright = 1;
  com.bapis.bilibili.app.dynamic.v2.DynModuleType moduleType = 2;
}

// Source: com/bapis/bilibili/mall/tab3/dynamic/v1/ItemInfoDescVO.java
message ItemInfoDescVO {
  int64 itemsId = 1;
  string name = 2;
  string img = 3;
  string price = 4;
  string priceSymbol = 5;
  string cache = 6;
  string sameKindDesc = 7;
  int32 count = 8;
  string url = 9;
  string guideText = 10;
  string subtitle = 11;
}

// Source: com/bapis/bilibili/mall/tab3/dynamic/v1/LiveInfo.java
message LiveInfo {
  int32 status = 1;
  string icon = 2;
  string darkIcon = 3;
  string liveLink = 4;
}

// Source: com/bapis/bilibili/mall/tab3/dynamic/v1/MallBenefit.java
message MallBenefit {
  repeated MallTagInfo mallTags = 1;
}

// Source: com/bapis/bilibili/mall/tab3/dynamic/v1/MallTagInfo.java
message MallTagInfo {
  string tagType = 1;
  string tagId = 2;
  string name = 3;
  IconInfo icon = 4;
  IconInfo nameSuffixIcon = 5;
  string url = 6;
}

// Source: com/bapis/bilibili/mall/tab3/dynamic/v1/OpusDetailReq.java
message OpusDetailReq {
  int64 dynId = 1;
  string adExtra = 2;
  int32 localTime = 3;
}

// Source: com/bapis/bilibili/mall/tab3/dynamic/v1/OpusDetailResp.java
message OpusDetailResp {
  com.bapis.bilibili.app.dynamic.v2.OpusItem opusItem = 1;
  TitleInfo title = 2;
  AuthorInfo authorInfo = 3;
  IpCity ipCity = 4;
  Bottom bottom = 5;
  bytes itemInfoDescvo = 6;
  repeated bytes itemsInfovos = 7;
  Pic pic = 8;
  int64 pubTime = 9;
  TopicInfo topicInfo = 10;
  string itemscene = 11;
  ReserveInfo reserveInfo = 12;
  bytes shareinfo = 13;
  bytes mallbenefit = 14;
  map<string, string> trackMap = 15;
  string itemType = 16;
  SupportInfo supportInfo = 17;
  CreatorSmallShopEntry smallShop = 18;
  RightButtonStamp rightButtonStamp = 19;
}

// Source: com/bapis/bilibili/mall/tab3/dynamic/v1/Pic.java
message Pic {
  repeated PicInfo pics = 1;
  string style = 2;
}

// Source: com/bapis/bilibili/mall/tab3/dynamic/v1/PicInfo.java
message PicInfo {
  string url = 1;
  double width = 2;
  double height = 3;
  double size = 4;
}

// Source: com/bapis/bilibili/mall/tab3/dynamic/v1/RelationInfo.java
message RelationInfo {
  int32 status = 1;
  string icon = 2;
  string darkIcon = 3;
}

// Source: com/bapis/bilibili/mall/tab3/dynamic/v1/ReserveInfo.java
message ReserveInfo {
  int64 sid = 1;
  string title = 2;
  int64 total = 3;
  string totalStr = 4;
  string liveTimeCapsule = 5;
  string liveTimeFloat = 6;
  int32 lotterytype = 7;
  bytes prizeinfo = 8;
  string upNameStr = 9;
  string avatar = 10;
  int64 isFollow = 11;
  string desc = 12;
  int64 livePlanStartTime = 13;
  ReserveState state = 14;
  map<int32, string> stateMap = 15;
  string liveRoomUrl = 16;
  string prizeInfoText = 17;
  int64 roomId = 18;
}

// Source: com/bapis/bilibili/mall/tab3/dynamic/v1/RightButtonStamp.java
message RightButtonStamp {
  string img = 1;
  double width = 2;
  double height = 3;
  string darkImg = 4;
}

// Source: com/bapis/bilibili/mall/tab3/dynamic/v1/ShareInfo.java
message ShareInfo {
  string shareId = 1;
  string shareOrigin = 2;
  int64 oid = 3;
  string title = 4;
  string subTitle = 5;
  string imgUrl = 6;
  string linkUrl = 7;
  bool share = 8;
  string outLinkUrl = 9;
}

// Source: com/bapis/bilibili/mall/tab3/dynamic/v1/ShopItem.java
message ShopItem {
  int64 itemId = 1;
  string itemImg = 2;
  string itemUrl = 3;
}

// Source: com/bapis/bilibili/mall/tab3/dynamic/v1/SupportInfo.java
message SupportInfo {
  string iconurl = 1;
  string supportStatus = 2;
  string title = 3;
  string score = 4;
  string longBgImg = 5;
  string shortBgImg = 6;
  string iconDynamicUrl = 7;
}

// Source: com/bapis/bilibili/mall/tab3/dynamic/v1/TitleInfo.java
message TitleInfo {
  repeated com.bapis.bilibili.app.dynamic.v2.Module modules = 1;
}

// Source: com/bapis/bilibili/mall/tab3/dynamic/v1/TopicInfo.java
message TopicInfo {
  int64 topicId = 1;
  string topicName = 2;
  string jumpUrl = 3;
}

// Source: com/bapis/bilibili/mall/tab3/dynamic/v1/UpActReserveRelationPrizeInfo.java
message UpActReserveRelationPrizeInfo {
  string text = 1;
  string jumpurl = 2;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/mall/tab3/dynamic/v1";
