// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.app.interfaces.v1;

enum DT {
  Unknown = 0;
  Phone = 1;
  Pad = 2;
  PC = 3;
  TV = 4;
}

// Source: com/bapis/bilibili/app/interfaces/v1/CardArticle.java
message CardArticle {
  repeated string covers = 1;
  string name = 2;
  int64 mid = 3;
  bool displayAttention = 4;
  string badge = 5;
  Relation relation = 6;
}

// Source: com/bapis/bilibili/app/interfaces/v1/CardCheese.java
message CardCheese {
  string cover = 1;
  int64 progress = 2;
  int64 duration = 3;
  string subtitle = 4;
}

// Source: com/bapis/bilibili/app/interfaces/v1/CardLive.java
message CardLive {
  string cover = 1;
  string name = 2;
  int64 mid = 3;
  string tag = 4;
  int32 status = 5;
  bool displayAttention = 6;
  Relation relation = 7;
}

// Source: com/bapis/bilibili/app/interfaces/v1/CardOGV.java
message CardOGV {
  string cover = 1;
  int64 progress = 2;
  int64 duration = 3;
  string subtitle = 4;
}

// Source: com/bapis/bilibili/app/interfaces/v1/CardUGC.java
message CardUGC {
  string cover = 1;
  int64 progress = 2;
  int64 duration = 3;
  string name = 4;
  int64 mid = 5;
  bool displayAttention = 6;
  int64 cid = 7;
  int32 page = 8;
  string subtitle = 9;
  Relation relation = 10;
}

// Source: com/bapis/bilibili/app/interfaces/v1/Cursor.java
message Cursor {
  int64 max = 1;
  int32 maxTp = 2;
}

// Source: com/bapis/bilibili/app/interfaces/v1/CursorItem.java
message CursorItem {
  oneof oneof_0 {
    CardUGC cardUgc = 1;
    CardOGV cardOgv = 2;
    CardArticle cardArticle = 3;
    CardLive cardLive = 4;
    CardCheese cardCheese = 5;
  }
  string title = 6;
  string uri = 7;
  int64 viewAt = 8;
  int64 kid = 9;
  int64 oid = 10;
  string business = 11;
  int32 tp = 12;
  DeviceType dt = 13;
  enum CardItemCase {
    CARDITEM_NOT_SET = 0;
    CARD_UGC = 1;
    CARD_OGV = 2;
    CARD_ARTICLE = 3;
    CARD_LIVE = 4;
    CARD_CHEESE = 5;
  }

}

// Source: com/bapis/bilibili/app/interfaces/v1/CursorReply.java
message CursorReply {
  repeated CursorItem items = 1;
  repeated CursorTab tab = 2;
  Cursor cursor = 3;
  bool hasMore = 4;
}

// Source: com/bapis/bilibili/app/interfaces/v1/CursorReq.java
message CursorReq {
  Cursor cursor = 1;
  string business = 2;
}

// Source: com/bapis/bilibili/app/interfaces/v1/CursorTab.java
message CursorTab {
  string business = 1;
  string name = 2;
}

// Source: com/bapis/bilibili/app/interfaces/v1/DeleteReq.java
message DeleteReq {
  repeated HisInfo hisInfo = 1;
}

// Source: com/bapis/bilibili/app/interfaces/v1/DeviceType.java
message DeviceType {
  DT type = 1;
  string icon = 2;
}

// Source: com/bapis/bilibili/app/interfaces/v1/HisInfo.java
message HisInfo {
  string business = 1;
  int64 kid = 2;
}

// Source: com/bapis/bilibili/app/interfaces/v1/NoReply.java
message NoReply {
}

// Source: com/bapis/bilibili/app/interfaces/v1/OfficialVerify.java
message OfficialVerify {
  int32 type = 1;
  string desc = 2;
}

// Source: com/bapis/bilibili/app/interfaces/v1/ReasonStyle.java
message ReasonStyle {
  string text = 1;
  string textColor = 2;
  string textColorNight = 3;
  string bgColor = 4;
  string bgColorNight = 5;
  string borderColor = 6;
  string borderColorNight = 7;
  int32 bgStyle = 8;
}

// Source: com/bapis/bilibili/app/interfaces/v1/Relation.java
message Relation {
  int32 status = 1;
  int32 isFollow = 2;
  int32 isFollowed = 3;
}

// Source: com/bapis/bilibili/app/interfaces/v1/ResultItem.java
message ResultItem {
  string from = 1;
  string title = 2;
  string keyword = 3;
  int32 position = 4;
  string cover = 5;
  double coverSize = 6;
  string sugType = 7;
  int32 termType = 8;
  string goto = 9;
  string uri = 10;
  OfficialVerify officialVerify = 11;
  string param = 12;
  int64 mid = 13;
  int32 fans = 14;
  int32 level = 15;
  int32 archives = 16;
  int64 ptime = 17;
  string seasonTypeName = 18;
  string area = 19;
  string style = 20;
  string label = 21;
  double rating = 22;
  int32 vote = 23;
  repeated ReasonStyle badges = 24;
  string styles = 25;
  int64 moduleId = 26;
}

// Source: com/bapis/bilibili/app/interfaces/v1/SuggestionResult3Reply.java
message SuggestionResult3Reply {
  string trackid = 1;
  repeated ResultItem list = 2;
  string expStr = 3;
}

// Source: com/bapis/bilibili/app/interfaces/v1/SuggestionResult3Req.java
message SuggestionResult3Req {
  string keyword = 1;
  int32 highlight = 2;
  int32 teenagersMode = 3;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/app/interfaces/v1";
