// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: bilibili/app/show/mixture/v1.proto

package mixture

import (
	middleware "github.com/stmtc233/bili-grpc-api-go/bilibili/app/archive/middleware"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GuideType int32

const (
	GuideType_GUIDE_TYPE_DEFAULT GuideType = 0
	GuideType_GUIDE_TYPE_FUNC GuideType = 1
)

// Enum value maps for GuideType.
var (
	GuideType_name = map[int32]string{
		0: "GUIDE_TYPE_DEFAULT",
		1: "GUIDE_TYPE_FUNC",
	}
	GuideType_value = map[string]int32{
		"GUIDE_TYPE_DEFAULT": 0,
		"GUIDE_TYPE_FUNC":    1,
	}
)

func (x GuideType) Enum() *GuideType {
	p := new(GuideType)
	*p = x
	return p
}

func (x GuideType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GuideType) Descriptor() protoreflect.EnumDescriptor {
	return file_bilibili_app_show_mixture_v1_proto_enumTypes[0].Descriptor()
}

func (GuideType) Type() protoreflect.EnumType {
	return &file_bilibili_app_show_mixture_v1_proto_enumTypes[0]
}

func (x GuideType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GuideType.Descriptor instead.
func (GuideType) EnumDescriptor() ([]byte, []int) {
	return file_bilibili_app_show_mixture_v1_proto_rawDescGZIP(), []int{0}
}

type RegionCardType int32

const (
	RegionCardType_REGION_CARD_TYPE_DEFAULT RegionCardType = 0
	RegionCardType_REGION_CARD_TYPE_AV RegionCardType = 1
)

// Enum value maps for RegionCardType.
var (
	RegionCardType_name = map[int32]string{
		0: "REGION_CARD_TYPE_DEFAULT",
		1: "REGION_CARD_TYPE_AV",
	}
	RegionCardType_value = map[string]int32{
		"REGION_CARD_TYPE_DEFAULT": 0,
		"REGION_CARD_TYPE_AV":      1,
	}
)

func (x RegionCardType) Enum() *RegionCardType {
	p := new(RegionCardType)
	*p = x
	return p
}

func (x RegionCardType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegionCardType) Descriptor() protoreflect.EnumDescriptor {
	return file_bilibili_app_show_mixture_v1_proto_enumTypes[1].Descriptor()
}

func (RegionCardType) Type() protoreflect.EnumType {
	return &file_bilibili_app_show_mixture_v1_proto_enumTypes[1]
}

func (x RegionCardType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegionCardType.Descriptor instead.
func (RegionCardType) EnumDescriptor() ([]byte, []int) {
	return file_bilibili_app_show_mixture_v1_proto_rawDescGZIP(), []int{1}
}

type RegionLimitCode int32

const (
	RegionLimitCode_REGION_LIMIT_CODE_DEFAULT RegionLimitCode = 0
	RegionLimitCode_REGION_LIMIT_CODE_NO_LOGIN RegionLimitCode = 1
	RegionLimitCode_REGION_LIMIT_CODE_MAX RegionLimitCode = 2
	RegionLimitCode_REGION_LIMIT_CODE_ERROR RegionLimitCode = 3
)

// Enum value maps for RegionLimitCode.
var (
	RegionLimitCode_name = map[int32]string{
		0: "REGION_LIMIT_CODE_DEFAULT",
		1: "REGION_LIMIT_CODE_NO_LOGIN",
		2: "REGION_LIMIT_CODE_MAX",
		3: "REGION_LIMIT_CODE_ERROR",
	}
	RegionLimitCode_value = map[string]int32{
		"REGION_LIMIT_CODE_DEFAULT":  0,
		"REGION_LIMIT_CODE_NO_LOGIN": 1,
		"REGION_LIMIT_CODE_MAX":      2,
		"REGION_LIMIT_CODE_ERROR":    3,
	}
)

func (x RegionLimitCode) Enum() *RegionLimitCode {
	p := new(RegionLimitCode)
	*p = x
	return p
}

func (x RegionLimitCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegionLimitCode) Descriptor() protoreflect.EnumDescriptor {
	return file_bilibili_app_show_mixture_v1_proto_enumTypes[2].Descriptor()
}

func (RegionLimitCode) Type() protoreflect.EnumType {
	return &file_bilibili_app_show_mixture_v1_proto_enumTypes[2]
}

func (x RegionLimitCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegionLimitCode.Descriptor instead.
func (RegionLimitCode) EnumDescriptor() ([]byte, []int) {
	return file_bilibili_app_show_mixture_v1_proto_rawDescGZIP(), []int{2}
}

type ChannelRedirectReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *ChannelRedirectReply) Reset() {
	*x = ChannelRedirectReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChannelRedirectReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelRedirectReply) ProtoMessage() {}

func (x *ChannelRedirectReply) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelRedirectReply.ProtoReflect.Descriptor instead.
func (*ChannelRedirectReply) Descriptor() ([]byte, []int) {
	return file_bilibili_app_show_mixture_v1_proto_rawDescGZIP(), []int{0}
}

func (x *ChannelRedirectReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ChannelRedirectReply) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ChannelRedirectReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ChannelRedirectReq) Reset() {
	*x = ChannelRedirectReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChannelRedirectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelRedirectReq) ProtoMessage() {}

func (x *ChannelRedirectReq) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelRedirectReq.ProtoReflect.Descriptor instead.
func (*ChannelRedirectReq) Descriptor() ([]byte, []int) {
	return file_bilibili_app_show_mixture_v1_proto_rawDescGZIP(), []int{1}
}

func (x *ChannelRedirectReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ClarityReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsPlayStory bool `protobuf:"varint,1,opt,name=is_play_story,json=isPlayStory,proto3" json:"is_play_story,omitempty"`
	IsSetPlayQn bool `protobuf:"varint,2,opt,name=is_set_play_qn,json=isSetPlayQn,proto3" json:"is_set_play_qn,omitempty"`
	LastPlayQnValue int64 `protobuf:"varint,3,opt,name=last_play_qn_value,json=lastPlayQnValue,proto3" json:"last_play_qn_value,omitempty"`
}

func (x *ClarityReply) Reset() {
	*x = ClarityReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClarityReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClarityReply) ProtoMessage() {}

func (x *ClarityReply) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClarityReply.ProtoReflect.Descriptor instead.
func (*ClarityReply) Descriptor() ([]byte, []int) {
	return file_bilibili_app_show_mixture_v1_proto_rawDescGZIP(), []int{2}
}

func (x *ClarityReply) GetIsPlayStory() bool {
	if x != nil {
		return x.IsPlayStory
	}
	return false
}

func (x *ClarityReply) GetIsSetPlayQn() bool {
	if x != nil {
		return x.IsSetPlayQn
	}
	return false
}

func (x *ClarityReply) GetLastPlayQnValue() int64 {
	if x != nil {
		return x.LastPlayQnValue
	}
	return 0
}

type ClarityReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClarityReq) Reset() {
	*x = ClarityReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClarityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClarityReq) ProtoMessage() {}

func (x *ClarityReq) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClarityReq.ProtoReflect.Descriptor instead.
func (*ClarityReq) Descriptor() ([]byte, []int) {
	return file_bilibili_app_show_mixture_v1_proto_rawDescGZIP(), []int{3}
}

type GuideCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image string `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Subtitle string `protobuf:"bytes,2,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
}

func (x *GuideCard) Reset() {
	*x = GuideCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuideCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuideCard) ProtoMessage() {}

func (x *GuideCard) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuideCard.ProtoReflect.Descriptor instead.
func (*GuideCard) Descriptor() ([]byte, []int) {
	return file_bilibili_app_show_mixture_v1_proto_rawDescGZIP(), []int{4}
}

func (x *GuideCard) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *GuideCard) GetSubtitle() string {
	if x != nil {
		return x.Subtitle
	}
	return ""
}

type GuideItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Card []*GuideCard `protobuf:"bytes,1,rep,name=card,proto3" json:"card,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *GuideItem) Reset() {
	*x = GuideItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuideItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuideItem) ProtoMessage() {}

func (x *GuideItem) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuideItem.ProtoReflect.Descriptor instead.
func (*GuideItem) Descriptor() ([]byte, []int) {
	return file_bilibili_app_show_mixture_v1_proto_rawDescGZIP(), []int{5}
}

func (x *GuideItem) GetCard() []*GuideCard {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *GuideItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type GuideTip struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image string `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Subtitle string `protobuf:"bytes,2,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *GuideTip) Reset() {
	*x = GuideTip{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuideTip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuideTip) ProtoMessage() {}

func (x *GuideTip) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuideTip.ProtoReflect.Descriptor instead.
func (*GuideTip) Descriptor() ([]byte, []int) {
	return file_bilibili_app_show_mixture_v1_proto_rawDescGZIP(), []int{6}
}

func (x *GuideTip) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *GuideTip) GetSubtitle() string {
	if x != nil {
		return x.Subtitle
	}
	return ""
}

func (x *GuideTip) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type RcmdReason struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	CornerMark int32 `protobuf:"varint,2,opt,name=corner_mark,json=cornerMark,proto3" json:"corner_mark,omitempty"`
}

func (x *RcmdReason) Reset() {
	*x = RcmdReason{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RcmdReason) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RcmdReason) ProtoMessage() {}

func (x *RcmdReason) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RcmdReason.ProtoReflect.Descriptor instead.
func (*RcmdReason) Descriptor() ([]byte, []int) {
	return file_bilibili_app_show_mixture_v1_proto_rawDescGZIP(), []int{7}
}

func (x *RcmdReason) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RcmdReason) GetCornerMark() int32 {
	if x != nil {
		return x.CornerMark
	}
	return 0
}

type RegionAv struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cover string `protobuf:"bytes,1,opt,name=cover,proto3" json:"cover,omitempty"`
	CoverViewText string `protobuf:"bytes,2,opt,name=cover_view_text,json=coverViewText,proto3" json:"cover_view_text,omitempty"`
	CoverDmText string `protobuf:"bytes,3,opt,name=cover_dm_text,json=coverDmText,proto3" json:"cover_dm_text,omitempty"`
	CoverRightText1 string `protobuf:"bytes,4,opt,name=cover_right_text1,json=coverRightText1,proto3" json:"cover_right_text1,omitempty"`
	JumpUrl string `protobuf:"bytes,5,opt,name=jump_url,json=jumpUrl,proto3" json:"jump_url,omitempty"`
	UpName string `protobuf:"bytes,6,opt,name=up_name,json=upName,proto3" json:"up_name,omitempty"`
	Aid int64 `protobuf:"varint,7,opt,name=aid,proto3" json:"aid,omitempty"`
	Title string `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty"`
	Cover43 string `protobuf:"bytes,9,opt,name=cover43,proto3" json:"cover43,omitempty"`
}

func (x *RegionAv) Reset() {
	*x = RegionAv{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionAv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionAv) ProtoMessage() {}

func (x *RegionAv) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionAv.ProtoReflect.Descriptor instead.
func (*RegionAv) Descriptor() ([]byte, []int) {
	return file_bilibili_app_show_mixture_v1_proto_rawDescGZIP(), []int{8}
}

func (x *RegionAv) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *RegionAv) GetCoverViewText() string {
	if x != nil {
		return x.CoverViewText
	}
	return ""
}

func (x *RegionAv) GetCoverDmText() string {
	if x != nil {
		return x.CoverDmText
	}
	return ""
}

func (x *RegionAv) GetCoverRightText1() string {
	if x != nil {
		return x.CoverRightText1
	}
	return ""
}

func (x *RegionAv) GetJumpUrl() string {
	if x != nil {
		return x.JumpUrl
	}
	return ""
}

func (x *RegionAv) GetUpName() string {
	if x != nil {
		return x.UpName
	}
	return ""
}

func (x *RegionAv) GetAid() int64 {
	if x != nil {
		return x.Aid
	}
	return 0
}

func (x *RegionAv) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RegionAv) GetCover43() string {
	if x != nil {
		return x.Cover43
	}
	return ""
}

type RegionBanner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	SubTitle string `protobuf:"bytes,2,opt,name=sub_title,json=subTitle,proto3" json:"sub_title,omitempty"`
	Url string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Index int64 `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	Cover string `protobuf:"bytes,5,opt,name=cover,proto3" json:"cover,omitempty"`
	Id int64 `protobuf:"varint,6,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RegionBanner) Reset() {
	*x = RegionBanner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionBanner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionBanner) ProtoMessage() {}

func (x *RegionBanner) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionBanner.ProtoReflect.Descriptor instead.
func (*RegionBanner) Descriptor() ([]byte, []int) {
	return file_bilibili_app_show_mixture_v1_proto_rawDescGZIP(), []int{9}
}

func (x *RegionBanner) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RegionBanner) GetSubTitle() string {
	if x != nil {
		return x.SubTitle
	}
	return ""
}

func (x *RegionBanner) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RegionBanner) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *RegionBanner) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *RegionBanner) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RegionCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Item:
	//
	//	*RegionCard_Av
	Item isRegionCard_Item `protobuf_oneof:"item"`
	Type RegionCardType `protobuf:"varint,1,opt,name=type,proto3,enum=bilibili.app.show.mixture.v1.RegionCardType" json:"type,omitempty"`
	ThreePoint *ThreePoint `protobuf:"bytes,3,opt,name=three_point,json=threePoint,proto3" json:"three_point,omitempty"`
}

func (x *RegionCard) Reset() {
	*x = RegionCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionCard) ProtoMessage() {}

func (x *RegionCard) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionCard.ProtoReflect.Descriptor instead.
func (*RegionCard) Descriptor() ([]byte, []int) {
	return file_bilibili_app_show_mixture_v1_proto_rawDescGZIP(), []int{10}
}

func (m *RegionCard) GetItem() isRegionCard_Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (x *RegionCard) GetAv() *RegionAv {
	if x, ok := x.GetItem().(*RegionCard_Av); ok {
		return x.Av
	}
	return nil
}

func (x *RegionCard) GetType() RegionCardType {
	if x != nil {
		return x.Type
	}
	return RegionCardType_REGION_CARD_TYPE_DEFAULT
}

func (x *RegionCard) GetThreePoint() *ThreePoint {
	if x != nil {
		return x.ThreePoint
	}
	return nil
}

type isRegionCard_Item interface {
	isRegionCard_Item()
}

type RegionCard_Av struct {
	Av *RegionAv `protobuf:"bytes,2,opt,name=av,proto3,oneof"`
}

func (*RegionCard_Av) isRegionCard_Item() {}

type RegionContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Icons []*RegionIcon `protobuf:"bytes,2,rep,name=icons,proto3" json:"icons,omitempty"`
}

func (x *RegionContent) Reset() {
	*x = RegionContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionContent) ProtoMessage() {}

func (x *RegionContent) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionContent.ProtoReflect.Descriptor instead.
func (*RegionContent) Descriptor() ([]byte, []int) {
	return file_bilibili_app_show_mixture_v1_proto_rawDescGZIP(), []int{11}
}

func (x *RegionContent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RegionContent) GetIcons() []*RegionIcon {
	if x != nil {
		return x.Icons
	}
	return nil
}

type RegionIcon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Img string `protobuf:"bytes,1,opt,name=img,proto3" json:"img,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Url string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	UniqueId int64 `protobuf:"varint,4,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
	Rid int64 `protobuf:"varint,5,opt,name=rid,proto3" json:"rid,omitempty"`
}

func (x *RegionIcon) Reset() {
	*x = RegionIcon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionIcon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionIcon) ProtoMessage() {}

func (x *RegionIcon) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionIcon.ProtoReflect.Descriptor instead.
func (*RegionIcon) Descriptor() ([]byte, []int) {
	return file_bilibili_app_show_mixture_v1_proto_rawDescGZIP(), []int{12}
}

func (x *RegionIcon) GetImg() string {
	if x != nil {
		return x.Img
	}
	return ""
}

func (x *RegionIcon) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RegionIcon) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RegionIcon) GetUniqueId() int64 {
	if x != nil {
		return x.UniqueId
	}
	return 0
}

func (x *RegionIcon) GetRid() int64 {
	if x != nil {
		return x.Rid
	}
	return 0
}

type RegionIndexReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Banner []*RegionBanner `protobuf:"bytes,1,rep,name=banner,proto3" json:"banner,omitempty"`
	HasNext bool `protobuf:"varint,2,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`
	Cards []*RegionCard `protobuf:"bytes,3,rep,name=cards,proto3" json:"cards,omitempty"`
	Title string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *RegionIndexReply) Reset() {
	*x = RegionIndexReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionIndexReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionIndexReply) ProtoMessage() {}

func (x *RegionIndexReply) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionIndexReply.ProtoReflect.Descriptor instead.
func (*RegionIndexReply) Descriptor() ([]byte, []int) {
	return file_bilibili_app_show_mixture_v1_proto_rawDescGZIP(), []int{13}
}

func (x *RegionIndexReply) GetBanner() []*RegionBanner {
	if x != nil {
		return x.Banner
	}
	return nil
}

func (x *RegionIndexReply) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

func (x *RegionIndexReply) GetCards() []*RegionCard {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *RegionIndexReply) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type RegionIndexReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rid int64 `protobuf:"varint,1,opt,name=rid,proto3" json:"rid,omitempty"`
	DisplayId int32 `protobuf:"varint,2,opt,name=display_id,json=displayId,proto3" json:"display_id,omitempty"`
	NeedBanner bool `protobuf:"varint,3,opt,name=need_banner,json=needBanner,proto3" json:"need_banner,omitempty"`
	PlayerArgs *middleware.PlayerArgs `protobuf:"bytes,4,opt,name=player_args,json=playerArgs,proto3" json:"player_args,omitempty"`
	Uuid string `protobuf:"bytes,5,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *RegionIndexReq) Reset() {
	*x = RegionIndexReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionIndexReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionIndexReq) ProtoMessage() {}

func (x *RegionIndexReq) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionIndexReq.ProtoReflect.Descriptor instead.
func (*RegionIndexReq) Descriptor() ([]byte, []int) {
	return file_bilibili_app_show_mixture_v1_proto_rawDescGZIP(), []int{14}
}

func (x *RegionIndexReq) GetRid() int64 {
	if x != nil {
		return x.Rid
	}
	return 0
}

func (x *RegionIndexReq) GetDisplayId() int32 {
	if x != nil {
		return x.DisplayId
	}
	return 0
}

func (x *RegionIndexReq) GetNeedBanner() bool {
	if x != nil {
		return x.NeedBanner
	}
	return false
}

func (x *RegionIndexReq) GetPlayerArgs() *middleware.PlayerArgs {
	if x != nil {
		return x.PlayerArgs
	}
	return nil
}

func (x *RegionIndexReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type RegionLimit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code RegionLimitCode `protobuf:"varint,1,opt,name=code,proto3,enum=bilibili.app.show.mixture.v1.RegionLimitCode" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *RegionLimit) Reset() {
	*x = RegionLimit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionLimit) ProtoMessage() {}

func (x *RegionLimit) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionLimit.ProtoReflect.Descriptor instead.
func (*RegionLimit) Descriptor() ([]byte, []int) {
	return file_bilibili_app_show_mixture_v1_proto_rawDescGZIP(), []int{15}
}

func (x *RegionLimit) GetCode() RegionLimitCode {
	if x != nil {
		return x.Code
	}
	return RegionLimitCode_REGION_LIMIT_CODE_DEFAULT
}

func (x *RegionLimit) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RegionListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shortcut *RegionContent `protobuf:"bytes,1,opt,name=shortcut,proto3" json:"shortcut,omitempty"`
	Contents []*RegionContent `protobuf:"bytes,2,rep,name=contents,proto3" json:"contents,omitempty"`
}

func (x *RegionListReply) Reset() {
	*x = RegionListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionListReply) ProtoMessage() {}

func (x *RegionListReply) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionListReply.ProtoReflect.Descriptor instead.
func (*RegionListReply) Descriptor() ([]byte, []int) {
	return file_bilibili_app_show_mixture_v1_proto_rawDescGZIP(), []int{16}
}

func (x *RegionListReply) GetShortcut() *RegionContent {
	if x != nil {
		return x.Shortcut
	}
	return nil
}

func (x *RegionListReply) GetContents() []*RegionContent {
	if x != nil {
		return x.Contents
	}
	return nil
}

type RegionListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegionListReq) Reset() {
	*x = RegionListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionListReq) ProtoMessage() {}

func (x *RegionListReq) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionListReq.ProtoReflect.Descriptor instead.
func (*RegionListReq) Descriptor() ([]byte, []int) {
	return file_bilibili_app_show_mixture_v1_proto_rawDescGZIP(), []int{17}
}

type RegionShortcutReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit *RegionLimit `protobuf:"bytes,1,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *RegionShortcutReply) Reset() {
	*x = RegionShortcutReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionShortcutReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionShortcutReply) ProtoMessage() {}

func (x *RegionShortcutReply) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionShortcutReply.ProtoReflect.Descriptor instead.
func (*RegionShortcutReply) Descriptor() ([]byte, []int) {
	return file_bilibili_app_show_mixture_v1_proto_rawDescGZIP(), []int{18}
}

func (x *RegionShortcutReply) GetLimit() *RegionLimit {
	if x != nil {
		return x.Limit
	}
	return nil
}

type RegionShortcutReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UniqueId []int64 `protobuf:"varint,1,rep,packed,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
}

func (x *RegionShortcutReq) Reset() {
	*x = RegionShortcutReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionShortcutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionShortcutReq) ProtoMessage() {}

func (x *RegionShortcutReq) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionShortcutReq.ProtoReflect.Descriptor instead.
func (*RegionShortcutReq) Descriptor() ([]byte, []int) {
	return file_bilibili_app_show_mixture_v1_proto_rawDescGZIP(), []int{19}
}

func (x *RegionShortcutReq) GetUniqueId() []int64 {
	if x != nil {
		return x.UniqueId
	}
	return nil
}

type ThreePoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WatchLater bool `protobuf:"varint,1,opt,name=watch_later,json=watchLater,proto3" json:"watch_later,omitempty"`
}

func (x *ThreePoint) Reset() {
	*x = ThreePoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThreePoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreePoint) ProtoMessage() {}

func (x *ThreePoint) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreePoint.ProtoReflect.Descriptor instead.
func (*ThreePoint) Descriptor() ([]byte, []int) {
	return file_bilibili_app_show_mixture_v1_proto_rawDescGZIP(), []int{20}
}

func (x *ThreePoint) GetWatchLater() bool {
	if x != nil {
		return x.WatchLater
	}
	return false
}

type WidgetGuideReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	GuideItem *GuideItem `protobuf:"bytes,2,opt,name=guide_item,json=guideItem,proto3" json:"guide_item,omitempty"`
	Tip *GuideTip `protobuf:"bytes,3,opt,name=tip,proto3" json:"tip,omitempty"`
}

func (x *WidgetGuideReply) Reset() {
	*x = WidgetGuideReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WidgetGuideReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetGuideReply) ProtoMessage() {}

func (x *WidgetGuideReply) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetGuideReply.ProtoReflect.Descriptor instead.
func (*WidgetGuideReply) Descriptor() ([]byte, []int) {
	return file_bilibili_app_show_mixture_v1_proto_rawDescGZIP(), []int{21}
}

func (x *WidgetGuideReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *WidgetGuideReply) GetGuideItem() *GuideItem {
	if x != nil {
		return x.GuideItem
	}
	return nil
}

func (x *WidgetGuideReply) GetTip() *GuideTip {
	if x != nil {
		return x.Tip
	}
	return nil
}

type WidgetGuideReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromSpmid string `protobuf:"bytes,1,opt,name=from_spmid,json=fromSpmid,proto3" json:"from_spmid,omitempty"`
	GuideType GuideType `protobuf:"varint,2,opt,name=guide_type,json=guideType,proto3,enum=bilibili.app.show.mixture.v1.GuideType" json:"guide_type,omitempty"`
}

func (x *WidgetGuideReq) Reset() {
	*x = WidgetGuideReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WidgetGuideReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetGuideReq) ProtoMessage() {}

func (x *WidgetGuideReq) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetGuideReq.ProtoReflect.Descriptor instead.
func (*WidgetGuideReq) Descriptor() ([]byte, []int) {
	return file_bilibili_app_show_mixture_v1_proto_rawDescGZIP(), []int{22}
}

func (x *WidgetGuideReq) GetFromSpmid() string {
	if x != nil {
		return x.FromSpmid
	}
	return ""
}

func (x *WidgetGuideReq) GetGuideType() GuideType {
	if x != nil {
		return x.GuideType
	}
	return GuideType_GUIDE_TYPE_DEFAULT
}

type WidgetItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cover string `protobuf:"bytes,1,opt,name=cover,proto3" json:"cover,omitempty"`
	View string `protobuf:"bytes,2,opt,name=view,proto3" json:"view,omitempty"`
	RcmdReason *RcmdReason `protobuf:"bytes,3,opt,name=rcmd_reason,json=rcmdReason,proto3" json:"rcmd_reason,omitempty"`
	Title string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Name string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Uri string `protobuf:"bytes,6,opt,name=uri,proto3" json:"uri,omitempty"`
	Goto string `protobuf:"bytes,7,opt,name=goto,proto3" json:"goto,omitempty"`
	Id int64 `protobuf:"varint,8,opt,name=id,proto3" json:"id,omitempty"`
	ViewIcon int32 `protobuf:"varint,9,opt,name=view_icon,json=viewIcon,proto3" json:"view_icon,omitempty"`
}

func (x *WidgetItem) Reset() {
	*x = WidgetItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WidgetItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetItem) ProtoMessage() {}

func (x *WidgetItem) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetItem.ProtoReflect.Descriptor instead.
func (*WidgetItem) Descriptor() ([]byte, []int) {
	return file_bilibili_app_show_mixture_v1_proto_rawDescGZIP(), []int{23}
}

func (x *WidgetItem) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *WidgetItem) GetView() string {
	if x != nil {
		return x.View
	}
	return ""
}

func (x *WidgetItem) GetRcmdReason() *RcmdReason {
	if x != nil {
		return x.RcmdReason
	}
	return nil
}

func (x *WidgetItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *WidgetItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WidgetItem) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *WidgetItem) GetGoto() string {
	if x != nil {
		return x.Goto
	}
	return ""
}

func (x *WidgetItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WidgetItem) GetViewIcon() int32 {
	if x != nil {
		return x.ViewIcon
	}
	return 0
}

type WidgetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item []*WidgetItem `protobuf:"bytes,1,rep,name=item,proto3" json:"item,omitempty"`
}

func (x *WidgetReply) Reset() {
	*x = WidgetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WidgetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetReply) ProtoMessage() {}

func (x *WidgetReply) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetReply.ProtoReflect.Descriptor instead.
func (*WidgetReply) Descriptor() ([]byte, []int) {
	return file_bilibili_app_show_mixture_v1_proto_rawDescGZIP(), []int{24}
}

func (x *WidgetReply) GetItem() []*WidgetItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type WidgetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromSpmid string `protobuf:"bytes,1,opt,name=from_spmid,json=fromSpmid,proto3" json:"from_spmid,omitempty"`
	PageNo int32 `protobuf:"varint,2,opt,name=page_no,json=pageNo,proto3" json:"page_no,omitempty"`
}

func (x *WidgetReq) Reset() {
	*x = WidgetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WidgetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetReq) ProtoMessage() {}

func (x *WidgetReq) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_show_mixture_v1_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetReq.ProtoReflect.Descriptor instead.
func (*WidgetReq) Descriptor() ([]byte, []int) {
	return file_bilibili_app_show_mixture_v1_proto_rawDescGZIP(), []int{25}
}

func (x *WidgetReq) GetFromSpmid() string {
	if x != nil {
		return x.FromSpmid
	}
	return ""
}

func (x *WidgetReq) GetPageNo() int32 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

var File_bilibili_app_show_mixture_v1_proto protoreflect.FileDescriptor

var file_bilibili_app_show_mixture_v1_proto_rawDesc = []byte{
	0x0a, 0x22, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x73,
	0x68, 0x6f, 0x77, 0x2f, 0x6d, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x2f, 0x76, 0x31, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1c, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61,
	0x70, 0x70, 0x2e, 0x73, 0x68, 0x6f, 0x77, 0x2e, 0x6d, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x2e,
	0x76, 0x31, 0x1a, 0x28, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2f, 0x61, 0x70, 0x70,
	0x2f, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x2f, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x77,
	0x61, 0x72, 0x65, 0x2f, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3c, 0x0a, 0x14,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x24, 0x0a, 0x12, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x84, 0x01, 0x0a, 0x0c, 0x43, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x22, 0x0a, 0x0d, 0x69, 0x73, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x50, 0x6c, 0x61, 0x79,
	0x53, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x23, 0x0a, 0x0e, 0x69, 0x73, 0x5f, 0x73, 0x65, 0x74, 0x5f,
	0x70, 0x6c, 0x61, 0x79, 0x5f, 0x71, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69,
	0x73, 0x53, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x51, 0x6e, 0x12, 0x2b, 0x0a, 0x12, 0x6c, 0x61,
	0x73, 0x74, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x71, 0x6e, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x6c, 0x61, 0x73, 0x74, 0x50, 0x6c, 0x61, 0x79,
	0x51, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x0c, 0x0a, 0x0a, 0x43, 0x6c, 0x61, 0x72, 0x69,
	0x74, 0x79, 0x52, 0x65, 0x71, 0x22, 0x3d, 0x0a, 0x09, 0x47, 0x75, 0x69, 0x64, 0x65, 0x43, 0x61,
	0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x75, 0x62, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x75, 0x62, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x22, 0x5e, 0x0a, 0x09, 0x47, 0x75, 0x69, 0x64, 0x65, 0x49, 0x74, 0x65,
	0x6d, 0x12, 0x3b, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x27, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x73,
	0x68, 0x6f, 0x77, 0x2e, 0x6d, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x75, 0x69, 0x64, 0x65, 0x43, 0x61, 0x72, 0x64, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x22, 0x52, 0x0a, 0x08, 0x47, 0x75, 0x69, 0x64, 0x65, 0x54, 0x69, 0x70,
	0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x75, 0x62, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x75, 0x62, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x47, 0x0a, 0x0a, 0x52, 0x63, 0x6d, 0x64,
	0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x72, 0x6e, 0x65, 0x72, 0x5f, 0x6d, 0x61, 0x72, 0x6b, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x63, 0x6f, 0x72, 0x6e, 0x65, 0x72, 0x4d, 0x61, 0x72,
	0x6b, 0x22, 0x8e, 0x02, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x41, 0x76, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63,
	0x6f, 0x76, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x0f, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x5f, 0x76, 0x69,
	0x65, 0x77, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63,
	0x6f, 0x76, 0x65, 0x72, 0x56, 0x69, 0x65, 0x77, 0x54, 0x65, 0x78, 0x74, 0x12, 0x22, 0x0a, 0x0d,
	0x63, 0x6f, 0x76, 0x65, 0x72, 0x5f, 0x64, 0x6d, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x44, 0x6d, 0x54, 0x65, 0x78, 0x74,
	0x12, 0x2a, 0x0a, 0x11, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x5f, 0x72, 0x69, 0x67, 0x68, 0x74, 0x5f,
	0x74, 0x65, 0x78, 0x74, 0x31, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6f, 0x76,
	0x65, 0x72, 0x52, 0x69, 0x67, 0x68, 0x74, 0x54, 0x65, 0x78, 0x74, 0x31, 0x12, 0x19, 0x0a, 0x08,
	0x6a, 0x75, 0x6d, 0x70, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6a, 0x75, 0x6d, 0x70, 0x55, 0x72, 0x6c, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x70, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x61, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x61,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x76, 0x65,
	0x72, 0x34, 0x33, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x76, 0x65, 0x72,
	0x34, 0x33, 0x22, 0x8f, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x42, 0x61, 0x6e,
	0x6e, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x75, 0x62,
	0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x75,
	0x62, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63,
	0x6f, 0x76, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x22, 0xdb, 0x01, 0x0a, 0x0a, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x43,
	0x61, 0x72, 0x64, 0x12, 0x38, 0x0a, 0x02, 0x61, 0x76, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x26, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x73,
	0x68, 0x6f, 0x77, 0x2e, 0x6d, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x41, 0x76, 0x48, 0x00, 0x52, 0x02, 0x61, 0x76, 0x12, 0x40, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2c, 0x2e, 0x62, 0x69,
	0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x73, 0x68, 0x6f, 0x77, 0x2e,
	0x6d, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x43, 0x61, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x49, 0x0a, 0x0b, 0x74, 0x68, 0x72, 0x65, 0x65, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e,
	0x61, 0x70, 0x70, 0x2e, 0x73, 0x68, 0x6f, 0x77, 0x2e, 0x6d, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x54, 0x68, 0x72, 0x65, 0x65, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x0a,
	0x74, 0x68, 0x72, 0x65, 0x65, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x69, 0x74,
	0x65, 0x6d, 0x22, 0x65, 0x0a, 0x0d, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x3e, 0x0a, 0x05, 0x69, 0x63, 0x6f,
	0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62,
	0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x73, 0x68, 0x6f, 0x77, 0x2e, 0x6d, 0x69, 0x78,
	0x74, 0x75, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x63,
	0x6f, 0x6e, 0x52, 0x05, 0x69, 0x63, 0x6f, 0x6e, 0x73, 0x22, 0x75, 0x0a, 0x0a, 0x52, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x49, 0x63, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x6d, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x6d, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x72, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x72, 0x69, 0x64,
	0x22, 0xc7, 0x01, 0x0a, 0x10, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x42, 0x0a, 0x06, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69,
	0x2e, 0x61, 0x70, 0x70, 0x2e, 0x73, 0x68, 0x6f, 0x77, 0x2e, 0x6d, 0x69, 0x78, 0x74, 0x75, 0x72,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x42, 0x61, 0x6e, 0x6e, 0x65,
	0x72, 0x52, 0x06, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x61, 0x73,
	0x5f, 0x6e, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68, 0x61, 0x73,
	0x4e, 0x65, 0x78, 0x74, 0x12, 0x3e, 0x0a, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61,
	0x70, 0x70, 0x2e, 0x73, 0x68, 0x6f, 0x77, 0x2e, 0x6d, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x43, 0x61, 0x72, 0x64, 0x52, 0x05, 0x63,
	0x61, 0x72, 0x64, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x22, 0xc7, 0x01, 0x0a, 0x0e, 0x52,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a,
	0x03, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x72, 0x69, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x49, 0x64, 0x12, 0x1f,
	0x0a, 0x0b, 0x6e, 0x65, 0x65, 0x64, 0x5f, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0a, 0x6e, 0x65, 0x65, 0x64, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12,
	0x4f, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x61, 0x72, 0x67, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e,
	0x61, 0x70, 0x70, 0x2e, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x2e, 0x6d, 0x69, 0x64, 0x64,
	0x6c, 0x65, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x41, 0x72, 0x67, 0x73, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x41, 0x72, 0x67, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x22, 0x6a, 0x0a, 0x0b, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x12, 0x41, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x2d, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70, 0x70,
	0x2e, 0x73, 0x68, 0x6f, 0x77, 0x2e, 0x6d, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0xa3, 0x01, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x47, 0x0a, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x63, 0x75, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c,
	0x69, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x73, 0x68, 0x6f, 0x77, 0x2e, 0x6d, 0x69, 0x78, 0x74, 0x75,
	0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x63, 0x75, 0x74, 0x12, 0x47, 0x0a,
	0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x2b, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x73,
	0x68, 0x6f, 0x77, 0x2e, 0x6d, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x08, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x0f, 0x0a, 0x0d, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x22, 0x56, 0x0a, 0x13, 0x52, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x63, 0x75, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3f,
	0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e,
	0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x73, 0x68, 0x6f,
	0x77, 0x2e, 0x6d, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22,
	0x30, 0x0a, 0x11, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x63, 0x75,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x08, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49,
	0x64, 0x22, 0x2d, 0x0a, 0x0a, 0x54, 0x68, 0x72, 0x65, 0x65, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x77, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x77, 0x61, 0x74, 0x63, 0x68, 0x4c, 0x61, 0x74, 0x65, 0x72,
	0x22, 0xa8, 0x01, 0x0a, 0x10, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x47, 0x75, 0x69, 0x64, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x46, 0x0a, 0x0a, 0x67, 0x75, 0x69,
	0x64, 0x65, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e,
	0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x73, 0x68, 0x6f,
	0x77, 0x2e, 0x6d, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x75, 0x69,
	0x64, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x09, 0x67, 0x75, 0x69, 0x64, 0x65, 0x49, 0x74, 0x65,
	0x6d, 0x12, 0x38, 0x0a, 0x03, 0x74, 0x69, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26,
	0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x73, 0x68,
	0x6f, 0x77, 0x2e, 0x6d, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x75,
	0x69, 0x64, 0x65, 0x54, 0x69, 0x70, 0x52, 0x03, 0x74, 0x69, 0x70, 0x22, 0x77, 0x0a, 0x0e, 0x57,
	0x69, 0x64, 0x67, 0x65, 0x74, 0x47, 0x75, 0x69, 0x64, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a,
	0x0a, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x73, 0x70, 0x6d, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x66, 0x72, 0x6f, 0x6d, 0x53, 0x70, 0x6d, 0x69, 0x64, 0x12, 0x46, 0x0a, 0x0a,
	0x67, 0x75, 0x69, 0x64, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x27, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x2e,
	0x73, 0x68, 0x6f, 0x77, 0x2e, 0x6d, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x75, 0x69, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x67, 0x75, 0x69, 0x64, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x22, 0xfe, 0x01, 0x0a, 0x0a, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x69, 0x65,
	0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x76, 0x69, 0x65, 0x77, 0x12, 0x49, 0x0a,
	0x0b, 0x72, 0x63, 0x6d, 0x64, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x28, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70,
	0x70, 0x2e, 0x73, 0x68, 0x6f, 0x77, 0x2e, 0x6d, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x63, 0x6d, 0x64, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x0a, 0x72, 0x63,
	0x6d, 0x64, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x69, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x6f, 0x74, 0x6f, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x67, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x76, 0x69, 0x65, 0x77,
	0x5f, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x76, 0x69, 0x65,
	0x77, 0x49, 0x63, 0x6f, 0x6e, 0x22, 0x4b, 0x0a, 0x0b, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x3c, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x28, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70,
	0x70, 0x2e, 0x73, 0x68, 0x6f, 0x77, 0x2e, 0x6d, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74,
	0x65, 0x6d, 0x22, 0x43, 0x0a, 0x09, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x1d, 0x0a, 0x0a, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x73, 0x70, 0x6d, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x72, 0x6f, 0x6d, 0x53, 0x70, 0x6d, 0x69, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x2a, 0x38, 0x0a, 0x09, 0x47, 0x75, 0x69, 0x64, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x47, 0x55, 0x49, 0x44, 0x45, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x44, 0x45, 0x46, 0x41, 0x55, 0x4c, 0x54, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f,
	0x47, 0x55, 0x49, 0x44, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x46, 0x55, 0x4e, 0x43, 0x10,
	0x01, 0x2a, 0x47, 0x0a, 0x0e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x43, 0x61, 0x72, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x18, 0x52, 0x45, 0x47, 0x49, 0x4f, 0x4e, 0x5f, 0x43, 0x41,
	0x52, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x44, 0x45, 0x46, 0x41, 0x55, 0x4c, 0x54, 0x10,
	0x00, 0x12, 0x17, 0x0a, 0x13, 0x52, 0x45, 0x47, 0x49, 0x4f, 0x4e, 0x5f, 0x43, 0x41, 0x52, 0x44,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x41, 0x56, 0x10, 0x01, 0x2a, 0x88, 0x01, 0x0a, 0x0f, 0x52,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1d,
	0x0a, 0x19, 0x52, 0x45, 0x47, 0x49, 0x4f, 0x4e, 0x5f, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x5f, 0x43,
	0x4f, 0x44, 0x45, 0x5f, 0x44, 0x45, 0x46, 0x41, 0x55, 0x4c, 0x54, 0x10, 0x00, 0x12, 0x1e, 0x0a,
	0x1a, 0x52, 0x45, 0x47, 0x49, 0x4f, 0x4e, 0x5f, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x5f, 0x43, 0x4f,
	0x44, 0x45, 0x5f, 0x4e, 0x4f, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x19, 0x0a,
	0x15, 0x52, 0x45, 0x47, 0x49, 0x4f, 0x4e, 0x5f, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x5f, 0x43, 0x4f,
	0x44, 0x45, 0x5f, 0x4d, 0x41, 0x58, 0x10, 0x02, 0x12, 0x1b, 0x0a, 0x17, 0x52, 0x45, 0x47, 0x49,
	0x4f, 0x4e, 0x5f, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x10, 0x03, 0x32, 0xfb, 0x05, 0x0a, 0x07, 0x4d, 0x69, 0x78, 0x74, 0x75, 0x72,
	0x65, 0x12, 0x77, 0x0a, 0x0f, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x64, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x12, 0x30, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e,
	0x61, 0x70, 0x70, 0x2e, 0x73, 0x68, 0x6f, 0x77, 0x2e, 0x6d, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x64, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x32, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c,
	0x69, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x73, 0x68, 0x6f, 0x77, 0x2e, 0x6d, 0x69, 0x78, 0x74, 0x75,
	0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x64,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x5f, 0x0a, 0x07, 0x43, 0x6c,
	0x61, 0x72, 0x69, 0x74, 0x79, 0x12, 0x28, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69,
	0x2e, 0x61, 0x70, 0x70, 0x2e, 0x73, 0x68, 0x6f, 0x77, 0x2e, 0x6d, 0x69, 0x78, 0x74, 0x75, 0x72,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x1a,
	0x2a, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x73,
	0x68, 0x6f, 0x77, 0x2e, 0x6d, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x6b, 0x0a, 0x0b, 0x52,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x2c, 0x2e, 0x62, 0x69, 0x6c,
	0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x73, 0x68, 0x6f, 0x77, 0x2e, 0x6d,
	0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x1a, 0x2e, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62,
	0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x73, 0x68, 0x6f, 0x77, 0x2e, 0x6d, 0x69, 0x78,
	0x74, 0x75, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x68, 0x0a, 0x0a, 0x52, 0x65, 0x67, 0x69,
	0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2b, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c,
	0x69, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x73, 0x68, 0x6f, 0x77, 0x2e, 0x6d, 0x69, 0x78, 0x74, 0x75,
	0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x1a, 0x2d, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61,
	0x70, 0x70, 0x2e, 0x73, 0x68, 0x6f, 0x77, 0x2e, 0x6d, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x74, 0x0a, 0x0e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x63, 0x75, 0x74, 0x12, 0x2f, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e,
	0x61, 0x70, 0x70, 0x2e, 0x73, 0x68, 0x6f, 0x77, 0x2e, 0x6d, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x63,
	0x75, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x31, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69,
	0x2e, 0x61, 0x70, 0x70, 0x2e, 0x73, 0x68, 0x6f, 0x77, 0x2e, 0x6d, 0x69, 0x78, 0x74, 0x75, 0x72,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x63, 0x75, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x5c, 0x0a, 0x06, 0x57, 0x69, 0x64, 0x67,
	0x65, 0x74, 0x12, 0x27, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70,
	0x70, 0x2e, 0x73, 0x68, 0x6f, 0x77, 0x2e, 0x6d, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x29, 0x2e, 0x62, 0x69,
	0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x73, 0x68, 0x6f, 0x77, 0x2e,
	0x6d, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x69, 0x64, 0x67, 0x65,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x6b, 0x0a, 0x0b, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74,
	0x47, 0x75, 0x69, 0x64, 0x65, 0x12, 0x2c, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69,
	0x2e, 0x61, 0x70, 0x70, 0x2e, 0x73, 0x68, 0x6f, 0x77, 0x2e, 0x6d, 0x69, 0x78, 0x74, 0x75, 0x72,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x47, 0x75, 0x69, 0x64, 0x65,
	0x52, 0x65, 0x71, 0x1a, 0x2e, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61,
	0x70, 0x70, 0x2e, 0x73, 0x68, 0x6f, 0x77, 0x2e, 0x6d, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x47, 0x75, 0x69, 0x64, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x42, 0x40, 0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x73, 0x74, 0x6d, 0x74, 0x63, 0x32, 0x33, 0x33, 0x2f, 0x62, 0x69, 0x6c, 0x69, 0x2d,
	0x67, 0x72, 0x70, 0x63, 0x2d, 0x61, 0x70, 0x69, 0x2d, 0x67, 0x6f, 0x2f, 0x62, 0x69, 0x6c, 0x69,
	0x62, 0x69, 0x6c, 0x69, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x73, 0x68, 0x6f, 0x77, 0x2f, 0x6d, 0x69,
	0x78, 0x74, 0x75, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bilibili_app_show_mixture_v1_proto_rawDescOnce sync.Once
	file_bilibili_app_show_mixture_v1_proto_rawDescData = file_bilibili_app_show_mixture_v1_proto_rawDesc
)

func file_bilibili_app_show_mixture_v1_proto_rawDescGZIP() []byte {
	file_bilibili_app_show_mixture_v1_proto_rawDescOnce.Do(func() {
		file_bilibili_app_show_mixture_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_bilibili_app_show_mixture_v1_proto_rawDescData)
	})
	return file_bilibili_app_show_mixture_v1_proto_rawDescData
}

var file_bilibili_app_show_mixture_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_bilibili_app_show_mixture_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_bilibili_app_show_mixture_v1_proto_goTypes = []interface{}{
	(GuideType)(0),                // 0: bilibili.app.show.mixture.v1.GuideType
	(RegionCardType)(0),           // 1: bilibili.app.show.mixture.v1.RegionCardType
	(RegionLimitCode)(0),          // 2: bilibili.app.show.mixture.v1.RegionLimitCode
	(*ChannelRedirectReply)(nil),  // 3: bilibili.app.show.mixture.v1.ChannelRedirectReply
	(*ChannelRedirectReq)(nil),    // 4: bilibili.app.show.mixture.v1.ChannelRedirectReq
	(*ClarityReply)(nil),          // 5: bilibili.app.show.mixture.v1.ClarityReply
	(*ClarityReq)(nil),            // 6: bilibili.app.show.mixture.v1.ClarityReq
	(*GuideCard)(nil),             // 7: bilibili.app.show.mixture.v1.GuideCard
	(*GuideItem)(nil),             // 8: bilibili.app.show.mixture.v1.GuideItem
	(*GuideTip)(nil),              // 9: bilibili.app.show.mixture.v1.GuideTip
	(*RcmdReason)(nil),            // 10: bilibili.app.show.mixture.v1.RcmdReason
	(*RegionAv)(nil),              // 11: bilibili.app.show.mixture.v1.RegionAv
	(*RegionBanner)(nil),          // 12: bilibili.app.show.mixture.v1.RegionBanner
	(*RegionCard)(nil),            // 13: bilibili.app.show.mixture.v1.RegionCard
	(*RegionContent)(nil),         // 14: bilibili.app.show.mixture.v1.RegionContent
	(*RegionIcon)(nil),            // 15: bilibili.app.show.mixture.v1.RegionIcon
	(*RegionIndexReply)(nil),      // 16: bilibili.app.show.mixture.v1.RegionIndexReply
	(*RegionIndexReq)(nil),        // 17: bilibili.app.show.mixture.v1.RegionIndexReq
	(*RegionLimit)(nil),           // 18: bilibili.app.show.mixture.v1.RegionLimit
	(*RegionListReply)(nil),       // 19: bilibili.app.show.mixture.v1.RegionListReply
	(*RegionListReq)(nil),         // 20: bilibili.app.show.mixture.v1.RegionListReq
	(*RegionShortcutReply)(nil),   // 21: bilibili.app.show.mixture.v1.RegionShortcutReply
	(*RegionShortcutReq)(nil),     // 22: bilibili.app.show.mixture.v1.RegionShortcutReq
	(*ThreePoint)(nil),            // 23: bilibili.app.show.mixture.v1.ThreePoint
	(*WidgetGuideReply)(nil),      // 24: bilibili.app.show.mixture.v1.WidgetGuideReply
	(*WidgetGuideReq)(nil),        // 25: bilibili.app.show.mixture.v1.WidgetGuideReq
	(*WidgetItem)(nil),            // 26: bilibili.app.show.mixture.v1.WidgetItem
	(*WidgetReply)(nil),           // 27: bilibili.app.show.mixture.v1.WidgetReply
	(*WidgetReq)(nil),             // 28: bilibili.app.show.mixture.v1.WidgetReq
	(*middleware.PlayerArgs)(nil), // 29: bilibili.app.archive.middleware.v1.PlayerArgs
}
var file_bilibili_app_show_mixture_v1_proto_depIdxs = []int32{
	7,  // 0: bilibili.app.show.mixture.v1.GuideItem.card:type_name -> bilibili.app.show.mixture.v1.GuideCard
	11, // 1: bilibili.app.show.mixture.v1.RegionCard.av:type_name -> bilibili.app.show.mixture.v1.RegionAv
	1,  // 2: bilibili.app.show.mixture.v1.RegionCard.type:type_name -> bilibili.app.show.mixture.v1.RegionCardType
	23, // 3: bilibili.app.show.mixture.v1.RegionCard.three_point:type_name -> bilibili.app.show.mixture.v1.ThreePoint
	15, // 4: bilibili.app.show.mixture.v1.RegionContent.icons:type_name -> bilibili.app.show.mixture.v1.RegionIcon
	12, // 5: bilibili.app.show.mixture.v1.RegionIndexReply.banner:type_name -> bilibili.app.show.mixture.v1.RegionBanner
	13, // 6: bilibili.app.show.mixture.v1.RegionIndexReply.cards:type_name -> bilibili.app.show.mixture.v1.RegionCard
	29, // 7: bilibili.app.show.mixture.v1.RegionIndexReq.player_args:type_name -> bilibili.app.archive.middleware.v1.PlayerArgs
	2,  // 8: bilibili.app.show.mixture.v1.RegionLimit.code:type_name -> bilibili.app.show.mixture.v1.RegionLimitCode
	14, // 9: bilibili.app.show.mixture.v1.RegionListReply.shortcut:type_name -> bilibili.app.show.mixture.v1.RegionContent
	14, // 10: bilibili.app.show.mixture.v1.RegionListReply.contents:type_name -> bilibili.app.show.mixture.v1.RegionContent
	18, // 11: bilibili.app.show.mixture.v1.RegionShortcutReply.limit:type_name -> bilibili.app.show.mixture.v1.RegionLimit
	8,  // 12: bilibili.app.show.mixture.v1.WidgetGuideReply.guide_item:type_name -> bilibili.app.show.mixture.v1.GuideItem
	9,  // 13: bilibili.app.show.mixture.v1.WidgetGuideReply.tip:type_name -> bilibili.app.show.mixture.v1.GuideTip
	0,  // 14: bilibili.app.show.mixture.v1.WidgetGuideReq.guide_type:type_name -> bilibili.app.show.mixture.v1.GuideType
	10, // 15: bilibili.app.show.mixture.v1.WidgetItem.rcmd_reason:type_name -> bilibili.app.show.mixture.v1.RcmdReason
	26, // 16: bilibili.app.show.mixture.v1.WidgetReply.item:type_name -> bilibili.app.show.mixture.v1.WidgetItem
	4,  // 17: bilibili.app.show.mixture.v1.Mixture.ChannelRedirect:input_type -> bilibili.app.show.mixture.v1.ChannelRedirectReq
	6,  // 18: bilibili.app.show.mixture.v1.Mixture.Clarity:input_type -> bilibili.app.show.mixture.v1.ClarityReq
	17, // 19: bilibili.app.show.mixture.v1.Mixture.RegionIndex:input_type -> bilibili.app.show.mixture.v1.RegionIndexReq
	20, // 20: bilibili.app.show.mixture.v1.Mixture.RegionList:input_type -> bilibili.app.show.mixture.v1.RegionListReq
	22, // 21: bilibili.app.show.mixture.v1.Mixture.RegionShortcut:input_type -> bilibili.app.show.mixture.v1.RegionShortcutReq
	28, // 22: bilibili.app.show.mixture.v1.Mixture.Widget:input_type -> bilibili.app.show.mixture.v1.WidgetReq
	25, // 23: bilibili.app.show.mixture.v1.Mixture.WidgetGuide:input_type -> bilibili.app.show.mixture.v1.WidgetGuideReq
	3,  // 24: bilibili.app.show.mixture.v1.Mixture.ChannelRedirect:output_type -> bilibili.app.show.mixture.v1.ChannelRedirectReply
	5,  // 25: bilibili.app.show.mixture.v1.Mixture.Clarity:output_type -> bilibili.app.show.mixture.v1.ClarityReply
	16, // 26: bilibili.app.show.mixture.v1.Mixture.RegionIndex:output_type -> bilibili.app.show.mixture.v1.RegionIndexReply
	19, // 27: bilibili.app.show.mixture.v1.Mixture.RegionList:output_type -> bilibili.app.show.mixture.v1.RegionListReply
	21, // 28: bilibili.app.show.mixture.v1.Mixture.RegionShortcut:output_type -> bilibili.app.show.mixture.v1.RegionShortcutReply
	27, // 29: bilibili.app.show.mixture.v1.Mixture.Widget:output_type -> bilibili.app.show.mixture.v1.WidgetReply
	24, // 30: bilibili.app.show.mixture.v1.Mixture.WidgetGuide:output_type -> bilibili.app.show.mixture.v1.WidgetGuideReply
	24, // [24:31] is the sub-list for method output_type
	17, // [17:24] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_bilibili_app_show_mixture_v1_proto_init() }
func file_bilibili_app_show_mixture_v1_proto_init() {
	if File_bilibili_app_show_mixture_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bilibili_app_show_mixture_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChannelRedirectReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_app_show_mixture_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChannelRedirectReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_app_show_mixture_v1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClarityReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_app_show_mixture_v1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClarityReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_app_show_mixture_v1_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuideCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_app_show_mixture_v1_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuideItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_app_show_mixture_v1_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuideTip); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_app_show_mixture_v1_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RcmdReason); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_app_show_mixture_v1_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionAv); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_app_show_mixture_v1_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionBanner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_app_show_mixture_v1_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_app_show_mixture_v1_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_app_show_mixture_v1_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionIcon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_app_show_mixture_v1_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionIndexReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_app_show_mixture_v1_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionIndexReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_app_show_mixture_v1_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionLimit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_app_show_mixture_v1_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_app_show_mixture_v1_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_app_show_mixture_v1_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionShortcutReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_app_show_mixture_v1_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionShortcutReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_app_show_mixture_v1_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThreePoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_app_show_mixture_v1_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WidgetGuideReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_app_show_mixture_v1_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WidgetGuideReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_app_show_mixture_v1_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WidgetItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_app_show_mixture_v1_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WidgetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_app_show_mixture_v1_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WidgetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_bilibili_app_show_mixture_v1_proto_msgTypes[10].OneofWrappers = []interface{}{
		(*RegionCard_Av)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bilibili_app_show_mixture_v1_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bilibili_app_show_mixture_v1_proto_goTypes,
		DependencyIndexes: file_bilibili_app_show_mixture_v1_proto_depIdxs,
		EnumInfos:         file_bilibili_app_show_mixture_v1_proto_enumTypes,
		MessageInfos:      file_bilibili_app_show_mixture_v1_proto_msgTypes,
	}.Build()
	File_bilibili_app_show_mixture_v1_proto = out.File
	file_bilibili_app_show_mixture_v1_proto_rawDesc = nil
	file_bilibili_app_show_mixture_v1_proto_goTypes = nil
	file_bilibili_app_show_mixture_v1_proto_depIdxs = nil
}
