// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: bilibili/account/service/v1.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RenderSchemeEnum int32

const (
	RenderSchemeEnum_Default RenderSchemeEnum = 0
	RenderSchemeEnum_Colorful RenderSchemeEnum = 1
)

// Enum value maps for RenderSchemeEnum.
var (
	RenderSchemeEnum_name = map[int32]string{
		0: "Default",
		1: "Colorful",
	}
	RenderSchemeEnum_value = map[string]int32{
		"Default":  0,
		"Colorful": 1,
	}
)

func (x RenderSchemeEnum) Enum() *RenderSchemeEnum {
	p := new(RenderSchemeEnum)
	*p = x
	return p
}

func (x RenderSchemeEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RenderSchemeEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_bilibili_account_service_v1_proto_enumTypes[0].Descriptor()
}

func (RenderSchemeEnum) Type() protoreflect.EnumType {
	return &file_bilibili_account_service_v1_proto_enumTypes[0]
}

func (x RenderSchemeEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RenderSchemeEnum.Descriptor instead.
func (RenderSchemeEnum) EnumDescriptor() ([]byte, []int) {
	return file_bilibili_account_service_v1_proto_rawDescGZIP(), []int{0}
}

type Color struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ColorDay string `protobuf:"bytes,1,opt,name=color_day,json=colorDay,proto3" json:"color_day,omitempty"`
	ColorNight string `protobuf:"bytes,2,opt,name=color_night,json=colorNight,proto3" json:"color_night,omitempty"`
}

func (x *Color) Reset() {
	*x = Color{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_account_service_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Color) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Color) ProtoMessage() {}

func (x *Color) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_account_service_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Color.ProtoReflect.Descriptor instead.
func (*Color) Descriptor() ([]byte, []int) {
	return file_bilibili_account_service_v1_proto_rawDescGZIP(), []int{0}
}

func (x *Color) GetColorDay() string {
	if x != nil {
		return x.ColorDay
	}
	return ""
}

func (x *Color) GetColorNight() string {
	if x != nil {
		return x.ColorNight
	}
	return ""
}

type ColorsInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ColorIds []int64 `protobuf:"varint,1,rep,packed,name=color_ids,json=colorIds,proto3" json:"color_ids,omitempty"`
	Color []*Color `protobuf:"bytes,2,rep,name=color,proto3" json:"color,omitempty"`
}

func (x *ColorsInfo) Reset() {
	*x = ColorsInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_account_service_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColorsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorsInfo) ProtoMessage() {}

func (x *ColorsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_account_service_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorsInfo.ProtoReflect.Descriptor instead.
func (*ColorsInfo) Descriptor() ([]byte, []int) {
	return file_bilibili_account_service_v1_proto_rawDescGZIP(), []int{1}
}

func (x *ColorsInfo) GetColorIds() []int64 {
	if x != nil {
		return x.ColorIds
	}
	return nil
}

func (x *ColorsInfo) GetColor() []*Color {
	if x != nil {
		return x.Color
	}
	return nil
}

type NameRender struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RenderScheme RenderSchemeEnum `protobuf:"varint,1,opt,name=render_scheme,json=renderScheme,proto3,enum=bilibili.account.service.v1.RenderSchemeEnum" json:"render_scheme,omitempty"`
	ColorsInfo *ColorsInfo `protobuf:"bytes,2,opt,name=colors_info,json=colorsInfo,proto3" json:"colors_info,omitempty"`
}

func (x *NameRender) Reset() {
	*x = NameRender{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_account_service_v1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NameRender) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameRender) ProtoMessage() {}

func (x *NameRender) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_account_service_v1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameRender.ProtoReflect.Descriptor instead.
func (*NameRender) Descriptor() ([]byte, []int) {
	return file_bilibili_account_service_v1_proto_rawDescGZIP(), []int{2}
}

func (x *NameRender) GetRenderScheme() RenderSchemeEnum {
	if x != nil {
		return x.RenderScheme
	}
	return RenderSchemeEnum_Default
}

func (x *NameRender) GetColorsInfo() *ColorsInfo {
	if x != nil {
		return x.ColorsInfo
	}
	return nil
}

var File_bilibili_account_service_v1_proto protoreflect.FileDescriptor

var file_bilibili_account_service_v1_proto_rawDesc = []byte{
	0x0a, 0x21, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31,
	0x22, 0x45, 0x0a, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x6c,
	0x6f, 0x72, 0x5f, 0x64, 0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f,
	0x6c, 0x6f, 0x72, 0x44, 0x61, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x5f,
	0x6e, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6c,
	0x6f, 0x72, 0x4e, 0x69, 0x67, 0x68, 0x74, 0x22, 0x63, 0x0a, 0x0a, 0x43, 0x6f, 0x6c, 0x6f, 0x72,
	0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x5f, 0x69,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x08, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x49,
	0x64, 0x73, 0x12, 0x38, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x22, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x22, 0xaa, 0x01, 0x0a,
	0x0a, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x52, 0x0a, 0x0d, 0x72,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x2d, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x45, 0x6e, 0x75,
	0x6d, 0x52, 0x0c, 0x72, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x12,
	0x48, 0x0a, 0x0b, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x63,
	0x6f, 0x6c, 0x6f, 0x72, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x2a, 0x2d, 0x0a, 0x10, 0x52, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x0b, 0x0a,
	0x07, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x6f,
	0x6c, 0x6f, 0x72, 0x66, 0x75, 0x6c, 0x10, 0x01, 0x42, 0x3f, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x6d, 0x74, 0x63, 0x32, 0x33, 0x33, 0x2f,
	0x62, 0x69, 0x6c, 0x69, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x61, 0x70, 0x69, 0x2d, 0x67, 0x6f,
	0x2f, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_bilibili_account_service_v1_proto_rawDescOnce sync.Once
	file_bilibili_account_service_v1_proto_rawDescData = file_bilibili_account_service_v1_proto_rawDesc
)

func file_bilibili_account_service_v1_proto_rawDescGZIP() []byte {
	file_bilibili_account_service_v1_proto_rawDescOnce.Do(func() {
		file_bilibili_account_service_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_bilibili_account_service_v1_proto_rawDescData)
	})
	return file_bilibili_account_service_v1_proto_rawDescData
}

var file_bilibili_account_service_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bilibili_account_service_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bilibili_account_service_v1_proto_goTypes = []interface{}{
	(RenderSchemeEnum)(0), // 0: bilibili.account.service.v1.RenderSchemeEnum
	(*Color)(nil),         // 1: bilibili.account.service.v1.Color
	(*ColorsInfo)(nil),    // 2: bilibili.account.service.v1.ColorsInfo
	(*NameRender)(nil),    // 3: bilibili.account.service.v1.NameRender
}
var file_bilibili_account_service_v1_proto_depIdxs = []int32{
	1, // 0: bilibili.account.service.v1.ColorsInfo.color:type_name -> bilibili.account.service.v1.Color
	0, // 1: bilibili.account.service.v1.NameRender.render_scheme:type_name -> bilibili.account.service.v1.RenderSchemeEnum
	2, // 2: bilibili.account.service.v1.NameRender.colors_info:type_name -> bilibili.account.service.v1.ColorsInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_bilibili_account_service_v1_proto_init() }
func file_bilibili_account_service_v1_proto_init() {
	if File_bilibili_account_service_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bilibili_account_service_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Color); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_account_service_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColorsInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_account_service_v1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NameRender); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bilibili_account_service_v1_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bilibili_account_service_v1_proto_goTypes,
		DependencyIndexes: file_bilibili_account_service_v1_proto_depIdxs,
		EnumInfos:         file_bilibili_account_service_v1_proto_enumTypes,
		MessageInfos:      file_bilibili_account_service_v1_proto_msgTypes,
	}.Build()
	File_bilibili_account_service_v1_proto = out.File
	file_bilibili_account_service_v1_proto_rawDesc = nil
	file_bilibili_account_service_v1_proto_goTypes = nil
	file_bilibili_account_service_v1_proto_depIdxs = nil
}
