// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.relation.interfaces;

import "bilibili/dagw/component/avatar/v1/messages.proto";

enum Act {
  ACT_NA = 0;
  ACT_ADD_FOLLOWING = 1;
  ACT_DEL_FOLLOWING = 2;
  ACT_ADD_WHISPER = 3;
  ACT_DEL_WHISPER = 4;
  ACT_ADD_BLACK = 5;
  ACT_DEL_BLACK = 6;
  ACT_DEL_FOLLOWER = 7;
}

// Source: com/bapis/bilibili/relation/interfaces/AtGroup.java
message AtGroup {
  Type groupType = 1;
  string groupName = 2;
  repeated AtItem items = 3;
  enum Type {
    AT_GROUP_TYPE_DEFAULT = 0;
    AT_GROUP_TYPE_RECENT = 1;
    AT_GROUP_TYPE_FOLLOW = 2;
    AT_GROUP_TYPE_FANS = 3;
    AT_GROUP_TYPE_OTHERS = 4;
  }

}

// Source: com/bapis/bilibili/relation/interfaces/AtItem.java
message AtItem {
  int64 mid = 1;
  string name = 2;
  string face = 3;
  int32 fans = 4;
  int32 officialVerifyType = 5;
  com.bapis.bilibili.dagw.component.avatar.v1.AvatarItem avatar = 6;
  string handle = 7;
}

// Source: com/bapis/bilibili/relation/interfaces/AtSearchReply.java
message AtSearchReply {
  repeated AtGroup groups = 1;
}

// Source: com/bapis/bilibili/relation/interfaces/AtSearchReq.java
message AtSearchReq {
  int64 mid = 1;
  string keyword = 2;
  int32 scene = 3;
}

// Source: com/bapis/bilibili/relation/interfaces/FollowingReq.java
message FollowingReq {
  int64 fid = 1;
  Act act = 2;
  uint32 source = 3;
  string spmid = 4;
  string extendContent = 5;
  string fromSpmid = 6;
  string fromScmid = 7;
  string actionId = 8;
}

// Source: com/bapis/bilibili/relation/interfaces/ModifyRelationReply.java
message ModifyRelationReply {
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/relation/interfaces";
