// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.mall.tab3.viewunite.common;

enum AttentionRelationStatus {
  ARS_NONE = 0;
  ARS_N0RELATION = 1;
  ARS_FOLLOWHIM = 2;
  ARS_FOLLOWME = 3;
  ARS_BUDDY = 4;
  ARS_SPECIAL = 5;
  ARS_CANCELBLOCK = 6;
  UNRECOGNIZED = -1;
}

enum DescType {
  DescTypeUnknown = 0;
  DescTypeText = 1;
  DescTypeAt = 2;
  UNRECOGNIZED = -1;
}

enum ExtType {
  ExtNone = 0;
  ExtDataCenter = 1;
  ExtDataEarnings = 2;
  UNRECOGNIZED = -1;
}

enum HonorJumpType {
  HONOR_JUMP_TYPE_UNKNOWN = 0;
  HONOR_OPEN_URL = 1;
  HONOR_HALF_SCREEN = 2;
  UNRECOGNIZED = -1;
}

enum HonorType {
  HONOR_NONE = 0;
  PLAYLET = 1;
  ARGUE = 2;
  NOTICE = 3;
  GUIDANCE = 4;
  HONOR_BILI_RANK = 5;
  HONOR_WEEKLY_RANK = 6;
  HONOR_DAILY_RANK = 7;
  HONOR_CHANNEL = 8;
  HONOR_MUSIC = 9;
  HONOR_REPLY = 10;
  UNRECOGNIZED = -1;
}

enum JumpType {
  JUMP_TYPE_UNKNOWN = 0;
  OPEN_URL = 1;
  REFRESH = 2;
  HALF_SCREEN = 3;
  OPEN_URL_BY_OUTER_BROWSER = 4;
  UNRECOGNIZED = -1;
}

enum KingPositionType {
  KING_POS_UNSPECIFIED = 0;
  LIKE = 1;
  DISLIKE = 2;
  COIN = 3;
  FAV = 4;
  SHARE = 5;
  CACHE = 6;
  DANMAKU = 7;
  UNRECOGNIZED = -1;
}

enum ModuleType {
  UNKNOWN = 0;
  OGV_INTRODUCTION = 1;
  OGV_TITLE = 2;
  UGC_HEADLINE = 3;
  UGC_INTRODUCTION = 4;
  KING_POSITION = 5;
  MASTER_USER_LIST = 6;
  STAFFS = 7;
  HONOR = 8;
  OWNER = 9;
  PAGE = 10;
  ACTIVITY_RESERVE = 11;
  LIVE_ORDER = 12;
  POSITIVE = 13;
  SECTION = 14;
  RELATE = 15;
  PUGV = 16;
  COLLECTION_CARD = 17;
  ACTIVITY = 18;
  CHARACTER = 19;
  FOLLOW_LAYER = 20;
  OGV_SEASONS = 21;
  UGC_SEASON = 22;
  OGV_LIVE_RESERVE = 23;
  COMBINATION_EPISODE = 24;
  SPONSOR = 25;
  ACTIVITY_ENTRANCE = 26;
  THEATRE_HOT_TOPIC = 27;
  RELATED_RECOMMEND = 28;
  PAY_BAR = 29;
  BANNER = 30;
  AUDIO = 31;
  AGG_CARD = 32;
  SINGLE_EP = 33;
  LIKE_COMMENT = 34;
  ATTENTION_RECOMMEND = 35;
  COVENANTER = 36;
  SPECIALTAG = 37;
  UPDATA = 38;
  PROFESSION_APPROVAL = 39;
  UNRECOGNIZED = -1;
}

enum OccupationType {
  STAFF = 0;
  CAST = 1;
  UNKNOWN_TYPE = -1;
  UNRECOGNIZED = -1;
}

enum RelateCardType {
  CARD_TYPE_UNKNOWN = 0;
  AV = 1;
  BANGUMI = 2;
  RESOURCE = 3;
  GAME = 4;
  CM = 5;
  LIVE = 6;
  AI_RECOMMEND = 7;
  BANGUMI_AV = 8;
  BANGUMI_UGC = 9;
  SPECIAL = 10;
  UNRECOGNIZED = -1;
}

enum ReserveBizType {
  BizTypeNone = 0;
  BizTypeReserveActivity = 1;
  BizTypeFavSeason = 2;
  UNRECOGNIZED = -1;
}

enum SeasonType {
  Unknown = 0;
  Base = 1;
  Good = 2;
  UNRECOGNIZED = -1;
}

enum SerialSeasonCoverStyle {
  TITLE = 0;
  PICTURE = 1;
  SERIAL_SEASON_COVER_STYLE_UNKNOWN = -1;
  UNRECOGNIZED = -1;
}

enum ShowStyle {
  SHOW_STYLE_UNKNOWN = 0;
  ONE_ROW_ONE_COLUMN = 1;
  ONE_ROW_MULTI_COLUMN = 2;
  ONE_COLUMN_MULTI_ROW = 3;
  UNRECOGNIZED = -1;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/ActBannerItem.java
message ActBannerItem {
  string url = 1;
  string cover = 2;
  JumpType jumpType = 3;
  map<string, string> report = 4;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/Activity.java
message Activity {
  int32 id = 1;
  string title = 2;
  string link = 3;
  string cover = 4;
  int32 type = 5;
  string ab = 6;
  string showName = 7;
  string picurl = 8;
  string picurlSelected = 9;
  string h5Link = 10;
  string jumpMode = 11;
  repeated Item items = 12;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/ActivityEntrance.java
message ActivityEntrance {
  string activityCover = 1;
  string activityTitle = 2;
  string wordTag = 3;
  string activitySubtitle = 4;
  string activityLink = 5;
  int32 activityType = 6;
  int32 reserveId = 7;
  int32 status = 8;
  repeated User upperList = 9;
  map<string, string> report = 10;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/ActivityEntranceModule.java
message ActivityEntranceModule {
  repeated ActivityEntrance activityEntrance = 1;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/ActivityReserve.java
message ActivityReserve {
  string title = 1;
  StatInfo vt = 2;
  StatInfo danmaku = 3;
  ReserveButton button = 4;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/ActivityResource.java
message ActivityResource {
  string modPoolName = 1;
  string modResourceName = 2;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/ActivityTab.java
message ActivityTab {
  int32 id = 1;
  string title = 2;
  int32 type = 3;
  string showName = 4;
  string picurl = 5;
  string picurlSelected = 6;
  string h5Link = 7;
  string link = 8;
  int32 linkType = 9;
  int64 bizKey = 10;
  string desc = 11;
  string actExt = 12;
  map<string, string> report = 13;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/ActPageItems.java
message ActPageItems {
  repeated ActBannerItem item = 1;
  ShowStyle showStyle = 2;
  string title = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/AggEpCard.java
message AggEpCard {
  string title = 1;
  string cover = 2;
  string icon = 3;
  int32 num = 4;
  string jumpUrl = 5;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/AggEps.java
message AggEps {
  repeated AggEpCard aggEpCards = 1;
  int32 placeIndex = 2;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/AttentionRecommend.java
message AttentionRecommend {
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/Audio.java
message Audio {
  map<int64, AudioInfo> audioInfo = 1;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/AudioInfo.java
message AudioInfo {
  string title = 1;
  string coverUrl = 2;
  int64 songId = 3;
  int64 playCount = 4;
  int64 replyCount = 5;
  int64 upperId = 6;
  string entrance = 7;
  int64 songAttr = 8;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/BadgeInfo.java
message BadgeInfo {
  string text = 1;
  string textColor = 2;
  string textColorNight = 3;
  string bgColor = 4;
  string bgColorNight = 5;
  string borderColor = 6;
  string borderColorNight = 7;
  int32 bgStyle = 8;
  string img = 9;
  int32 type = 10;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/Banner.java
message Banner {
  string title = 1;
  repeated RelateItem relateItem = 2;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/BizFavParam.java
message BizFavParam {
  int64 seasonId = 1;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/BizReserveActivityParam.java
message BizReserveActivityParam {
  int64 activityId = 1;
  string from = 2;
  string type = 3;
  int64 oid = 4;
  int64 reserveId = 5;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/Button.java
message Button {
  string title = 1;
  string leftStrikethroughText = 2;
  string type = 3;
  string link = 4;
  BadgeInfo badgeInfo = 5;
  string subTitle = 6;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/CardBasicInfo.java
message CardBasicInfo {
  string title = 1;
  string desc = 2;
  string cover = 3;
  string uri = 4;
  string trackId = 5;
  string uniqueId = 6;
  int64 fromSourceType = 7;
  string fromSourceId = 8;
  int64 materialId = 9;
  string coverGif = 10;
  Owner author = 11;
  int64 id = 12;
  string from = 13;
  string fromSpmidSuffix = 14;
  string reportFlowData = 15;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/CardStyle.java
message CardStyle {
  int32 id = 1;
  string name = 2;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/Celebrity.java
message Celebrity {
  int32 id = 1;
  string name = 2;
  string role = 3;
  string avatar = 4;
  string shortDesc = 5;
  string desc = 6;
  string characterAvatar = 7;
  string link = 8;
  int64 mid = 9;
  int32 isFollow = 10;
  string occupationName = 11;
  OccupationType occupationType = 12;
  int32 relateAttr = 13;
  string smallAvatar = 14;
  map<string, string> report = 15;
  OfficialVerify official = 16;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/CellFluid.java
message CellFluid {
  string topBaseColor = 1;
  string topSplitColor = 2;
  string topTextColor = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/CharacterGroup.java
message CharacterGroup {
  string title = 1;
  repeated Celebrity characters = 2;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/Characters.java
message Characters {
  repeated CharacterGroup groups = 1;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/CoinExtend.java
message CoinExtend {
  string coinAppZipIcon = 1;
  string coinAppIcon1 = 2;
  string coinAppIcon2 = 3;
  string coinAppIcon3 = 4;
  string coinAppIcon4 = 5;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/CombinationEp.java
message CombinationEp {
  int32 id = 1;
  int32 sectionId = 2;
  string title = 3;
  int32 canOrdDesc = 4;
  string more = 5;
  repeated int32 episodeIds = 6;
  repeated ViewEpisode episodes = 7;
  string splitText = 8;
  Style moduleStyle = 9;
  repeated SerialSeason serialSeason = 10;
  SectionData sectionData = 11;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/ContractText.java
message ContractText {
  string title = 1;
  string subtitle = 2;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/Covenanter.java
message Covenanter {
  int32 isFollowDisplay = 1;
  ContractText text = 2;
  int32 isInteractDisplay = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/DeliveryData.java
message DeliveryData {
  string title = 1;
  Style moduleStyle = 2;
  string more = 3;
  oneof oneof_0 {
    Activity activity = 4;
    Characters characters = 5;
    TheatreHotTopic theatreHotTopic = 6;
    AggEps aggEps = 7;
    ActPageItems actPageItems = 10;
  }
  int32 id = 8;
  map<string, string> report = 9;
  enum DataCase {
    ACTIVITY = 4;
    CHARACTERS = 5;
    THEATRE_HOT_TOPIC = 6;
    AGG_EPS = 7;
    ACT_PAGE_ITEMS = 10;
    DATA_NOT_SET = 0;
  }

}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/Desc.java
message Desc {
  string info = 1;
  string title = 2;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/DescV2.java
message DescV2 {
  string text = 1;
  DescType type = 2;
  string uri = 3;
  int64 rid = 4;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/Dimension.java
message Dimension {
  int64 width = 1;
  int64 height = 2;
  int64 rotate = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/DislikeReasons.java
message DislikeReasons {
  int64 id = 1;
  int64 mid = 2;
  int32 rid = 3;
  int64 tagId = 4;
  string name = 5;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/ExtTab.java
message ExtTab {
  ExtType extType = 1;
  string data = 2;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/FollowLayer.java
message FollowLayer {
  Staff staff = 1;
  Desc desc = 2;
  map<string, string> report = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/Headline.java
message Headline {
  Label label = 1;
  string content = 2;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/HistoryNode.java
message HistoryNode {
  int64 nodeId = 1;
  string title = 2;
  int64 cid = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/Honor.java
message Honor {
  string icon = 1;
  string iconNight = 2;
  string text = 3;
  string textExtra = 4;
  string textColor = 5;
  string textColorNight = 6;
  string bgColor = 7;
  string bgColorNight = 8;
  string url = 9;
  string urlText = 10;
  HonorType type = 11;
  HonorJumpType honorJumpType = 12;
  map<string, string> report = 13;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/IconFont.java
message IconFont {
  string name = 1;
  string text = 2;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/Interaction.java
message Interaction {
  int64 epId = 1;
  HistoryNode historyNode = 2;
  int64 graphVersion = 3;
  string msg = 4;
  bool isInteraction = 5;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/Item.java
message Item {
  string link = 1;
  string cover = 2;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/KingPos.java
message KingPos {
  bool disable = 1;
  string icon = 2;
  KingPositionType type = 3;
  string disableToast = 4;
  string checkedToast = 5;
  oneof oneof_0 {
    LikeExtend like = 6;
    CoinExtend coin = 7;
  }
  enum ExtendCase {
    LIKE = 6;
    COIN = 7;
    EXTEND_NOT_SET = 0;
  }

}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/KingPosition.java
message KingPosition {
  repeated KingPos kingPos = 1;
  repeated KingPos extend_ = 2;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/Label.java
message Label {
  int32 type = 1;
  string uri = 2;
  string icon = 3;
  string iconNight = 4;
  int64 iconWidth = 5;
  int64 iconHeight = 6;
  string lottie = 7;
  string lottieNight = 8;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/LikeComment.java
message LikeComment {
  string reply = 1;
  string title = 2;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/LikeExtend.java
message LikeExtend {
  UpLikeImg tripleLike = 1;
  string likeAnimation = 2;
  PlayerAnimation playerAnimation = 3;
  ActivityResource resource = 4;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/Live.java
message Live {
  int64 mid = 1;
  int64 roomId = 2;
  string uri = 3;
  string endpageUri = 4;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/LiveOrder.java
message LiveOrder {
  int64 sid = 1;
  string text = 2;
  int64 livePlanStartTime = 3;
  bool isFollow = 4;
  int64 followCount = 5;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/Mine.java
message Mine {
  double amount = 1;
  int32 rank = 2;
  string msg = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/Module.java
message Module {
  ModuleType type = 1;
  oneof oneof_0 {
    OgvIntroduction ogvIntroduction = 2;
    UgcIntroduction ugcIntroduction = 3;
    KingPosition kingPosition = 4;
    Headline headLine = 5;
    OgvTitle ogvTitle = 6;
    Honor honor = 7;
    UserList list = 8;
    Staffs staffs = 9;
    ActivityReserve activityReserve = 10;
    LiveOrder liveOrder = 11;
    SectionData sectionData = 12;
    DeliveryData deliveryData = 13;
    FollowLayer followLayer = 14;
    OgvSeasons ogvSeasons = 15;
    UgcSeasons ugcSeason = 16;
    OgvLiveReserve ogvLiveReserve = 17;
    CombinationEp combinationEp = 18;
    Sponsor sponsor = 19;
    ActivityEntranceModule activityEntranceModule = 20;
    SerialSeason serialSeason = 21;
    Relates relates = 22;
    Banner banner = 23;
    Audio audio = 24;
    LikeComment likeComment = 25;
    AttentionRecommend attentionRecommend = 26;
    Covenanter covenanter = 27;
    SpecialTag specialTag = 28;
    UpDataModule upDataModule = 29;
    ProfessionApproval professionApproval = 30;
  }
  enum DataCase {
    OGV_INTRODUCTION = 2;
    UGC_INTRODUCTION = 3;
    KING_POSITION = 4;
    HEAD_LINE = 5;
    OGV_TITLE = 6;
    HONOR = 7;
    LIST = 8;
    STAFFS = 9;
    ACTIVITY_RESERVE = 10;
    LIVE_ORDER = 11;
    SECTION_DATA = 12;
    DELIVERY_DATA = 13;
    FOLLOW_LAYER = 14;
    OGV_SEASONS = 15;
    UGC_SEASON = 16;
    OGV_LIVE_RESERVE = 17;
    COMBINATION_EP = 18;
    SPONSOR = 19;
    ACTIVITY_ENTRANCE_MODULE = 20;
    SERIAL_SEASON = 21;
    RELATES = 22;
    BANNER = 23;
    AUDIO = 24;
    LIKE_COMMENT = 25;
    ATTENTION_RECOMMEND = 26;
    COVENANTER = 27;
    SPECIAL_TAG = 28;
    UP_DATA_MODULE = 29;
    PROFESSION_APPROVAL = 30;
    DATA_NOT_SET = 0;
  }

}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/MultiViewEp.java
message MultiViewEp {
  int64 epId = 1;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/NewEp.java
message NewEp {
  int32 id = 1;
  string title = 2;
  string desc = 3;
  int32 isNew = 4;
  string more = 5;
  string cover = 6;
  string indexShow = 7;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/OfficialVerify.java
message OfficialVerify {
  int32 type = 1;
  string desc = 2;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/OgvIntroduction.java
message OgvIntroduction {
  string followers = 1;
  string score = 2;
  StatInfo playData = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/OgvLiveReserve.java
message OgvLiveReserve {
  int64 reserveId = 1;
  string title = 2;
  string icon = 3;
  string nightIcon = 4;
  string clickButton = 5;
  string link = 6;
  int32 followVideoIsReserveLive = 7;
  string bgColor = 8;
  string nightBgColor = 9;
  string textColor = 10;
  string nightTextColor = 11;
  string btBgColor = 12;
  string btFrameColor = 13;
  string nightBtBgColor = 14;
  string nightBtFrameColor = 15;
  int32 activeType = 16;
  int32 reserveStatus = 17;
  string btTextColor = 18;
  string nightBtTextColor = 19;
  map<string, string> report = 20;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/OgvSeasons.java
message OgvSeasons {
  string title = 1;
  repeated SerialSeason serialSeason = 2;
  SerialSeasonCoverStyle style = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/OgvTitle.java
message OgvTitle {
  string title = 1;
  BadgeInfo badgeInfo = 2;
  int32 isShowBtnAnimation = 3;
  int32 followVideoIsReserveLive = 4;
  int64 reserveId = 5;
  TitleDeliveryButton titleDeliveryButton = 6;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/Owner.java
message Owner {
  AvatarItem avatar = 1;
  string url = 2;
  string title = 3;
  string fans = 4;
  string arcCount = 5;
  int32 attention = 6;
  AttentionRelationStatus attentionRelation = 7;
  string pubLocation = 8;
  Vip vip = 9;
  string titleUrl = 10;
  string face = 11;
  int64 mid = 12;
  OfficialVerify officialVerify = 13;
  Live live = 14;
  int64 fansNum = 15;
  repeated int64 assists = 16;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/Page.java
message Page {
  int64 cid = 1;
  string part = 2;
  int64 duration = 3;
  string desc = 4;
  Dimension dimension = 5;
  string dlTitle = 6;
  string dlSubtitle = 7;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/Pendant.java
message Pendant {
  int32 pid = 1;
  string name = 2;
  string image = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/PlayerAnimation.java
message PlayerAnimation {
  string playerIcon = 1;
  string playerTripleIcon = 2;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/PointActivity.java
message PointActivity {
  string tip = 1;
  string content = 2;
  string link = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/PowerIconStyle.java
message PowerIconStyle {
  string iconUrl = 1;
  string iconNightUrl = 2;
  int64 iconWidth = 3;
  int64 iconHeight = 4;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/ProfessionApproval.java
message ProfessionApproval {
  string title = 1;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/Rank.java
message Rank {
  string icon = 1;
  string iconNight = 2;
  string text = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/RankInfo.java
message RankInfo {
  string iconUrlNight = 1;
  string iconUrlDay = 2;
  string bkgNightColor = 3;
  string bkgDayColor = 4;
  string fontNightColor = 5;
  string fontDayColor = 6;
  string rankContent = 7;
  string rankLink = 8;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/Rating.java
message Rating {
  string score = 1;
  int32 count = 2;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/RelateAVCard.java
message RelateAVCard {
  int64 duration = 1;
  int64 cid = 2;
  Dimension dimension = 3;
  Stat stat = 4;
  string jumpUrl = 5;
  bool showUpName = 6;
  BadgeInfo rcmdReason = 7;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/RelateBangumiAvCard.java
message RelateBangumiAvCard {
  BadgeInfo badge = 1;
  Stat stat = 2;
  Rating rating = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/RelateBangumiCard.java
message RelateBangumiCard {
  int32 seasonId = 1;
  int32 seasonType = 2;
  NewEp newEp = 3;
  Stat stat = 4;
  Rating rating = 5;
  string rcmdReason = 6;
  BadgeInfo badgeInfo = 7;
  string gotoType = 8;
  map<string, string> report = 9;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/RelateBangumiResourceCard.java
message RelateBangumiResourceCard {
  int32 type = 1;
  string scover = 2;
  int32 reType = 3;
  string reValue = 4;
  string corner = 5;
  int32 card = 6;
  string siz = 7;
  int32 position = 8;
  string rcmdReason = 9;
  string label = 10;
  map<string, string> report = 11;
  string gotoType = 12;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/RelateBangumiUGCCard.java
message RelateBangumiUGCCard {
  BadgeInfo badge = 1;
  Stat stat = 2;
  Rating rating = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/RelateCard.java
message RelateCard {
  RelateCardType relateCardType = 1;
  oneof oneof_0 {
    RelateAVCard av = 2;
    RelateBangumiCard bangumi = 3;
    RelateBangumiResourceCard resource = 4;
    RelateGameCard game = 5;
    RelateCMCard cm = 6;
    RelateLiveCard live = 7;
    RelateBangumiAvCard bangumiAv = 8;
    RelatedAICard aiCard = 9;
    RelateBangumiUGCCard bangumiUgc = 13;
    RelateSpecial special = 14;
  }
  RelateThreePoint threePoint = 10;
  Any cmStock = 11;
  CardBasicInfo basicInfo = 12;
  enum CardCase {
    AV = 2;
    BANGUMI = 3;
    RESOURCE = 4;
    GAME = 5;
    CM = 6;
    LIVE = 7;
    BANGUMI_AV = 8;
    AI_CARD = 9;
    BANGUMI_UGC = 13;
    SPECIAL = 14;
    CARD_NOT_SET = 0;
  }

}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/RelateCMCard.java
message RelateCMCard {
  int64 aid = 1;
  Any sourceContent = 2;
  int64 duration = 3;
  Stat stat = 4;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/RelateConfig.java
message RelateConfig {
  int64 validShowM = 1;
  int64 validShowN = 2;
  Pagination pagination = 3;
  bool canLoadMore = 4;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/RelatedAICard.java
message RelatedAICard {
  int64 aid = 1;
  int64 duration = 2;
  Staff upInfo = 3;
  Stat stat = 4;
  map<string, string> report = 5;
  string gotoType = 6;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/RelateDislike.java
message RelateDislike {
  string title = 1;
  string subTitle = 2;
  string closedSubTitle = 3;
  string pasteText = 4;
  string closedPasteText = 5;
  repeated DislikeReasons dislikeReason = 6;
  string toast = 7;
  string closedToast = 8;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/RelateGameCard.java
message RelateGameCard {
  int64 reserveStatus = 1;
  string reserveStatusText = 2;
  string reserve = 3;
  float rating = 4;
  string tagName = 5;
  RankInfo rankInfo = 6;
  Button packInfo = 7;
  Button notice = 8;
  PowerIconStyle powerIconStyle = 9;
  string gameRcmdReason = 10;
  WikiInfo wikiInfo = 11;
  BadgeInfo badge = 12;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/RelateItem.java
message RelateItem {
  string url = 1;
  string cover = 2;
  bool useDefaultBrowser = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/RelateLiveCard.java
message RelateLiveCard {
  int64 iconType = 1;
  string areaName = 2;
  int64 watchedShow = 3;
  int64 liveStatus = 4;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/Relates.java
message Relates {
  repeated RelateCard cards = 1;
  RelateConfig config = 2;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/RelateSpecial.java
message RelateSpecial {
  BadgeInfo badge = 1;
  BadgeInfo rcmdReason = 2;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/RelateThreePoint.java
message RelateThreePoint {
  RelateDislike dislike = 1;
  RelateDislike feedback = 2;
  bool watchLater = 3;
  string dislikeReportData = 4;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/ReserveButton.java
message ReserveButton {
  bool status = 1;
  string text = 3;
  string selectedText = 4;
  ReserveBizType orderType = 7;
  oneof oneof_0 {
    BizReserveActivityParam reserve = 8;
    BizFavParam fav = 9;
  }
  enum OrderParamCase {
    RESERVE = 8;
    FAV = 9;
    ORDERPARAM_NOT_SET = 0;
  }

}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/Rights.java
message Rights {
  int32 allowDownload = 1;
  int32 allowReview = 2;
  int32 canWatch = 3;
  string resource = 4;
  int32 allowDm = 5;
  int32 allowDemand = 6;
  int32 areaLimit = 7;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/SeasonHead.java
message SeasonHead {
  string title = 1;
  string intro = 2;
  StatInfo vt = 3;
  StatInfo danmaku = 4;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/SeasonShow.java
message SeasonShow {
  string buttonText = 1;
  string joinText = 2;
  string ruleText = 3;
  string checkinText = 4;
  string checkinPrompt = 5;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/SectionData.java
message SectionData {
  int32 id = 1;
  int32 sectionId = 2;
  string title = 3;
  int32 canOrdDesc = 4;
  string more = 5;
  repeated int32 episodeIds = 6;
  repeated ViewEpisode episodes = 7;
  string splitText = 8;
  Style moduleStyle = 9;
  string moreBottomDesc = 10;
  repeated SerialSeason seasons = 11;
  Button moreLeft = 12;
  int32 type = 13;
  map<string, string> report = 14;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/SerialSeason.java
message SerialSeason {
  int32 seasonId = 1;
  string title = 2;
  string seasonTitle = 3;
  int32 isNew = 4;
  string cover = 5;
  string badge = 6;
  int32 badgeType = 7;
  BadgeInfo badgeInfo = 8;
  string link = 9;
  string resource = 10;
  NewEp newEp = 11;
  map<string, string> report = 12;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/SkipRange.java
message SkipRange {
  int32 start = 1;
  int32 end = 2;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/SpecialCell.java
message SpecialCell {
  string icon = 1;
  string iconNight = 2;
  string text = 3;
  string textColor = 4;
  string textColorNight = 5;
  string jumpUrl = 6;
  string cellType = 7;
  string cellBgcolor = 8;
  string cellBgcolorNight = 9;
  string param = 10;
  string pageTitle = 11;
  string jumpType = 12;
  string endIcon = 13;
  string endIconNight = 14;
  CellFluid cellFluid = 15;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/SpecialTag.java
message SpecialTag {
  repeated SpecialCell specialCell = 1;
  bool refresh = 2;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/Sponsor.java
message Sponsor {
  int64 total = 1;
  int64 week = 2;
  repeated SponsorRank rankList = 3;
  Mine mine = 4;
  PointActivity pointActivity = 5;
  repeated Pendant pendants = 6;
  repeated Threshold threshold = 7;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/SponsorRank.java
message SponsorRank {
  int64 uid = 1;
  string msg = 2;
  string uname = 3;
  string face = 4;
  Vip vip = 5;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/Staff.java
message Staff {
  int64 mid = 1;
  int32 attention = 2;
  string title = 3;
  string name = 4;
  string face = 5;
  OfficialVerify official = 6;
  Vip vip = 7;
  int32 labelStyle = 8;
  string fans = 9;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/Staffs.java
message Staffs {
  repeated Staff staff = 1;
  string title = 2;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/Stat.java
message Stat {
  StatInfo vt = 1;
  StatInfo danmaku = 2;
  int64 reply = 3;
  int64 fav = 4;
  int64 coin = 5;
  int64 share = 6;
  int64 like = 7;
  int64 follow = 8;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/StatInfo.java
message StatInfo {
  int64 value = 1;
  string text = 2;
  string pureText = 3;
  string icon = 4;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/Style.java
message Style {
  int32 line = 1;
  int32 hidden = 2;
  repeated string showPages = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/Tag.java
message Tag {
  int64 tagId = 1;
  string name = 2;
  string uri = 3;
  string tagType = 4;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/TheatreHotTopic.java
message TheatreHotTopic {
  int64 theatreId = 1;
  int64 theatreSetId = 2;
  string theatreTitle = 3;
  string backgroundImageUrl = 4;
  string theatreUrl = 5;
  int64 hotTopicId = 6;
  int64 hottopicsetid = 7;
  string hottopictitle = 8;
  string hotTopicUrl = 9;
  int32 isSubscribe = 10;
  map<string, string> report = 11;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/Threshold.java
message Threshold {
  int32 bp = 1;
  int32 days = 2;
  string daysText = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/TitleDeliveryButton.java
message TitleDeliveryButton {
  string icon = 1;
  string title = 2;
  string link = 3;
  map<string, string> report = 4;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/UgcEpisode.java
message UgcEpisode {
  int64 id = 1;
  int64 aid = 2;
  int64 cid = 3;
  string title = 4;
  string cover = 5;
  string coverRightText = 6;
  Page page = 7;
  StatInfo vt = 8;
  StatInfo danmaku = 9;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/UgcIntroduction.java
message UgcIntroduction {
  repeated Tag tags = 1;
  Rating rating = 2;
  Rank rank = 3;
  repeated ViewMaterial bgm = 4;
  repeated ViewMaterial sticker = 5;
  repeated ViewMaterial videoSource = 6;
  int64 pubdate = 7;
  repeated DescV2 desc = 8;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/UgcSeasonActivity.java
message UgcSeasonActivity {
  int32 type = 1;
  int64 oid = 2;
  int64 activityId = 3;
  string title = 4;
  string intro = 5;
  int32 dayCount = 6;
  int32 userCount = 7;
  int64 joinDeadline = 8;
  int64 activityDeadline = 9;
  int32 checkinViewTime = 10;
  bool newActivity = 11;
  UserActivity userActivity = 12;
  SeasonShow seasonShow = 13;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/UgcSeasons.java
message UgcSeasons {
  int64 id = 1;
  string title = 2;
  string cover = 3;
  string supernatantTitle = 4;
  repeated UgcSection section = 5;
  string unionTitle = 6;
  SeasonHead head = 7;
  int64 epCount = 8;
  SeasonType seasonType = 9;
  UgcSeasonActivity activity = 10;
  repeated string seasonAbility = 11;
  string seasonTitle = 12;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/UgcSection.java
message UgcSection {
  int64 id = 1;
  string title = 2;
  int64 type = 3;
  repeated UgcEpisode episodes = 4;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/UpDataModule.java
message UpDataModule {
  repeated ExtTab extTabs = 1;
  int32 idx = 2;
  string protocolUrl = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/UpLikeImg.java
message UpLikeImg {
  string preImg = 1;
  string sucImg = 2;
  string content = 3;
  int64 type = 4;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/User.java
message User {
  int64 mid = 1;
  string name = 2;
  string face = 3;
  int64 follower = 4;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/UserActivity.java
message UserActivity {
  int32 userState = 1;
  int64 lastCheckinDate = 2;
  int32 checkinToday = 3;
  int32 userDayCount = 4;
  int32 userViewTime = 5;
  string portrait = 6;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/UserList.java
message UserList {
  repeated User list = 1;
  string title = 2;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/UserStatus.java
message UserStatus {
  int32 show = 1;
  int32 follow = 2;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/ViewEpisode.java
message ViewEpisode {
  int64 epId = 1;
  string badge = 2;
  int32 badgeType = 3;
  BadgeInfo badgeInfo = 4;
  int32 duration = 5;
  int32 status = 6;
  string cover = 7;
  int64 aid = 8;
  string title = 9;
  string movieTitle = 10;
  string subtitle = 11;
  string longTitle = 12;
  string toastTitle = 13;
  int64 cid = 14;
  string from = 15;
  string shareUrl = 16;
  string shareCopy = 17;
  string shortLink = 18;
  string vid = 19;
  string releaseDate = 20;
  Dimension dimension = 21;
  Rights rights = 22;
  Interaction interaction = 23;
  string bvid = 24;
  int32 archiveAttr = 25;
  string link = 26;
  string linkType = 27;
  string bmid = 28;
  int64 pubTime = 29;
  int32 pv = 30;
  int32 epIndex = 31;
  int32 sectionIndex = 32;
  repeated Staff upInfos = 33;
  Staff upInfo = 34;
  string dialogType = 35;
  string toastType = 36;
  repeated MultiViewEp multiViewEps = 37;
  bool isSubView = 38;
  bool isViewHide = 39;
  string jumpLink = 40;
  Stat statForUnity = 41;
  map<string, string> report = 42;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/ViewMaterial.java
message ViewMaterial {
  int64 oid = 1;
  int64 mid = 2;
  string title = 3;
  string author = 4;
  string jumpUrl = 5;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/Vip.java
message Vip {
  int32 type = 1;
  int32 vipStatus = 2;
  int32 themeType = 3;
  VipLabel label = 4;
  int32 isVip = 5;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/VipLabel.java
message VipLabel {
  string path = 1;
  string text = 2;
  string labelTheme = 3;
}

// Source: com/bapis/bilibili/mall/tab3/viewunite/common/WikiInfo.java
message WikiInfo {
  string wikiLabel = 1;
  string wikiUrl = 2;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/mall/tab3/viewunite/common";
