// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.community.service.cert.v1;

enum Action {
  ACTION_CERT_CANCEL = 0;
  ACTION_CERT_CONFIRM = 1;
}

// Source: com/bapis/bilibili/community/service/cert/v1/FieldCertPopActionReq.java
message FieldCertPopActionReq {
  int64 avid = 1;
  Action action = 2;
}

// Source: com/bapis/bilibili/community/service/cert/v1/FieldCertPopActionRsp.java
message FieldCertPopActionRsp {
}

// Source: com/bapis/bilibili/community/service/cert/v1/FieldCertPopRecordReq.java
message FieldCertPopRecordReq {
  int64 avid = 1;
}

// Source: com/bapis/bilibili/community/service/cert/v1/FieldCertPopRecordRsp.java
message FieldCertPopRecordRsp {
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/community/service/cert/v1";
