// Reconstructed from gRPC service descriptors.
syntax = "proto3";

package bilibili.community.service.cert.v1;

import "bilibili/community/service/cert/v1/messages.proto";

service FieldCert {
  rpc FieldCertPopAction(.com.bapis.bilibili.community.service.cert.v1.FieldCertPopActionReq) returns (.com.bapis.bilibili.community.service.cert.v1.FieldCertPopActionRsp);
  rpc FieldCertPopRecord(.com.bapis.bilibili.community.service.cert.v1.FieldCertPopRecordReq) returns (.com.bapis.bilibili.community.service.cert.v1.FieldCertPopRecordRsp);
}

option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/community/service/cert/v1";
