// Reconstructed from gRPC service descriptors.
syntax = "proto3";

package bilibili.app.mine.v1;

import "bilibili/app/mine/v1/messages.proto";
import "google/protobuf/empty.proto";

service Mine {
  rpc DisplayReport(.com.bapis.bilibili.app.mine.v1.DisplayReportReq) returns (.google.protobuf.Empty);
  rpc PubModule(.com.bapis.bilibili.app.mine.v1.PubModuleReq) returns (.com.bapis.bilibili.app.mine.v1.PubModuleResp);
}

option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/app/mine/v1";
