// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.metadata.locale;

// Source: com/bapis/bilibili/metadata/locale/Locale.java
message Locale {
  LocaleIds cLocale = 1;
  LocaleIds sLocale = 2;
  string simCode = 3;
  string timezone = 4;
  string utcOffset = 5;
  bool isDaylightTime = 6;
  bool alwaysTranslate = 7;
  string storeCountry = 8;
  string storeCurrency = 9;
  string storePayChannel = 10;
}

// Source: com/bapis/bilibili/metadata/locale/LocaleIds.java
message LocaleIds {
  string language = 1;
  string script = 2;
  string region = 3;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/metadata/locale";
