// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.gaia.gw;

enum EncryptType {
  INVALID_ENCRYPT_TYPE = 0;
  CLIENT_AES = 1;
  SERVER_RSA_AES = 2;
  UNRECOGNIZED = -1;
}

enum PayloadType {
  INVALID_PAYLOAD = 0;
  DEVICE_APP_LIST = 1;
  UNRECOGNIZED = -1;
}

// Source: com/bapis/bilibili/gaia/gw/DeviceAppList.java
message DeviceAppList {
  string source = 1;
  repeated string systemAppList = 2;
  repeated string userAppList = 3;
}

// Source: com/bapis/bilibili/gaia/gw/FetchPublicKeyReply.java
message FetchPublicKeyReply {
  string version = 1;
  string publicKey = 2;
  int64 deadline = 3;
}

// Source: com/bapis/bilibili/gaia/gw/GaiaDeviceBasicInfo.java
message GaiaDeviceBasicInfo {
  string platform = 1;
  string device = 2;
  string mobiApp = 3;
  string origin = 4;
  string appId = 5;
  string sdkver = 6;
  string appVersion = 7;
  string appVersionCode = 8;
  string build = 9;
  string channel = 10;
  string brand = 11;
  string model = 12;
  string osver = 13;
  string userAgent = 14;
  string buvidLocal = 15;
  string buvid = 16;
  string mid = 17;
  int64 fts = 18;
  int32 first = 19;
  string network = 20;
}

// Source: com/bapis/bilibili/gaia/gw/GaiaEncryptMsgReq.java
message GaiaEncryptMsgReq {
  GaiaMsgHeader header = 1;
  bytes encryptPayload = 2;
}

// Source: com/bapis/bilibili/gaia/gw/GaiaMsgHeader.java
message GaiaMsgHeader {
  EncryptType encodeType = 1;
  PayloadType payloadType = 2;
  bytes encodedAesKey = 3;
  int64 ts = 4;
}

// Source: com/bapis/bilibili/gaia/gw/UploadAppListReply.java
message UploadAppListReply {
  string traceId = 1;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/gaia/gw";
