// Reconstructed from gRPC service descriptors.
syntax = "proto3";

package bilibili.gaia.gw;

import "bilibili/gaia/gw/messages.proto";
import "google/protobuf/empty.proto";

service Gaia {
  rpc ExClimbAppleTrees(.com.bapis.bilibili.gaia.gw.GaiaEncryptMsgReq) returns (.com.bapis.bilibili.gaia.gw.UploadAppListReply);
  rpc ExFetchPublicKey(.google.protobuf.Empty) returns (.com.bapis.bilibili.gaia.gw.FetchPublicKeyReply);
  rpc ExGetAxe(.google.protobuf.Empty) returns (.com.bapis.bilibili.gaia.gw.FetchPublicKeyReply);
  rpc ExUploadAppList(.com.bapis.bilibili.gaia.gw.GaiaEncryptMsgReq) returns (.com.bapis.bilibili.gaia.gw.UploadAppListReply);
}

option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/gaia/gw";
