// Reconstructed from protobuf-lite metadata in the APK.
syntax = "proto3";

package com.bapis.bilibili.main.community.reply.v2;

import "google/protobuf/wrappers.proto";

enum EditorIconState {
  EditorIconState_DEFAULT = 0;
  EditorIconState_ENABLE = 1;
  EditorIconState_DISABLE = 2;
  EditorIconState_HIDE = 3;
}

enum FunctionButtonType {
  FunctionButtonType_DEFAULT = 0;
  FunctionButtonType_Screenshot = 1;
  FunctionButtonType_UploadPicture = 2;
  FunctionButtonType_Vote = 3;
  FunctionButtonType_Note = 4;
  FunctionButtonType_Goods = 5;
  FunctionButtonType_InsertContent = 6;
  FunctionButtonType_Elec = 7;
  FunctionButtonType_CMBizHelper = 8;
}

enum UserCallbackAction {
  USER_CALLBACK_ACTION_DEFAULT = 0;
  USER_CALLBACK_ACTION_DISMISS = 1;
}

enum UserCallbackScene {
  USER_CALLBACK_SCENE_DEFAULT = 0;
  USER_CALLBACK_SCENE_INSERT = 1;
  USER_CALLBACK_SCENE_RECOMMEND_SUPERB_REPLY = 2;
}

// Source: com/bapis/bilibili/main/community/reply/v2/Emote.java
message Emote {
  int64 size = 1;
  string url = 2;
  string jumpUrl = 3;
  string jumpTitle = 4;
  int64 id = 5;
  int64 packageId = 6;
  string gifUrl = 7;
  string text = 8;
  string webpUrl = 9;
}

// Source: com/bapis/bilibili/main/community/reply/v2/EmptyPage.java
message EmptyPage {
  string imageUrl = 1;
  repeated EmptyPage_Text texts = 2;
  EmptyPage_Button leftButton = 3;
  EmptyPage_Button rightButton = 4;
  enum Action {
    UNAVAILABLE = 0;
    SHOW_KEYBOARD = 1;
    SEND_REPLY_WITH_BOLD_TEXT = 2;
  }

}

// Source: com/bapis/bilibili/main/community/reply/v2/EmptyPage.java
message EmptyPage_Button {
  string title = 1;
  EmptyPage.Action action = 2;
}

// Source: com/bapis/bilibili/main/community/reply/v2/EmptyPage.java
message EmptyPage_Text {
  string raw = 1;
  TextStyle style = 2;
  EmptyPage.Action action = 3;
}

// Source: com/bapis/bilibili/main/community/reply/v2/GuideText.java
message GuideText {
  repeated GuideText_Text texts = 1;
}

// Source: com/bapis/bilibili/main/community/reply/v2/GuideText.java
message GuideText_Text {
  string raw = 1;
  TextStyle style = 2;
  string link = 3;
}

// Source: com/bapis/bilibili/main/community/reply/v2/PlayerParams.java
message PlayerParams {
  bool isStory = 1;
  bool disableFilterTag = 2;
}

// Source: com/bapis/bilibili/main/community/reply/v2/Resource.java
message Resource {
  BizKind bizKind = 1;
  string url = 2;
  enum BizKind {
    UNKNOWN = 0;
    LIKE_SUCCESS = 1;
    REPLY_SUCCESS = 2;
    REPLY_EASTER_EGG = 3;
  }

}

// Source: com/bapis/bilibili/main/community/reply/v2/RichText.java
message RichText {
  string raw = 1;
  TextStyle style = 2;
  int32 marginLeft = 3;
}

// Source: com/bapis/bilibili/main/community/reply/v2/SubjectDescriptionReply.java
message SubjectDescriptionReply {
  int64 count = 1;
  SubjectDescriptionReply_InputConfig input = 2;
  SubjectDescriptionReply_EmoteConfig emote = 3;
  EmptyPage emptyPage = 4;
  repeated SubjectDescriptionReply_FilterTag supportFilterTags = 5;
  repeated string preloadResUrls = 6;
  repeated UserCallback userCallbacks = 7;
  int64 upMid = 8;
  repeated Resource preloadResources = 9;
  bool guestLimit = 10;
  GuideText filterGuideText = 11;
  string upFilterLink = 12;
  string webUpFilterLink = 13;
}

// Source: com/bapis/bilibili/main/community/reply/v2/SubjectDescriptionReply.java
message SubjectDescriptionReply_EmoteConfig {
  bool jumpEmoteDisabled = 1;
  repeated Emote suggestEmotes = 2;
}

// Source: com/bapis/bilibili/main/community/reply/v2/SubjectDescriptionReply.java
message SubjectDescriptionReply_FilterTag {
  int64 id = 1;
  string title = 2;
  string eventId = 3;
  bool supportPicList = 4;
}

// Source: com/bapis/bilibili/main/community/reply/v2/SubjectDescriptionReply.java
message SubjectDescriptionReply_InputConfig {
  bool disabled = 1;
  string rootText = 2;
  string childText = 3;
  string giveUpText = 4;
  SubjectDescriptionReply_InputConfig_EditorIconConfig editorIconConfig = 5;
  SubjectDescriptionReply_InputConfig_GradePanel gradePanel = 6;
  SubjectDescriptionReply_InputConfig_FunctionButtonGroup funcButtons = 7;
}

// Source: com/bapis/bilibili/main/community/reply/v2/SubjectDescriptionReply.java
message SubjectDescriptionReply_InputConfig_EditorIconConfig {
  EditorIconState screenshotIconState = 1;
  EditorIconState uploadPictureIconState = 2;
  EditorIconState voteIconState = 3;
  EditorIconState noteIconState = 4;
  EditorIconState goodsIconState = 5;
  EditorIconState insertContentIconState = 6;
  EditorIconState elecIconState = 7;
  EditorIconState cmBizHelperIconState = 8;
}

// Source: com/bapis/bilibili/main/community/reply/v2/SubjectDescriptionReply.java
message SubjectDescriptionReply_InputConfig_FunctionButton {
  FunctionButtonType type = 1;
  string name = 2;
  EditorIconState state = 3;
  string link = 4;
}

// Source: com/bapis/bilibili/main/community/reply/v2/SubjectDescriptionReply.java
message SubjectDescriptionReply_InputConfig_FunctionButtonGroup {
  repeated SubjectDescriptionReply_InputConfig_FunctionButton buttons = 1;
}

// Source: com/bapis/bilibili/main/community/reply/v2/SubjectDescriptionReply.java
message SubjectDescriptionReply_InputConfig_GradePanel {
  string promptText = 1;
  repeated SubjectDescriptionReply_InputConfig_GradePanel_Grade grades = 2;
  repeated SubjectDescriptionReply_InputConfig_GradePanel_CidGradeGroup cidGradeGroups = 3;
  SubjectDescriptionReply_InputConfig_GradePanel_Grade singleGrade = 4;
  GradeType gradeType = 5;
  string replyAddReportParams = 6;
  enum GradeType {
    UNKNOWN = 0;
    S13 = 1;
    ESPORTS = 2;
    OGV = 3;
  }

}

// Source: com/bapis/bilibili/main/community/reply/v2/SubjectDescriptionReply.java
message SubjectDescriptionReply_InputConfig_GradePanel_CidGradeGroup {
  int64 cid = 1;
  string title = 2;
  repeated SubjectDescriptionReply_InputConfig_GradePanel_Grade grades = 3;
}

// Source: com/bapis/bilibili/main/community/reply/v2/SubjectDescriptionReply.java
message SubjectDescriptionReply_InputConfig_GradePanel_Grade {
  int64 id = 1;
  string image = 2;
  string title = 3;
  google.protobuf.Int32Value defaultScore = 4;
  bool disableZero = 5;
  string gradePrompt = 6;
  repeated RichText richTitle = 7;
  repeated RichText richSubtitle = 8;
}

// Source: com/bapis/bilibili/main/community/reply/v2/SubjectDescriptionReq.java
message SubjectDescriptionReq {
  SubjectID subjectId = 1;
  PlayerParams playerParams = 2;
}

// Source: com/bapis/bilibili/main/community/reply/v2/SubjectID.java
message SubjectID {
  int64 oid = 1;
  int64 type = 2;
}

// Source: com/bapis/bilibili/main/community/reply/v2/TextStyle.java
message TextStyle {
  int32 fontSize = 1;
  FontStyle fontStyle = 2;
  string textDayColor = 3;
  string textNightColor = 4;
  enum FontStyle {
    NORMAL = 0;
    BOLD = 1;
    MEDIUM = 2;
  }

}

// Source: com/bapis/bilibili/main/community/reply/v2/UserCallback.java
message UserCallback {
  UserCallbackScene scene = 1;
  UserCallbackAction action = 2;
}


option go_package = "github.com/stmtc233/bili-grpc-api-go/bilibili/main/community/reply/v2";
